### ISSUE TITLE
RPC ```eth_getBalance``` Metamask Error ```Insufficient funds.``` While Explorer Shows Address Has SHM

### ISSUE THREAD

**Issue by ksbaskar** [Shardeum/shardeum-bug-reporting#100]
##### What is the issue?
I am getting Insufficient fund error while making transaction even i am having sufficient SHM in Wallet (Metamask)
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?
Can't able to exceute the transaction for a while.
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 
It's visual warning appears in Metamask (Pls., see attachement image)
##### How to reproduce the issue? 
1. Login to Dexpad.io
2. Select Sphinx 1.x as Network
3. Goto Token Factory and try to create a Token
4. Confirmation Message in Metamak shows this error.
: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
<img width="496" alt="s1" src="https://user-images.githubusercontent.com/6725456/220875631-cd2da5fb-fea3-4c81-b719-f8bc0786aedd.png">

**Comment by MarcusWentz** [comment]
Related to:

https://github.com/Shardeum/shardeum-bug-reporting/issues/44

Betanet 1.1 appears to have RPC and Validator issues causing this. We are looking into this.
