### ISSUE TITLE
Validator Not Starting After Updating to Version 1.1.1?

### ISSUE THREAD

**Issue by LIHebzy** [Shardeum/shardeum-bug-reporting#101]
I updated my node to 1.1  and after that i cannot start node and i can't view node from web using my Ip and Port
![web](https://user-images.githubusercontent.com/119897053/220898782-57a57aea-f246-4b66-a27d-7367bebf69dd.jpg)

**Comment by MarcusWentz** [comment]
What do you see when:

you run:

```shell
operator-cli start
```
then after a few seconds, run:

```shell
operator-cli status
```

?

https://docs.shardeum.org/node/run/validator#step-5-start-validator

**Comment by LIHebzy** [comment]
> What do you see when:
> 
> you run:
> 
> ```shell
> operator-cli start
> ```
> 
> then after a few seconds, run:
> 
> ```shell
> operator-cli status
> ```
> 
> ?
> 
> https://docs.shardeum.org/node/run/validator#step-5-start-validator

It shows Not found for everything

**Comment by MarcusWentz** [comment]
What do you see in your Validator CLI after you run:

```curl
operator-cli --help
```

https://docs.shardeum.org/node/run/validator#commands

?

**Comment by Ezebrown** [comment]
It says command not found

**Comment by Ezebrown** [comment]
![Screenshot_20230224-074145_Termius](https://user-images.githubusercontent.com/107863520/221110154-6cc11e8f-dba7-477b-9542-9edba83b05ae.jpg)
What will I do here @MarcusWentz

**Comment by MarcusWentz** [comment]
I would recommend uninstalling the validator:

https://docs.shardeum.org/node/run/validator#uninstall-validator

then installing the validator again:

https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

Does that fix the issue?

**Comment by Ezebrown** [comment]
![Screenshot_20230224-081125_Termius](https://user-images.githubusercontent.com/107863520/221115932-bb571cbe-b12e-4a2a-af91-fc2e1f069155.jpg)
 It shows this after I run the command

**Comment by MarcusWentz** [comment]
@Ezebrown 

Type:

```
y
```

then press Enter. 

Does that continue the installation?

**Comment by LIHebzy** [comment]
> operator-cli --help

I will try this now

**Comment by LIHebzy** [comment]
Working fine now. I will keep observing it

> @Ezebrown
> 
> Type:
> 
> ```
> y
> ```
> 
> then press Enter.
> 
> Does that continue the installation?

Working fine now. I will keep observing it

**Comment by MarcusWentz** [comment]
Closing issue.

Let's start a new issue if a new error comes up.
