### ISSUE TITLE
[Duplicate] Validator ```Add Stake``` and ```Remove Stake``` Transactions Fail With ```32603: Internal error```

### ISSUE THREAD

**Issue by maximilianWP** [Shardeum/shardeum-bug-reporting#105]
##### What is the issue?

After updating the node to the 1.1 I used to remove the previous staking and add a new one.
Trying to do this for several times, spent some hours, but all my attempts are failed. After signing the transaction nothing  happens. Metamask wallet is being reset.
![image](https://user-images.githubusercontent.com/95386839/220980449-f56584ee-36cc-4e7a-93b9-8cc44f720963.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share this here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/86
