### ISSUE TITLE
[Duplicate] Validator Randomly Stops

### ISSUE THREAD

**Issue by gprok100** [Shardeum/shardeum-bug-reporting#106]
My node is running in Google cloud . Before being active it never stop , status is 'standby'.
But after being active it stop automatically again and again.

So I don't think it is a firewall issue on the VM cloud provider.

A Quick Fix:

Write a function to auto start node if it stop and ask permission to do so with a consent button on the dashboard.

So that you can figure out the real cause.

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/35
