### ISSUE TITLE
"VmError" revert on Liberty2.1, create2 not working properly?

### ISSUE THREAD

**Issue by simone1999** [Shardeum/shardeum-bug-reporting#11]
##### Overview
When sending a transaction that is intended to create a new token pair on a UniswapV2 like DEX, this transaction reverts with VmError.

##### Context 
The reverting transaction can be seen here: https://explorer-liberty20.shardeum.org/tx/0x8452cefe9f2bcf312672d2455fccb93e3eb81a152a8699e2045598f090b75cfe

The transaction calls the addLiquidity method of the UniswapV2 Router02 contract, which internally calls the uniswapV2 Factory contract which then uses the create2 opcode to deploy a UniswapV2 pair contract and send tokens via transferFrom to that new contract. The tokens are approved and the approval transaction worked like expected.
The reason might be the create2 opcode not working correctly in the internal access list generation, but thats just a guess.

##### Resources
used Contracts:
Router02: https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol
Factory: https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2Factory.sol
ERC20 tokens: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/presets/ERC20PresetMinterPauser.sol
Pair that gets created in the transaction: https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2Pair.sol

**Comment by MarcusWentz** [comment]
Bug patch will be added soon. 

Update for issue #12 as well.

**Comment by MarcusWentz** [comment]
Bug patch tested locally and will be added soon as stated in:

https://github.com/Shardeum/shardeum-bug-reporting/issues/12#issuecomment-1380897548

**Comment by MarcusWentz** [comment]
UniswapV2 token pair (ERC-20) on Betanet 1.X worked. 

UniswapV2Factory Solidity: 

https://goerli.etherscan.io/address/0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f#code 

Token A: 

0x6aA9f5Caab83fc7DF571Ed0083e1E4484D22baef 

Token B: 

0x683c874eef78116071328ac71367b5E1cF9f7e46  

UniswapV2Factory: 

0x65EB96E70Dc815dA41C672ED1D6Ab9737a0BA054 

getPair (with Token A and Token B addresses): 

0xfdCBd118E17C6f7f0eC87c7C9Bf966C00d1009C0
