### ISSUE TITLE
Validator GUI Error ```This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.```

### ISSUE THREAD

**Issue by Jamarox** [Shardeum/shardeum-bug-reporting#111]
I have tried to update node and after this it probably created new node, and now I have a screen like below. What should I do to run previous node?

![image](https://user-images.githubusercontent.com/126200428/221016019-f7243d26-f7c1-4eca-97ef-4016655dfb82.png)

**Comment by MarcusWentz** [comment]
Are you able to remove your current stake as suggested in the error message?

**Comment by Jamarox** [comment]
> 

No, it is impossible:
![image](https://user-images.githubusercontent.com/126200428/221018368-556d0f35-3a65-40a8-858e-77743ba6f689.png)

**Comment by MarcusWentz** [comment]
This is related to an RPC issue with transactions failing in general.

Please share your info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
