### ISSUE TITLE
[Duplicate] Validator ```Add Stake``` and ```Remove Stake``` Transactions Fail With ```32603: Internal error```

### ISSUE THREAD

**Issue by crypto-mathi** [Shardeum/shardeum-bug-reporting#112]
I re-Installed the node without unstaking. Now it is not allowing me to unstake SHM.

It shows the following  error message in the dashboard,

"
<img width="1145" alt="Screenshot 2023-02-23 at 10 10 24 PM" src="https://user-images.githubusercontent.com/122903651/221031024-fa069da1-0c45-4c50-85c1-10975964fa7c.png">
This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node."

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share your info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
