### ISSUE TITLE
Validator Unable To Update To Latest Version 

### ISSUE THREAD

**Issue by Mathman14** [Shardeum/shardeum-bug-reporting#113]
##### What is the issue?
unable to update my node to the newest version  
:red_circle:  Describe the error in simple terms. :red_circle: 
    permission deny , failure writing output to destination
#### What impact does the issue have?
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
What happens when you manually uninstall the validator:

https://docs.shardeum.org/node/run/validator#uninstall-validator

and then try to download and install the latest validator version:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

?
