### ISSUE TITLE
Node Change After Update , Cannot Remove Stake , Cannot Send Token To Other Wallet 

### ISSUE THREAD

**Issue by kurniamisbah** [Shardeum/shardeum-bug-reporting#116]
![image](https://user-images.githubusercontent.com/116286924/221081855-75539f06-69b0-4e4a-ac79-7a6f6e811146.png)
![image](https://user-images.githubusercontent.com/116286924/221081888-3d5e3fac-b7f6-4682-a10e-322633c774ee.png)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share your info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92

**Comment by DoVanThang-AI** [comment]
the same errors
