### ISSUE TITLE
Validator Download And Install Setup?

### ISSUE THREAD

**Issue by Ezebrown** [Shardeum/shardeum-bug-reporting#117]
I was unable to login to my validator site to Chek if my node is running or not. 
It asked to run "unminimized" command on my code editor,  but I don't know how to do it, to get the node running again
![Screenshot_20230224-074145_Termius](https://user-images.githubusercontent.com/107863520/221111380-211d2952-2ac4-4f1e-92ec-7d563b64aeca.jpg)

**Comment by MarcusWentz** [comment]
Q1. What do you see with:

```shell
operator-cli status
```

https://docs.shardeum.org/node/run/validator#step-6-monitor-validator

?

Q2. What web browser did you try to open the GUI with?

Q3. Do you have a screenshot for what you see in the GUI in your web browser?

**Comment by Ezebrown** [comment]
Yes I have the screenshot of whY I see in the browser.
![16772227403786224488779413320018](https://user-images.githubusercontent.com/107863520/221115506-66776f84-7137-45ed-9305-222eaac63b4d.jpg)
 It says site can't be reached

**Comment by Ezebrown** [comment]
After I run the command from your from.up there
It show this 
![Screenshot_20230224-074145_Termius](https://user-images.githubusercontent.com/107863520/221115629-9b5ab2eb-a189-4f33-aa17-2d4557d0148c.jpg)

**Comment by MarcusWentz** [comment]
Q1. Did you try adding:

```
https://
```

at the start of the URL for the GUI interface in your web browser

https://docs.shardeum.org/node/run/validator#step-4-open-validator-gui

?

Q2. From your root directory, can you access the hidden Shardeum folder with

```shell
cd .shardeum
```

https://docs.shardeum.org/node/run/validator#step-3-open-validator-cli

?

**Comment by Ezebrown** [comment]
Answer 
1. I add https but it is not going through.
2. I will try running the command and Check.

**Comment by Ezebrown** [comment]
![Screenshot_20230224-084722_Termius](https://user-images.githubusercontent.com/107863520/221122019-190eeb47-683a-4fe3-a773-542c8935e447.jpg)
It continues with the installation.

**Comment by MarcusWentz** [comment]
@Ezebrown 

This looks good so far.

I would wait for the installation to finish.

After the installation is complete try:

```
cd .shardeum
```

**Comment by Ezebrown** [comment]
It is now working,  I can now access the site

**Comment by Ezebrown** [comment]
After running cd.shardeum , it jump to next line

**Comment by MarcusWentz** [comment]
While in the ".shardeum" directory, try:

```shell
./shell.sh
```

https://docs.shardeum.org/node/run/validator#step-3-open-validator-cli

**Comment by Ezebrown** [comment]
![Screenshot_20230224-090226_Termius](https://user-images.githubusercontent.com/107863520/221124925-d2261d32-41f4-4833-8439-a56c84eaf49d.jpg)
It show this

**Comment by MarcusWentz** [comment]
You are now in the Validator CLI which is good.

Are you able to start the CLI from the GUI:

https://docs.shardeum.org/node/run/validator#step-4-open-validator-gui

?

**Comment by Ezebrown** [comment]
I have logged in.
But it asked me to unstake my SHM so i can stake it on the new validator created, which I've tried but it is not successful yet.
Maybe I will try later

**Comment by MarcusWentz** [comment]
The staking and unstaking issues are related to the RPC. 

Please share this here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
