### ISSUE TITLE
[Duplicate] Validator Restart Lost Stake Reward

### ISSUE THREAD

**Issue by johnc76** [Shardeum/shardeum-bug-reporting#118]
After each active cycle my rewards drop back to 0. I’m not sure if this happens at the start, during or and the end of the active cycle. However; when my node has stopped under normal conditions my rewards are at 0.

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/34
