### ISSUE TITLE
Validator GUI Chrome Error ```This site can't be reached```

### ISSUE THREAD

**Issue by terminator007x** [Shardeum/shardeum-bug-reporting#120]
![Screenshot (51)](https://user-images.githubusercontent.com/126277499/221242029-727d2d59-de38-4251-b730-332d2dc41411.png)

**Comment by MarcusWentz** [comment]
What happens when you add

```
https://
```

to the start of your URL then try to access the GUI from there again?

https://docs.shardeum.org/node/run/validator#step-4-open-validator-gui

**Comment by terminator007x** [comment]
got ann solution,thanks
