### ISSUE TITLE
[Duplicate] Validator ```Add Stake``` and ```Remove Stake``` Transactions Fail With ```32603: Internal error```

### ISSUE THREAD

**Issue by Khris5** [Shardeum/shardeum-bug-reporting#121]
##### What is the issue?

:red_circle:  I can't remove my currently staked tokens. :red_circle: 
    
#### What impact does the issue have?

:red_circle: I'm not currently able to stake in the updated node. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
When I click the remove stake button, it processes for a while (like 10 seconds) then brings a pop-up error message from my wallet
    
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: 
![Screenshot (158)](https://user-images.githubusercontent.com/123326241/221248151-edde0378-600b-47b5-b356-c019fb4699f8.png)

 :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share your info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92

**Comment by Khris5** [comment]
I'm having problems removing my currently staked token. I updated my node
now I have to remove all my stake first before I can stake again
