### ISSUE TITLE
[Duplicate] Validator GUI SHM Rewards Decreasing

### ISSUE THREAD

**Issue by RobeelZahid111** [Shardeum/shardeum-bug-reporting#122]
##### What is the issue?

:red_circle:  Rewards reset everyday I have 45 SHM reward next day it was 23 SHM and very next day they were just 9 SHM.  :red_circle: 
    
#### What impact does the issue have?

:red_circle: It don't show the reward increasing but everyday reward is decreasing :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
![image_2023-02-24_232226991](https://user-images.githubusercontent.com/97405756/221259195-b70e7623-d8b3-41b5-ba18-bc0eb7f32fb1.png)

```
    -Error seen on Dashboard 
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: I have attach only one issue raised my community member there are dozen of complaint regarding this and I am also included in it. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/45
