### ISSUE TITLE
Validator CLI Docker Shell Script Run ```ERROR: for shardeum-dashboard no such image```

### ISSUE THREAD

**Issue by Roccaaa** [Shardeum/shardeum-bug-reporting#123]
Validator stop working with following message: 
```
ERROR: for shardeum-dashboard no such image: 
sha256:802b92711f96f308d19159b4aa 0928a050799a90c53f6f3e49793a3cd558: 
No such image: 
sha256:802b92711f9f6f308d1
9159b4a0928a050799a90c536f3e4e9793a3cd558f
```

When i reinstall the node i also lost all the reward accumulated.

**Comment by MarcusWentz** [comment]
This error might be related to a docker image. 

Q1. Do you see this error in the Validator CLI or GUI?

Q2. Can you still access the GUI and connect your wallet to check your staked SHM balance?

**Comment by Roccaaa** [comment]
Q1) in the validator CLI, i wasn't able to access the GUI. 
Q2) Once i reinstall the validator i open the GUI and the staked  SHM balance was still there, but if i try to stack again this ERROR show up: "This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node".
What can this be?

**Comment by MarcusWentz** [comment]
Q1. Did you see this image error when trying to start the Validator CLI 
(I see this docker issue when I restart my computer sometimes):
```shell
./shell
```
https://docs.shardeum.org/node/run/validator#step-3-open-validator-cli
?

Q2. Are you able to unstake then stake again with your current Validator?

**Comment by Roccaaa** [comment]
Q1: YES, i wasn't able to access the GUI so i open the terminal and tried to solve the problem! 

Q2: Yes, i'm able but i lost all my reward from the previous validator. Is there any way i can recover my reward? Does it have any sense?

**Comment by MarcusWentz** [comment]
What is your wallet address?

**Comment by MarcusWentz** [comment]
Q1: Did you try to fix the docker image issue with:
```shell
sudo service docker start
```
and
```shell
sudo usermod -a -G docker $USER && newgrp docker
```
https://docs.shardeum.org/node/run/validator#step-3-open-validator-cli
?

If this doesn't work: 

First uninstall the Validator:

https://docs.shardeum.org/node/run/validator#uninstall-validator

Then reinstall the Validator:   

https://docs.shardeum.org/node/run/validator#step-1-install-prerequisites

Q2: What is your wallet address?

We are tracking the lost reward issue here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/34

**Comment by Roccaaa** [comment]
why do you need it?

Il giorno sab 25 feb 2023 alle ore 01:47 Marcus Wentz <
***@***.***> ha scritto:

**Comment by MarcusWentz** [comment]
I can send you some replacement testnet SHM 
for now to make up for the lost Validator rewards and try to track the issue there too.

Please try everything listed here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/123#issuecomment-1444830686

**Comment by Roccaaa** [comment]
i recovered my staked SHM... And the new validator is up and running.  
If i will have similar problem i ll try to fix it with your instructions.

**Comment by Roccaaa** [comment]
if you want to send additional SHM you can do it at this wallet: 0xf33018e9b3fC4D24A920f1C7F96307118CcdE9bD 
it would be appreciated =)

**Comment by MarcusWentz** [comment]
Sent you some SHM now. 

If there is a new error we can open another bug report. 

If this error comes back we can reopen this bug report.
