### ISSUE TITLE
[Duplicate] Validator Stops With Error ```Fatal: Could not get seed list from seed node server. Timeout awaiting 'request' for 5000ms```

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#124]
##### What is the issue?

Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 500

#### What impact does the issue have?

stopped node

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share your info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104

**Comment by AndreiW3b3** [comment]
i am still have the same issue. i can not have an active validator for over 1 month. so annoying
