### ISSUE TITLE
Validator Stopped With No Exit Log To Debug Errors In GUI

### ISSUE THREAD

**Issue by CryptoWild999** [Shardeum/shardeum-bug-reporting#125]
I need to click the "run a node" button again. I close the dashboard, and everything looks good but after some time, if I check it again my node is stopped. 

I did it 3 times with the same result. 

I am using VPS (Linux/Ubuntu 20.04)

![ggg](https://user-images.githubusercontent.com/117856956/221292910-e5c610fe-1630-4a30-8af1-adb5342e43a8.jpg)

**Comment by MarcusWentz** [comment]
Open a terminal on your system:
```
(Press at the same time)
Ctrl + Alt + T
```

Read exit log from the:

Method 1: Terminal directly:
```shell
sudo docker exec shardeum-dashboard cat cli/build/logs/exit-summary.json
```

Method 2: Validator CLI:

Navigate to the .shardeum directory by entering:
```shell
cd .shardeum
```
Execute the shell.sh script by entering: 
```shell
./shell.sh
```
With the Validator CLI running, navigate to the cli/build/logs directory by entering:
```shell
cd cli/build/logs
```
View the contents of the exit-summary.json file by entering:
```shell
cat exit-summary.json
```

**Comment by CryptoWild999** [comment]
![shardeum](https://user-images.githubusercontent.com/117856956/221320148-02fd5982-b3e6-4a8b-a75e-b4dbc4a9133c.jpg)

There are 
![hhhhhhh](https://user-images.githubusercontent.com/117856956/221320397-821fa55b-068f-4067-84d4-0d27997336b8.jpg)
logs and the error in the dashboard. After running again the node works right around an hour. Then it stops again.

**Comment by MarcusWentz** [comment]
Thank you for finding this error in the exit log. 

Please share this info this bug report as well:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104
