### ISSUE TITLE
[Duplicate] Validator ```Add Stake``` and ```Remove Stake``` Transactions Fail With ```32603: Internal error```

### ISSUE THREAD

**Issue by bombermine3** [Shardeum/shardeum-bug-reporting#126]
I am trying to remove SHM from staking, but I get an error. It was the same before I updated the node.    
<img width="530" alt="Screenshot 2023-02-25 at 00 12 07" src="https://user-images.githubusercontent.com/84911882/221294985-e3789bdc-cca9-48f5-8005-f99cd1792012.png">
<img width="679" alt="Screenshot 2023-02-25 at 00 14 00" src="https://user-images.githubusercontent.com/84911882/221295074-2a23d72d-5489-43bb-b4d1-f0fddd9d7d54.png">

internalTXType: 7
isInternalTx: true
nominator: "0x700a023f22c4a4fbfdeed3d00b951ef8ea932be1"
nominee: "6ccc0ae3457d7e3f0a2505f191f7e1eda0c27ff0bda77372c925317f7b05aea8"
timestamp: 1677273636678

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
