### ISSUE TITLE
[Duplicate] Validator Stops Error ```Fatal: Node cannot join with invalid external IP: 0.0.0.0```

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#127]
##### What is the issue?

Node exited with following message: Fatal: Node cannot join with invalid external IP: 0.0.0.0

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share your info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/83
