### ISSUE TITLE
Validator Status ```Null``` in PuTTY

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#128]
##### What is the issue?

When I give this command to check validator status i get this back:
```shell
¨status: null¨
```

**Comment by MarcusWentz** [comment]
What OS are you using?

**Comment by AndreiW3b3** [comment]
@MarcusWentz  
linux

**Comment by MarcusWentz** [comment]
Q1. Do you have a screenshot for the issue?

Q2. What Validator Version do you have:

```shell
curl localhost:9001/nodeinfo
```

?

https://docs.shardeum.org/node/run/validator#check-installed-version

**Comment by AndreiW3b3** [comment]
How can i check what Validator Version i have ? 

By using this command:
```shell
curl localhost:9001/nodeinfo
```
?

What can i share from it as i do not what to share private information

**Comment by MarcusWentz** [comment]
This command should tell you your Validator Version. 

Do you see Validator Version 1.1.1 when you run this command?

**Comment by AndreiW3b3** [comment]
yes it is version 1.1.1

**Comment by MarcusWentz** [comment]
It is possible there was an issue installing the latest version with the old version still installed.

First uninstall the Validator:

https://docs.shardeum.org/node/run/validator#uninstall-validator

Then reinstall the Validator:

https://docs.shardeum.org/node/run/validator#step-1-install-prerequisites

Is the issue still there after doing this?

**Comment by AndreiW3b3** [comment]
i did uninstal the older version and after installed new version. but can do the process al over again when i wake up and keep you posted

**Comment by AndreiW3b3** [comment]
@MarcusWentz just an update:
i have instaled it back and i run command curl localhost:9001/nodeinfo and it still says at status ¨null¨

**Comment by MarcusWentz** [comment]
I will share this with the core team. Thank you.

**Comment by MarcusWentz** [comment]
Q1. Is your Validator running when you run this command?

Q2. Do you have a screenshot for the error? 

Q3. Can you also replace localhost with the IP address running the Validator as a test too?

**Comment by AndreiW3b3** [comment]
@MarcusWentz 

A1. i done it 2 times with both stopped and running node and still have status: null

A2.i done a screenshoot of the command curl localhost:9001/nodeinfo

A3. how do i do that?

**Comment by AndreiW3b3** [comment]
it was in active first. It exist without any issues and went to standy and after that came back with this error 
Node exited with following message:
Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist:
Timeout awaiting 'request' for
5000ms

but it still says in status in puty null

**Comment by MarcusWentz** [comment]
To write:
```
https://localhost:8080/
```
With the IP address directly for your local machine is:
```
https://0.0.0.0:8080/
```
Try to get the IP address from your terminal:
```
hostname -I
```
Then put the 4 digit IP address in this format:
```
https://<server_ip>:8080/
```

**Comment by MarcusWentz** [comment]
Share your info the timeout issue here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104
