### ISSUE TITLE
[Duplicate] Validator ```Add Stake``` and ```Remove Stake``` Transactions Fail With ```32603: Internal error```

### ISSUE THREAD

**Issue by Afitdaryanto** [Shardeum/shardeum-bug-reporting#129]
after updating for the node, and will remove the stake, can't make a transaction because of an error. I've tried in several browsers: kiwi browser, misses browser, yandex. I hope this is fixed soon.

how is it possible that users will use shardeum if the Rpc always has errors for transactions.

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Please share your info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
