### ISSUE TITLE
Balance read from erc20 is incorrect

### ISSUE THREAD

**Issue by leapuff** [Shardeum/shardeum-bug-reporting#13]
##### Overview

    balance is incorrect after transfer erc20 token

##### Context 

    After transfer 1  token to another address, balance of erc20 is incorrect if read from api/remix, but correct  from explorer

##### Resources
https://explorer-liberty20.shardeum.org/transaction/0xe2b8ad0676290b1f3d81ae98a91d3eadfff01a84cd6abefec8a9d8f21a85c4a1

**Comment by MarcusWentz** [comment]
Please share a copy of the Solidity ERC-20 contract that was deployed related to the transaction link.

**Comment by leapuff** [comment]
same as ERC-721
https://explorer-liberty20.shardeum.org/account/0xd662c28aaedbab2de2bc2a365cba7bdd14db5427

**Comment by MarcusWentz** [comment]
Does the issue still exist for ERC-20 and ERC-721 tokens? Did you see issues with ERC-1155 as well?

Please share the exact contracts you are using if the issue is still present so I can attempt to reproduce the issue.

**Comment by MarcusWentz** [comment]
I am not able to reproduce this issue while token transfers on Betanet with token standards:

    -ERC-20 
    -ERC-721 
    -ERC-1155

Please reopen the issue if:

    -the bug occurs on Betanet during testing
    -you have specific steps on how to reproduce the issue for testing
