### ISSUE TITLE
[Duplicate] Validator Staking GUI SHM Rewards Decreasing

### ISSUE THREAD

**Issue by terminator007x** [Shardeum/shardeum-bug-reporting#130]
![Screenshot (58)](https://user-images.githubusercontent.com/126277499/221340096-0532117f-07cb-48e1-9baf-354474e9cc18.png)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Please share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/45

**Comment by terminator007x** [comment]
i already updated to 1.1.1,then also my earnings are automatically decrerasing

**Comment by MarcusWentz** [comment]
Please mention that this issue is present in Validator Version 1.1.1 here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/45

**Comment by terminator007x** [comment]
so when it will be solved??

**Comment by MarcusWentz** [comment]
Track the bug report for updates:

https://github.com/Shardeum/shardeum-bug-reporting/issues/45
