### ISSUE TITLE
Validator Stopped Error ```Cannot read properties of undefined (reading 'id')```

### ISSUE THREAD

**Issue by KacperGawlik** [Shardeum/shardeum-bug-reporting#132]
##### What is the issue?

:red_circle: 
After starting node, everything works.
After some time, the node stops working and reports an error.
Cannot read properties of undefined (reading 'id')
:red_circle: 
    
#### What impact does the issue have?

:red_circle: 
The error appears in a visual way, on the node page in the "maintenance" tab
:red_circle: 

#![Screenshot_2023-02-25_155625](https://user-images.githubusercontent.com/43355194/221365213-1e3cfdfd-1721-4fd8-8834-587d8e25b1fa.png)

**Comment by MarcusWentz** [comment]
Are you able to see other error messages when you run:
```shell
sudo docker exec shardeum-dashboard cat cli/build/logs/exit-summary.json
```
https://docs.shardeum.org/node/run/validator#exit-error-logs
?

**Comment by KacperGawlik** [comment]
After typing this command, the same error message pops up.

"Cannot read properties of undefined (reading 'id')"

I also collected information in a group of people who put node together with us, they claim that they have alternately errors:

1. Cannot read properties of undefined (reading 'id')

2. Node exited with the following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms

3. Node exited with following message: Fatal: Node cannot join with invalid external IP: 0.0.0.0

For the second error, opening ports doesn't help.
In the case of the third error, exporting the server IP in the console does not help.

**Comment by ksbaskar** [comment]
<img width="795" alt="err_id" src="https://user-images.githubusercontent.com/6725456/221762921-bf48c0f1-bcc5-4800-ac6c-f10186bf4fa7.png">
Facing same issue

**Comment by earningdose** [comment]
![Screenshot_2023-03-01-07-01-27-14_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/116700183/222022688-548e5fdb-774b-4972-97e5-04cc638e8cf8.jpg)

3 days gone no solution sir ... 🥲

**Comment by sagarvd01** [comment]
I faced the same issue today after node being active for some time. This is the exit summary @MarcusWentz 

```shell
{
  "status": "Exit with error",
  "message": "Cannot read properties of undefined (reading 'id')",
  "exitTime": 1678092024011,
  "totalActiveTime": 2400000,
  "nodeInfo": {
    "id": "3eb9da16c225d7f33b2ef3e21c48f4b061cd2554583843e9b0c2d94019707240",
    "publicKey": "82b7a5af8ca3dc5578ecd03c16d44bc1a6883fe95edfe98ae855a5302d3e06                                                                                                                                                             31",
    "curvePublicKey": "b236b803dc799ec1936bbd3a7f4e5267e06e8560d7598d734455f3168                                                                                                                                                             5cc4743",
    "externalIp": "63.142.254.102",
    "externalPort": 9001,
    "internalIp": "63.142.254.102",
    "internalPort": 10001,
    "status": null
  },
  "lastRotationIndex": {
    "idx": 177,
    "total": 186
  },
  "activeNodes": 173,
  "lastActiveTime": 1678091963000
}
```

**Comment by alexkirillovtech** [comment]
Hey, I am facing same error
```shell
{
  "status": "Exit with error",
  "message": "Cannot read properties of undefined (reading 'id')",
  "exitTime": 1678914444013,
  "totalActiveTime": 3120000,
  "nodeInfo": {
    "id": "16fae42962ab13c4246736f9b3cbee169221cf59f5119abd76f03dd510cd12af",
    "publicKey": "5b8dbc662c7450b7931836de9adc1a1598e0811de6e70c119140a37fe44b8f34",
    "curvePublicKey": "f1374d2173d02fb3dedcf85312805d6ecd605f61beb498d490f79ac63ee9eb35",
    "externalIp": "185.244.183.176",
    "externalPort": 9001,
    "internalIp": "185.244.183.176",
    "internalPort": 10001,
    "status": null
  },
  "lastRotationIndex": {
    "idx": 197,
    "total": 209
  },
  "activeNodes": 180,
  "lastActiveTime": 1678914383000
```

**Comment by swarna1101** [comment]
The issue affecting validator nodes is acknowledged and being actively addressed by our development team. However, due to the intricacies involved in the fix, it necessitates additional refinement and validation before deployment. The team is diligently working on this to ensure a comprehensive and robust solution in the subsequent update after the next one.
