### ISSUE TITLE
[Duplicate] Validator GUI Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.```

### ISSUE THREAD

**Issue by Tobbymaster** [Shardeum/shardeum-bug-reporting#133]
##### What is the issue?

I forgot to unstake from old node and installed new node , but now the new node displays on dashboard below error. Refer attched image as well.
"This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node."
    
#### What impact does the issue have?

It does not let me unstake from old node, let me know how can that be done. Refer attached images for error type.

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?
![Screenshot 2023-02-25 221349](https://user-images.githubusercontent.com/123926897/221369011-ddac4883-7a9b-4290-980f-e9c097e889ae.jpg)

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Please share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
