### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.```

### ISSUE THREAD

**Issue by Viktor0102** [Shardeum/shardeum-bug-reporting#134]
When upgrading a node, it asks to remove the bid from the last node! I press "remove" and there is an instant error in the metamask! what to do about it? due to this error, I started using another wallet! is that bad?
![777](https://user-images.githubusercontent.com/107187072/221370350-fb908f86-6c54-4ae0-a560-0c42f3ae59e4.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
