### ISSUE TITLE
[Duplicate] Validator GUI Not Connecting To ```<server_ip>:8080```

### ISSUE THREAD

**Issue by Noah407** [Shardeum/shardeum-bug-reporting#135]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Do you have a screenshot?

**Comment by Noah407** [comment]
![Screenshot (82)](https://user-images.githubusercontent.com/118976162/221370879-2867b000-06ce-4b3a-9962-b7e662a1856a.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85
