### ISSUE TITLE
[Duplicate] Validator GUI Not Connecting To ```<server_ip>:8080```

### ISSUE THREAD

**Issue by Noah407** [Shardeum/shardeum-bug-reporting#136]
I tried connecting to my Shardeum Dashboard but i keep getting this response 'refused to connect' 
An image description is attached 
![Screenshot (82)](https://user-images.githubusercontent.com/118976162/221370774-0d232690-a7b5-4da8-9aa7-ad2cdbf960e2.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.  

Share this screenshot and more info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85

**Comment by Noah407** [comment]
ok
