### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.```

### ISSUE THREAD

**Issue by crbaa** [Shardeum/shardeum-bug-reporting#137]
This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.
My wallet address: 0x55543e721A5278EC9940c0E4966759Bd63F6F571

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
