### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by simpletox** [Shardeum/shardeum-bug-reporting#138]
##### What is the issue?
Hello, my problem is related to giving and taking Stake, when I want to start a node it stops with the following message: "Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms" also when adding a Stake and removing it, it fails. I tried many times to repeat and reset my wallet account, it did not help either, here is my wallet: 0x0273E2baeda85Ea361f52380DBb1a5f3Ec142B26
I understand that this is most likely a problem with RPC, but I will be very grateful if the team finds a solution to this problem
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?
![Знімок екрана (973)](https://user-images.githubusercontent.com/101927107/221379679-88235de2-cac5-4f11-b6b8-2e6704987a91.png)

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
