### ISSUE TITLE
[Duplicate] Validator Stopped With Error ```removed from network in normal conditions```

### ISSUE THREAD

**Issue by anshutalk** [Shardeum/shardeum-bug-reporting#139]
Node exited with following message:  removed from network in normal conditions 
as a result of this error shm earning getting reset from 25-30shm to 3-5shm depends on last earning, this was happening again and again 
![Screenshot_20230220_221043](https://user-images.githubusercontent.com/116296314/221393950-7e3d2961-970e-4a55-91f8-c65d2a5b488a.png)
![image](https://user-images.githubusercontent.com/116296314/221393975-efc4f581-acea-471a-9cfa-21567f431763.png)
![image](https://user-images.githubusercontent.com/116296314/221393982-b8cb4ea9-a7d9-49e8-bf0a-6a1dcefbade5.png)

_Originally posted by @anshutalk in https://github.com/Shardeum/shardeum-bug-reporting/issues/72#issuecomment-1445272794_

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/72
