### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by Danieladedapo** [Shardeum/shardeum-bug-reporting#140]
This is the error code I am getting
Failed transaction
Transaction 1 failed! [ethjs-query] while formatting outputs from RPC ""value":
{"code":-32603, "data":
("code"-32603, "message", "Internal error"))

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92

**Comment by Gujaratojas** [comment]
On removing these stakes, transaction failing.
