### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Node cannot join with invalid external IP: 0.0.0.0```

### ISSUE THREAD

**Issue by MrOD4321** [Shardeum/shardeum-bug-reporting#142]
##### What is the issue?

The configured APP-IP has been set and the node is running, the node crashed due to another reason. Restart the node, the node is running but crashes again with the 'Fatal: Node cannot join with invalid external IP: 0.0.0.0'. The command 'Echo $APP_IP' is showing auto again and must be reconfigured with the public IP.
    
#### What impact does the issue have?

Causes the node to exit, requires the public IP to be configured again and then the node must be restarted.

##### How to reproduce the issue? 

Validator version 1.1.1.
Public IP is configured with the 'export APP_IP' command and the node is running.
The node crashed or stopped, mainly because the node exited after it was active, this happens roughly 1 time per day.
Restart the node. 
The node crashes relatively shortly with the 'Fatal: Node cannot join with invalid external IP: 0.0.0.0' error.
The command 'Echo $APP_IP' is showing auto again and must be manually reconfigured again with the public IP.
Restart the node.

##### What other resources can you share regarding this issue?

![image](https://user-images.githubusercontent.com/106428309/221406714-47fe708f-c360-497e-a8cd-b72f92d09316.png)
![image](https://user-images.githubusercontent.com/106428309/221406729-38f58bfe-5db1-41a5-87cb-8eb48fe783fe.png)

New bug opened based on this comment: https://github.com/Shardeum/shardeum-bug-reporting/issues/83#issuecomment-1441706449

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/83
