### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Could not get seed list from seed node server. Timeout awaiting 'request' for 5000ms```

### ISSUE THREAD

**Issue by LorisYanis** [Shardeum/shardeum-bug-reporting#143]
![Screenshot_20230226_183224](https://user-images.githubusercontent.com/115280526/221423514-828c44ea-c0d1-40d2-b0a1-5ad3b540935f.png)

Got this error even though everything is fine with my server.

Frankly speaking, I have no idea why this could happen, most likely something wrong with the source files, please pass this error to the developers.

**Comment by cnlcy** [comment]
I have the same issue

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104
