### ISSUE TITLE
Validator Install Outside Root Directory

### ISSUE THREAD

**Issue by LorisYanis** [Shardeum/shardeum-bug-reporting#144]
When I'm trying to install shardeum node to custom directory, I get these errors:

![1](https://user-images.githubusercontent.com/115280526/221424821-b96e6d61-0ec7-4ca7-a416-a2b4dd3e5843.png)
![2](https://user-images.githubusercontent.com/115280526/221424827-a0e53303-5221-462a-b129-74061313b551.png)
![3](https://user-images.githubusercontent.com/115280526/221424838-30e10695-5a00-4564-afcc-124a07589bf7.png)
![4](https://user-images.githubusercontent.com/115280526/221424842-c77bf65b-dd5b-46da-9df4-02704d47329e.png)

Most likely the problem lies in a bad installation script that aims to install only one directory.

My discord: Yanis Irving#0886 | Wallet: 0x972A1af4549FDe3b69604f1449b360B312836fE8

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104

**Comment by MarcusWentz** [comment]
Can you install in the root directory for now?

**Comment by LorisYanis** [comment]
> Can you install in the root directory for now?

Yes I can. That's what I did. But I prefer to use custom directories, and this is what I encountered when I tried it

**Comment by MarcusWentz** [comment]
Validator Version 1.1.5 is out now. 

Upgrade to this latest version.

If you still see this issue then we can reopen the issue.
