### ISSUE TITLE
[Duplicate] Validator Error ```Problem with node operation, dashboard```

### ISSUE THREAD

**Issue by serhiiqw** [Shardeum/shardeum-bug-reporting#146]
##### What is the issue?

:red_circle:  the node works for 10 seconds and turns itself off, the dashboard is not active
attempts: to update the client, node, restart the node - did not help :red_circle: 
    
#### What impact does the issue have?

:red_circle: Node not working, dashboard not active. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
The node worked for a week, is not active, there were coins on the balance, no rewards were received for 3-4 days

![1](https://user-images.githubusercontent.com/95383379/221455586-5e0f9dab-2dba-4808-94c1-2cfff8ba2ea6.png)
![binare](https://user-images.githubusercontent.com/95383379/221455587-433da774-c9b2-4b83-b2b1-3a32afe93d69.png)
![Untitled](https://user-images.githubusercontent.com/95383379/221455590-722c8f94-a8f4-4735-b4af-b1b6a712a51c.png)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/145
