### ISSUE TITLE
[Duplicate] Validator GUI Pages Randomly Not Loading ```Application error: a client-side exception has occurred```

### ISSUE THREAD

**Issue by CHINGIZ8** [Shardeum/shardeum-bug-reporting#147]
The page didn't load. After restarting the container, it loads as in the screenshot
![image](https://user-images.githubusercontent.com/121540462/221475071-12341234-02b1-432d-b3c1-e9de41045051.png)

**Comment by CHINGIZ8** [comment]
![image](https://user-images.githubusercontent.com/121540462/221480517-f353581d-53f9-40a9-87c8-4b1a220a62f5.png)

**Comment by CHINGIZ8** [comment]
I don't see a solution

**Comment by MASTAN82** [comment]
i did nt see solution

**Comment by 0xmtnslk** [comment]
![shardeum](https://user-images.githubusercontent.com/106913323/221485713-f92b025d-b19d-4fc1-b684-79fe42c2b667.png)
Node interface not working. Node seems to be stopped via terminal. I checked all the steps. But the problem persists.

**Comment by Hyperpepe** [comment]
![image](https://user-images.githubusercontent.com/74920047/221487004-78910da6-12f1-4a06-aa8b-03da3df544dd.png)
i also reinstall it 
but it still not working

**Comment by rirasel55** [comment]
Same to ne

**Comment by Ziki7Cheng** [comment]
metoo
![validator GUI no load](https://user-images.githubusercontent.com/126446612/221491951-64a79d6d-f4f5-40f1-83cc-0be1ebff7ffd.png)

**Comment by MrOD4321** [comment]
Same here, crashed around 6 hours and 20 min ago.

    _currentUrl: 'http://archiver-sphinx.shardeum.org:4000/nodelist',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 3.127.57.166:4000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '3.127.57.166',
    port: 4000
  }
}
/home/node/app/cli/build/src/utils/fetch-network-data.js:43
        throw new Error('Unable to fetch list of nodes in the network');
              ^

Error: Unable to fetch list of nodes in the network
    at getActiveNode (/home/node/app/cli/build/src/utils/fetch-network-data.js:43:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:14:9)
    at async fetchStakeParameters (/home/node/app/cli/build/src/utils/fetch-network-data.js:129:25)
    at async Promise.all (index 0)
    at async /home/node/app/cli/build/src/node-commands.js:110:98

**Comment by sedarat** [comment]
> Same here, crashed around 6 hours and 20 min ago.
> 
> ```
> _currentUrl: 'http://archiver-sphinx.shardeum.org:4000/nodelist',
> [Symbol(kCapture)]: false
> ```
> 
> }, cause: Error: connect ECONNREFUSED 3.127.57.166:4000 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) { errno: -111, code: 'ECONNREFUSED', syscall: 'connect', address: '3.127.57.166', port: 4000 } } /home/node/app/cli/build/src/utils/fetch-network-data.js:43 throw new Error('Unable to fetch list of nodes in the network'); ^
> 
> Error: Unable to fetch list of nodes in the network at getActiveNode (/home/node/app/cli/build/src/utils/fetch-network-data.js:43:15) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:14:9) at async fetchStakeParameters (/home/node/app/cli/build/src/utils/fetch-network-data.js:129:25) at async Promise.all (index 0) at async /home/node/app/cli/build/src/node-commands.js:110:98

Should we enter these new commands?

**Comment by duong-dang** [comment]
I do the same thing

**Comment by Cyb3rNodes** [comment]
Same here. The dashboard is empty now.

**Comment by Cryptohito** [comment]
Stop the node and wait for update.

**Comment by Sebatron777** [comment]
I have  same problem) 
![image](https://user-images.githubusercontent.com/79991401/221530374-10ed56a0-2acf-4e9c-8045-d48d7538acd7.png)

![image](https://user-images.githubusercontent.com/79991401/221530446-937bc840-75b1-4b88-95d0-6595d77bad4a.png)

**Comment by rizpk** [comment]
Had same issue i tried the following: 
operator-cli stop
operator-cli gui stop

and start it again

operator-cli gui start
operator-cli start

**Comment by MarcusWentz** [comment]
Seems to be fixed after uninstalling then reinstalling the latest validator version.
