### ISSUE TITLE
[Duplicate] Validator GUI Tabs Load However Content Does Not Load

### ISSUE THREAD

**Issue by MASTAN82** [Shardeum/shardeum-bug-reporting#148]
my shardeum node dash board showing error and not showing anything
![Screenshot_2023-02-27-10-17-54-51_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/119680467/221477739-e6dfeae8-13b0-4a05-a063-e924c5ee0a67.jpg)

**Comment by MASTAN82** [comment]
please sort out this issue

**Comment by MASTAN82** [comment]
please respond 94.131.113.122

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/147

**Comment by MASTAN82** [comment]
what to do now?
what solution you said
