### ISSUE TITLE
[Duplicate] Validator GUI Tabs Load However Content Does Not Load

### ISSUE THREAD

**Issue by MASTAN82** [Shardeum/shardeum-bug-reporting#149]
my dashboard showing empty
![Screenshot_2023-02-27-10-17-54-51_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/119680467/221481905-20f181b5-315d-4b34-a43e-fc872d746c12.jpg)

plese help sort out issue  
what to do ?

**Comment by MASTAN82** [comment]
Marcus Wentz  please tell solution 
donot tell this solution
Duplicate issue.

please tell solution of ,dasboard  empty, please

**Comment by MarcusWentz** [comment]
https://github.com/Shardeum/shardeum-bug-reporting/issues/147#issuecomment-1447714424
