### ISSUE TITLE
[Duplicate] Validator Stopped Lost Stake Reward 

### ISSUE THREAD

**Issue by farooq12786** [Shardeum/shardeum-bug-reporting#151]
##### What is the issue?

:red_circle:  I started getting rewards after my node become active validator. and when on next cycle the rewards become zero . :red_circle: 
    
#### What impact does the issue have?

:red_circle: It impacts total rewards accumulated so far. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    We cannot manually reproduce it . Suppose if your node becomes active for the second time , the rewards accumulated so far was vanishned.
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue. Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/34
