### ISSUE TITLE
[Duplicate] Validator GUI Tabs Load However Content Does Not Load

### ISSUE THREAD

**Issue by szefo8181** [Shardeum/shardeum-bug-reporting#152]
Did anyone solve the problem with dashboard is empty, what's wrong?

![shardeum error](https://user-images.githubusercontent.com/81183952/221518042-91a2e7af-bc2c-47ec-b326-c41072252bc8.jpg)

**Comment by MarcusWentz** [comment]
https://github.com/Shardeum/shardeum-bug-reporting/issues/147#issuecomment-1447714424
