### ISSUE TITLE
Validator Stopped Error ```Could not get seed list from seed node server connect ECONNREFUSED```

### ISSUE THREAD

**Issue by hieuwb** [Shardeum/shardeum-bug-reporting#154]
![image](https://user-images.githubusercontent.com/54319153/221538333-e8dac6cc-83c0-46bc-b37e-2b94ca7cc8c3.png)
.
STATUS:
```
node@2afaaa091a59:~/app$ operator-cli status
state: stopped
exitMessage: >-
  Fatal: Could not get seed list from seed node server
  http://archiver-sphinx.shardeum.org:4000/nodelist: connect ECONNREFUSED
  3.127.57.166:4000
exitStatus: Exit with error
performance:
  memPercentage: 95.59750072419453
  diskPercentage: 62.67585294950293
  cpuPercentage: 20.698254364089774
stakeRequirement: '10.0'
lockedStake: '11.0'
nominatorAddress: '0x664784b2a4019b85aa095488efa86fce4e85d8a6'
```

**Comment by hieuwb** [comment]
![image](https://user-images.githubusercontent.com/54319153/221539274-b25115b2-139a-4589-85f6-bc0f4ae41778.png)

**Comment by earningdose** [comment]
![image](https://user-images.githubusercontent.com/116700183/221606198-38a3956b-fdb7-46a1-aba0-a265e50e0ecd.png)
Same Error I'm facing right now
running node is full of bug 😢

**Comment by DEEPAK05399** [comment]
It just stopped after getting active. I resumed it and again I'm getting same error.

**Comment by creador-dev** [comment]
I am also facing the same issue.

**Comment by zklim** [comment]
I got this error too

**Comment by Daraming** [comment]
me too

**Comment by Ezebrown** [comment]
just restart the node

**Comment by swarna1101** [comment]
Check Network and Server: Ensure stable internet connectivity and verify the availability of the server at http://archiver-sphinx.shardeum.org:4000/nodelist.

Restart Node: An immediate solution is to restart the node. This action can often resolve transient connection issues and help re-establish the connection to fetch the required seed list.
