### ISSUE TITLE
BALANCE IS SHOWING INCORRECTLY 

### ISSUE THREAD

**Issue by LIHebzy** [Shardeum/shardeum-bug-reporting#155]
My reward is 45shm now this is what i am seeing
![Bug](https://user-images.githubusercontent.com/119897053/221580542-e72527ad-7b95-4d4b-b6d1-5e64052ad29d.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/34

**Comment by LIHebzy** [comment]
![lol](https://user-images.githubusercontent.com/119897053/221788031-3ae79484-2871-406b-a6ca-b6f40c372936.jpg)
I also have this error after my reward refreshed and i started it again

**Comment by LIHebzy** [comment]
Couldn't find an answer
