### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Could not get seed list from seed node server. Timeout awaiting 'request' for 5000ms```

### ISSUE THREAD

**Issue by jerizhangWeb3th** [Shardeum/shardeum-bug-reporting#156]
##### What is the issue?

:red_circle:  [Describe the error in simple terms](rror: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms). :red_circle: 
   Use `node --trace-deprecation ...` to show where the warning was created)
Error: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms
    at evalmachine.<anonymous>:1:154262
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at T (evalmachine.<anonymous>:1:154013)
    at Object.startup (evalmachine.<anonymous>:1:155750)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4885:5
(node:21452) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104
