### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by honeztwo** [Shardeum/shardeum-bug-reporting#157]
# What is the issue?
```
 This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.
 ```   
#### What impact does the issue have?

:red_circle: i want to reinstall my node because of i got frequantly stopped and diffrent eror so i decided to a clean setup . i use same ip, same vps ,but i got this eror .:red_circle: 

```
before this eror i got two different issue ;

1- "Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms "

2 - "Node exited with following message: Fatal: Node cannot join with invalid external IP: 0.0.0.0"
```

# After my new setup i got this ;

:red_circle: Photos and links related to the error. :red_circle: 
![Screenshot_1](https://user-images.githubusercontent.com/95377480/221649175-12bc9c05-e5c8-4f00-80bd-4f23e55e6c24.png)

Also i cant restake my shm or stake on  my new node , All Transaction got failed.

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
