### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Could not get seed list from seed node server. Timeout awaiting 'request' for 5000ms```

### ISSUE THREAD

**Issue by lancecruxx** [Shardeum/shardeum-bug-reporting#158]
PLS SHARDEUM TEAM,am begging you for God sake pls fix this issues of

"Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms"
before you come at me and ask if i opened port 4000 or all other stuff i've tried alll the guides in your discord and this errors still occur, it's actually two the one of external ip too and the moment i fixed external ip, the first error will appear again, the momement i fixed the first error, the second will appear again, it's bouncing btween them, this have happpened to 100 of users running your node pls fix this pls!!!

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/104
