### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Could not get seed list from seed node server. Timeout awaiting 'request' for 5000ms```

### ISSUE THREAD

**Issue by Ramfreepi** [Shardeum/shardeum-bug-reporting#159]
**Node exited with following message: 
Fatal: Could not get seed list from seed node server 
http://archiver-sphinx.shardeum.org:4000/nodelist: 
Timeout awaiting 'request' for 5000ms**

hi, above massage show and my node is stopped just after few minutes when i run . always need to manually start.
and always showing standby.

please help me to getting from it.
![221361006-08c44e8e-ad1e-4322-9b37-4021c89274a6](https://user-images.githubusercontent.com/121171910/221768232-5f9b68ea-7cb9-4a22-9967-a5bb14d7b651.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104

**Comment by Ramfreepi** [comment]
#104 

Node exited with following message:
Fatal: Could not get seed list from seed node server
http://archiver-sphinx.shardeum.org:4000/nodelist:
Timeout awaiting 'request' for 5000ms

hi, above massage show and my node is stopped just after few minutes when i run . always need to manually start.
and always showing standby.

please help me to getting from it.
![221361006-08c44e8e-ad1e-4322-9b37-4021c89274a6](https://user-images.githubusercontent.com/121171910/221842995-91e9c0aa-1b3e-4958-8c30-1eaef835cdba.png)
