### ISSUE TITLE
RPC ```eth_estimateGas``` for `gasLimit` not warning about a potential transaction going to revert from

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#16]
##### Overview

EVM RPC does not detect transactions that are expected to revert.
This feature helps prevent users from sending transactions that will fail.
Adding this feature will save users gas and time.

##### Context 

Test by setting the storage value to be the same as its current value with ```set(uint x)``` function:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.7;

error sameStorageValue();

contract SimpleStorage {

    uint public storedData;  //Do not set 0 manually it wastes gas!

    event setOpenDataEvent(); 

    function set(uint x) public {
        if(storedData == x) { revert sameStorageValue(); }        
        storedData = x;
        emit setOpenDataEvent();
    }

}
```

Goerli has warnings in: 

-Remix IDE:

![remixIDE](https://user-images.githubusercontent.com/52706599/210273519-5314c15c-5724-4e3b-a1ce-3119e78f2c45.png)

-Metamask:

![metamaskEtherscan](https://user-images.githubusercontent.com/52706599/210273492-5f9ffbf9-8377-418a-b789-571798eb2e12.png)

Shardeum has no warning about a transaction that is about to be sent failing:

![shardeumNoWarning](https://user-images.githubusercontent.com/52706599/210273619-4042eaac-88d7-42ea-a974-c7d3cc9ad434.png)

##### Resources

Goerli test verified contract:

https://goerli.etherscan.io/address/0x080FfD52b6c217C1B69a03446f2956580e25fd43#code

Shardeum contract (same as Goerli verified contract):

https://explorer-liberty20.shardeum.org/account/0x68611038f494be3173f6f93daee756ca85aa4a54?page=1

**Comment by MarcusWentz** [comment]
Metamask seems to detect transactions from potentially reverting
based on contract calls before they are signed for gas estimations:

https://ethereum.stackexchange.com/a/110957

**Comment by MarcusWentz** [comment]
Test gas estimation with RPC method:

```shell
curl https://liberty20.shardeum.org/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_estimateGas","params":[{
                                                 "from":"0x66C1d8A5ee726b545576A75380391835F8AAA43c",
                                                 "to":"0xd3CdA913deB6f67967B99D67aCDFa1712C293601",
                                                 "value":"0x186a0"
                                                }],
"id":1,"jsonrpc":"2.0"}'
```

Returns:

```shell
{"jsonrpc":"2.0","id":1,"result":"0x1C9C380"}
```

A smart contract with simple revert branch paths 
based on different transaction data would be good to see if the estimated gas price changes as it should.

RPC method ```eth_estimateGas``` reference:

https://www.quicknode.com/docs/ethereum/eth_estimateGas

**Comment by MarcusWentz** [comment]
```eth_estimateGas``` has a fixed value on Liberty 2.X.

Test cases will be created comparing Liberty 2.X and Goerli success fail paths with ```eth_estimateGas```.

**Comment by MarcusWentz** [comment]
Test confirms that Liberty 2.X has a constant gas estimation even when the transaction will revert:

```javascript
const ethers = require("ethers");

//Goerli
const provider = new ethers.providers.JsonRpcProvider(process.env.goerliHTTPS_InfuraAPIKey)
const contractAddress = '0x080FfD52b6c217C1B69a03446f2956580e25fd43'

//Betanet 1.X
// const provider = new ethers.providers.JsonRpcProvider("https://sphinx.shardeum.org/")
// const contractAddress = '0xD55b6893779d64756Ed0162579f54F2Fc83bAC24'

const contractABI = [{"inputs":[],"name":"sameStorageValue","type":"error"},{"anonymous":false,"inputs":[],"name":"setOpenDataEvent","type":"event"},{"inputs":[{"internalType":"uint256","name":"x","type":"uint256"}],"name":"set","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"storedData","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}]

const signer = new ethers.Wallet(Buffer.from(process.env.devTestnetPrivateKey, 'hex'), provider);

const contractDeployed = new ethers.Contract(contractAddress, contractABI, signer);

estimateGasTests()

async function estimateGasTests() {

  const unixTIme = Date.now();
  const callDataObjectSuccess = await contractDeployed.populateTransaction.set(unixTIme);
  const txDataSuccess = callDataObjectSuccess.data;

  const estimateGasSuccess = await provider.estimateGas({
    to: contractAddress,
    data: txDataSuccess,
  });
  console.log(estimateGasSuccess);

  const storedDataValue = await contractDeployed.storedData()
  const callDataObjectFail = await contractDeployed.populateTransaction.set(storedDataValue);
  const txDataFail = callDataObjectFail.data;

  try{
      const estimateGasFail = await provider.estimateGas({
        to: contractAddress,
        data: txDataFail,
      });
      console.log("🔴 Test failed! Gas estimation should not be possible when REVERT opcode is executed.")
      console.log(estimateGasFail);
  } catch (error) {
      console.log("🟢 Test successful! RPC method eth_estimateGas as expected failed to estimate gas, transaction will most likely revert.")
  }

}
```

Goerli:

```javascript
BigNumber { _hex: '0xae2b', _isBigNumber: true }
🟢 Test successful! RPC method eth_estimateGas as expected failed to estimate gas, transaction will most likely revert.
```

Betanet 1.X:

```javascript
BigNumber { _hex: '0x01C9C380', _isBigNumber: true }
🔴 Test failed! Gas estimation should not be possible when REVERT opcode is executed.
BigNumber { _hex: '0x01C9C380', _isBigNumber: true }
```

**Comment by swarna1101** [comment]
Upon testing in the new network version 1.7.1, it has been verified that the EVM RPC now correctly identifies transactions that are expected to revert. This enhancement will significantly assist users by saving both gas and time, preventing unnecessary transaction attempts that would have otherwise failed
