### ISSUE TITLE
EXIT WITH ERROR

### ISSUE THREAD

**Issue by LIHebzy** [Shardeum/shardeum-bug-reporting#160]
![lol](https://user-images.githubusercontent.com/119897053/221789050-2ce96771-fe8c-4e99-b089-f0965fe010d2.jpg)
I also have this error after my reward refreshed and i started it again

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/132
