### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by pvsairam** [Shardeum/shardeum-bug-reporting#161]
##### What is the issue?

:red_circle:  I have reinstalled the validator node without unstaking the SHM and I am not getting the error - "This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node."  :red_circle: 

![image](https://user-images.githubusercontent.com/9134015/221826030-29fa06ba-4174-410a-94b6-7f0bed2358c8.png)
    
#### What impact does the issue have?

:red_circle: Unable to unstake or add stake with the existing wallet as well as brand new wallet. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    - Install and Run the validator node
    - now stake SHM
    - Without unstaking the SHM, just reinstall the validator node and try to connect with existing wallet.
    - An error will appear - This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.
    - You should not able to stake SHM either with existing/old wallet or brand new wallet.
    
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Existing Wallet address - 0x3e407f4158440F1e5a9E6BA98b0198AEA6d837E3 :red_circle:
:red_circle: New wallet address - 0x5a0b42A7806687A4fb32AA6fe410FEc60257D147 :red_circle:
:red_circle: I am unable to stake with both old and new wallet addresses. :red_circle:

:red_circle: ![image](https://user-images.githubusercontent.com/9134015/221826242-7a3af537-1a84-4b79-9985-bc30dc235a91.png). :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
