### ISSUE TITLE
Validator Stopped Error ```FailAndRestartPartition_globalReport_B``` and Validator CLI ```operator-cli status``` returns ```TypeError: Cannot read properties of undefined (reading 'idx')```

### ISSUE THREAD

**Issue by AndrewFucher** [Shardeum/shardeum-bug-reporting#162]
##### What is the issue?

[1] In one moment my node started giving this error when I request status: FailAndRestartPartition_globalReport_B. Also whenever I execute command `operator-cli status` I get following error: 

[2]
```
/home/node/app/cli/build/src/node-commands.js:172
                        ? `${nodeProgress.lastRotationIndex.idx}/${nodeProgress.lastRotationIndex.total}`
                                                            ^

TypeError: Cannot read properties of undefined (reading 'idx')
    at /home/node/app/cli/build/src/node-commands.js:172:61
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
    
#### What impact does the issue have?

My node is not working because of it. Stopping and restarting does not help.

##### How to reproduce the issue? 

Error [1] can be found when executing command `sudo docker exec shardeum-dashboard cat cli/build/logs/exit-summary.json`.
Error [2] can be found when executing command `operator-cli status` within provided shell.

##### What other resources can you share regarding this issue?

I cannot think of anything helpful.

**Comment by 1613557499** [comment]
So what's the solution?
@MarcusWentz

**Comment by MarcusWentz** [comment]
@1613557499 

Q1. What do you see when you run:
```shell
curl localhost:9001/nodeinfo
```
?
Q2. What do you see when you run:
```shell
cat cli/build/logs/exit-summary.json
```
?
Q3. What do you see when you run:
```
tail cli/build/logs/fatal.log
```
?

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
