### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Could not get seed list from seed node server. Timeout awaiting 'request' for 5000ms```

### ISSUE THREAD

**Issue by terminator007x** [Shardeum/shardeum-bug-reporting#164]
Automatically node is stopping with the error given below
![Screenshot (73)](https://user-images.githubusercontent.com/126277499/222431604-7e10352e-1201-42f5-bc90-68cb6b36467e.png)

**Comment by 666btc** [comment]
i have the same error 2 times and no one knows how to solve it

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104
