### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Node cannot join with invalid external IP: 0.0.0.0```

### ISSUE THREAD

**Issue by 666btc** [Shardeum/shardeum-bug-reporting#165]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    at the first when i run the node i have the issue that [Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms]
and then appear the issue which i mentioned in the title
![Снимок экрана_20230302_172835](https://user-images.githubusercontent.com/126798940/222474308-4f774b77-d0b8-422f-8ec9-300f34b9c669.png)
![Снимок экрана_20230302_170350](https://user-images.githubusercontent.com/126798940/222474359-f5b651fa-2682-4c68-90e3-8e917c1c035c.png)

#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/83
