### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Could not get seed list from seed node server. Timeout awaiting 'request' for 5000ms```

### ISSUE THREAD

**Issue by zklim** [Shardeum/shardeum-bug-reporting#166]
##### What is the issue?

:red_circle:  Node stop itself with error. :red_circle: 
    
#### What impact does the issue have?

:red_circle: It stops the node :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
start running the node, check back after one day, exit with error code
`Fatal: Could not get seed list from seed node server
  http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request'
  for 5000ms`

and this error message too:
`Fatal: Could not get seed list from seed node server
  http://archiver-sphinx.shardeum.org:4000/nodelist: connect ECONNREFUSED 3.127.57.166:4000`
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle:
![Capture](https://user-images.githubusercontent.com/53001910/222630248-54264159-ee31-4c03-8874-30d122121c0c.PNG)

![2](https://user-images.githubusercontent.com/53001910/222630403-ffa1c7ab-06be-42a5-8e2f-6bbd2c49bc4a.PNG)

 :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104
