### ISSUE TITLE
Validator Stopped And Still Not Active After A Week

### ISSUE THREAD

**Issue by f4slu** [Shardeum/shardeum-bug-reporting#167]
##### What is the issue? node stopping some times and it doest active i have been using it for a week.

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have? critical tension

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
What error message do you see when the validator stops?

**Comment by MarcusWentz** [comment]
Validators join the network based on network demand.

**Comment by MarcusWentz** [comment]
What error message do you see when your validator stops?

**Comment by MarcusWentz** [comment]
Validator Version 1.1.5 is out now. 

Upgrade to this latest version.

If you still see this issue then we can reopen the issue.
