### ISSUE TITLE
SwappedFinance Swap Transaction Fails

### ISSUE THREAD

**Issue by Artem1422** [Shardeum/shardeum-bug-reporting#168]
Can’t swap USDC - SWPD 0xdde8e291e062d32f242903bb7154b5c875f869988353f7cbc71672c4e8b4bdc2
and SWPD - SHM 0x2c6bbea50f5103f3b1d0611d1b0086151a0995cc8e720647ce5dfe7cc80408e8

All pools added successful.
![Снимок экрана 2023-03-03 в 11 18 32](https://user-images.githubusercontent.com/100275308/222657556-97a4943d-e276-4939-a265-1d09b865e68a.png)
![Снимок экрана 2023-03-03 в 11 21 19](https://user-images.githubusercontent.com/100275308/222657575-22ac8489-c8c7-4393-b5b9-f702e58f1f9d.png)

**Comment by MarcusWentz** [comment]
Are you on Liberty 2.X or Betanet 1.X?

**Comment by MarcusWentz** [comment]
Liberty 2.X:

40 SWPD to SHM:

https://explorer-liberty20.shardeum.org/tx/0xe2174a49c3836582bba38b2398d8d7d7f66cbc6c177d3c490f4e42cbaf5d6ebb

0.01 USDC FOR SWPD:

https://explorer-liberty20.shardeum.org/tx/0x6c2375d5b7e88887c944ae15663c7ca8c63b5299ae0e1f46c1ac7b78656de152
