### ISSUE TITLE
RPC `eth_getLogs`  fails with log filters `fromBlock` and `toBlock` in block (Shardeum bundle) range

### ISSUE THREAD

**Issue by leapuff** [Shardeum/shardeum-bug-reporting#17]
##### Overview

RPC method ```eth_getlogs``` fails with log filters ```fromBlock``` and ```toBlock```.

##### Context 
```javascript
curl --location --request POST 'https://liberty20.shardeum.org/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "fromBlock": 197136,
            "toBlock": 197369
        }
    ],
    "id": 8081
}'
```

```javascript
{
    "jsonrpc": "2.0",
    "id": 8081,
    "result": "test"
}
```

#### Resources

RPC method eth_getLogs specification:

https://www.quicknode.com/docs/ethereum/eth_getLogs

**Comment by MarcusWentz** [comment]
I tested Ethereum Mainnet and this worked: 

```shell
curl $mainnetHTTPS_InfuraAPIKey \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getLogs","params":[{
                                             "fromBlock": "latest" ,
                                             "toBlock": "latest" 
          }],"id":1,"jsonrpc":"2.0"}'
```

I tested Liberty 2.1

(Note: "id" doesn't seem like the chainId for the JSON RPC data, but tried it with 8081 as well but got the same result you did https://ethereum.stackexchange.com/questions/50647/json-rpc-api-id)

```shell
curl https://liberty20.shardeum.org/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getLogs","params":[{
                                             "fromBlock": "latest" ,
                                             "toBlock": "latest" 
          }],"id":1,"jsonrpc":"2.0"}'
```

I will discuss with the core team.

**Comment by MarcusWentz** [comment]
RPC ```eth_getLogs``` is currently not supported no Shardeum. 

This RPC will be added at or after Betanet.

**Comment by MarcusWentz** [comment]
Would this JSON RPC URL filter log work for now: 

https://explorer-liberty20.shardeum.org/api/log?address=0xd9bb7242d8fc9c8e46ddf4337caaf76e7216adc0&page=1 

?

A user interface for this: 

https://explorer-liberty20.shardeum.org/log?address=0xd9bb7242d8fc9c8e46ddf4337caaf76e7216adc0

**Comment by leapuff** [comment]
Yes, its worked for explorer api. But it could be better once `https://liberty20.shardeum.org/` can be used for.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/93641386/215446554-eecd57a8-0983-4018-ba06-9e0faaeefdf5.png">

**Comment by allush** [comment]
> Yes, its worked for explorer api. But it could be better once `https://liberty20.shardeum.org/` can be used for. <img alt="image" width="477" src="https://user-images.githubusercontent.com/93641386/215446554-eecd57a8-0983-4018-ba06-9e0faaeefdf5.png">

Yes, I wait for implementation as well. @MarcusWentz

**Comment by MarcusWentz** [comment]
@leapuff @allush 

The core team said they will look into adding more data to blocks (Shardeum bundles) as this also impacts:

https://github.com/Shardeum/shardeum-bug-reporting/issues/40
