### ISSUE TITLE
Validator Update Error ```Waiting for cache lock could not get lock /var/lib/dpkg/lock-frontend. It is held by process 2930 (apt)```

### ISSUE THREAD

**Issue by saddamnexus** [Shardeum/shardeum-bug-reporting#171]
##### What is the issue?

:red_circle:  
    Is there any issue on node setup
I get error from yestarday afternoon 
I attached the picture of my issue 
After running my 1st command:-  sudo apt update && apt upgrade -y
thus issue reflect.

Help me please

Any update 
If there is any solution to this kindly help me out.

Sir any update regarding my issue 😢😢
![IMG_20230303_143043_058](https://user-images.githubusercontent.com/126864647/222679214-bd018b49-45c0-415d-8814-5d95206676b8.jpg)

#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Q1. Did you try to uninstall:

https://docs.shardeum.org/node/run/validator#uninstall-validator

then reinstall:

https://docs.shardeum.org/node/run/validator#step-1-install-prerequisites

Q2. Did you try this:

https://askubuntu.com/a/1109989

?

**Comment by MarcusWentz** [comment]
Closing issue for now. 

Please reopen issue if it is seen again.
