### ISSUE TITLE
[Duplicate] Validator GUI ```https://<server_ip>:8080``` Web Browser Error ```This site can’t be reached```

### ISSUE THREAD

**Issue by earningdose** [Shardeum/shardeum-bug-reporting#172]
![image](https://user-images.githubusercontent.com/116700183/222883434-68429fe5-67ec-4224-bb5d-246681e98906.png)

Unable to Open dashboard ....
What I tried CHeck ✔

![image](https://user-images.githubusercontent.com/116700183/222883492-ebb3f153-3916-42cb-95be-bde7b0228608.png)

Already Opened all ports 
check Here Again 
![image](https://user-images.githubusercontent.com/116700183/222883647-9c8f24c2-4604-4b9a-b7e4-2f6cc8db1c02.png)

No support from Discord Kindly Help me in this Thank you 😟

**Comment by pittpv** [comment]
The same issue after update my node from 1.1.1. to 1.1.2

**Comment by pittpv** [comment]
I can resolve issue by full reinstall node `curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh`

The installation is quite long. You just have to wait

**Comment by earningdose** [comment]
just reinstalled but still facing same issue 😪

**Comment by earningdose** [comment]
As I already shared my problem regarding dashboard .. Now i'm trying to stake with command line but there're no official statement post... Kindly have a look team 

I exported metamask pvt key now unable to set network check ss pls @MarcusWentz 😢

![image](https://user-images.githubusercontent.com/116700183/222891376-1e750649-447c-4a97-b100-68bb034a1636.png)

**Comment by pittpv** [comment]
> I can resolve issue by full reinstall node `curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh`
> 
> The installation is quite long. You just have to wait

But then i have this issue https://github.com/Shardeum/shardeum-bug-reporting/issues/92

**Comment by MarcusWentz** [comment]
Have you tried setting up your Validator GUI URL in this format:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85

?

If so, we can close this bug report and continue the report there.

**Comment by earningdose** [comment]
Yes i tried but issue is still live .. @MarcusWentz 

Q1 As I'm using Amazon AWS is there anything missing with security group

Q2 If GUI not working then what's wrong with CLI unable to stake from CLI 

🚨 Check Screenshot below 👇

![222891376-1e750649-447c-4a97-b100-68bb034a1636](https://user-images.githubusercontent.com/116700183/222978176-7633d85a-e83c-42f9-961b-59865c04e095.png)

**Comment by MarcusWentz** [comment]
Let's continue this discussion here since this bug report is not considered redundant with the issue:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85
