### ISSUE TITLE
Explorer Failed Transaction Method Tag Color Green In Address History Should Be Red

### ISSUE THREAD

**Issue by saurabhburade** [Shardeum/shardeum-bug-reporting#173]
##### What is the issue?
 On account page on explorer, it shows same color on tag for failed txn.
    
#### What impact does the issue have?

- Inconvenient to distinguish failed and success txns

##### How to reproduce the issue? 
- On account page on explorer

Explain in as much detail as possible to help reproduce the bug:
```
    - Seen on Sphinx Explorer
```

##### What other resources can you share regarding this issue?

Transaction that failed but shows green on account transaction history:

https://explorer-sphinx.shardeum.org/transaction/0x0f075f04fea17cbc0020cdde32fcec81838bad8b54f0790a706d8859a605efa7

<img width="1424" alt="Screenshot 2023-03-04 at 8 21 33 PM" src="https://user-images.githubusercontent.com/39492927/222914115-2d48197d-16f4-4abe-a85c-54635b3006db.png">

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
