### ISSUE TITLE
Validator Docker Container Does Not Run After Server Restart

### ISSUE THREAD

**Issue by Jamarox** [Shardeum/shardeum-bug-reporting#175]
##### What is the issue?
:red_circle: 
When I start the CLI with shell script './shell.sh' I see:
Error response from daemon: Container f40532eb1963cc9a2a676bf0e6d25332f5f5d0764d01adfcde83b21664dc0fc7 is not running. :red_circle: 
    
#### What impact does the issue have?
:red_circle: Validator is not running. :red_circle: 

##### How to reproduce the issue? 
:red_circle: Normal server restart. Before restarting, the validator worked normally for many days. :red_circle:

**Comment by thomson2k** [comment]
@Jamarox  

Try running the command:
```shell
docker ps -a
``` 
to see a list of all containers on your system. 

If it is not running, you can try starting it manually using the command 
```shell
docker start <containerID>
```

**Comment by Jamarox** [comment]
Thank you @thomson2k. 

After command:
```shell
docker start -a
``` 
container started and now is running normally. After command:
```shell
docker start -a
``` 
something was automatically installed. 

After this I started node without problems and now and now also is running normally.
