### ISSUE TITLE
Validator Error Loading extension section v3_req 

### ISSUE THREAD

**Issue by zwlj** [Shardeum/shardeum-bug-reporting#176]
##### What is the issue?

init shm node(curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh),meet this error
![44301677949758_ pic](https://user-images.githubusercontent.com/30178623/222940723-6a8ed27a-0b58-416c-bcf3-56cd0efffc11.jpg)

    
#### What impact does the issue have?
i can not open web dashboard
##### How to reproduce the issue? 
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
##### What other resources can you share regarding this issue?
no

**Comment by MarcusWentz** [comment]
Validator Version 1.1.5 is out now. 

Upgrade to this latest version.

If you still see this issue then we can reopen the issue.
