### ISSUE TITLE
Shardefi Does Not Respond After Connecting Wallet

### ISSUE THREAD

**Issue by helllaEg** [Shardeum/shardeum-bug-reporting#177]
##### What is the issue?

(https://swap.shardefi.com/#/swap) The problem occurs when connecting to the wallet - when you click the "connect" button, nothing happens does not happen and the wallet does not work.
    
#### What impact does the issue have?

The problem affects the quality of passing the testnet and in some cases makes it impossible to pass it

##### How to reproduce the issue? 

The problem appears when you follow the link in Discord to the page https://swap.shardefi.com/#/swap. Next, you click "connect" and choose a wallet. After that, no action takes place

##### What other resources can you share regarding this issue?

![Shardeum Test - Google Chrome 05 03 2023 10_59_25](https://user-images.githubusercontent.com/98079474/222951174-a3e93659-77f2-4e31-b68b-ded577767933.png)

**Comment by MarcusWentz** [comment]
What network are you using?

Did you try all 3 testnets:

https://docs.shardeum.org/network/endpoints

?

**Comment by MarcusWentz** [comment]
Metamask connected after switching to Liberty 1.X:

https://docs.shardeum.org/network/endpoints#connect-wallet-2
