### ISSUE TITLE
[Duplicate] Validator Stopped Lost Stake Reward 

### ISSUE THREAD

**Issue by sagarvd01** [Shardeum/shardeum-bug-reporting#178]
##### What is the issue?

When a node start participating in the network, all previous earnings are getting reset. #72 talks about node being stopped during node rotation. After this, if we start the node again and it'll be in standby mode. After that, when the network add this node, the earned SHM will start fresh from 0. Lifetime earnings are not showing.
    
#### What impact does the issue have?

It could be loss of funds. Cannot confirm since the lifetime earnings are not showing anything.

##### How to reproduce the issue? 

1. Start the node.
2. Wait for the node to join the network.
3. The Earned SHM will start from 0.

```
- Web dashboard.
```
:red_circle: 

##### What other resources can you share regarding this issue?

My Earned SHM was 23+ SHM Yesterday. After my node is being added to the network again, it started from 0. Here's a screenshot of the dashboard right now.
![image](https://user-images.githubusercontent.com/15938422/222972881-60ac1230-5e61-4107-98b5-e78737b7a0e1.png)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/34
