### ISSUE TITLE
Explorer Internal Transactions Not Visible

### ISSUE THREAD

**Issue by rishotics** [Shardeum/shardeum-bug-reporting#179]
##### What is the issue?

I am making a transaction which involves internal transactions but they are not visible in the scanner.
    

##### Explain in as much detail as possible to help reproduce the bug:

Here is our smart contract wallet: https://explorer-sphinx.shardeum.org/account/0x46098024dcec0d6cebd148ccc3cfa8521d54eae6

When we are making a transaction through it, we are not seeing any internal transactions

Here is SAME smart contract wallet on polygon: https://mumbai.polygonscan.com/address/0xbE98cc95C639aB8a3765e2Cb2F87C2142B10a3eD#internaltx which is having internal transactions

Here are our contracts: https://github.com/Banana-Wallet/banana-contracts-shardeum

We have made the same transaction on both contracts.

**Comment by swarna1101** [comment]
This issue is fixed in the latest 1.9.0 release of Network, pls try again
