### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ranjit12321** [Shardeum/shardeum-bug-reporting#180]
##### What is the issue?
On 1st march i did update shardeum node multiple time. But found multiple error even after fixing the problem.  Validator stops with an error after certain regular interval. 

Describe the error in simple terms. : 
Validator has completely stopped and had to restart the validator manually.     

#### What impact does the issue have?
Node exited with following message: 
Fatal: Could not get seed list from seed node server 
http://archiver-sphinx.shardeum.org:4000/nodelist: 
Timeout awaiting 'request' for 5000ms

![222474359-f5b651fa-2682-4c68-90e3-8e917c1c035c](https://user-images.githubusercontent.com/36276526/222979649-d618fd47-ad3a-4fe7-8a7a-a675d440a052.png)

####### Another error also i found after some interval of time 
.

![222474308-4f774b77-d0b8-422f-8ec9-300f34b9c669](https://user-images.githubusercontent.com/36276526/222979766-dea4017a-c5e2-4c44-be68-05d2b65c3f71.png)

#### Command till now i have tried out ( But didnt work) : 

 cd ~/.shardeum
./shell.sh
curl https://ipinfo.io/ip 
export APP_IP="103.154.233.117"  

Restart the node :

 operator-cli stop
 operator-cli start

sudo apt install ufw

sudo ufw allow 4000
sudo ufw allow 4001
sudo ufw allow 9001
sudo ufw allow 10001 
sudo ufw allow 22
sudo ufw allow 8080
sudo ufw allow https
sudo ufw allow http
sudo ufw allow 443
sudo ufw enable
sudo ufw reload
sudo ufw status 
  

( Yes i also change my metamask wallet address also, but still getting the same error, and NODE stops after some interval of time. )

**Comment by MarcusWentz** [comment]
Duplicate issues.

Share this info for these bug reports: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/104

and

https://github.com/Shardeum/shardeum-bug-reporting/issues/83
