### ISSUE TITLE
[Duplicate] Validator Install Error ```Client timeout exceed while waiting for headers```

### ISSUE THREAD

**Issue by dharam99971** [Shardeum/shardeum-bug-reporting#182]
Not able to run validator node. please find the attached terminal output below.  Please help me on this.
================================================

Enter the port (1025-65536) to access the web based Dashboard (default 8080):
To run a validator on the Sphinx network, you will need to open two ports in your firewall.
This allows p2p communication between nodes. Enter the first port (1025-65536) for p2p communication (default 9001):
Enter the second port (1025-65536) for p2p communication (default 10001):
What base directory should the node use (defaults to ~/.shardeum):

###########################
# 1. Pull Compose Project #
###########################

Removing existing directory /root/.shardeum...
Cloning into '/root/.shardeum'...
remote: Enumerating objects: 495, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 495 (delta 130), reused 57 (delta 57), pack-reused 322
Receiving objects: 100% (495/495), 157.84 KiB | 4.15 MiB/s, done.
Resolving deltas: 100% (312/312), done.

###############################
# 2. Create and Set .env File #
###############################

##########################
# 3. Clearing Old Images #
##########################

down exiting stack
Docker Compose project is not up
delete existing image
Error: No such image: test-dashboard
Error: No such image: local-dashboard
Error: No such image: registry.gitlab.com/shardeum/server
done.

##########################
# 4. Building base image #
##########################

Sending build context to Docker daemon  266.8kB
Step 1/9 : FROM registry.gitlab.com/shardeum/server:latest
Get "https://registry.gitlab.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Trying again with sudo...
Sending build context to Docker daemon  266.8kB
Step 1/9 : FROM registry.gitlab.com/shardeum/server:latest
Get "https://registry.gitlab.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
root@99crypto:~#

**Comment by MarcusWentz** [comment]
Duplicate issue:

https://github.com/Shardeum/shardeum-bug-reporting/issues/47
