### ISSUE TITLE
[Duplicate] Validator Staking GUI SHM Rewards Decreasing

### ISSUE THREAD

**Issue by Khvesyk** [Shardeum/shardeum-bug-reporting#183]
Hi. I installed a node and earned about 130 tokens(yeaterday i checked "Overview" on the website and they were) but I just logged in and instead of 130 tokens there were 22 in my account. 
![Screenshot_1](https://user-images.githubusercontent.com/102920844/223202665-35098ebe-27a3-4fe3-8dc0-0a6727af8c19.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/45
