### ISSUE TITLE
[Duplicate] Validator GUI ```https://<server_ip>:8080``` Web Browser Error ```This site can’t be reached```

### ISSUE THREAD

**Issue by naflan222** [Shardeum/shardeum-bug-reporting#184]
Im facing a error can anyone help me to fix this 

When i try to check shardeum node site is not loading and im getting this error

''This site can’t be reached94.131.9.168 refused to connect.
Try:

Checking the connection
ERR_CONNECTION_REFUSED"

![Screenshot_20230307_033057_Kiwi Browser](https://user-images.githubusercontent.com/85609432/223244743-4a389948-9ed2-4e4d-b3d0-ccc5eb840832.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/85
