### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by LIHebzy1** [Shardeum/shardeum-bug-reporting#185]
Failed transaction trying to unstake then i update node to latest version and node cannot run poperly because of the old staking

![Shardeum shii](https://user-images.githubusercontent.com/127190138/223371641-e054651f-c57b-4413-9318-acbc300f5c31.jpg)

**Comment by Ezebrown** [comment]
Run exit on the IDE. 
IT will exit it and you don't need to unstake.
So you will use other wallet to re-stake when you upgrade to 1.1.2

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
