### ISSUE TITLE
[Duplicate] Validator Unable To Update To Latest Version 

### ISSUE THREAD

**Issue by crypto-mathi** [Shardeum/shardeum-bug-reporting#186]
##### What is the issue?

:red_circle:  I upgraded the shardeum node to Version number 1.1.2  today after the announcement on discord. But i still see the "Validator Latest version: 1.1.0" on dashboard. Is this correct? or Validator is still not upgraded to the latest version?

![Uploading Screenshot 2023-03-07 at 9.53.06 AM.png…]()

**Comment by madmerr** [comment]
And what about Validator running version?
https://prnt.sc/9EjP9WsvPFy0

**Comment by MarcusWentz** [comment]
Duplicate issue.

Try this:

https://github.com/Shardeum/shardeum-bug-reporting/issues/113#issuecomment-1442743970
