### ISSUE TITLE
[Duplicate] Validator Unable To Update To Latest Version 

### ISSUE THREAD

**Issue by crypto-mathi** [Shardeum/shardeum-bug-reporting#187]
##### What is the issue?

Getting error in the end while upgrading shardeum node with installer.sh scrip.

Error: Pasting the complete logs

_root@h3001583:~# curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8719  100  8719    0     0  22617      0 --:--:-- --:--:-- --:--:-- 22646
During this early stage of Betanet the Shardeum team will be collecting some performance and debugging info from your node to help improve future versions of the software.
This is only temporary and will be discontinued as we get closer to mainnet.
Thanks for running a node and helping to make Shardeum better.

By running this installer, you agree to allow the Shardeum team to collect this data. (y/n)?: y
docker-compose is installed on this machine
Docker daemon is running_

#########################
# 0. GET INFO FROM USER #
#########################

Do you want to run the web based Dashboard? (y/n): y
Set the password to access the Dashboard: **********
Enter the port (1025-65536) to access the web based Dashboard (default 8080): 
To run a validator on the Sphinx network, you will need to open two ports in your firewall.
This allows p2p communication between nodes. Enter the first port (1025-65536) for p2p communication (default 9001): 
Enter the second port (1025-65536) for p2p communication (default 10001): 
What base directory should the node use (defaults to ~/.shardeum): 

###########################
# 1. Pull Compose Project #
###########################

Cloning into '/root/.shardeum'...
remote: Enumerating objects: 495, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 495 (delta 131), reused 57 (delta 57), pack-reused 322
Receiving objects: 100% (495/495), 155.10 KiB | 6.20 MiB/s, done.
Resolving deltas: 100% (313/313), done.

###############################
# 2. Create and Set .env File #
###############################

Device "link" does not exist.

##########################
# 3. Clearing Old Images #
##########################

down exiting stack
Docker Compose project is not up
delete existing image
Error response from daemon: No such image: test-dashboard:latest
Error response from daemon: No such image: local-dashboard:latest
Error response from daemon: No such image: registry.gitlab.com/shardeum/server:latest
done.

##########################
# 4. Building base image #
##########################

[+] Building 60.9s (10/10) FINISHED                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                 0.1s
 => => transferring dockerfile: 576B                                                                                                 0.1s
 => [internal] load .dockerignore                                                                                                    0.1s
 => => transferring context: 114B                                                                                                    0.1s
 => [internal] load metadata for registry.gitlab.com/shardeum/server:latest                                                          0.9s
 => [internal] load build context                                                                                                    0.0s
 => => transferring context: 224.56kB                                                                                                0.0s
 => CACHED [1/5] FROM registry.gitlab.com/shardeum/server:latest@sha256:74f4f2a2896eddb980a3cb73d20d808a7bc96efd29d126138be739bfe68  0.0s
 => [2/5] RUN apt-get install -y sudo                                                                                                3.3s
 => [3/5] RUN usermod -aG sudo node &&  echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&  chown -R node /usr/local/bin /usr/  21.4s
 => [4/5] WORKDIR /home/node/app                                                                                                     0.1s 
 => [5/5] COPY --chown=node:node . .                                                                                                 0.1s 
 => exporting to image                                                                                                              35.0s 
 => => exporting layers                                                                                                             35.0s 
 => => writing image sha256:236f8744441f0d8957c0660316fc58564add08a8e2e6628f2a6f82c962554071                                         0.0s 
 => => naming to docker.io/library/local-dashboard                                                                                   0.0s

############################
# 5. Start Compose Project #
############################

Creating network "shardeum_default" with the default driver
Creating shardeum-dashboard ... done
Starting image. This could take a while...
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm notice 
npm notice New major version of npm available! 8.0.0 -> 9.6.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.0>
npm notice Run `npm install -g npm@9.6.0` to update!
npm notice 
Cloning into 'cli'...
Cloning into 'gui'...
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
[DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.
Generating a RSA private key
..............................................................................+++++
.....+++++
writing new private key to 'CA_key.pem'
_**-----
Error Loading extension section v3_req
140393075819648:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:../crypto/x509v3/v3_alt.c:464:value=
140393075819648:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=@alt_names
Error Loading extension section req_ext
140238200640640:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:../crypto/x509v3/v3_alt.c:464:value=
140238200640640:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=@alt_names
cat: selfsigned_node.crt: No such file or directory**_
  To use the Web Dashboard:
    1. Note the IP address that you used to connect to the node. This could be an external IP, LAN IP or localhost.
    2. Open a web browser and navigate to the web dashboard at https://<Node IP address>:8080
    3. Go to the Settings tab and connect a wallet.
    4. Go to the Maintenance tab and click the Start Node button.

  If this validator is on the cloud and you need to reach the dashboard over the internet,
  please set a strong password and use the external IP instead of localhost.

To use the Command Line Interface:
	1. Navigate to the Shardeum home directory (/root/.shardeum).
	2. Enter the validator container with ./shell.sh.
	3. Run "operator-cli --help" for commands_

    
#### What impact does the issue have?

:red_circle: Unable to open the dashboard on browser. it still says Site cannot be reached :red_circle: 
operator-cli gui status - This command says it is online.

_node@41b9ff214d5c:~/app$ operator-cli gui status
name: operator-gui
uptimeInSeconds: 0.432
restarts: 203
status: online
cpuUsagePercent: 0
memUsedInBytes: 58970112
link: http://localhost:8080/_

**Comment by MarcusWentz** [comment]
Duplicate issue.

Try this:

https://github.com/Shardeum/shardeum-bug-reporting/issues/113#issuecomment-1442743970
