### ISSUE TITLE
[Duplicate] Validator GUI ```https://<server_ip>:8080``` Web Browser Error ```This site can’t be reached```

### ISSUE THREAD

**Issue by ranjit12321** [Shardeum/shardeum-bug-reporting#188]
##### What is the issue?
Shardeum Validator Dashboard not open 

    
#### What impact does the issue have?
Shardeum Validator Dashboard not open  , I cannot stake shm and run the node.

Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :
Shardeum Validator Dashboard not open  

![Screenshot (2592)](https://user-images.githubusercontent.com/36276526/223388154-dd6b0088-4299-40f5-b43a-d341f4be8b56.jpg)

* The previous version 1.1.1 was working fine ( with password ).  Here is the link https://103.154.233.117:8080/ 

* After upgradation, ( For my satisfaction )  i uninstall the whole node and reinstall the node again. But still getting the same error.

* Here are some screenshort that will help you to figure out.
![Screenshot (2591)](https://user-images.githubusercontent.com/36276526/223389417-f28dd3c2-883f-49b2-8c05-b90bb32e34a7.jpg)

![Screenshot (2598)](https://user-images.githubusercontent.com/36276526/223389632-47a13871-6106-40bb-8e7a-044d9911bece.jpg)

![Screenshot (2593)](https://user-images.githubusercontent.com/36276526/223389768-16d5e945-dfd3-4e4d-8bb4-f5024479a505.jpg)

*  Command those i used so far to resolve my issue : 

Restart the node :

 operator-cli stop
 operator-cli start

 
cd ~/.shardeum
./shell.sh 
curl https://ipinfo.io/ip 
export APP_IP="103.154.233.117" 

./docker-up.sh 

( Before reinstall the upgraded node) 
sudo apt install ufw

sudo ufw allow 4000
sudo ufw allow 4001
sudo ufw allow 9001
sudo ufw allow 10001 
sudo ufw allow 22
sudo ufw allow 8080
sudo ufw allow https
sudo ufw allow http
sudo ufw allow 443
sudo ufw enable
sudo ufw reload
sudo ufw status 
 

### I asked support in discord, but many are facing the same problem.

( Kindly resolve this issue with command line )

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85
