### ISSUE TITLE
RPC Pending Transaction Stuck

### ISSUE THREAD

**Issue by Elang02** [Shardeum/shardeum-bug-reporting#189]
##### What is the issue?

:red_circle:  can't cancel pending tx :red_circle: 
    
#### What impact does the issue have?

:red_circle:c can't doing new transaction because of this :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -can't make a new transaction
    -transaction cannot made because account nonce and tx nonce is not same because i have a pending tx
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: ![image](https://user-images.githubusercontent.com/122076311/223397057-5f97c844-0b63-4b13-95fd-1ce980c22018.png). :red_circle:

**Comment by Ezebrown** [comment]
You can wait till got completed or failed

**Comment by MarcusWentz** [comment]
@Elang02 

Reset your Metamask nonce:

https://support.metamask.io/hc/en-us/articles/360015488891-How-to-reset-an-account

Then try to transfer SHM to another wallet. 

Does that new transaction override the old transaction?

**Comment by Elang02** [comment]
![image](https://user-images.githubusercontent.com/122076311/223602470-9df13213-3bce-40aa-b176-47ee9b047713.png)
ya, after still same after reset

**Comment by MarcusWentz** [comment]
@Elang02 

What is your wallet address?

**Comment by Elang02** [comment]
0x7ada76e1B47e730128B961f5C7A10fF19530D02F
i have try send small amount and it works and when i try to send 8 shm its failed (i have 25 shm)
![image](https://user-images.githubusercontent.com/122076311/223886949-58246b80-8542-4dad-b030-f1a5f4b94368.png)

**Comment by MarcusWentz** [comment]
Validator Version 1.1.3 will be coming out soon (hopefully next week).

This might help with RPC issues like this. 

Are you able to use another wallet for now that works?

**Comment by Elang02** [comment]
ya it works on other wallet

**Comment by MarcusWentz** [comment]
Please use the other wallet for now until Validator Version 1.1.3 comes out sometime hopefully next week.
