### ISSUE TITLE
Contract Deployment is failing from the address and draining whole balance except 1 SHM

### ISSUE THREAD

**Issue by dexpad-dev** [Shardeum/shardeum-bug-reporting#19]
##### Overview

   While deploying a simple Airdropper contract it failed and took the full balance except leaving 1.8 SHM. Failed transaction not showing any sign of huge gas transfer.

##### Context 

I was deploying DexPad contracts and while a couple of deployments failed with my original deployer account which had around 100 SHM, all was gone in a single deployment transaction. The address affected by this 

https://explorer-liberty20.shardeum.org/account/0x2cb57241a135c0c151b1f97c2088750cd9a2d739

**Comment by MarcusWentz** [comment]
Please add contracts to test with GitHub links and directly in the issue. 

Example: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/12

**Comment by MarcusWentz** [comment]
Is this related to #22 ?

Please share the contract so we can try to reproduce the issue.

**Comment by dexpad-dev** [comment]
The issue seems to be resolved in the latest beta net.
