### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by vsonu04** [Shardeum/shardeum-bug-reporting#190]

**Comment by Ezebrown** [comment]
Run exit on the IDE then upgrade to the new version 1.1.2.
Then use another wallet to request SHM from the faucet and stake with another wallet.

**Comment by vsonu04** [comment]
But that's not solution , we have to unstake with old Wallet

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
