### ISSUE TITLE
Validator Install Error ```sed: can't read docker-compose.tmpl: No such file or directory```

### ISSUE THREAD

**Issue by Ezebrown** [Shardeum/shardeum-bug-reporting#191]
After I run the command:
```shell 
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```
And accepting all instances it brought.
It later show that file directory not found.
![Screenshot_20230307-124818_Termius](https://user-images.githubusercontent.com/107863520/223416945-dff701a2-cf79-421e-b402-68df643345d2.jpg)

**Comment by MarcusWentz** [comment]
Q1. What OS are you using?

Q2. What do you see with 
```shell
docker --version
```
?
Q3. What do you see with 
```shell
docker-compose --version
```
?

**Comment by Ezebrown** [comment]
I just rẹ run it.
I firstly make a mistake of running  `cd.Shardeum` instead of `cd ..`, so I have re-run it , I will login to my localhost now and let you know if it works 
![Screenshot_20230307-172121_Termius](https://user-images.githubusercontent.com/107863520/223485365-273331ea-3abc-4d89-bb51-52edec4a49b8.jpg)

**Comment by Ezebrown** [comment]
If I stake SHM with other wallets , does it have any effect or setback in the Progressive of the node ,i'm running?

**Comment by Ezebrown** [comment]
I was able to login but not able to stake and remove stake.
It is not even showing the connected wallet address.
It is still showing my former SHM stake.
So I re-stake with other wallet

**Comment by Ezebrown** [comment]
Why am I seeing this ?
![16782098224212946535234027431737](https://user-images.githubusercontent.com/107863520/223500279-b9b7b779-47a2-4925-86e3-f36ecba0b76e.jpg)

**Comment by MarcusWentz** [comment]
The original issue seems resolved.

Try this for the issue you have now:

https://github.com/Shardeum/shardeum-bug-reporting/issues/83#issuecomment-1437401891
