### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by sagarvd01** [Shardeum/shardeum-bug-reporting#192]
##### What is the issue?

While trying to unstake from node, an RPC error is occurring with the message "No reward endTime set, can't unstake node yet"
    
#### What impact does the issue have?

Unable to unstake from node before updating to latest version.

##### How to reproduce the issue? 

1. Stop Node.
2. Click on Remove stake and submit transaction.
3. The transaction will fail with error message.

##### What other resources can you share regarding this issue?

Error Screenshot
![image](https://user-images.githubusercontent.com/15938422/223428662-07b220e1-afbd-4b86-a676-644fbcd13fe5.png)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
