### ISSUE TITLE
Validator Stopped Error ```Cannot read properties of null (reading 'counter')```

### ISSUE THREAD

**Issue by guruchaithanya** [Shardeum/shardeum-bug-reporting#194]
##### What is the issue?

:red_circle:  Node was running for many hours without any issue till the time it was in standby. As soon as the node turned Active, following error stopped the node:
"Cannot read properties of null (reading 'counter')"
:red_circle: 
    
#### What impact does the issue have?

:red_circle: Node is stopped :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Run the node, wait for it to turn active.
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle:

Running on a 6 vCPU machine, 32 GB RAM and 512 GB storage 

node@2814c93bbf11:~/app$ operator-cli status
state: stopped
exitMessage: Cannot read properties of null (reading 'counter')
exitStatus: Exit with error
performance:
  memPercentage: 21.820038050545193
  diskPercentage: 8.495560494090926
  cpuPercentage: 0.5016722408026753
stakeRequirement: '10.0'
lockedStake: '11.0'
nominatorAddress: '0xf96c8d5f28d63231732fbfaacd9009cb30a55419'
currentRewards: '0.540871666666666666'

Log Files:
[validator-error.zip](https://github.com/Shardeum/shardeum-bug-reporting/files/10918515/validator-error.zip)

PM2 logs:
![image](https://user-images.githubusercontent.com/13099594/223651027-3c2f0012-6265-44e9-bdf0-39fcddbab0fe.png)

:red_circle: 

I had restarted the node and below screen shots are after that.

Stats when node is running:
![image](https://user-images.githubusercontent.com/13099594/223650218-241b548d-f5f9-41fa-8d41-77dd02536520.png)

Dashboard:
![image](https://user-images.githubusercontent.com/13099594/223650634-f3af9047-a91a-4db6-b7bf-f4727db3be26.png)

**Comment by MarcusWentz** [comment]
Validator Version 1.1.5 is out now. 

Upgrade to this latest version.

If you still see this issue then we can reopen the issue.
