### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by FyboS** [Shardeum/shardeum-bug-reporting#195]
Try to unstake SHM before update from 1.1.1 to 1.1.2 but get this error in MM: 
No reward endTime set, can't unstake node yet

Already try to reinstall MM, but this problem not in MM.
![image](https://user-images.githubusercontent.com/33482639/223657831-f7ec1264-4aff-421e-ab86-2a9533e607ca.png)

**Comment by FyboS** [comment]
nominatorAddress: '0x426efd68e2f59820def7f4da5aaf32ccc8d22126'

**Comment by MarcusWentz** [comment]
Duplicate issue with a bug patch coming soon (hopefully next week):

https://github.com/Shardeum/shardeum-bug-reporting/issues/92#issuecomment-1458270420

**Comment by FyboS** [comment]
@MarcusWentz it's not duplicate
