### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shardeums** [Shardeum/shardeum-bug-reporting#196]
I am endeavoring to run Node within a time frame of twenty-four hours or less. However, upon opening the VPS IP, it fails to load, and consequently, I am compelled to reinstall it frequently. At times, it displays 'standby' mode without any rewards or active status. Additionally, it occasionally exits with an error. wallet address i use to run my node. 0xeddF8a36037f55FfedF646a72A8caf0bA686650d

**Comment by MarcusWentz** [comment]
What do you see when you run this Shell command from a new terminal:
```shell
sudo docker exec shardeum-dashboard cat cli/build/logs/exit-summary.json
```
?
