### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by dapravin** [Shardeum/shardeum-bug-reporting#197]
##### What is the issue?
Cannot stake or unstake SHM
    
#### What impact does the issue have?
Since we cannot unstake, i stopped node, updated and connected to new wallet for staking. but still i am getting old wallet option after restarting node and connecting to new walllet as well. options are unstake or add stake.

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue with a bug patch coming soon (hopefully next week):

https://github.com/Shardeum/shardeum-bug-reporting/issues/92#issuecomment-1458270420
