### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Cannot read properties of undefined (reading 'certExp')```

### ISSUE THREAD

**Issue by wang161** [Shardeum/shardeum-bug-reporting#198]
![tt](https://user-images.githubusercontent.com/104962608/223902546-5456d795-4908-4d70-8bfa-12df2b7f875f.png)
![tt2](https://user-images.githubusercontent.com/104962608/223902548-6bbc327d-0fbc-4dc4-b019-db02d1b4b248.png)
at first,my node have the issue and the status is 'stop'
when I restart my node,the status just is 'active',and the time last active is not update,should be a bug,pls check.Thanks!

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/65
