### ISSUE TITLE
MetaMask: Received invalid network parameters

### ISSUE THREAD

**Issue by RyanHubs** [Shardeum/shardeum-bug-reporting#2]
MetaMask: Received invalid network parameters. 

chainId: "0x1f90"
networkVersion: 8080

**Comment by MarcusWentz** [comment]
Please update the issue with the following format:
https://github.com/Shardeum/shardeum-bug-reporting#format-bug-report

**Comment by saurabhburade** [comment]
Issue reported with convention at #7

**Comment by MarcusWentz** [comment]
Closing issue a new issue has been created for the same topic here: https://github.com/Shardeum/shardeum-bug-reporting/issues/7
