### ISSUE TITLE
[Duplicate] Validator GUI ```https://<server_ip>:8080``` Web Browser Error ```This site can’t be reached```

### ISSUE THREAD

**Issue by dhunurayne** [Shardeum/shardeum-bug-reporting#201]
##### What is the issue?

I cannot access my web based dashboard on my browser 

:red_circle:  Describe the error in simple terms. :red_circle: 
 I have carefully run the code, more than 5 times, still when I replace my IP with this https://<server_ip>:8080/ nothing comes up on my browser.
![9B7AE26F-A002-4D48-963A-606A43B17CAA](https://user-images.githubusercontent.com/58150954/224020844-8ef82a9e-2f71-442e-a632-db1ded2f0703.png)
![024B9AD6-59E7-413B-81B1-AC61E3391FBB](https://user-images.githubusercontent.com/58150954/224020894-a4bed97a-a5f5-4998-89df-61caeeab4761.png)

    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?
Here is my IP address: 3.27.11.223

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85
