### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by mahmads0343** [Shardeum/shardeum-bug-reporting#202]
##### What is the issue?

I was running node from past 17 days and then on 18th day the issue arises and it was showing cannot connect to host
    
#### What impact does the issue have?

my connection with validator was broken.

##### What other resources can you share regarding this issue?

I again followed the steps to run node and it was showing that your wallet is connect to another node. if you want to add stake you have to remove stake from previous node.
how can I connect to previous same 
![1](https://user-images.githubusercontent.com/122096871/224080996-0a7c006a-c64a-4ed6-a942-7edee7e7a9c3.png)
![issue](https://user-images.githubusercontent.com/122096871/224081000-5593d005-fd11-4dd6-8867-ec85047035f1.png)
node and then add stake....

**Comment by MarcusWentz** [comment]
Duplicate issues.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92

and

https://github.com/Shardeum/shardeum-bug-reporting/issues/85

**Comment by mahmads0343** [comment]
> 

I am describing my issue...
