### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Node cannot join with invalid external IP: 0.0.0.0```

### ISSUE THREAD

**Issue by sasips2021** [Shardeum/shardeum-bug-reporting#203]
##### What is the issue?
Node exited with following message: Fatal: Node cannot join with invalid external IP: 0.0.0.0
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 
Node exited with following message: Fatal: Node cannot join with invalid external IP: 0.0.0.0
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
Already tried the solutions given in https://discord.com/channels/933959587462254612/1076064586601599017/1076066284971761755
But the below codes are now NOT working. When start the node, after few minutes it is stopped with error Node cannot join with invalid external IP: 0.0.0.0
```
cd ~/.shardeum
./shell.sh
curl https://ipinfo.io/ip
export APP_IP="EXTERNAL_IP"
```

    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
![Error](https://user-images.githubusercontent.com/127483102/224262901-95b07f0e-5dbb-48b3-9997-56839758d380.PNG)

**Comment by alterkahn** [comment]
I'm also having this issue after I successfully delegated and the node started trying to join an active validator set

<img width="1128" alt="Снимок экрана 2023-03-10 в 13 34 24" src="https://user-images.githubusercontent.com/67752860/224306335-bd517851-dc94-4286-bc33-f2d092b99061.png">

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/83
