### ISSUE TITLE
Validator Active With No SHM Rewards

### ISSUE THREAD

**Issue by singh27808** [Shardeum/shardeum-bug-reporting#204]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Do you have a screenshot from your GUI?

**Comment by singh27808** [comment]
Yes

**Comment by MarcusWentz** [comment]
Please share the screenshots from your GUI and if you have logs from your CLI please share as well.

**Comment by ksbaskar** [comment]
<img width="859" alt="1111" src="https://user-images.githubusercontent.com/6725456/224896434-c8b95dd4-5770-4a40-bb77-4f075135a82f.png">

**Comment by tuzara82** [comment]
It's been like this for several days and there are no charges

<a href="https://ibb.co/YLh2vRF"><img src="https://i.ibb.co/bKX1pWM/Shardeum.jpg" alt="Shardeum" border="0"></a>

**Comment by Maha1323** [comment]
I am running two nodes . One is doesn't show my total validating time but my rewards increasing and status shows me as standby and i have checked in cli status there show as me shows in gui total time validating not show there also .
Another node status don't shows and total time validating shows me from 4 days above. My rewards not increasing.
I have checked in cli status shows null .
Please solve this is bug.
![Screenshot_2023-04-05-07-44-02-51_d4b821f22c36211daa9077338f9854d0](https://user-images.githubusercontent.com/122420140/229975283-acd8ee98-71d5-4479-b404-d80c6f537a40.jpg)

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
