### ISSUE TITLE
Validator CLI ```autorestart``` Not Working

### ISSUE THREAD

**Issue by idkravitz** [Shardeum/shardeum-bug-reporting#206]
##### What is the issue?

:red_circle:  As one can see in issues currently, there are a lot of reports about validator crashes. Unfortunately validator doesn't recover on its own :red_circle: 
    
#### What impact does the issue have?

:red_circle: The overall impact is that node runners either had to restart it manually by checking every few hours on its status, or write some hacky crontabs to automate the process. :red_circle: 

##### What is my suggestion to resolve the issue? 

Currently the start job on validator explicitly disables `autorestart` to handle the stop command, unfortunately node runners currently prefer to have it constantly running instead of being able to stop at any moment. But the stop issue can be resolved, while having autorestart policy activated, [see pm2 docs](https://pm2.keymetrics.io/docs/usage/restart-strategies/#skip-auto-restart-for-specific-exit-codes). It makes sense to ignore exit codes for normal shutdown (exit code 0) and it requires a simple job of graceful shutdown handling, examples and guides on it [can be found in pm2 docs](https://pm2.io/docs/runtime/best-practices/graceful-shutdown/)

**Comment by MarcusWentz** [comment]
Do you have a screenshot from your Validator GUI?

**Comment by idkravitz** [comment]
@MarcusWentz Sure, I'll try to take it next time the validator stops.
Right now you can verify that `autorestart` is disabled by checking the codebase:
https://gitlab.com/shardeum/validator/cli/-/blob/main/src/node-commands.ts#L309

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
