### ISSUE TITLE
[Duplicate] Validator GUI Tabs Load However Content Does Not Load

### ISSUE THREAD

**Issue by DevendarPunna** [Shardeum/shardeum-bug-reporting#208]
![Error1](https://user-images.githubusercontent.com/66458750/224532948-aae40a30-c063-4ed6-bc1c-e193e6dac52c.JPG)

https://user-images.githubusercontent.com/66458750/224532950-39161520-bde1-4109-8813-a9ee36076b02.mp4

##### What is the issue?

:red_circle:  I cannot stake SHM on the node :red_circle: 
    
#### What impact does the issue have?

:red_circle: I cannot stake, also Metamask wallet is not getting connected. :red_circle: 

##### How to reproduce the issue? 

PFA the screenshots.

**Comment by MarcusWentz** [comment]
What browser are you using?

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/147
