### ISSUE TITLE
[Duplicate] Validator Stopped Lost Stake Reward 

### ISSUE THREAD

**Issue by HrithikVinod** [Shardeum/shardeum-bug-reporting#209]
##### What is the issue?
At first after the node become active i started to earn rewards.i got around 220 shm tokens from running node .But after i unstaked my shm a staked again all my rewards gone and started from 0 again.Then i got around 10shm again but after the update it is 0 again.I think this is some kind of bug
Hope you can solve it

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by Kafiirr** [comment]
```Stanby's Rewards Node disappears when it turns Active```

This case is the same but the difference is that I did not unstake when my Node was still in **__Standby__**. When my Node was still in Stanby I had earned around **__60+ SHM__**, but when my Node turned into **__Active__** SHM Rewards that I had earned when my Node was still in Stanby disappeared and started earning from the beginning.

![Shardeum Node](https://user-images.githubusercontent.com/124496288/224558825-5f2a7f66-ec83-4c41-8c7b-1aa6a750ec18.png)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/34
