### ISSUE TITLE
RPC ```net_version``` returns ```chainId``` as type ```number``` instead of type ```string```

### ISSUE THREAD

**Issue by dexpad-dev** [Shardeum/shardeum-bug-reporting#21]
##### Overview

`net_version`  RPC calls are used by Graph Protocol 
and other tools like Metamask to get the chainId in string format instead of number

##### Context 

When running graph node on Shardeum Liberty it throws an error with the following message.

 ```shell
graph-node_1  | Jan 13 09:22:49.537 WARN Trying again after net_version RPC call 
failed (attempt #10) with result Err(Decoder error: Error("invalid type: number, expected
 a string", line: 0, column: 0)), provider: mainnet-rpc-0
```
    
The rootcause for this is the type of `chainId` field in the response json from rpc call is coming as number instead of string.
    
RPC Endpoint Shardeum:  `https://liberty20.shardeum.org`

Request: 

```json
{
	"jsonrpc":"2.0",
	"method":"net_version",
        "params":[],
        "id":1
      }
```
      
Expected Response:
     
```json
{
          "jsonrpc": "2.0",
          "id": 1,
          "result": "8081"
      }
```
     

Actual Response:

```json
{
          "jsonrpc": "2.0",
          "id": 1,
          "result": 8080
      }
```

##### Resources

RPC method ```net_version``` documentation:

https://www.quicknode.com/docs/ethereum/net_version

**Comment by MarcusWentz** [comment]
The Graph is currently not supported.

We are currently working on adding Graph support.

**Comment by dexpad-dev** [comment]
It's not just related to graph but metamask is also reporting it as error because the integer value is being read as hex value in Metamask through ethers.js. and if the response sends string value then both the issues will be resolved.

**Comment by MarcusWentz** [comment]
Betanet 1.X test:

```shell
curl https://sphinx.shardeum.org/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}'
```

Returns chainId as a string now:

```json
{
   "jsonrpc":"2.0",
   "id":67,
   "result":"8082"
}
```
This looks fixed now.
