### ISSUE TITLE
[Duplicate] Validator GUI ```https://<server_ip>:8080``` Web Browser Error ```This site can’t be reached```

### ISSUE THREAD

**Issue by barnabas626** [Shardeum/shardeum-bug-reporting#211]
![ADA98C76-BD02-46D9-AC78-9072C9F1A7A0](https://user-images.githubusercontent.com/127697879/224577026-e84bd6aa-798a-4504-8df9-b42dfcec6300.jpeg)
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help 
![1C5ECD9A-ACB4-43F3-A67A-5BB6353F53D4](https://user-images.githubusercontent.com/127697879/224577059-449bc9c6-9d43-4bd4-9f9c-725ddc94d367.jpeg)

**Comment by barnabas626** [comment]
Please fix this why this showing

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85
