### ISSUE TITLE
[Duplicate] Validator GUI ```https://<server_ip>:8080``` Web Browser Error ```This site can’t be reached```

### ISSUE THREAD

**Issue by barnabas626** [Shardeum/shardeum-bug-reporting#212]
> 
![08C1783E-CC33-454B-A402-35C0462BF333](https://user-images.githubusercontent.com/127697879/224577308-2df56896-d2e7-4475-a54a-111ad41233ba.jpeg)
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by barnabas626** [comment]
Please take a look

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85
