### ISSUE TITLE
[Duplicate] Validator Stopped Lost Stake Reward 

### ISSUE THREAD

**Issue by SpaceRider401** [Shardeum/shardeum-bug-reporting#213]
After update node is active, but earning rewards disappeared and rest to 0.4833shm and After update node running for 14hrs but still showing reward as 0.4833shm , Totally 95 Shm disappeared in a week after update...
![Rewards Disappeared 13 03 2023](https://user-images.githubusercontent.com/126847147/224611646-8cc5ab66-bab2-48bd-8fc4-f9ba48d6e7a8.jpg)
Address: 0xf6b37aA2cafC178AD3B10cc9C9464FDEa79037e7
https://94.131.10.13:8080/

.

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/34
