### ISSUE TITLE
[Duplicate] Validator Stopped Lost Stake Reward 

### ISSUE THREAD

**Issue by MJZ1995** [Shardeum/shardeum-bug-reporting#214]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/22395939/224687680-5b960665-17d9-4d72-8bb3-4bcd7137dce5.png">
I have already associated this wallet in version 1.1.1. Will there be any bad effects if I switch wallets? Was the time I was running before wasted?

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/34
