### ISSUE TITLE
Validator Active Shows ```Total time validating: 00:00:00```

### ISSUE THREAD

**Issue by ksbaskar** [Shardeum/shardeum-bug-reporting#215]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
Validator Node shows status  "Active" i am receiving SHM Rewards but Total time validating shows : 00:00:00
    
#### What impact does the issue have?
No idea
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    in Gui Dashboard
 -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?
my ip is: 192.3.111.15
:red_circle: Photos and links related to the error. :red_circle: 
screen shot
<img width="797" alt="timer" src="https://user-images.githubusercontent.com/6725456/224897504-317193d7-2982-41ba-86e8-0ce213ffb2ec.png">

**Comment by MarcusWentz** [comment]
What do you see in the Validator CLI with:
```shell
operator-cli status
```
?
https://docs.shardeum.org/node/run/validator#step-6-monitor-validator

**Comment by ksbaskar** [comment]
Running the following in the Validator CLI:
```shell
operator-cli status
```
Returns:
```shell
state: active
totalTimeRunning: 25186.498
totalTimeValidating: '00:00:00'
lastActive: Sun Mar 12 2023 18:46:23 GMT+0000 (Coordinated Universal Time)
lastRotationIndex: 62/259
stakeRequirement: '10.0'
nominatorAddress: '0xd52aa64a11c876681c1661e850e51ec4f786ff48'
nomineeAddress: c416f5883483be38db9f216246523f52014a087e77ff8831deef6e602335d868
performance:
  memPercentage: 87.53941208318736
  diskPercentage: 64.75700020495366
  cpuPercentage: 6.000000000000005
currentRewards: '58.512670555555555555'
lockedStake: '51.0'
nodeInfo:
  id: eeade366082391a52872dfbbcf82f9b096605b559be3da5aedfce11fcc7ea066
  publicKey: c416f5883483be38db9f216246523f52014a087e77ff8831deef6e602335d868
  curvePublicKey: 98a55bd3437e66773ea86604b42f3dc8f8515e65053da8c5443630125560400e
  externalIp: 192.3.111.15
  externalPort: 9001
  internalIp: 192.3.111.15
  internalPort: 10001
  status: active
```

**Comment by ksbaskar** [comment]
<img width="481" alt="tes" src="https://user-images.githubusercontent.com/6725456/225213246-aefdf903-27b7-48d7-bad2-c51aebcd66c1.png">

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
