### ISSUE TITLE
RPC `eth_getBlockByNumber` returns `null`

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#218]
##### What is the issue?

Cannot get emulated block data with cycle number.
    
#### What impact does the issue have?

Makes it hard to see the cycle marker hash and other details from a cycle number.

##### How to reproduce the issue? 

Test eth_getBlockByNumber:

```javascript
const ethers = require("ethers");

(async () => {

  // const provider = new ethers.providers.JsonRpcProvider("https://sphinx.shardeum.org/");
  // const blockNumber = "0x8192"

  const provider = new ethers.providers.JsonRpcProvider(process.env.mainnetHTTPS_QuicknodeAPIKey);
  const blockNumber = "0xc5043f"
  
  const blockData = await provider.getBlock(
    blockNumber,
    false
  );
  console.log(blockData);

})();
```

##### What other resources can you share regarding this issue?

RPC method eth_getBlockByNumber specification:

https://www.quicknode.com/docs/ethereum/eth_getBlockByNumber

**Comment by MarcusWentz** [comment]
Explorer API filtered for a specific cycle by cycle number:

https://explorer-sphinx.shardeum.org/api/cycleinfo?from=42620&to=42620

Proposed solution in Typescript by adding input string cycle number then returning the JSON response:

```typescript
import axios from "axios";

test_eth_getBlockByNumber(42620)

async function eth_getBlockByNumber(cycleToEmulateBlock: number) {

	let baseUrl = 
    "https://explorer-sphinx.shardeum.org/api/cycleinfo?from=" + 
    cycleToEmulateBlock.toString() +
    "&to=" +
    cycleToEmulateBlock.toString();
    
    // console.log(baseUrl)

    let responseRawJSON = await axios.get(baseUrl);
    let responseDataJSON = responseRawJSON.data;
    return responseDataJSON

}

async function test_eth_getBlockByNumber(cycleToEmulateBlock: number){

  let cycleData = await eth_getBlockByNumber(cycleToEmulateBlock);
  console.log("JSON object: ", cycleData);
  console.log("Raw string response: ", JSON.stringify(cycleData));

}
```

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
