### ISSUE TITLE
Validator GUI Login Password Character "@" Not Supported

### ISSUE THREAD

**Issue by SuperX-X** [Shardeum/shardeum-bug-reporting#220]
Since 1.1.2, i can t connect to the dashboard of my node.

I tried on several browser without success, i also try to change my password with another and problem still the same.

I tried to reinstall the node with the same password, no success.

I tried to reinstall and i changed my password without the symbol "@" in my password for the dashboard and this is ok.

So, i think there is a problem with the symbol "@" in the password for the dashboard access.

**Comment by MarcusWentz** [comment]
Validator Version 1.1.3 should fix this issue. 

Please reopen this issue if you see this with Validator Version 1.1.3
