### ISSUE TITLE
Validator Status Syncing For Several Days

### ISSUE THREAD

**Issue by ksbaskar** [Shardeum/shardeum-bug-reporting#222]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    Validator Node Status shows "Syncing" from date of installation (Almost 3 days)
#### What impact does the issue have?
Not went for Standby or Active so No SHM rewards 
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen -> GUI Dashboard and operator-cli status
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

node@303f0fb83c37:~/app$ operator-cli status
state: syncing
totalTimeRunning: 121.781
totalTimeValidating: '00:00:00'
lastActive: ''
lastRotationIndex: 0/0
stakeRequirement: '10.0'
nominatorAddress: '0x5afc84da313013bb56f584675d998ce901f498a0'
nomineeAddress: 981263de0bcf4485eeb4700f45054e294d04f0814d2dc2fd9683d7cb70365108
performance:
  memPercentage: 93.85131692092105
  diskPercentage: 61.89522457990987
  cpuPercentage: 4.040404040404044
currentRewards: '0.0'
lockedStake: '11.0'
nodeInfo:
  id: db3fd229894cee890ee735edd40c5d784de5cf6d8437c18facd4166786de4c88
  publicKey: 981263de0bcf4485eeb4700f45054e294d04f0814d2dc2fd9683d7cb70365108
  curvePublicKey: f41a57eab12cfd7372bd8e77168ace0443bf52a9716af4194a28329c87e01531
  externalIp: 107.175.21.40
  externalPort: 9001
  internalIp: 107.175.21.40
  internalPort: 10001
  status: syncing

:red_circle: Photos and links related to the error. :red_circle: 
<img width="806" alt="syncing" src="https://user-images.githubusercontent.com/6725456/225805014-3782eaef-f797-4123-9227-4d8891df3c22.png">
<img width="490" alt="stat" src="https://user-images.githubusercontent.com/6725456/225805246-f72a4ffd-09aa-4039-8226-9232b27f3949.png">

**Comment by MarcusWentz** [comment]
Validator Version 1.1.5 is out now. 

Upgrade to this latest version.

If you still see this issue then we can reopen the issue.
