### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by Wojtula0908** [Shardeum/shardeum-bug-reporting#226]
Node updated.
Try with:
NODE ON/ NODE OFF
Force unstake ON/OFF.
Chain deleted and added.

Now i use fourth wallet becuase when i update node i have "This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node." issue and only way to stake is new wallet.

![3](https://user-images.githubusercontent.com/128171655/226107910-46c64fca-6d9f-44c5-a494-15418a8b4f3a.png)
![4](https://user-images.githubusercontent.com/128171655/226107914-a77ee67a-6061-4c1c-a31b-0a2edd342d8d.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
