### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by ecolefrancaisedesnus** [Shardeum/shardeum-bug-reporting#229]
![image](https://user-images.githubusercontent.com/128230312/226143266-52efa5a1-d8de-4000-9869-45d5a50b03d1.png)

I clicked on the button more than 50 times. And every time transaction failed :(

Does anyone know how to solve the problem?

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
