### ISSUE TITLE
[Duplicate] Validator Active Shows ```Total time validating: 00:00:00```

### ISSUE THREAD

**Issue by vsonu04** [Shardeum/shardeum-bug-reporting#230]
The status is active and getting reward too but total time validation is not running after update 
![Screenshot_2023-03-19-05-24-07-94_4d38fce200f96aeac5e860e739312e76~2](https://user-images.githubusercontent.com/56659079/226146044-6244469f-208e-4134-b1af-25a7afb4f564.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/215
