### ISSUE TITLE
[Duplicate] Validator Cannot Unstake Error ``` This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.``` With ```Remove Stake``` Transaction

### ISSUE THREAD

**Issue by Rocks0015** [Shardeum/shardeum-bug-reporting#231]
I have tried to unstake  for 2day but not happened. Im getting error  in metamask  rpc. I have attached the error code below.
 kindly help me i need to update  my node. My telegram id: @Yuvaraj1995 my discord id: yuvaraj#4244.

(Failed transaction Transaction 7 failed! [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code": 101,"message": "No reward endTime set, can't unstake node yet","data":{"originalError": {"status":400}}}}}')

**Comment by ecolefrancaisedesnus** [comment]
bro try to stake and unstake from the validator cli

**start the cli by running the following shell script:**

`cd`
`cd .shardeum`
`./shell.sh`

**set your private key in your validator cli**

`export PRIV_KEY=<private_key>`
`echo $PRIV_KEY`
`operator-cli unstake`

https://docs.shardeum.org/node/run/validator#cli

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92

**Comment by Brave-Humens** [comment]
bro try to stake and unstake from the validator cli

start the cli by running the following shell script:

cd
cd .shardeum
./shell.sh

set your private key in your validator cli

export PRIV_KEY=<private_key>
echo $PRIV_KEY
operator-cli unstake

https://docs.shardeum.org/node/run/validator#cli

Hello, can you help to find PRIV_KEY? i realy dont understand were is it
