### ISSUE TITLE
[Duplicate] Validator Stopped Error ```FailAndRestartPartition_globalReport_B``` and Validator CLI ```operator-cli status``` returns ```TypeError: Cannot read properties of undefined (reading 'idx')```

### ISSUE THREAD

**Issue by 1613557499** [Shardeum/shardeum-bug-reporting#233]
##### What is the issue?

Program running exception
  
#### What impact does the issue have?

Abnormal state, no benefit

##### How to reproduce the issue? 

I don't know. It was working fine. Suddenly there

##### What other resources can you share regarding this issue?

1. Failed to restart operator-cli
2. The container cannot be restarted
![image](https://user-images.githubusercontent.com/86406225/226261340-87a2bc27-c8e3-4527-8ce4-17803b6a4a36.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/162
