### ISSUE TITLE
Validator Stopped Error `Fatal: No seed nodes in seed list!`

### ISSUE THREAD

**Issue by alexkirillovtech** [Shardeum/shardeum-bug-reporting#234]
##### What is the issue?

Validator nodes are crushing with critical error 
    
#### What impact does the issue have?

It breaks functionality, causing a system to fail

##### How to reproduce the issue? 

Validator running version: 1.1.2

- Start the operator
- Wait some time – operator will crush with critical error

##### What other resources can you share regarding this issue?

<img width="529" alt="image" src="https://user-images.githubusercontent.com/51885928/226291549-008b315c-3217-4e4e-89d9-90cadc3f8f5e.png">

**Comment by MarcusWentz** [comment]
Q1. What do you see when you run:
```shell
curl localhost:9001/nodeinfo
```
?
Q2. What do you see when you run:
```shell
cat cli/build/logs/exit-summary.json
```
?
Q3. What do you see when you run:
```
tail cli/build/logs/fatal.log
```
?

**Comment by zdzieblowski** [comment]
Hi,
I'm also trying to set up a validator and all the *-sphinx.shardeum.org servers seem to be down ... and the validator/node crashes immediately after starting ...

`/home/node/app/cli/build/src/utils/fetch-network-data.js:45 throw new Error('Unable to fetch list of nodes in the network');`

My answers to your question @MarcusWentz:

**Q1:**
`{"nodeInfo":{"publicKey":"e1680b8154c0d1b086a674e0902fcdd5d8a487b4e4643d4f5adfaf2ca2d6f4c4","curvePublicKey":"32015460f732323d9733a5c4600796bdf9ba4e80377e943a23afbb2c77c4421d","externalIp":"---","externalPort":9001,"internalIp":"---","internalPort":10001,"status":null,"appData":{"shardeumVersion":"1.1.4","minVersion":"","activeVersion":"","latestVersion":""}}}`


**Q2:**
```
{
  "status": "Exit with warning",
  "message": "Process exited with SIGINT",
  "exitTime": 1679439320188,
  "totalActiveTime": 0,
  "nodeInfo": {
    "publicKey": "e1680b8154c0d1b086a674e0902fcdd5d8a487b4e4643d4f5adfaf2ca2d6f4c4",
    "curvePublicKey": "32015460f732323d9733a5c4600796bdf9ba4e80377e943a23afbb2c77c4421d",
    "externalIp": "---",
    "externalPort": 9001,
    "internalIp": "---",
    "internalPort": 10001,
    "status": null
  },
  "activeNodes": 0
}
```


**Q3:**
NOTHING

**Comment by MarcusWentz** [comment]
@zdzieblowski 

There will be a network update soon.

**Comment by MarcusWentz** [comment]
Validator Version 1.1.5 is out now. 

Upgrade to this latest version.

If you still see this issue then we can reopen the issue.
