### ISSUE TITLE
[Duplicate] Validator Stopped Error ```Fatal: Could not get seed list from seed node server. Timeout awaiting 'request' for 5000ms```

### ISSUE THREAD

**Issue by Ben15111** [Shardeum/shardeum-bug-reporting#235]
**I have 2 nodes with this [issue:**] If your node is stopped, it will not be part of the network and therefore is not eligible to receive node rewards
Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms

IP: 89.117.60.114: ![image](https://user-images.githubusercontent.com/114851627/226452820-5616abd1-08b7-4e72-a208-c62cdafc55d4.png)
IP: 185.213.25.49: 
![image](https://user-images.githubusercontent.com/114851627/226453202-17699804-12c2-4c8f-a2b1-51809cf4ce5b.png)

HOW TO FIX THIS ISSUE?

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104
