### ISSUE TITLE
[Duplicate] Validator GUI Tabs Load However Content Does Not Load

### ISSUE THREAD

**Issue by SpaceRider401** [Shardeum/shardeum-bug-reporting#236]
Dashboard Blank cannot see any thing and also cleared cache.
![Dashboard Blank21 03 2023](https://user-images.githubusercontent.com/126847147/226518016-19f7e1fa-412e-44ce-9f0a-2ad85265fc19.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/147
