### ISSUE TITLE
Validator VPS IP Address Expired Cannot Add Stake

### ISSUE THREAD

**Issue by Ezebrown** [Shardeum/shardeum-bug-reporting#238]
My VPS got expired before i renew it, but when i renew it ,  , when i get on board on the latest version, i was unable to Add stakes , what should i do?

**Comment by MarcusWentz** [comment]
Do you have a screenshot for your dashboard?

**Comment by Ezebrown** [comment]
![20230324_153841](https://user-images.githubusercontent.com/107863520/227556034-be8fcd74-aa81-4e98-93f2-eeb40e6b4e41.jpg)
Yes this is it.

**Comment by MarcusWentz** [comment]
What do you see exactly when you click the add stake button?

**Comment by Ezebrown** [comment]
I have solved it , i reset the wallet and retry , I have staked it.

**Comment by Ezebrown** [comment]
But when I firstly  clicked the button , it won't show anything , it will just get failed straight up.
But I've solved it now.
