### ISSUE TITLE
[Duplicate] Validator Stopped Error `Fatal: _getSeedNodes seed list was not signed by archiver`

### ISSUE THREAD

**Issue by undecesjours** [Shardeum/shardeum-bug-reporting#240]
Hi, 

I have this message, my node always stops :

![image](https://user-images.githubusercontent.com/127980910/227616236-9af37711-3886-49e0-8029-b2ccbbe69c6d.png)

Can you help me please ?

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/237
