### ISSUE TITLE
Validator SHM staked option not showing in browser FireFox and Safari

### ISSUE THREAD

**Issue by ivan-strelka** [Shardeum/shardeum-bug-reporting#241]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
 The "SHM staked:" option does not appear in the "Maintenance" tab. The data came from the back end. But the front is not displayed. 
![Monosnap Shardeum Dashboard 2023-03-25 01-10-19(1)](https://user-images.githubusercontent.com/48506765/227624256-b1580d7f-1546-45e2-a6f8-a0dd39e5b5b6.jpg)
![Monosnap Shardeum Dashboard 2023-03-25 01-13-57(1)](https://user-images.githubusercontent.com/48506765/227624355-ddc4fe15-1430-41d0-ba3d-e403b5b75988.jpg)

Version FireFox - 110.0.1 64bit MacOS Monterey 12.5.1 (21G83)
Version Safari - 15.6.1 (17613.3.9.1.16)  MacOS Monterey 12.5.1 (21G83)

![image](https://user-images.githubusercontent.com/48506765/227694448-f4219ff2-c9ed-42e9-9920-2c09e86d28e5.png)


Method request not received - /stakeInfo 
![image](https://user-images.githubusercontent.com/48506765/227627007-21893957-6f70-4d33-b3b1-5a249445e8c2.png)

```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Q1. Did you try Chrome?

Q2. Did you try Brave?

Q3. Do you have a screenshot?

**Comment by ivan-strelka** [comment]
> Q1. Did you try Chrome?
> 
> Q2. Did you try Brave?
> 
> Q3. Do you have a screenshot?

1. Chrome - works good
2. I Did not try Brave
3. screenshots here  https://drive.google.com/drive/folders/1nB3WwM2Y1ySPia9bPwdV4FDyedRrtONK?usp=sharing 
4. In FireFox and Safari  method not working  /stakeInfo If you take this parameter from there

**Comment by ivan-strelka** [comment]
screenshots

![Monosnap Shardeum Dashboard 2023-03-25 02-59-23(1)](https://user-images.githubusercontent.com/48506765/227645747-f047648e-c02a-4b9e-b6bc-a8017154a5bd.jpg)
![Monosnap Shardeum Dashboard 2023-03-25 02-59-23(1)](https://user-images.githubusercontent.com/48506765/227645839-c28ffbe0-8589-49c7-b974-b75892913c90.jpg)
![Monosnap Shardeum Dashboard 2023-03-25 02-56-08(1)](https://user-i
![Monosnap Shardeum Dashboard 2023-03-25 01-10-19](https://user-images.githubusercontent.com/48506765/227645865-2f9335a2-ea53-4175-8a36-aca22cdc3741.jpg)
mages.githubusercontent.com/48506765/227645852-26274f79-ca29-4e6c-8d8b-da923b19926f.jpg)
![Monosnap Shardeum Dashboard 2023-03-25 02-55-21(1)](https://user-images.githubusercontent.com/48506765/227645856-9c744e8e-ca4c-4301-a8e0-c70a444897c5.jpg)
![Monosnap Shardeum Dashboard 2023-03-25 01-28-40](https://user-images.githubusercontent.com/48506765/227645857-63990461-2ab7-43b4-a9de-972dc681b07e.jpg)
![Monosnap Shardeum Dashboard 2023-03-25 01-13-57(1)](https://user-images.githubusercontent.com/48506765/227645861-6c3224b6-e3b2-4e63-9245-dd0ceeb075bd.jpg)
![Monosnap Shardeum Dashboard 2023-03-25 01-10-19(1)](https://user-images.githubusercontent.com/48506765/227645863-b5fd5799-a799-481e-bcc0-36ff9f8c153f.jpg)

**Comment by MarcusWentz** [comment]
I have this working on FireFox in Linux. 

Please continue to use Chrome for now until this issue is fixed.

**Comment by ivan-strelka** [comment]
![image](https://user-images.githubusercontent.com/48506765/227694500-7f19bce4-8bd2-4e16-9c58-74a8d26de4ec.png)

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
