### ISSUE TITLE
Validator GUI Unstable query behavior?

### ISSUE THREAD

**Issue by ivan-strelka** [Shardeum/shardeum-bug-reporting#242]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 
Methods are not stable:
``` /api/node/status
/stakeInfo ```

An error occurs - see below

##### How to reproduce the issue? 
just wait and look to DevTools

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
  {"errorMessage":"Unable to fetch status","errorDetails":"AxiosError: timeout of 2000ms exceeded\n    at RedirectableRequest.handleRequestTimeout (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2781:16)\n    at RedirectableRequest.emit (node:events:390:28)\n    at Timeout.<anonymous> (/home/node/app/cli/node_modules/follow-redirects/index.js:169:12)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7) {\n  code: 'ECONNABORTED',\n  config: {\n    transitional: {\n      silentJSONParsing: true,\n      forcedJSONParsing: true,\n      clarifyTimeoutError: false\n    },\n    adapter: [ 'xhr', 'http' ],\n    transformRequest: [ [Function: transformRequest] ],\n    transformResponse: [ [Function: transformResponse] ],\n    timeout: 2000,\n    xsrfCookieName: 'XSRF-TOKEN',\n    xsrfHeaderName: 'X-XSRF-TOKEN',\n    maxContentLength: -1,\n    maxBodyLength: -1,\n    env: { FormData: [Function], Blob: null },\n    validateStatus: [Function: validateStatus],\n    headers: AxiosHeaders {\n      Accept: 'application/json, text/plain, */*',\n      'User-Agent': 'axios/1.2.2',\n      'Accept-Encoding': 'gzip, compress, deflate, br'\n    },\n    method: 'get',\n    url: 'http://103.190.37.10:9393/account/6f433d079395c4d3cfbc426328dfa7a4303fc31c432d3a5c289e630bcbe9e3f0?type=9',\n    data: undefined\n  },\n  request: <ref *1> Writable {\n    _writableState: WritableState {\n      objectMode: false,\n      highWaterMark: 16384,\n      finalCalled: false,\n      needDrain: false,\n      ending: false,\n      ended: false,\n      finished: false,\n      destroyed: false,\n      decodeStrings: true,\n      defaultEncoding: 'utf8',\n      length: 0,\n      writing: false,\n      corked: 0,\n      sync: true,\n      bufferProcessing: false,\n      onwrite: [Function: bound onwrite],\n      writecb: null,\n      writelen: 0,\n      afterWriteTickInfo: null,\n      buffered: [],\n      bufferedIndex: 0,\n      allBuffers: true,\n      allNoop: true,\n      pendingcb: 0,\n      constructed: true,\n      prefinished: false,\n      errorEmitted: false,\n      emitClose: true,\n      autoDestroy: true,\n      errored: null,\n      closed: false,\n      closeEmitted: false,\n      [Symbol(kOnFinished)]: []\n    },\n    _events: [Object: null prototype] {\n      response: [Function: handleResponse],\n      error: [Function: handleRequestError],\n      socket: [Array]\n    },\n    _eventsCount: 3,\n    _maxListeners: undefined,\n    _options: {\n      maxRedirects: 21,\n      maxBodyLength: Infinity,\n      protocol: 'http:',\n      path: '/account/6f433d079395c4d3cfbc426328dfa7a4303fc31c432d3a5c289e630bcbe9e3f0?type=9',\n      method: 'GET',\n      headers: [Object: null prototype],\n      agents: [Object],\n      auth: undefined,\n      beforeRedirect: [Function: dispatchBeforeRedirect],\n      beforeRedirects: [Object],\n      hostname: '103.190.37.10',\n      port: '9393',\n      agent: undefined,\n      nativeProtocols: [Object],\n      pathname: '/account/6f433d079395c4d3cfbc426328dfa7a4303fc31c432d3a5c289e630bcbe9e3f0',\n      search: '?type=9'\n    },\n    _ended: true,\n    _ending: true,\n    _redirectCount: 0,\n    _redirects: [],\n    _requestBodyLength: 0,\n    _requestBodyBuffers: [],\n    _onNativeResponse: [Function (anonymous)],\n    _currentRequest: ClientRequest {\n      _events: [Object: null prototype],\n      _eventsCount: 7,\n      _maxListeners: undefined,\n      outputData: [],\n      outputSize: 0,\n      writable: true,\n      destroyed: false,\n      _last: true,\n      chunkedEncoding: false,\n      shouldKeepAlive: false,\n      maxRequestsOnConnectionReached: false,\n      _defaultKeepAlive: true,\n      useChunkedEncodingByDefault: false,\n      sendDate: false,\n      _removedConnection: false,\n      _removedContLen: false,\n      _removedTE: false,\n      _contentLength: 0,\n      _hasBody: true,\n      _trailer: '',\n      finished: true,\n      _headerSent: true,\n      _closed: false,\n      socket: [Socket],\n      _header: 'GET /account/6f433d079395c4d3cfbc426328dfa7a4303fc31c432d3a5c289e630bcbe9e3f0?type=9 HTTP/1.1\\r\\n' +\n        'Accept: application/json, text/plain, */*\\r\\n' +\n        'User-Agent: axios/1.2.2\\r\\n' +\n        'Accept-Encoding: gzip, compress, deflate, br\\r\\n' +\n        'Host: 103.190.37.10:9393\\r\\n' +\n        'Connection: close\\r\\n' +\n        '\\r\\n',\n      _keepAliveTimeout: 0,\n      _onPendingData: [Function: nop],\n      agent: [Agent],\n      socketPath: undefined,\n      method: 'GET',\n      maxHeaderSize: undefined,\n      insecureHTTPParser: undefined,\n      path: '/account/6f433d079395c4d3cfbc426328dfa7a4303fc31c432d3a5c289e630bcbe9e3f0?type=9',\n      _ended: false,\n      res: null,\n      aborted: false,\n      timeoutCb: null,\n      upgradeOrConnect: false,\n      parser: [HTTPParser],\n      maxHeadersCount: null,\n      reusedSocket: false,\n      host: '103.190.37.10',\n      protocol: 'http:',\n      _redirectable: [Circular *1],\n      [Symbol(kCapture)]: false,\n      [Symbol(kNeedDrain)]: false,\n      [Symbol(corked)]: 0,\n      [Symbol(kOutHeaders)]: [Object: null prototype]\n    },\n    _currentUrl: 'http://103.190.37.10:9393/account/6f433d079395c4d3cfbc426328dfa7a4303fc31c432d3a5c289e630bcbe9e3f0?type=9',\n    _timeout: null,\n    [Symbol(kCapture)]: false\n  }\n}\n"}

```
:red_circle: 

##### What other resources can

 you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 

![Monosnap Shardeum Dashboard 2023-03-25 03-36-54(1)](https://user-images.githubusercontent.com/48506765/227652458-ae19fbcf-580f-464a-b8ad-701720ec5789.jpg)

![Monosnap Shardeum Dashboard 2023-03-25 03-42-50(1)](https://user-images.githubusercontent.com/48506765/227653001-75e8ba2c-1037-4b9b-aae2-19141159d57f.jpg)

![Monosnap Shardeum Dashboard 2023-03-25 03-42-50](https://user-images.githubusercontent.com/48506765/227653005-70b2862c-5586-4d8d-bb46-cb41bef379df.jpg)

**Comment by ivan-strelka** [comment]
![Uploading Monosnap S
![Monosnap Shardeum Dashboard 2023-03-25 03-42-50(1)](https://user-images.githubusercontent.com/48506765/227653172-
![Monosnap Shardeum Dashboard 2023-03-25 03-42-36(1)](https://user-images.githubusercontent.com/48506765/227653197-49c92f40-aa31-4621-85ff-a169fd6b17df.jpg)
e2b774ad-868a-45e8-8a70-970be93da5f2.jpg)
hardeum Dashboard 2023-03-25 03-36-54(1).jpg…]()

**Comment by ivan-strelka** [comment]
![Monosnap Shardeum Dashboard 2023-03-25 03-42-36](https://user-images.githubusercontent.com/48506765/227653261-8e4ce245-19ee-4178-b434-e629f7640512.jpg)

![Monosnap Shardeum Dashboard 2023-03-25 03-36-54(1)](https://user-images.githubusercontent.com/48506765/227653292-c6f36c0f-213d-428e-a0e4-82d6e24f6de5.jpg)

![Monosnap Shardeum Dashboard 2023-03-25 03-42-50(1)](https://user-images.githubusercontent.com/48506765/227653319-ff95cc0d-b71d-4757-9856-85a54db2c84d.jpg)

**Comment by swarna1101** [comment]
The error encountered when utilizing the /stakeInfo method, leading to an "Application error: Unable to fetch status," has been thoroughly investigated. However, due to the intricacies involved, this issue will be resolved in the forthcoming update.
