### ISSUE TITLE
Validator Unstake Metamask Error `Transaction Expired`

### ISSUE THREAD

**Issue by ivan-strelka** [Shardeum/shardeum-bug-reporting#243]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```

Trying to remove a stake and an error occurs 

```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 

![Monosnap Monosnap 2023-03-25 04-01-39(1)](https://user-images.githubusercontent.com/48506765/227655404-86d1976c-8a97-4586-b816-b2562f90d678.jpg)

**Comment by MarcusWentz** [comment]
Q1. Did you reset your wallet activity in Metamask to update the nonce?

Q2. Can you transfer SHM between wallets?

Q3. If you can transfer SHM between wallets, can you unstake after a few attempts?

**Comment by ivan-strelka** [comment]
1. Yes, I dropped it. Before and after the reset, the behavior is the same
2. No. Transfer between accounts does not work
3. I tried to cancel the bet 10-15 times - the result is the same - the same error. Also between accounts 10 -15 is not transferred

**Comment by MarcusWentz** [comment]
Are you able to use another wallet account in Metamask for now or do those transactions fail too?

**Comment by ivan-strelka** [comment]
I can't check for now. Because I can't remove the stake. There are other accounts. But I can’t make transactions because there is nowhere.

**Comment by MarcusWentz** [comment]
Are you able to use any of these faucets with another wallet:
https://docs.shardeum.org/faucet/claim
?

If not, can you send me another wallet address you would like to use?
I can send you some testnet SHM to that wallet then.

**Comment by ivan-strelka** [comment]
yes my new wallet 0xb8BdaBd22183cb0f572B4d95f902BA5Dc2069f0C send please SHM

**Comment by MarcusWentz** [comment]
I sent you some SHM to wallet address 0xb8BdaBd22183cb0f572B4d95f902BA5Dc2069f0C now.

Q1. Are you able to transfer SHM between wallets?

Q2. After uninstalling https://docs.shardeum.org/node/run/validator#uninstall-validator then reinstalling https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator the Validator, can you use this wallet to stake?

**Comment by ivan-strelka** [comment]
1.  I tried to transfer between wallets - the transaction is hanging -  id transaction 0xee67d084c47317b3ad14584ec7464692833e48b27a4ad8001fd8d7b0cdbbe425
2.  To be honest, I don't know. This case has not been tried.

**Comment by ivan-strelka** [comment]
after 15 minute success 0xee67d084c47317b3ad14584ec7464692833e48b27a4ad8001fd8d7b0cdbbe425

**Comment by ivan-strelka** [comment]
When translating, my colleague did not succeed
![image](https://user-images.githubusercontent.com/48506765/227736138-352cc18f-66cb-485a-b9b7-f66b0f7ea850.png)

**Comment by ivan-strelka** [comment]
Thanks for SHM ❤️❤️❤️

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
