### ISSUE TITLE
Validator GUI Shows 0 SHM Staked On Maintenance Page While Overview Shows SHM Staked

### ISSUE THREAD

**Issue by vsonu04** [Shardeum/shardeum-bug-reporting#244]
In dashboard , overview page showing I have staked 11shm but in maintenance page it's showing 0, after update I have successfully unstaked but can't stake again with same Wallet 
![Screenshot_2023-03-25-10-20-40-58_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/56659079/227697240-195ad13b-5535-45b1-b15f-522c9c99f225.jpg)
![Screenshot_2023-03-25-10-20-47-52_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/56659079/227697250-31d96a27-f689-444b-afc2-5b329b1fdd30.jpg)

**Comment by MarcusWentz** [comment]
What do you see when you run the following in your Vaildator CLI:
```shell
operator-cli status
```
?
Source:
https://docs.shardeum.org/node/run/validator#step-6-monitor-validator

**Comment by vsonu04** [comment]
![Uploading Screenshot_2023-03-25-10-58-59-87_61c78dc80ee02b53007c815fefe993e3.jpg…]()

**Comment by MarcusWentz** [comment]
@vsonu04 

I am not able to see your screenshot.

Can you copy and paste the Validator CLI output or take a screenshot again?

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
