### ISSUE TITLE
[Duplicate] RPC ```eth_getBalance``` returns 0 SHM in Metamask

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#245]
##### What is the issue?

The same issue that is was fixed in the past and now it came back again. Decreasing balance in my metamask 
    
#### What impact does the issue have?

it can drain all your balance as it is decreasing

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/44

**Comment by AndreiW3b3** [comment]
@MarcusWentz can close this as it seams balance not decreasing anymore. will eep an eye on it
