### ISSUE TITLE
Solidity Remix IDE Compiler Error `Uncaught NetworkError`

### ISSUE THREAD

**Issue by Ronindboss** [Shardeum/shardeum-bug-reporting#247]
![Screenshot (143)](https://user-images.githubusercontent.com/120661366/227734262-4e1a9f1d-1258-418e-aa05-6fe9ec588b92.png)
when complying a smart contract, it brings an error as you can see at the bottom part of the screen
this is the error code  '"Worker error: Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://binaries.soliditylang.org/wasm/soljson-v0.8.17+commit.8df45f5f.js' failed to load"

wallet address: 0x174bb8172d23316C338DFB21FaF32eecbAa62Afe

**Comment by MarcusWentz** [comment]
Can you share the contract in text form?

**Comment by Ronindboss** [comment]
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17; // Specifies the version of Solidity, using semantic versioning.

contract HelloWorld { // Defines a contract named `HelloWorld`

   string public message; // Declares a state variable `message` of type `string`.

   constructor(string memory initMessage) {    // Constructors are used to initialize the contract's data.
      message = initMessage;      // Accepts a string argument `initMessage`.
   }

   function update(string memory newMessage) public { // A public function that accepts a string argument.
      message = newMessage;
   }

}
```

**Comment by Ronindboss** [comment]
![Screenshot (144)](https://user-images.githubusercontent.com/120661366/227736514-1a7d70dc-2d13-466b-97a1-cdec66be92f2.png)
contract was gotten from the offcial site
https://docs.shardeum.org/smartContracts/deploy/remix

**Comment by MarcusWentz** [comment]
The contract compiles for me in Remix IDE with Betanet 1.X selected.

Please refresh Remix IDE and compile only the contract.

**Comment by Ronindboss** [comment]
Alright, I'll try that, what's the RPC setting for Betanet 1.X

I only have Sphinx 1.X and Liberty 1.X
