### ISSUE TITLE
RPC Transaction Error `Transaction nonce != actualNonce expectedNonce`

### ISSUE THREAD

**Issue by ivan-strelka** [Shardeum/shardeum-bug-reporting#249]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```

Accounts belong to different people. Try transfer 0xb8BdaBd22183cb0f572B4d95f902BA5Dc2069f0C to 0xdc5536C720ffc3dfd76a5269DCda992EC787a67e 
Not successful


![image](https://user-images.githubusercontent.com/48506765/227736671-1ad702f9-390c-47be-ae2a-89e852f5a8c3.png)

```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by ivan-strelka** [comment]
![image](https://user-images.githubusercontent.com/48506765/227736753-e0caa036-a710-4b06-929e-0a4a9ec8a6e6.png)

**Comment by MarcusWentz** [comment]
Did you reset your Metamask activity to update the nonce value
https://support.metamask.io/hc/en-us/articles/360015488891-How-to-reset-an-account
?

**Comment by ivan-strelka** [comment]
No, I didn't drop it. It was a brand new wallet with a clean history.

**Comment by ivan-strelka** [comment]
Now I dropped my wallet. It was possible to transfer between the accounts of different people.

**Comment by ivan-strelka** [comment]
id transaction 0xb4a68b3476d3a4f7dfed00a4c7b46a78aff7843d11579e830e72fa176998d8f9

**Comment by MarcusWentz** [comment]
This error also appears for transactions outside of Metamask through programming scripts.

**Comment by nfts2me** [comment]
On my first deploy and first TX from the account (nonce 0), I got this error:
```js
ProviderError: 
[ethjs-query] while formatting outputs from RPC 
'{"value":{"code":-32603,"data":{"code":101,"message":"Transaction nonce != 0 1","data":{"originalError":{"status":400}}}}}'`
```

On the second TX from the account after the fail (nonce === 1) I got success from the RPC, but the explorer shows an error: https://explorer-sphinx.shardeum.org/transaction/0x5781948fd9ee6051d60ae2f7ed09f3c1f9075dd0e1419caf3be7b9201a7234d5

It says it failed, but the new contract was created at https://explorer-sphinx.shardeum.org/address/0x0bd74C45553609C024D4FC5dD31AF14a9f74423d


Then, I tried to deploy another contract (was nonce == 2), and got this error:
```js
ProviderError: 
[ethjs-query] while formatting outputs from RPC 
'{"value":{"code":-32603,"data":{"code":101,"message":"Transaction nonce != 2 1","data":{"originalError":{"status":400}}}}}'
```

Then, when trying to the TX Hash, I got this error:
```js
ProviderError: JsonRpcEngine: Response has no error or result for request:

{
  "method": "eth_getTransactionByHash",
  "params": [
    "0x5781948fd9ee6051d60ae2f7ed09f3c1f9075dd0e1419caf3be7b9201a7234d5"
  ],
  "jsonrpc": "2.0",
  "id": 1583191147,
  "tabId": 1993636167
}
```

**Comment by MarcusWentz** [comment]
For now you can manually calculate the nonce while we look into this.

Example:

https://gist.github.com/skundu42/870a27cb76b472e270fe7e02987e4819

**Comment by rmagon** [comment]
Facing the same issue, will try the suggested solution

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.

**Comment by rmagon** [comment]
> this issue has been successfully resolved in the latest version of our network.

I can confirm that we haven't faced this issue for [airlyft](https://airlyft.one/) in the latest network integration. Thanks!
