### ISSUE TITLE
Validator GUI Add Stake Button Loading

### ISSUE THREAD

**Issue by ivan-strelka** [Shardeum/shardeum-bug-reporting#250]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```

1. Add a bet

```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 

![image](https://user-images.githubusercontent.com/48506765/227737011-e1955cd6-e0c5-4f5a-9946-4170fe24bae2.png)

**Comment by MarcusWentz** [comment]
Q1. What happens when you refresh the page?

Q2. Were you able to stake?

**Comment by ivan-strelka** [comment]
1 There is a refresh page button becomes active like this

![image](https://user-images.githubusercontent.com/48506765/227756829-84cce1d0-0f65-4adb-b174-1af7053557b0.png)

2 Yes. Successfully completed

**Comment by wkripto** [comment]
I have enough SHM in my wallet. I press the Stake button and it asks for wallet permission. I give the permission, the staking button appears as loading on the page, then suddenly it reverts back and no transaction can be made. How can i solve this problem?

**Comment by MarcusWentz** [comment]
@wkripto 

Uninstall
https://docs.shardeum.org/node/run/validator#uninstall-validator 
then reinstall 
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator
then try again.

**Comment by ogeleka** [comment]
I have enough SHM in my wallet. I press the Stake button and it asks for wallet permission. I give the permission, the staking button appears as loading on the page, then suddenly it reverts back and no transaction can be made. How can i solve this problem? i have also uninstall and reinstall, what can i do about it
![Screenshot (42)](https://user-images.githubusercontent.com/118355571/229268074-75893f3c-2cfa-4c74-b3dd-e9398e406a7d.png)

**Comment by ogeleka** [comment]
> I have enough SHM in my wallet. I press the Stake button and it asks for wallet permission. I give the permission, the staking button appears as loading on the page, then suddenly it reverts back and no transaction can be made. How can i solve this problem?

have you finnally solve yours ? how did you do it.....

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
