### ISSUE TITLE
https://app.swapped.finance/tr/swap

### ISSUE THREAD

**Issue by cemkayabasi** [Shardeum/shardeum-bug-reporting#251]
Oops!
Swap failed: Bilinmeyen hata : "[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal error"}}}'" . Fiyat değişme toleransınızı artırmayı deneyin

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/168
