### ISSUE TITLE
Faucet Does Not Give SHM Betanet 1.1.5

### ISSUE THREAD

**Issue by undecesjours** [Shardeum/shardeum-bug-reporting#252]
Hi, i followd carefully the process to update my node, including the reset of my metamask account:

![image](https://user-images.githubusercontent.com/127980910/227792382-b972559e-0fe9-4a73-8ab2-1123ee2a65bd.png)
![image](https://user-images.githubusercontent.com/127980910/227792452-e275c28f-56de-4670-849a-4c7e0ebb0de9.png)

I can't stake and the faucets don't arrive to my account ....

I spend a lot of time with this node and i'm loosing anking.

Can you help me ? I know it is a testnet, but there are too many bugs. 

Thank you

**Comment by MarcusWentz** [comment]
What happens when you click the stake button when you input 10 SHM?

**Comment by MarcusWentz** [comment]
Q1. Did you try every faucet 
https://docs.shardeum.org/faucet/claim#shardeum-discord-website 
?
Q2. What is your wallet address? I can send you some tokens if you need them.

**Comment by undecesjours** [comment]
Yes, i tried the faucet on discord, it seems to work but faucet never arrive ... 
My adress is 0x26fa047f961faC08e6AD4721B16e6482D8053Fd5

Thanks .. i have the feeling transactions don't work at all,

**Comment by MarcusWentz** [comment]
Sent you tokens now.

Can you transfer SHM between wallets as a test transaction?

**Comment by undecesjours** [comment]
Hi,
here is my account 0x26fa047f961faC08e6AD4721B16e6482D8053Fd5 you sent faucets to :
![image](https://user-images.githubusercontent.com/127980910/227803215-42529275-e99b-4ecb-8c75-a4b8bbfbb25f.png)

I can try a transfer from this other account :
0x44925Fc9700A655d9692394D2C55B215Ab12CD01

But i need you to send me faucets on this one too to transfer SHM to the main one.

Thks

PS: how can i reinstall the nodewith my private key ?

**Comment by MarcusWentz** [comment]
I see you have SHM to the original wallet you shared:
https://explorer-sphinx.shardeum.org/account/0x26fa047f961fac08e6ad4721b16e6482d8053fd5

What do you see in Metamask now for that wallet?

You don't need to do anything with your private key when reinstalling the validator.

**Comment by cmnascimentor** [comment]
Having same issue here, but not even receiving SHM from Discord faucet. On Shardeum Explorer it says that my account does not exist, even though I have SHM and multiple txs on Liberty 2.1.

Address: 0x843cC2e5957dA6aA349792F65C07D50626E96205

Thank you in advance!

**Comment by undecesjours** [comment]
> I see you have SHM to the original wallet you shared: https://explorer-sphinx.shardeum.org/account/0x26fa047f961fac08e6ad4721b16e6482d8053fd5
> 
> What do you see in Metamask now for that wallet?
> 
> You don't need to do anything with your private key when reinstalling the validator.

Hi, it seems to work for the moment, thanks ;)

**Comment by MarcusWentz** [comment]
@cmnascimentor 

I see your address on the Explorer now after sending you tokens.

https://explorer-sphinx.shardeum.org/account/0x843cc2e5957da6aa349792f65c07d50626e96205

@undecesjours 

Thank you for confirming.
