### ISSUE TITLE
Staking Problem

### ISSUE THREAD

**Issue by wkripto** [Shardeum/shardeum-bug-reporting#253]
I have enough SHM in my wallet. I press the Stake button and it asks for wallet permission. I give the permission, the staking button appears as loading on the page, then suddenly it reverts back and no transaction can be made. How can I solve this problem?

![image](https://user-images.githubusercontent.com/123942381/227802628-f1f600f4-6c6d-46d6-b1f1-94ebe2f2c985.png)

![image](https://user-images.githubusercontent.com/123942381/227802649-df4bf108-2c56-4b33-aea2-6decafc6435b.png)

![image](https://user-images.githubusercontent.com/123942381/227802660-6df63a22-26d6-414e-9aa2-ec7f55ac28a4.png)

**Comment by wkripto** [comment]
Resetting metamask solved the problem. But I did this before the update. Now i did it for the second time.

**Comment by ogeleka** [comment]
> Resetting metamask solved the problem. But I did this before the update. Now i did it for the second time.

did same and it worked thank you.
