### ISSUE TITLE
Validator 1.1.5 Stake Transactions Fail

### ISSUE THREAD

**Issue by Konst2172** [Shardeum/shardeum-bug-reporting#254]
Good evening!
Please, check and fix a possibility to add stake. Couldn't do it for 2 days.
![image](https://user-images.githubusercontent.com/129011009/227807750-364b65de-073d-4b9a-8bff-4936f2c60a69.png)
![image](https://user-images.githubusercontent.com/129011009/227807790-b0d52f17-3201-47b3-a07e-abbfe76df823.png)

**Comment by MarcusWentz** [comment]
Q1. Can you transfer SHM between wallets as a test?

Q2. Did you try with another wallet?

**Comment by Konst2172** [comment]
You know, Its a magic, but stake was successful today! Thank you for your attention!
But I have another question. I made additional node and account to check you reccomendations. And I realised that my node is always in standby mode. I staked 10 shm there. How to make t active?

**Comment by MarcusWentz** [comment]
The validator will automatically become active.

The time become active depends on network demand and validator supply.
