### ISSUE TITLE
Solidity ThirdWeb Smart Contracts Deployments Fail on Betanet 1.X 

### ISSUE THREAD

**Issue by imayanmajumdar** [Shardeum/shardeum-bug-reporting#255]
##### What is the issue?
I am currently unable to successfully deploy smart contracts, specifically those related to NFT Drop and Drop, on Shardeum Sphinx 1.X utilizing Thirdweb.
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?
It is important to note that the community will not have the capability to deploy smart contracts
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 
One possible method of reproducing the issue at hand involves accessing Thirdweb and attempting to deploy a NFT Drop Smart Contract.
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Do you have a GitHub link to a specific ThirdWeb contract that fails?

**Comment by imayanmajumdar** [comment]
Just go to Thirdweb and try to deploy a NFT Drop Smart Contract

**Comment by MarcusWentz** [comment]
Do you have a link to the exact interface you are using to deploy this?

**Comment by MarcusWentz** [comment]
Website link for deploying contracts for testing:

https://thirdweb.com/thirdweb.eth/DropERC721

First transaction successful, but the second transaction failed. 

I tried this with Metamask and Bitkeep wallets and see this issue.

I cannot use the Brave wallet with this site.

**Comment by imayanmajumdar** [comment]
I've been trying on this for the past 15 days, and unfortunately, the problem isn't just limited to Betanet; it also persists on Alpha Net (Liberty Test Network).

**Comment by imayanmajumdar** [comment]
**Update:** 

Now I can't even complete the first transaction

**Comment by imayanmajumdar** [comment]
![image](https://user-images.githubusercontent.com/21265128/229482244-0fb26e92-957b-44d6-add4-f8cc96e8ec05.png)

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
