### ISSUE TITLE
Spriyo Website Wallet Not Connecting? 

### ISSUE THREAD

**Issue by zexer2137** [Shardeum/shardeum-bug-reporting#256]
##### What is the issue?

:red_circle:  Can't connect metamask to spriyo (after connecting there is still the "connect wallet" button instead of create
    
#### What impact does the issue have?

:red_circle: Can't create any nft . :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Which network are you using?

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
