### ISSUE TITLE
[Duplicate] Explorer Address Error ```Account Not Found!```

### ISSUE THREAD

**Issue by yassir781** [Shardeum/shardeum-bug-reporting#257]
##### What is the issue?

:red_circle:  The explorer shows that my account is not found in the explorer and I can't get faucet tokens :red_circle: 
    
#### What impact does the issue have?

:red_circle: I think it makes all my interactions with faucets fail, I've been trying for days. it works on beta 1.6 and 2.1 but not on sphinx, impossible to get tokens needed to start my node :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Search for my adress in the sphinx explorer:
https://explorer-sphinx.shardeum.org/account/0x7077ff7e627767dc20c802e76202106ed5f4e52d
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: ![image](https://user-images.githubusercontent.com/4275863/227992743-498b7fb7-51b8-415e-84fa-12d17239b9f7.png) :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/95
