### ISSUE TITLE
Validator `operator-gui` status `errored`

### ISSUE THREAD

**Issue by AnDropKiny** [Shardeum/shardeum-bug-reporting#258]
![image](https://user-images.githubusercontent.com/112488858/228042974-c2bee791-9c02-4035-9c6b-b8f47b006149.png)
![image](https://user-images.githubusercontent.com/112488858/228043057-b2235fff-8bb4-4cb3-96cf-8587435fb8d8.png)
Problems started after version 1.1.3
What steps have I tried:
1) Reinstalling the node
2) Various updates on the server
3) Complete server reset and node installation from scratch
4) Reinstalling the OS on the server and installing the node
5) Trying to login to Dashboard from other devices, even asking people to login from USA

**Comment by MarcusWentz** [comment]
What OS are you using?

**Comment by AnDropKiny** [comment]
first 22.04 didn't work, then reset to Ubuntu 20.04 64bit still doesn't work

**Comment by MarcusWentz** [comment]
What web browsers have you tried the Validator GUI with?

**Comment by AnDropKiny** [comment]
did you read the steps i did?
I tried different browsers, different internets, different computers and even countries!

**Comment by MarcusWentz** [comment]
Please state the specific browsers you tried.

**Comment by AnDropKiny** [comment]
safari, chrome, opera, cleared cookies and cache too.

**Comment by AnDropKiny** [comment]
This isnt just my problem! look in the discord in the discussion thread

**Comment by MarcusWentz** [comment]
Q1. Are you using HTTPS or HTTP for your Validator GUI URL?

Q2. Are you able to stake and unstake from the Validator CLI as a test to see if this is just a visual Validator GUI issue?

**Comment by AnDropKiny** [comment]
Q1. I have tried HTTPS and HTTP

Q2. don't want to connect my wallet key to the validator

**Comment by MarcusWentz** [comment]
I will share this feedback with the core team. 

I have the Validator GUI running on my computer for reference.

My setup:

OS: Linux Mint
Web browser: FireFox

**Comment by MarcusWentz** [comment]
What happens when you rebuild and start the Validator GUI:
```shell
cd gui 
npm run build && npm start
```
?

**Comment by AnDropKiny** [comment]
![image](https://user-images.githubusercontent.com/112488858/228649521-b019f173-0a92-4f8a-8d1a-6fcaef778284.png)
![image](https://user-images.githubusercontent.com/112488858/228649612-176eaa5a-3e4b-4773-8286-ad6e32f1d90f.png)
did but didnt help
![image](https://user-images.githubusercontent.com/112488858/228650605-e1e20c8b-6487-484e-9e11-67b1216b3581.png)
but now it doesn’t write an error and the status doesn’t give an error either, it says that it works ... I also updated the validator to a new version

**Comment by AnDropKiny** [comment]
109.106.255.144:8080 you can try too connect

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
