### ISSUE TITLE
Explorer Error `Unhandled Runtime Error`

### ISSUE THREAD

**Issue by LorisYanis** [Shardeum/shardeum-bug-reporting#259]
![shardeum](https://user-images.githubusercontent.com/115280526/228160264-cde0ccbd-55fc-4fff-804b-c06b6cb5cb82.png)

🔴 https://explorer-sphinx.shardeum.org/ doesn't work

**Comment by MarcusWentz** [comment]
Q1. How did you get this error?

Q2. What is your wallet address?

**Comment by LorisYanis** [comment]
> 

1. Just trying to enter the explorer
2. 0x972A1af4549FDe3b69604f1449b360B312836fE8

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
