### ISSUE TITLE
[Duplicate] Explorer Address Error `Account Not Found!`

### ISSUE THREAD

**Issue by cmnascimentor** [Shardeum/shardeum-bug-reporting#260]
:red_circle:  Not even receiving SHM from any faucet including Discord :red_circle: 

:red_circle: Unable to operate on Sphynx. :red_circle: 

On Shardeum Explorer it says that my account does not exist, even though I have SHM and multiple txs on Liberty 2.1.

Address: 0x843cC2e5957dA6aA349792F65C07D50626E96205

Thank you in advance!

**Comment by MarcusWentz** [comment]
Duplicate issue.

https://github.com/Shardeum/shardeum-bug-reporting/issues/95

I sent you SHM and I see your account now:

https://explorer-sphinx.shardeum.org/account/0x843cc2e5957da6aa349792f65c07d50626e96205

**Comment by cmnascimentor** [comment]
Appreciate it, Marcus!

Hopefully I'll be able to request from faucet and interact with Betanet now

Have a wonderful week
