### ISSUE TITLE
Kana Labs is not working?

### ISSUE THREAD

**Issue by reshmamohammed** [Shardeum/shardeum-bug-reporting#261]
Ran into an error with the following issue

![image](https://user-images.githubusercontent.com/33890325/228231665-bd23ceee-25fc-461f-8e92-beba27c22723.png)

**Comment by MarcusWentz** [comment]
Are you able to connect your wallet to the site?

**Comment by reshmamohammed** [comment]
> Are you able to connect your wallet to the site?

I wasn't able to connect. Home page itself was not displaying so couldn't play around much.

**Comment by MarcusWentz** [comment]
Did you try every network listed here:
https://docs.shardeum.org/network/endpoints
?

**Comment by swarna1101** [comment]
This is resolved with new network release.
