### ISSUE TITLE
[Duplicate] Validator GUI Pages Randomly Not Loading ```Application error: a client-side exception has occurred```

### ISSUE THREAD

**Issue by wyzwanie** [Shardeum/shardeum-bug-reporting#264]
##### What is the issue?

:red_circle:  Fresh installation of Shinx validator node, when trying to navigatge to settings tab, i get error. :red_circle: 
    
#### What impact does the issue have?

Bug makes it unable to add wallet through web ui.

##### How to reproduce the issue? 

:red_circle: 
Install fresh node using instructions provided in documentation, after install follow step 3 from instructions in console (    3. Go to the Settings tab and connect a wallet.) see error.

:red_circle: 

##### What other resources can you share regarding this issue?

Screenshorts attached:
![Screenshot from 2023-03-29 12-55-32](https://user-images.githubusercontent.com/59451058/228513479-7a28dd69-763b-4a1a-844a-4f47bdffb302.png)
![Screenshot from 2023-03-29 13-00-04](https://user-images.githubusercontent.com/59451058/228513536-76b13e12-32d6-4f93-ba34-794ac460fc07.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/94
