### ISSUE TITLE
RPC Error `Busy or error` After Simultaneous Requests

### ISSUE THREAD

**Issue by satoshiman** [Shardeum/shardeum-bug-reporting#265]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 

I use RPC (https://liberty20.shardeum.org/ ) for my DAPP, to increase web loading speed, I use Promise.all() to call simultaneous requests from the blockchain through RPC. I noticed that RPC often reports busy when there are a large number of requests (maybe 10 requests at the same time). This does not happen with the testnet networks I have used like BSC testnet. Can I increase the number of simultaneous requests?

<img width="477" alt="image" src="https://user-images.githubusercontent.com/37683529/228577431-72a4e966-3f6e-40b6-82bf-07018af8cdc4.png">

#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

The web app is working slowly and not smoothly.

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
