### ISSUE TITLE
Explorer Liberty 2.X Transaction Blank Screen

### ISSUE THREAD

**Issue by scarlet1000** [Shardeum/shardeum-bug-reporting#270]
![2023-03-29 (15)](https://user-images.githubusercontent.com/114299166/228631747-11193dc1-e644-493b-9113-209082195b51.png)

**Comment by MarcusWentz** [comment]
Link to the transaction?

**Comment by scarlet1000** [comment]
Following is the link:
https://explorer-liberty20.shardeum.org/tx/0xb913a860167e37ffadfecd596b5348d72c75302ee4190a4fd5587dec10c9d46a

If you need any further information, please let me know

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MarcusWentz** [comment]
Q1. What was done in this transaction exactly?

Q2. Did you see this error on Betanet 1.X as well?

**Comment by MarcusWentz** [comment]
I see this from the Explorer API JSON view:

https://explorer-liberty20.shardeum.org/api/transaction?txHash=0xb913a860167e37ffadfecd596b5348d72c75302ee4190a4fd5587dec10c9d46a

**Comment by MarcusWentz** [comment]
Looks like the transaction failed from the Explorer API:
```json
{
  "success": false,
  "transactions": [
    {
      "txStatus": {
        "txHash": "0xb913a860167e37ffadfecd596b5348d72c75302ee4190a4fd5587dec10c9d46a",
        "raw": "0xf90155038501dfd140008402f34f609491a6e56a5f6eec9b01eee1b2eb02d5a0fd1e8f2b888ac7230489e80000b8e47ff36ab500000000000000000000000000000000000000000000000018e3dec6abdbe2590000000000000000000000000000000000000000000000000000000000000080000000000000000000000000c4f694f8da796b7b36d9f5ceeacae5722c2d1d6e00000000000000000000000000000000000000000000000000000000642484380000000000000000000000000000000000000000000000000000000000000002000000000000000000000000d1c9b058da559e026ff3ca2493d1acf639de82cf000000000000000000000000656f8df327fcc9020894e295e8852d308fc69d88823f45a07e760e3147d483c061cf08739564625104b5ba08566781e27e7e94c1196e138ba03f096e4d860b65c899050c2ecc01f873c5069e7feeebeb4fb8e64b4e1ff01654",
        "injected": true,
        "accepted": false,
        "reason": "Transaction nonce != 3 4",
        "timestamp": 1680113756562,
        "ip": "172.70.254.105"
      }
    }
  ]
}
```
due to
```json
"reason":"Transaction nonce != 3 4"
```
Share this info here:
https://github.com/Shardeum/shardeum-bug-reporting/issues/249

**Comment by scarlet1000** [comment]
I tried to swap 10 SHM for 1.80789 SDT on https://testnet.shardex.org/
The swap went through. But the explorer initially showed something and then
it went blank

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by scarlet1000** [comment]
I did not see any error messages in Betanet.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
