### ISSUE TITLE
Removal liquidity pair AMM DEX fails?

### ISSUE THREAD

**Issue by scarlet1000** [Shardeum/shardeum-bug-reporting#271]
I created a SWPD/SHM liquidity pair (SWPD=0.0110918, SHM=10.0558). After couple of hours,
![2023-03-29 (21)](https://user-images.githubusercontent.com/114299166/228692486-b22228bf-0af5-414f-b2ac-b29683a05736.png)
![2023-03-29 (22)](https://user-images.githubusercontent.com/114299166/228692493-e97915d6-44c7-41f9-8b14-926aff3971d1.png)
 tried to remove the liquidity, but it failed 3 times.

**Comment by MarcusWentz** [comment]
Which AMM DEX are you providing liquidity to?

**Comment by scarlet1000** [comment]
https://app.swapped.finance/pool

I have 2 pools: SWPD/SHM and USDC/SHM

I tried to remove the pool SWPD/SHM 3 times last night and it failed all 3
times

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by scarlet1000** [comment]
I tried just now to remove the pool and it failed again. I have attached
the Shardeum explorer transaction details

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MarcusWentz** [comment]
From SwappedFinance?

**Comment by scarlet1000** [comment]
Yes
