### ISSUE TITLE
[Duplicate] Validator Staking GUI SHM Rewards Decreasing

### ISSUE THREAD

**Issue by SpaceRider401** [Shardeum/shardeum-bug-reporting#272]
I earned 5.3Shm(Time last active:27.03.2023) , Now my node again active on:29.03.2023 But earnings reset to 1.45Shm
My Dashboard Address: https://94.131.10.13:8080/
![Earnings Disappeared 30 03 2023](https://user-images.githubusercontent.com/126847147/228736017-d24eb605-f374-48f8-b1ae-a7d932727e02.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/45
