### ISSUE TITLE
Validator Unstake Error `No reward endTime set, can't unstake node yet`

### ISSUE THREAD

**Issue by ivan-strelka** [Shardeum/shardeum-bug-reporting#273]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

Make detached bets. Errors occur

Vervion node

{
    "runningCliVersion": "0.1.1",
    "minimumCliVersion": "0.1.0",
    "latestCliVersion": "0.1.1",
    "minShardeumVersion": "1.1.5",
    "activeShardeumVersion": "1.1.5",
    "runningGuiVersion": "0.1.1",
    "minimumGuiVersion": "0.1.0",
    "latestGuiVersion": "0.1.1",
    "runnningValidatorVersion": "1.1.5"
}

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
![image](https://user-images.githubusercontent.com/48506765/228747336-72c06405-ef38-45e9-8fa9-fb20010a96d9.png)
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by ivan-strelka** [comment]
![image](https://user-images.githubusercontent.com/48506765/228747336-72c06405-ef38-45e9-8fa9-fb20010a96d9.png)

**Comment by ivan-strelka** [comment]
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"No reward endTime set, can't unstake node yet","data":{"originalError":{"status":400}}}}}' {code: -32603, message: `[ethjs-query] while formatting outputs from RPC '{… yet","data":{"originalError":{"status":400}}}}}'`}code: -32603message: "[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":101,\"message\":\"No reward endTime set, can't unstake node yet\",\"data\":{\"originalError\":{\"status\":400}}}}}'"[[Prototype]]: Object
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17
await in _processRequest (async)
_handle @ inpage.js:17
handle @ inpage.js:17
_rpcRequest @ inpage.js:1
(anonymous) @ inpage.js:1
request @ inpage.js:1
i @ _app-d7cb3041380e4f83.js:1
send @ _app-d7cb3041380e4f83.js:1
(anonymous) @ _app-d7cb3041380e4f83.js:1
Promise.then (async)
sendUncheckedTransaction @ _app-d7cb3041380e4f83.js:1
(anonymous) @ _app-d7cb3041380e4f83.js:1
a @ _app-d7cb3041380e4f83.js:1
Promise.then (async)
l @ _app-d7cb3041380e4f83.js:1
(anonymous) @ _app-d7cb3041380e4f83.js:1
p @ _app-d7cb3041380e4f83.js:1
sendTransaction @ _app-d7cb3041380e4f83.js:1
d @ maintenance-e0c1253d5fff0365.js:1
await in d (async)
y @ maintenance-e0c1253d5fff0365.js:1
await in y (async)
T @ maintenance-e0c1253d5fff0365.js:1
R @ maintenance-e0c1253d5fff0365.js:1
onClick @ maintenance-e0c1253d5fff0365.js:1
eV @ framework-3b5a00d5d7e8d93b.js:9
eW @ framework-3b5a00d5d7e8d93b.js:9
(anonymous) @ framework-3b5a00d5d7e8d93b.js:9
rn @ framework-3b5a00d5d7e8d93b.js:9
rt @ framework-3b5a00d5d7e8d93b.js:9
(anonymous) @ framework-3b5a00d5d7e8d93b.js:9
oN @ framework-3b5a00d5d7e8d93b.js:9
eF @ framework-3b5a00d5d7e8d93b.js:9
ri @ framework-3b5a00d5d7e8d93b.js:9
nV @ framework-3b5a00d5d7e8d93b.js:9
nI @ framework-3b5a00d5d7e8d93b.js:9

**Comment by MarcusWentz** [comment]
Q1. Are you trying to unstake?

Q2. If you are trying to unstake, did you click the toggle button "Force Remove Stake"?

**Comment by ivan-strelka** [comment]
1. Yes
2. When I used "Force Remove Stake" everything was successful
