### ISSUE TITLE
Faucet Not Working Sphinx 1.1.6

### ISSUE THREAD

**Issue by faizanr11** [Shardeum/shardeum-bug-reporting#274]
I have been begging for sphinx faucet..no one is giving..faucet in discord not working
0x433026F0311D63A7f873DB75Eb1e744df624Ec30
Please send me more than 20 tokens...i want to update my  validator @MarcusWentz

**Comment by MarcusWentz** [comment]
Sent you tokens now.

**Comment by lowcap5** [comment]
I've been making requests to the discord faucet unsuccessfully for a week.
 I'm trying to stake SHM to run my sphinx validator node
I need at least 11 SHM 0xc5a2ce3a6C74704E9CdF48B1cFe23F60b17007FA

**Comment by MarcusWentz** [comment]
@lowcap5 

Sent you some tokens.

**Comment by MetaverseMike** [comment]
Two days. Someone gave me 15 but it seems I used them somehow. I thought I was paying with matic to get my .shm. no biggie but I'd like to do more things. 

0x4B2f6F8d0a47c3Bd47bcF98ADc329638C9d20D64

**Comment by MarcusWentz** [comment]
@MetaverseMike 

Sent you tokens now.

I see you have them here:
https://explorer-sphinx.shardeum.org/account/0x4b2f6f8d0a47c3bd47bcf98adc329638c9d20d64

**Comment by sametserpil** [comment]
I can't also get any tokens from faucet. I have running node but I can't stake any SHM.

@MarcusWentz 
Please send some to 0x9d3094B3291D91DFe5fa1755D9331a8aebf6ac33

Thank you in advance

**Comment by MarcusWentz** [comment]
@sametserpil 

Sent you tokens now.

I see you have them here:
https://explorer-sphinx.shardeum.org/account/0x9d3094B3291D91DFe5fa1755D9331a8aebf6ac33

**Comment by sametserpil** [comment]
> @sametserpil
> 
> Sent you tokens now.
> 
> I see you have them here: https://explorer-sphinx.shardeum.org/account/0x9d3094B3291D91DFe5fa1755D9331a8aebf6ac33

They've arrived. Thanks.

**Comment by kameroongod** [comment]
Please send tokens for Sphinx 1 too. Need 11 to run a node
0x9eCd2eD8762C693008141a3809a56616Da0f596C

Metamask showing 0.

**Comment by lowcap5** [comment]
I was able to install the updated validator but my previous testnet SHM was lost in the update and I still can't get any from the faucet, so I'm here to humbly request testnet tokens to start my stake and run my node.
0xc5a2ce3a6C74704E9CdF48B1cFe23F60b17007FA

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
