### ISSUE TITLE
Validator Version 1.1.6 Update Not Working 

### ISSUE THREAD

**Issue by CryptoWild999** [Shardeum/shardeum-bug-reporting#275]
![uuuuuuu](https://user-images.githubusercontent.com/117856956/228868588-3a30f02a-85f3-4d32-bed9-6cb46eac52ba.jpg)
I'd like to update my validator for 1.1.6 version from 1.1.5

:red_circle: My installation stops at 5 [step](![uuuuuuu](https://user-images.githubusercontent.com/117856956/228868297-4b6d3132-0b8a-4ed9-8348-68dbc2f79426.jpg)) (Create Compose Project). :red_circle: 

I am waiting and they Putty shows an error and I need to close my CLI to run it again. I tried 2 times with the same result.

**Comment by MarcusWentz** [comment]
Does this work if you uninstall:
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator
then reinstall:
https://docs.shardeum.org/node/run/validator#uninstall-validator
?

**Comment by CryptoWild999** [comment]
It doesn't help.

**Comment by CryptoWild999** [comment]
Anything else I can do?

**Comment by MarcusWentz** [comment]
The last line I see in your terminal for the installation is
```shell
Starting image. This could take a while...
```
Did you see errors after this?

If you did, please share a screenshot for the errors.

**Comment by CryptoWild999** [comment]
I stopped another node that I have on the VPS and then it started to work.
I believe it used too much resources. Thanks for help

sob., 1 kwi 2023 o 18:20 Marcus Wentz ***@***.***> napisał(a):
