### ISSUE TITLE
RPC `eth_gasPrice` value does not multiply with gasLimit from `eth_estimateGas` to be estimated Transaction Fee in Metamask 

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#276]
##### What is the issue?

The estimated transaction fee calculated is incorrect.

:warning: Note that :warning: 
```javascript
gasPrice*gasLimit = estimatedTransactionFee
```
since
```javascript
gasPrice*gasUsed = transactionFee
```
   
#### What impact does the issue have?

Makes it difficult for users to know how much their transaction fees will be.

##### How to reproduce the issue? 

Expected:
```javascript
estimatedTransactionFee = 0.01 Ether
```

Actual calculated in Metamask:
```javascript
const ethers = require("ethers");
(async () => {
  const provider = new ethers.providers.JsonRpcProvider("https://sphinx.shardeum.org/");
  const signer = new ethers.Wallet(Buffer.from(process.env.devTestnetPrivateKey, 'hex'), provider);
  const gasPrice = await provider.getGasPrice();
  console.log("gasPrice: " + gasPrice.toString() + " Wei");

  const gasLimit = await provider.estimateGas({
    to: signer.address,
    value: 1,
  });
  console.log("gasLimit: " + gasLimit.toString() + " Wei");

  const estimatedTransactionFee = gasPrice*gasLimit;
  console.log("estimatedTransactionFee = gasPrice*gasLimit = " + estimatedTransactionFee/(10**18) + " Ether"); // Rounded to 0.2415 Ether in Metamask.

})();
```
Returns:
```javascript
gasPrice: 8049999872 Wei
gasLimit: 30000000 Wei
estimatedTransactionFee = gasPrice*gasLimit = 0.24149999616 Ether
```

##### What other resources can you share regarding this issue?

RPC method eth_gasPrice specification:

https://www.quicknode.com/docs/ethereum/eth_gasPrice

RPC method eth_estimateGas specification:

https://www.quicknode.com/docs/ethereum/eth_estimateGas

Ethereum Legacy Transactions: How to calculate transaction fee?

https://ethereum.stackexchange.com/a/19690

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
