### ISSUE TITLE
Validator GUI `Remove Stake` Button Randomly Goes Away

### ISSUE THREAD

**Issue by Jamarox** [Shardeum/shardeum-bug-reporting#278]
After upgrade Sphinx validator client to 1.1.6 it was hard to unstake and stake. It took both 3-4 attempts but finally it works (I tried increase gas). But when I watch maintenance tab now, I see that Add / Remove Stake area randomly switches:
![image](https://user-images.githubusercontent.com/126200428/228941179-cb6c0e58-7946-4260-b099-9dea5e52d2c2.png)
![image](https://user-images.githubusercontent.com/126200428/228941267-cc54ce08-acc0-4c62-90b8-6c9acf202f5b.png)
![image](https://user-images.githubusercontent.com/126200428/228941296-0e87d85d-1806-4677-ac0a-fbd7033479aa.png)

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
