### ISSUE TITLE
RPC ```eth_call``` in Golang works with ```client.Call(&result, "eth_call", req, "latest")``` but ```client.CallContract(context.Background(), callMsg, nil)``` returns ```Busy or error```

### ISSUE THREAD

**Issue by shreethejaBandit** [Shardeum/shardeum-bug-reporting#28]
Shardeum RPC URL throws error when contract read methods are called via go client which is a official version of Geth client.
    
Impact : Read And Write To blockchain From Golang Applications are not possible.

##### How to reproduce the issue? 

```go
package main

import (
	"context"
	"fmt"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	client, _ := ethclient.Dial("https://liberty20.shardeum.org")
	defer client.Close()

	contractAddr := common.HexToAddress("0x8f01876ccd727fd703787ed477b7f71e1e3adbb1")
	callMsg := ethereum.CallMsg{
		To:   &contractAddr,
		Data: common.FromHex("0x8da5cb5b"),
	}
	res, err := client.CallContract(context.Background(), callMsg, nil)
	if err != nil {
		fmt.Println("Error Found :")
		fmt.Print(err)
		return
	}
	fmt.Printf("Owner: %s\n", common.BytesToAddress(res).Hex())

}
```

The above mentioned snippet calls owner() function from a contract deployed onto shardeum. Works fine on metamask and other chains and even on JS applications.

to run this code just type in command 
`go run main.go`

Throws error saying : busy or error

##### What other resources can you share regarding this issue?

<img width="184" alt="image" src="https://user-images.githubusercontent.com/104569507/215778629-1100423e-5cb4-4495-9c33-33e66b60b7a3.png">

**Comment by MarcusWentz** [comment]
Did you setup the contract to have the generated Go file to handle method call types for the contract:

```shell
//Step 1: Create abi file by running: solc --abi Store.sol > store.abi
//Step 2: Create bin file by running: solc --bin Store.sol > store.bin
//Step 3: Remove comments above the abi and bin files.
//Step 4: Generate Go contract interaction file by running:  abigen --bin=store.bin --abi=store.abi --pkg=store --out=store.go
//Step 5: Run: getSetEvent.go
```

?

See this example:

https://github.com/MarcusWentz/Web3_Get_Set_Contract_Metamask/tree/main/Scripts/go

**Comment by shreethejaBandit** [comment]
Yes that is for contract call i have tried that method too but this doesnt need abigen stuff this directly calls rpc method eth_call with passing raw data. To make this issue simpler i have shared a raw example.

**Comment by shreethejaBandit** [comment]
If the reference to the abigen method needed attached the code below 

```
func (rpc *EvmRpc) callTokenUri(contractAddress string, tokenId string) (string, error) {
	contract, err := erc721.NewMainCaller(common.HexToAddress(contractAddress), rpc)
	if err != nil {
		return "", err
	}

	token, err := strconv.Atoi(tokenId)
	if err != nil {
		return "", err
	}
	uri, err := contract.TokenURI(&bind.CallOpts{}, big.NewInt(int64(token)))
	if err != nil {
		return "", err
	}
	return uri, nil
}
```
Here erc721 is the contract generated from abigen method tried with this method too on eth bayc contract worked fine but in case of shardeum fails with above error.

**Comment by MarcusWentz** [comment]
I was able to run:

```go
package main

import (
	"fmt"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	client, _ := ethclient.Dial("https://liberty20.shardeum.org")
	defer client.Close()

	contractAddr := common.HexToAddress("0x8f01876ccd727fd703787ed477b7f71e1e3adbb1")
	callMsg := ethereum.CallMsg{
		To:   &contractAddr,
		Data: common.FromHex("0x8da5cb5b"),
	}
	fmt.Printf("callMsg: ", callMsg)

}
```

Are you able to use the equivalent to:

```go
client.CallContract(context.Background(), callMsg, nil)
```

in Javascript, Python and Rust in the meantime while we look into this?

**Comment by shreethejaBandit** [comment]
```
fmt.Printf("callMsg: ", callMsg)
```
This just prints the call arguments 
actual call is done by this line 
```
client.CallContract(context.Background(), callMsg, nil)
```
Which throws error. JS Python looks good but go is throwing some problems is this related to the issue #23 ?

**Comment by MarcusWentz** [comment]
Does the callMsg look correct?

**Comment by MarcusWentz** [comment]
Does the curl request work with this data as mentioned in https://github.com/Shardeum/shardeum-bug-reporting/issues/23?

**Comment by MarcusWentz** [comment]
I found another bug while testing this with a possible solution as well: https://github.com/Shardeum/shardeum-bug-reporting/issues/29

**Comment by shreethejaBandit** [comment]
> Does the callMsg printed output look correct?

<img width="863" alt="image" src="https://user-images.githubusercontent.com/104569507/215822920-f4f23bec-a916-4796-9d10-212e4a441a0a.png">
This is the call message output it seems to be proper is it acessList should be handled on sharded network.

**Comment by shreethejaBandit** [comment]
> Does the curl request work with this data as mentioned in #23?

Yes Curl works fine as attached below 
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/104569507/215823411-7733cc5d-37d1-4a9e-8d32-80ed689633b5.png">

**Comment by MarcusWentz** [comment]
Thank you for testing the curl request.

We will look into what might be causing this issue.

Please use Javascript and Python (or maybe even Rust) in the meantime until this is fixed.

**Comment by MarcusWentz** [comment]
The curl request in text form to test:

```shell
curl 'https://liberty20.shardeum.org/'  -H 'content-type: application/json'  --data-raw '{"method":"eth_call","params":[
{
    "to":"0x8f01876ccd727fd703787ed477b7f71e1e3adbb1",
    "data":"0x8da5cb5b"
},"latest"],"id":46,"jsonrpc":"2.0"}' 
```

Result:

```shell
{"jsonrpc":"2.0","id":46,"result":"0x000000000000000000000000911027f9a8e982b8f6e6d6e3e844bae26490fca4"}
```

**Comment by MarcusWentz** [comment]
It is possible the Owner function data might not match this contract for some reason. 

I recommend doing a contract call like this based on generated contract types:

```go
func getstoredData(contract *store.Store) (storedData *big.Int) {

  storedData, err := contract.StoredData(&bind.CallOpts{})
  if err != nil {
        log.Fatal(err)
  }
  return

}
```

to find the Owner.

Golang example:

https://github.com/MarcusWentz/Web3_Get_Set_Contract_Metamask/blob/main/Scripts/go/getSetEvent.go

**Comment by shreethejaBandit** [comment]
> It is possible the Owner function data might not match this contract for some reason.
> 
> I recommend doing a contract call like this based on generated contract types:
> 
> ```go
> func getstoredData(contract *store.Store) (storedData *big.Int) {
> 
>   storedData, err := contract.StoredData(&bind.CallOpts{})
>   if err != nil {
>         log.Fatal(err)
>   }
>   return
> 
> }
> ```
> 
> to find the Owner.
> 
> Golang example:
> 
> https://github.com/MarcusWentz/Web3_Get_Set_Contract_Metamask/blob/main/Scripts/go/getSetEvent.go

The Original Method Follows the same as mentioned still the same error.

**Comment by MarcusWentz** [comment]
In Javascript I get:

```javascript
const ethers = require("ethers");
(async () => {

  const provider = new ethers.providers.JsonRpcProvider("https://liberty20.shardeum.org")
  const contractAddress = "0x8f01876ccd727fd703787ed477b7f71e1e3adbb1";

  const rawCallData = "0x8da5cb5b";

  let callReturnData = await provider.call({
    to: contractAddress,
    data: rawCallData
  });

  console.log(callReturnData);
  console.log(typeof(callReturnData));
  
})();
```

which returns:

```javascript
0x000000000000000000000000911027f9a8e982b8f6e6d6e3e844bae26490fca4
string
```

I will try to test this in Rust next to see if it has any type errors like Golang.

**Comment by MarcusWentz** [comment]
Is this contract deployed to Goerli as well?

If not, please deploy it to Goerli so we can test the return value and type as well.

**Comment by shreethejaBandit** [comment]
> Is this contract deployed to Goerli as well?
> 
> If not, please deploy the contract to Goerli, then share the contract address on Goerli so we can test the return value and type as well.

Yes Goerli tested against all standard networks and JS also no problem only on golang we get this error. same code with goerlli rpc will work.

**Comment by MarcusWentz** [comment]
Rust test working:

```rust
// use std::env;

use std::str::FromStr;

use ethers::types::transaction::eip2718::TypedTransaction;

use ethers_providers::{Provider};
use ethers_core::types::{Address};

use ethers::{
    prelude::*,
};

use eyre::Result;

#[tokio::main]
async fn main() -> Result<()> {

    // let rpc_goerli_infura_https = env::var("goerliHTTPS_InfuraAPIKey").expect("$goerliHTTPS_InfuraAPIKey is not set");

    // let provider = Provider::<Http>::try_from(rpc_goerli_infura_https).expect("could not instantiate HTTP Provider");

    // let contract_address = "0x326C977E6efc84E512bB9C30f76E30c160eD06FB".parse::<Address>()?; //Chainlink Address Goerli

    // let raw_call_data = Bytes::from_str("0x70a0823100000000000000000000000066C1d8A5ee726b545576A75380391835F8AAA43c").unwrap(); //ERC-20: balanceOf(0x66C1d8A5ee726b545576A75380391835F8AAA43c)

    // let mut tx_raw = TypedTransaction::Legacy(TransactionRequest::new());
    // tx_raw.set_to(contract_address);
    // tx_raw.set_data(raw_call_data);
    // tx_raw.set_chain_id(5);

    let rpc_shardeum_https = "https://liberty20.shardeum.org/";

    let provider = Provider::<Http>::try_from(rpc_shardeum_https).expect("could not instantiate HTTP Provider");

    let contract_address = "0x8f01876ccd727fd703787ed477b7f71e1e3adbb1".parse::<Address>()?;

    let raw_call_data = Bytes::from_str("0x8da5cb5b").unwrap(); //ERC-20: balanceOf(0x66C1d8A5ee726b545576A75380391835F8AAA43c)

    let mut tx_raw = TypedTransaction::Legacy(TransactionRequest::new());
    tx_raw.set_to(contract_address);
    tx_raw.set_data(raw_call_data);
    tx_raw.set_chain_id(8081);

    println!("{:?}", tx_raw);

    let call_return_data = provider.call(&tx_raw,None).await?;
    
    println!("{:?}", call_return_data);
    // println!("{:?}", call_return_data.whatisthis); //Shows type as "ethers::types::Bytes" in error message. Credit: https://stackoverflow.com/a/21747400

    Ok(())

}
```

Returns:

```rust
Legacy(TransactionRequest { from: None, to: Some(Address(0x8f01876ccd727fd703787ed477b7f71e1e3adbb1)), gas: None, gas_price: None, value: None, data: Some(Bytes(0x8da5cb5b)), nonce: None, chain_id: Some(8081) })
Bytes(0x000000000000000000000000911027f9a8e982b8f6e6d6e3e844bae26490fca4)
```

I see the response is type Bytes (Javascript showed type String):

```rust
error[E0609]: no field `whatisthis` on type `ethers::types::Bytes`
  --> src/main.rs:50:39
   |
50 |     println!("{:?}", call_return_data.whatisthis); //Shows type as "ethers::types::Bytes" in error message. Credit: https://stackoverflow...
   |                                       ^^^^^^^^^^ unknown field
   |
   = note: available fields are: `0
```

It is possible that Golang is sensitive to this 
return type potentially being wrong when trying to unmarshal the JSON RPC response.

**Comment by MarcusWentz** [comment]
Golang 

```go
client.CallContract(context.Background(), callMsg, nil)
```

test:

```go
package main

import (
	"context"
    "encoding/hex"
	"fmt"
    "log"
    "os"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/ethclient"
    "github.com/ethereum/go-ethereum/common"
)

func main() {

	client, err := ethclient.Dial(os.Getenv("goerliHTTPS_InfuraAPIKey"))
    // client, err := ethclient.Dial("https://liberty10.shardeum.org")
    if err != nil {
        log.Fatal(err)
    }

    //Goerli
    tx_to := common.HexToAddress("0x326C977E6efc84E512bB9C30f76E30c160eD06FB")
    tx_data := common.FromHex("0x70a0823100000000000000000000000066C1d8A5ee726b545576A75380391835F8AAA43c")

    //Liberty 2.X
	// tx_to := common.HexToAddress("0x8f01876ccd727fd703787ed477b7f71e1e3adbb1")
    // tx_data := common.FromHex("0x8da5cb5b")

	callMsg := ethereum.CallMsg{
		To:   &tx_to,
		Data: tx_data,
	}
    
    fmt.Printf("callMsg: ")
    fmt.Println(callMsg)
    
	res, err := client.CallContract(context.Background(), callMsg, nil)
	if err != nil {
        log.Fatal(err)
	}

    fmt.Printf("eth_call: " + hex.EncodeToString(res) + "\n")

}
```

Goerli:

```go
callMsg: {0x0000000000000000000000000000000000000000 0x326C977E6efc84E512bB9C30f76E30c160eD06FB 0 <nil> <nil> <nil> <nil> [112 160 130 49 0 0 0 0 0 0 0 0 0 0 0 0 102 193 216 165 238 114 107 84 85 118 167 83 128 57 24 53 248 170 164 60] []}
eth_call: 0000000000000000000000000000000000000000000000008ac7230489e80000
```

Liberty 2.X:

```go
callMsg: {0x0000000000000000000000000000000000000000 0x8F01876CCd727Fd703787eD477B7f71E1E3ADbb1 0 <nil> <nil> <nil> <nil> [141 165 203 91] []}
2023/02/14 12:59:37 Busy or error
exit status 1
```

**Comment by MarcusWentz** [comment]
Golang RPC method working by sending the info raw to the RPC client:

```golang
package main

import (
	"fmt"
	"log"
    // "os"

	"github.com/ethereum/go-ethereum/rpc"
)

func main() {
    // client, err := rpc.DialHTTP(os.Getenv("goerliHTTPS_InfuraAPIKey"))
	client, err := rpc.DialHTTP("https://liberty20.shardeum.org")
	if err != nil {
		log.Fatal(err)
	}

	type request struct {
		To   string `json:"to"`
		Data string `json:"data"`
	}

	var result string

	// req := request{"0x326C977E6efc84E512bB9C30f76E30c160eD06FB", "0x70a0823100000000000000000000000066C1d8A5ee726b545576A75380391835F8AAA43c"}
	req := request{"0x8f01876ccd727fd703787ed477b7f71e1e3adbb1", "0x8da5cb5b"}
	if err := client.Call(&result, "eth_call", req, "latest"); err != nil {
		log.Fatal(err)
	}

	fmt.Printf(result + "\n")
}
```

**Comment by MarcusWentz** [comment]
Test with contract IDEX.sol on Ethereum Mainnet:

https://etherscan.io/address/0xcc13fc627effd6e35d2d2706ea3c4d7396c610ea#code

from:

https://ethereum.stackexchange.com/a/63813

Betatnet 1.X contract address:

https://explorer-sphinx.shardeum.org/account/0xa66cc96316a4df10b96dc3e62dae184d04e93ad9

RPC `eth_call` in Golang works with `client.Call(&result, "eth_call", req, "latest")`:
```go
package main

import (
	"fmt"
	"log"
    "os"

	"github.com/ethereum/go-ethereum/rpc"
)

func main() {
	client, err := rpc.DialHTTP(os.Getenv("mainnetHTTPS_InfuraAPIKey"))
	// client, err := rpc.DialHTTP("https://sphinx.shardeum.org/")
	if err != nil {
		log.Fatal(err)
	}

	type request struct {
		To   string `json:"to"`
		Data string `json:"data"`
	}

	var result string

	req := request{"0xcc13fc627effd6e35d2d2706ea3c4d7396c610ea", "0x8da5cb5b"}
	// req := request{"0xA66CC96316A4dF10b96Dc3e62dAE184d04E93Ad9", "0x8da5cb5b"}
	if err := client.Call(&result, "eth_call", req, "latest"); err != nil {
		log.Fatal(err)
	}

	fmt.Printf(result + "\n")
}
```

`client.CallContract(context.Background(), callMsg, nil)` returns `Busy or error`:

```go
package main

import (
	"context"
    "encoding/hex"
	"fmt"
    "log"
    "os"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/ethclient"
    "github.com/ethereum/go-ethereum/common"
)

func main() {

	client, err := ethclient.Dial(os.Getenv("mainnetHTTPS_InfuraAPIKey"))
    
    // client, err := ethclient.Dial("https://sphinx.shardeum.org/")

    if err != nil {
        log.Fatal(err)
    }

    //Ethereum Mainnet
    tx_to := common.HexToAddress("0xcc13fc627effd6e35d2d2706ea3c4d7396c610ea")

    //Betanet 1.X
	// tx_to := common.HexToAddress("0xA66CC96316A4dF10b96Dc3e62dAE184d04E93Ad9")

    tx_data := common.FromHex("0x8da5cb5b")

	callMsg := ethereum.CallMsg{
		To:   &tx_to,
		Data: tx_data,
	}

    fmt.Printf("callMsg: ")
    fmt.Println(callMsg)
    
	res, err := client.CallContract(context.Background(), callMsg, nil)
	if err != nil {
        log.Fatal(err)
	}

    fmt.Printf("eth_call: " + hex.EncodeToString(res) + "\n")

}
```

**Comment by skundu42** [comment]
The golang eth implementation aways sends the message with the "From" address, so if you do not provide it it will send the request with the zero value for address: 0x0000000000000000000000000000000000000000

like 

curl 'https://sphinx.shardeum.org/'  -H 'content-type: application/json'  --data-raw '{"method":"eth_call","params":[
{
    "from": "0x0000000000000000000000000000000000000000",
    "to":"0x8f01876ccd727fd703787ed477b7f71e1e3adbb1",
    "data":"0x8da5cb5b"
},"latest"],"id":46,"jsonrpc":"2.0"}'

which gives a {"jsonrpc":"2.0","id":46,"error":{"code":500,"message":"Busy or error"}}
response from our network 


fix: make our rpc identify  0x0000000000000000000000000000000000000000 as no Value (null) 

workaround: use a address in the golang request


func main() {

    client, err := ethclient.Dial("https://sphinx.shardeum.org/%22/)
    defer client.Close()

    contractAddr := common.HexToAddress("0x8f01876ccd727fd703787ed477b7f71e1e3adbb1")
    callMsg := ethereum.CallMsg{
        From: common.HexToAddress("0xfC321461191148FfC45Df25829717795909Ef8Ce"),
        To:   &contractAddr,
        Data: common.FromHex("0x8da5cb5b"),
    }
    res, err := client.CallContract(context.Background(), callMsg, nil)
    if err != nil {
        fmt.Println("Error Found 😊
        fmt.Print(err)
        return
    }
    fmt.Printf("Owner: %s\n", common.BytesToAddress(res).Hex())

}

this will give you a 200 response!

**Comment by rmagon** [comment]
Thanks, this helps for now
