### ISSUE TITLE
Validator Installation Error `debconf: delaying package configuration, since apt-utils is not installed`

### ISSUE THREAD

**Issue by Jimrish** [Shardeum/shardeum-bug-reporting#280]
##### What is the issue?

While uploading gui error message showing.
    
It shows that the delaying package configuration since apt-utils not installed

**Comment by MarcusWentz** [comment]
Do you have a screenshot?

**Comment by 0xm4gna** [comment]
This is the issue.. have the same problem

![shardeum issue](https://user-images.githubusercontent.com/122984690/229914477-1617370d-4935-4b66-af03-7a5bd0c0417d.JPG)

**Comment by MarcusWentz** [comment]
@0xm4gna 

Did the installation complete with this warning?

**Comment by Jimrish** [comment]
Yes

**Comment by MarcusWentz** [comment]
Are you able to start the GUI and CLI?

**Comment by Jimrish** [comment]
Yes, I can.
