### ISSUE TITLE
Validator GUI timing, earnings problem, log file error

### ISSUE THREAD

**Issue by Sylwester79** [Shardeum/shardeum-bug-reporting#281]
Validator Varsion 1.1.6
serwer VPS , ubuntu 20.04

- after the active status, the time is reset to 00:00:00
- after  active status, the earnings are reset and counted again (example: the current earnings are 2.5 SHM, the transition to active status takes place and the earnings are counted again and after completion is  for example 1.4 SHM , the previous earnings were zeroed)
- a large number of errors in the log file

 files in attachment

[errorFile.log](https://github.com/Shardeum/shardeum-bug-reporting/files/11118906/errorFile.log)
[errorFile log 2.log](https://github.com/Shardeum/shardeum-bug-reporting/files/11118909/errorFile.log.2.log)
![validator](https://user-images.githubusercontent.com/128922366/229043472-798ff02c-50f3-4b8e-9dba-4326e58f203c.jpg)

**Comment by swarna1101** [comment]
the issue has been successfully resolved in the latest version of our network.
