### ISSUE TITLE
Validators Not Active in more than one and a half month

### ISSUE THREAD

**Issue by Hummagumma** [Shardeum/shardeum-bug-reporting#282]
I have 2 nodes and never got active in more then one and a half month. 
    

Previously I used a Contabo server and node gets Active several times.
Now I upgraded to a better VPS (IONOS), I have 2 VPS so I'm running 2 shardeum nodes. 
Since then neve got active.
In those VPS's I have other (project) nodes so I had to change the ports so to not have conflicts
In the first VPS I changed 8080 to 12548
In the second VPS I changed 9001 to 12548
The nodes are running and the resources are far enough
But never got active. 

What Can I do?

Those are:

https://109.228.40.239:8080/
https://82.223.202.50:12548/

Please help me.
I love the project and I dont want to give up

**Comment by MarcusWentz** [comment]
When is the last time you installed and upgraded your validators?

**Comment by Hummagumma** [comment]
When 1.1.6 was released . Every time an upgrade is released I update my nodesEnviado desde mi iPhoneEl 31 mar 2023, a las 16:30, Marcus Wentz ***@***.***> escribió:﻿
When is the last time you installed and upgraded your validators?

**Comment by MarcusWentz** [comment]
It is possible there was an issue with the upgrade. 

Try to uninstall:
https://docs.shardeum.org/node/run/validator#uninstall-validator
then reinstall:
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

**Comment by Hummagumma** [comment]
Ok, done with the 2 nodes. Let’s see what happens now. Thanx !Enviado desde mi iPhoneEl 1 abr 2023, a las 2:54, Marcus Wentz ***@***.***> escribió:﻿
It is possible there was an issue with the upgrade.
Try to uninstall:
https://docs.shardeum.org/node/run/validator#uninstall-validator
then reinstall:
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

**Comment by Brave-Humens** [comment]
Hello, i have the same problem, I installed the validator on March 31, version 1.1.6. But from that moment on, he is also constantly in the Standby state. how long will he be like this? or is it a mistake?

**Comment by MarcusWentz** [comment]
@Brave-Humens 

```
If your node status is on Standby and you have 10 SHM or more staked, your validator node is setup correctly.

The network will automatically add your validator to be active in the network.

The time to be added as an active validator will vary based on network load and validators in the network.
```
https://docs.shardeum.org/node/run/validator#step-9-stake-shm-to-validator

**Comment by Hummagumma** [comment]
> It is possible there was an issue with the upgrade.
> 
> Try to uninstall: https://docs.shardeum.org/node/run/validator#uninstall-validator then reinstall: https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

Almost 2 weeks passed since I uninstall and reinstall, in addition I run a third node. The three of them are still in standby. I think I'm missing something.

**Comment by MarcusWentz** [comment]
@Hummagumma 

I would wait for Validator Version 1.1.7 coming out later this week or sometime next week hopefully.

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
