### ISSUE TITLE
Explorer Liberty 2.X Account out of SHM after several transactions

### ISSUE THREAD

**Issue by satoshiman** [Shardeum/shardeum-bug-reporting#283]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 

I claimed 100SHM, after several Tx interactive with smart contract (small amount transfer) my account out of money

  https://explorer-liberty20.shardeum.org/account/0xb64e8b1704bc45cea607bf2f96cc6620d715a5cd?page=1&txType=0

![image](https://user-images.githubusercontent.com/37683529/229046231-b536e401-a8cb-4b9c-b835-23d494423bf2.png)

**Comment by MarcusWentz** [comment]
I sent you more Liberty 2.X SHM now. 

Did you interact with any smart contracts or you just did SHM transfers?

**Comment by satoshiman** [comment]
I interactived my smart contract at https://liberty20.numr.io/

My Metamask shows balance same result with explorer.
