### ISSUE TITLE
RPC Transfer SHM Fails Mobile Metamask?

### ISSUE THREAD

**Issue by Nzubaha** [Shardeum/shardeum-bug-reporting#284]
I was trying  to send SHM to one address but it didn't work

🔴 Transaction errors
    
It doesn't allow me to send SHM

. 🔴 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by Nzubaha** [comment]
![Screenshot_20230331-173200](https://user-images.githubusercontent.com/129573658/229265755-d928d3a9-8ec8-4a2c-b011-00d8a4931b3e.png)

**Comment by Nzubaha** [comment]
My wallet address l: 0x78006361150bd7935625ac1b233e55810C0bDBbB

**Comment by MarcusWentz** [comment]
Q1. Did you reset your Metamask activity?

Q2. Did you try this with a wallet on desktop?

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
