### ISSUE TITLE
Solidity Seaport Contracts Deployment Fails

### ISSUE THREAD

**Issue by infamousdegen** [Shardeum/shardeum-bug-reporting#285]
##### What is the issue?

:red_circle:  Unable to Deploy large codebase such as seaport contract :red_circle: 
    
#### What impact does the issue have?

:red_circle: The deployment transaction gives the following error 
                  1) Transaction Nonce!=2
                  2)Maximum Load exceeded 
                  3) No clear indication on the block explorer ui whether the transaction was included or exactly the reason it failed :red_circle:

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
 To reproduce the bug deploy the seaport contract as mentioned in the following doc
 https://github.com/ProjectOpenSea/seaport/blob/b13939729001cb12f715d7b73422aafeca0bcd0d/docs/Deployment.md
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
![Screenshot from 2023-03-28 13-29-44](https://user-images.githubusercontent.com/83490717/229277319-34a37e66-8a77-48f6-9fce-809c492b4a8d.png)

![Screenshot from 2023-03-28 13-56-02](https://user-images.githubusercontent.com/83490717/229277339-f1594b08-af67-4ffe-b677-cb8a3c66a0a5.png)

**Comment by MarcusWentz** [comment]
We are working on the nonce and network load issue.

Did the contract deploy after multiple attempts?

**Comment by infamousdegen** [comment]
> We are working on the nonce and network load issue.
> 
> Did the contract deploy after multiple attempts?

No it didn't. Some of the periphery contracts(such as create 2 factory)  were deployed after multiple attempts but unable to deploy the main seaport contract even after multiple attempts

**Comment by MarcusWentz** [comment]
Q1. Is it this exact contract 
https://github.com/ProjectOpenSea/seaport/blob/main/contracts/Seaport.sol
?
Q2. Did you also try to deploy in Remix IDE?

**Comment by infamousdegen** [comment]
> Q1. Is it this exact contract https://github.com/ProjectOpenSea/seaport/blob/main/contracts/Seaport.sol ? Q2. Did you also try to deploy in Remix IDE?

1) https://github.com/ProjectOpenSea/seaport/blob/b13939729001cb12f715d7b73422aafeca0bcd0d/docs/Deployment.md

I followed the steps mentioned in this documentation 

2) The seaport codebase is with lot of moving parts so wanted to deploy them properly as mentioned in the docs

**Comment by infamousdegen** [comment]
@MarcusWentz any update on the progress

**Comment by MarcusWentz** [comment]
@infamousdegen 

There is a nonce issue the whole network is having.

Once this is fixed, we can try again.

**Comment by infamousdegen** [comment]
@MarcusWentz when can I anticipate an update

**Comment by MarcusWentz** [comment]
We will make an announcement in Discord hopefully next week.

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
