### ISSUE TITLE
[Duplicate] Validator Version 1.1.6 Unstake Error

### ISSUE THREAD

**Issue by Brave-Humens** [Shardeum/shardeum-bug-reporting#286]
Hello, i'm also have a problem with
This wallet already has an active stake on a different node. Remove your stake first if you wish to stake for the current node.
![image](https://user-images.githubusercontent.com/129593734/229285763-4029dac5-f790-4f10-8acf-96613cb01f56.png)

i Have a versions of all in docker:

```
 operator-cli version
runningCliVersion: 0.1.1
minimumCliVersion: 0.1.0
latestCliVersion: 0.1.1
minShardeumVersion: 1.1.6
activeShardeumVersion: 1.1.6
runningGuiVersion: 0.1.1
minimumGuiVersion: 0.1.0
latestGuiVersion: 0.1.1
runnningValidatorVersion: 1.1.6
```
But i can't Remove stake. When I click on "Remove Stake" - It opens the metamask, there I click confirm, it closes, but nothing happens on the node. How fix it?

```
export PRIV_KEY=<private_key>
echo $PRIV_KEY
operator-cli unstake
https://docs.shardeum.org/node/run/validator#cli
```

I also tried to unstake it through the console, but got stuck at the moment of the PRIV_KEY. Can you tell me what the key is? where to find it? Because I can not find in the articles that are given above by reference.

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Please share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/266
