### ISSUE TITLE
[Duplicate] Faucet Not Working Sphinx 1.1.6

### ISSUE THREAD

**Issue by vivli-hub** [Shardeum/shardeum-bug-reporting#288]
Faucet site is not working nor is discord, any idea on when it will be fixed?

Address: 0xF671697c0ce533921F9Ee1adC625a824B7b659e3

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/274
