### ISSUE TITLE
Validator GUI Start and Stop Buttons Not Visible 

### ISSUE THREAD

**Issue by faizanr11** [Shardeum/shardeum-bug-reporting#289]
There is no start and stop button nor any status In dashboard..when running operater status command it shows status as null

**Comment by MarcusWentz** [comment]
Do you have a screenshot?

**Comment by faizanr11** [comment]
Thanks it just worked...i used terminal for stop and start command. Then worked 
![Uploading Screenshot_2023-04-02-12-56-07-06_4d38fce200f96aeac5e860e739312e76.jpg…]()
