### ISSUE TITLE
Validator Version 1.1.6 IP Address 0.0.0.0 Earning SHM Rewards

### ISSUE THREAD

**Issue by fxams** [Shardeum/shardeum-bug-reporting#290]
##### What is the issue?

:red_circle:  IP 0.0.0.0 / status: null but Earning SHM Rewards . :red_circle: 
    
#### What impact does the issue have?

:red_circle: Probably display issue in CLI Status. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Running operator-cli status in the terminal
```
    -show after command: operator-cli status
  externalIp: 0.0.0.0
  externalPort: 9001
  internalIp: 0.0.0.0
  internalPort: 10001
  status: null

Total time validating: 1 Days 13 Hours 25 Minutes
Earnings: 39.555 SHM
```
:red_circle:

**Comment by fxams** [comment]
in addition, ip was setup with export APP_IP="EXTERNAL_IP"

**Comment by MarcusWentz** [comment]
Are you running this locally or on a remote server?

**Comment by fxams** [comment]
Running it on a remote server.

**Comment by fxams** [comment]
Any update on this?

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
