### ISSUE TITLE
Validator How To Uninstall Then Reinstall

### ISSUE THREAD

**Issue by sophisticated20** [Shardeum/shardeum-bug-reporting#291]
I've been trying to complete my node over 2 days but unable to because of a mistake and it keep showing me last login which make me no to be able to proceed.  How can I delete everything and restart

**Comment by MarcusWentz** [comment]
Uninstall validator:
https://docs.shardeum.org/node/run/validator#uninstall-validator
then reinstall validator: 
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

**Comment by sophisticated20** [comment]
![Screenshot_2023-04-03-05-49-24-793_com server auditor ssh client](https://user-images.githubusercontent.com/101137884/229414805-79371ff6-be45-4280-9852-ba91550f89b2.jpg)

Still not working
