### ISSUE TITLE
Validator GUI AWS Error `This site can't be reached`

### ISSUE THREAD

**Issue by Ezebrown** [Shardeum/shardeum-bug-reporting#293]
I was unable to use my AWS VPS to run the node validation.
After I through with the commands on the IDE, I was unable to access my dashboard.
![Screenshot_20230403-080626_Chrome](https://user-images.githubusercontent.com/107863520/229436049-db419f5a-6bff-4b2b-9fd5-cc9cc5dabf81.jpg)

**Comment by MarcusWentz** [comment]
Q1. Did you try this URL format:
```shell
https://<server_ip>:8080/
```
https://docs.shardeum.org/node/run/validator#step-4-open-validator-gui
?
Q2. Are you able to start the validator from the CLI with 
```shell
operator-cli start
```
and then check the validator status with
```shell
operator-cli status
```
https://docs.shardeum.org/node/run/validator#step-5-start-validator
https://docs.shardeum.org/node/run/validator#step-6-monitor-validator
?

**Comment by 0xniek** [comment]
Having the Same Issue. Running on a VPS. Have no Idea what I can do :(
![File_000](https://user-images.githubusercontent.com/120184354/230372962-b67e039d-d78a-443f-a3b0-4d39a714a463.png)
![File_000 (1)](https://user-images.githubusercontent.com/120184354/230373007-c3e442b7-fe9b-4aa7-bbcb-60f82ee518b4.png)
![File_000 (2)](https://user-images.githubusercontent.com/120184354/230373020-b8fa43a1-088f-4a54-b710-27551fcd5916.png)

**Comment by MarcusWentz** [comment]
@0xniek 

Did you try this
https://github.com/Shardeum/shardeum-bug-reporting/issues/293#issuecomment-1494417598
?

**Comment by 0xniek** [comment]
@MarcusWentz 
yeah you can see on my second picture the status

**Comment by 0xniek** [comment]
http://85.214.98.110:8080/

**Comment by 0xniek** [comment]
![beb2e21b-2c0b-4fe7-8487-70c4c08e6ee2](https://user-images.githubusercontent.com/120184354/230423912-7f6e3534-789d-4b6e-8535-53c85849c736.jpg)
![07f1406d-430e-400d-bc4b-70ecffc28db5](https://user-images.githubusercontent.com/120184354/230423936-04ac265d-c108-4da6-afd4-f4c46136bfb6.jpg)

**Comment by MarcusWentz** [comment]
https://85.214.98.110:8080/
is not working either?

Try to uninstall
https://docs.shardeum.org/node/run/validator#uninstall-validator
then reinstall
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator
