### ISSUE TITLE
Swapping Tokens Issue?

### ISSUE THREAD

**Issue by Sufyanpt** [Shardeum/shardeum-bug-reporting#294]
##### What is the issue?

:red_circle:  while I am trying to swap shm to usdt , the transaction failed and token gone . :red_circle: 
    
####loss of fund and token? 

:red_circle: showing transaction success message. :red_circle: 

##### How to reproduce the issue?  Swap shm in shardex

:red_circle: 
Explain in as much detail as possible to help reproduce the bug: swap shm in shardex both usdt and SBT token
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by Sufyanpt** [comment]
Showing this message when we click transaction hash : {"message":"Route GET://tx/0xcbf664743ff5c10f0f331abe0a3050bb96d211de013b8060f1c994872f10bdca not found","error":"Not Found","statusCode":404}

**Comment by MarcusWentz** [comment]
Q1. Which Shardeum network
https://docs.shardeum.org/network/endpoints
?
Q2. Where are you doing swaps (name of the AMM DEX protocol)?

**Comment by Sufyanpt** [comment]
1)  Liberty 2.x

2) SharDex AMM

**Comment by Sufyanpt** [comment]
https://testnet.shardex.org/

**Comment by Sufyanpt** [comment]
Swap through mobile app

**Comment by MarcusWentz** [comment]
Can you swap with 
https://app.swapped.finance/en/swap
?

**Comment by Sufyanpt** [comment]
Getting different kind of error


![Screenshot_2023-04-04-04-45-16-53_3ce871bb60cb313382b75690e63e41d0.jpg](https://user-images.githubusercontent.com/121370124/229647624-1f3b03e6-51fb-415b-bf80-ff19db811b34.jpg)

![Screenshot_2023-04-04-04-51-11-70_3ce871bb60cb313382b75690e63e41d0.jpg](https://user-images.githubusercontent.com/121370124/229647628-c3463d62-ad28-4b54-9d13-576eeb976926.jpg)

![Screenshot_2023-04-04-04-50-35-06_3ce871bb60cb313382b75690e63e41d0.jpg](https://user-images.githubusercontent.com/121370124/229647621-c08821b0-9763-4eb8-89f8-79c45cc3384d.jpg)

![Screenshot_2023-04-04-04-50-54-59_3ce871bb60cb313382b75690e63e41d0.jpg](https://user-images.githubusercontent.com/121370124/229647623-ae6a4817-d446-42d3-bc4f-9096eac8bc6f.jpg)

![Screenshot_2023-04-04-04-51-04-47_3ce871bb60cb313382b75690e63e41d0.jpg](https://user-images.githubusercontent.com/121370124/229647622-db662ba1-c171-48bc-8abe-50e36705a1b5.jpg)

![Screenshot_2023-04-04-04-50-48-53_3ce871bb60cb313382b75690e63e41d0.jpg](https://user-images.githubusercontent.com/121370124/229647625-3d85dd13-15ba-4a0b-8df3-0ccfa905f251.jpg)

![Screenshot_2023-04-04-04-51-33-92_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/121370124/229647627-076a8128-ba6a-46e4-a4b7-d730cd3108fb.jpg)

![Screenshot_2023-04-04-04-50-29-37_3ce871bb60cb313382b75690e63e41d0.jpg](https://user-images.githubusercontent.com/121370124/229647626-a285d00b-84ca-4578-ab71-28bb12d62d94.jpg)

**Comment by Sufyanpt** [comment]
https://explorer-liberty20.shardeum.org/account/0x00007fcf2649756581146e40836e25e6109f9338

**Comment by Sufyanpt** [comment]
![Screenshot_2023-04-04-04-58-41-20_3ce871bb60cb313382b75690e63e41d0.jpg](https://user-images.githubusercontent.com/121370124/229648337-0c1475e7-d460-439f-82e7-74e4021c4153.jpg)


{"message":"Route GET://tx/0xcbf664743ff5c10f0f331abe0a3050bb96d211de013b8060f1c994872f10bdca not found","error":"Not Found","statusCode":404}

This transaction being stuck somewhere and not reflecting in shardeum explorer . But reflected in balance

**Comment by Slashishere** [comment]
Hello 

I have these messages for any swap transaction in any DEX 
https://app.swapped.finance/swap

and 

https://testnet.shardex.org/

Network : 2.1
Using desktop 

![Screen Shot 2023-04-11 at 12 20 32 AM](https://user-images.githubusercontent.com/130408792/231005539-7c9fa0b3-b419-4ebb-a9ec-c5c9d6d6d699.png)
![Screen Shot 2023-04-11 at 12 50 16 AM](https://user-images.githubusercontent.com/130408792/231005752-6a2e15fe-2057-4d5b-bc93-40369d76e51c.png)

**Comment by swarna1101** [comment]
Can you check on Swapped Finance on Sphinx Dappnet, this issue is resolved in the latest version of the network.
