### ISSUE TITLE
Validator GUI Status `-`

### ISSUE THREAD

**Issue by 73lv** [Shardeum/shardeum-bug-reporting#296]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: i can’t start or stop my node
    
#### What impact does the issue have?
Not validating 
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: nothing is failing

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
![60DBB5C3-A3D8-493B-93B0-25EFFCE66D7C](https://user-images.githubusercontent.com/129773909/229559095-8e52c822-8c86-4c68-b6b9-3c8e34102ee2.jpeg)

**Comment by MarcusWentz** [comment]
What do you see in the Validator CLI when you run
```shell
operator-cli status
```
https://docs.shardeum.org/node/run/validator#step-6-monitor-validator
?

**Comment by camzilla1050** [comment]
```
$ operator-cli status
state: stopped
performance:
  memPercentage: 81.63178545791605
  diskPercentage: 8.419576999892792
  cpuPercentage: 0.5000000000000004
stakeRequirement: '10.0'
lockedStake: ''
```

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/ec1743df-5a2c-4c2f-bee1-569c8b1a11c3)
