### ISSUE TITLE
[Duplicate] Faucet Not Working Sphinx 1.1.6

### ISSUE THREAD

**Issue by scarlet1000** [Shardeum/shardeum-bug-reporting#297]
I tweeted like it says on https://faucet-sphinx.shardeum.org/.

My tweet: https://twitter.com/Anna1099/status/1642973696083066886

I never received 15 SHM like it said 

In Liberty 2.X, I received 100 SHM right away

**Comment by MarcusWentz** [comment]
Sent you tokens
https://explorer-sphinx.shardeum.org/account/0xc4f694f8da796b7b36d9f5ceeacae5722c2d1d6e

Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/274

**Comment by scarlet1000** [comment]
Thanks
