### ISSUE TITLE
[Duplicate] Validator Staking GUI SHM Rewards Decreasing

### ISSUE THREAD

**Issue by jonathanrolfe** [Shardeum/shardeum-bug-reporting#298]
##### What is the issue?
rewards from past active session disappeared
:red_circle:  Describe the error in simple terms. :red_circle: 
    i noticed my second active session had started but the 'running' rewards total in shm was less than after the close of the first session - this second session has finished and confirmed i have less rewards than after the first. perhaps related is that the total validating time is now set to 00.00
#### What impact does the issue have?
sows distrust and doubt of the rewards system
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 
node now back to standby and looks fully functioning in that mode
##### How to reproduce the issue? 
i'm not sure on this - i have to wait and see if it repeats but i know it has been reported by others on discord
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen the error is seen in the shardeum rewards total and total active time showing 00.00
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run glad to share code if i am advised on which  logs to download/send
```
:red_circle: 

##### What other resources can you share regarding this issue?
![SHM BUG REPORT 1](https://user-images.githubusercontent.com/96307912/229707241-f05c525d-21be-4c65-9d0a-bf82aaa75376.jpg)

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/45

**Comment by jonathanrolfe** [comment]
do i need to do anything else - not sure i understand the last comment
