### ISSUE TITLE
[Duplicate] RPC Transaction Error `Transaction nonce != actualNonce expectedNonce`

### ISSUE THREAD

**Issue by berejznoy** [Shardeum/shardeum-bug-reporting#299]
##### What is the issue?

:red_circle:  Can't send tokens from wallet :red_circle: 
    
#### What impact does the issue have?

:red_circle: The wallet is a get-shm.online faucet. There have been a lot of bug reports lately. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
I send tokens through metamask and through the faucet, I get an error in response
```
   ui-4.js:1 [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Failed to process transaction: {\"raw\":\"0xf8728235518505d21dba008401c9c380942be9f78f15f988e9208158367b2a8174e509ca5d88a688906bd8b0000080823f48a0d96d11b7e7e350a6fddb3b90ae508391e7ccea6a3f29982932e54e066cac1ce9a04dd49078abc53435b95ec73e9d7d47e86487afdb98aff1dbac423a7b792a1670\",\"timestamp\":1680601508649} TypeError: Cannot read properties of undefined (reading 'length')","data":{"originalError":{"status":500}}}}}'

and 

ui-4.js:1 [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Transaction nonce != 13687  txNonce:13653 accountNonce:13653 queueCount:34","data":{"originalError":{"status":400}}}}}'


```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: I can get logs from get-shm.online :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/249

**Comment by berejznoy** [comment]
I wrote 2 erros sorry 
What about it ?
 ui-4.js:1 [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Failed to process transaction: {\"raw\":\"0xf8728235518505d21dba008401c9c380942be9f78f15f988e9208158367b2a8174e509ca5d88a688906bd8b0000080823f48a0d96d11b7e7e350a6fddb3b90ae508391e7ccea6a3f29982932e54e066cac1ce9a04dd49078abc53435b95ec73e9d7d47e86487afdb98aff1dbac423a7b792a1670\",\"timestamp\":1680601508649} TypeError: Cannot read properties of undefined (reading 'length')","data":{"originalError":{"status":500}}}}}'
