### ISSUE TITLE
Metamask: Estimate fee wrong

### ISSUE THREAD

**Issue by bui-duc-huy** [Shardeum/shardeum-bug-reporting#3]
When I deploy new contract on Shareum, Metamask show the transaction took `0.245 SHM` for fee, but on the scan this only took `0.00000000003 SHM`

**Comment by MarcusWentz** [comment]
I tested this now and it looks like the 0.245 SHM value 
might be a constant and is much bigger than the transaction fee I actually paid. 

I will look into how this fee is being recorded from Shardeum into Metamask.

**Comment by MarcusWentz** [comment]
Liberty 2.1 in Metamask shows 0.2415 SHM for the gas fee. 

The gas fee was 1.0000 SHM in reality:
https://explorer-liberty20.shardeum.org/transaction/0x569cf1062cef863bd1c46008399890f4529d0dba28fc8ef660a712fe81210187

We will have updates at Betanet and Mainnet regarding the gas fee display in Metamask.

**Comment by bui-duc-huy** [comment]
Thanks for responding! I think this issue should be close
