### ISSUE TITLE
Validator Version 1.1.6 Nominee Public Key For Staking SHM Not Appearing 

### ISSUE THREAD

**Issue by gimbil** [Shardeum/shardeum-bug-reporting#300]
hi dear my Nominee Public Key in validator is empty its normal ?
![photo_2023-04-04_12-58-56](https://user-images.githubusercontent.com/124584954/229796399-09dda460-4a6b-4fd8-b89e-4688d87dfde0.jpg)

**Comment by MarcusWentz** [comment]
Does the nominee public key appear after refreshing the page?

**Comment by gimbil** [comment]
> Does the nominee public key appear after refreshing the page?

No

**Comment by MarcusWentz** [comment]
What happens when you uninstall
https://docs.shardeum.org/node/run/validator#uninstall-validator
then reinstall
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator
?

**Comment by gimbil** [comment]
i just update my node after update it not show key

**Comment by MarcusWentz** [comment]
Q1. What OS are you using?

Q2. Did you notice this issue on different web browsers? 

Q3. What is your wallet address?

**Comment by mistozy** [comment]
![2023-04-06_12-51-45](https://user-images.githubusercontent.com/130079979/230432196-ca05c89d-fa91-4607-a0eb-ed09af3c4700.png)

I've got the same problem! reinstall doens't help

**Comment by gimbil** [comment]
i reinstall 2 time and not solved i before run node 2 month after this update i see this bug. any help ? WTF

**Comment by MarcusWentz** [comment]
I will share this with the core team .

**Comment by MarcusWentz** [comment]
@gimbil 

Q1. What do you see with 
```shell
curl localhost:9001/nodeinfo
```
https://docs.shardeum.org/node/run/validator#version
?
Q2. Do you see any errors in the GUI logs?

**Comment by mistozy** [comment]
> @MarcusWentz hello! Why you didn't answer to me?:( Can you please help with this?

**Comment by MarcusWentz** [comment]
@mistozy 

Did you try this too 

https://github.com/Shardeum/shardeum-bug-reporting/issues/300#issuecomment-1501161678

?

**Comment by gimbil** [comment]
@MarcusWentz 
![image](https://user-images.githubusercontent.com/124584954/230868221-ca4f3bee-d7f0-4ab4-8022-3b49c655cee8.png)

**Comment by mistozy** [comment]
> @mistozy
> 
> Did you try this too
> 
> [#300 (comment)](https://github.com/Shardeum/shardeum-bug-reporting/issues/300#issuecomment-1501161678)
> 
> ?

Yes, i tried it! Mistake

**Comment by mistozy** [comment]
![2023-04-10_12-24-51](https://user-images.githubusercontent.com/130079979/230932463-22b44320-f880-427d-b12d-37ca3afac329.png)

**Comment by MarcusWentz** [comment]
@mistozy 

Is this on your local computer or a server?

**Comment by mistozy** [comment]
@MarcusWentz A server

**Comment by MarcusWentz** [comment]
@mistozy 

Can you try running the validator locally as a test?

**Comment by gimbil** [comment]
@MarcusWentz bro any way to insert Nominee Public key  manually?

**Comment by mistozy** [comment]
> @MarcusWentz bro any way to insert Nominee Public key manually?

where can i get it?

**Comment by MarcusWentz** [comment]
@gimbil @mistozy 

I would wait for Validator Version 1.1.7 coming out later this week or sometime next week hopefully.
