### ISSUE TITLE
[Duplicate] Validator Version 1.1.6 status `Null` Earning SHM rewards stopped

### ISSUE THREAD

**Issue by Sylwester79** [Shardeum/shardeum-bug-reporting#302]
CLI/GUI Running Version: 0.1.1 / 0.1.1
CLI/GUI Latest Version: 0.1.1 / 0.1.1
Validator Running Version: 1.1.6
Active Network Version: 1.1.6
Validator Minimum Version: 1.1.6

problem: no status display , total TimeValidating is still growing, but current rewards hasn't changed
logs attached

after executing the command "operator-cli status"  I receive "status: null"
0x94e8cC423572Ac78A39f5f759B9eaCCbfaF83C03
[logs.zip](https://github.com/Shardeum/shardeum-bug-reporting/files/11158123/logs.zip)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/292

**Comment by fxams** [comment]
![image](https://user-images.githubusercontent.com/38005580/231193660-153319c4-669e-4b69-ba89-c93481f9e399.png)
