### ISSUE TITLE
[Duplicate] Validator Active Shows ```Total time validating: 00:00:00```

### ISSUE THREAD

**Issue by Sufyanpt** [Shardeum/shardeum-bug-reporting#303]
##### What is the issue?

:red_circle:  My node was active and validated more than 2 hour. After that status moved to standby and showing zero validating time. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Total validating time missing in dashboard. Showing wrong information in dashboard.

. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Start a node ,and activate it once. Then check the status, If it's standby then check the validated time and validating reward. You will get validating reward and  zero validating time in dashboard. This will make lot of confusion for a validator. Please attached file and screenshot shot time :
```
    
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle:  ![Screenshot_2023-04-05-09-02-26-64_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/121370124/230016887-f5e38049-51e6-4703-81ae-9c6f2d91da54.jpg)

![Screenshot_2023-04-05-04-32-02-15_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/121370124/230016886-decbf3d5-e94f-4485-a893-359cbb640d25.jpg)

  . :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/215
