### ISSUE TITLE
[Duplicate] Validator Staking GUI SHM Rewards Decreasing

### ISSUE THREAD

**Issue by noel4za** [Shardeum/shardeum-bug-reporting#304]
##### What is the issue?
My reward reset to 0 when my node become active again from standby

So this morning when my node standby earning is 4.333 SHM and when my node become active again reset 0.

after active again reset to 0 and now earning 1.8
it's bug ? my external ip 158.220.96.100
![image](https://user-images.githubusercontent.com/9096947/230084078-563af19a-db65-441a-becb-7c0cf92c8577.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/45
