### ISSUE TITLE
[Duplicate] Validator Active Shows ```Total time validating: 00:00:00```

### ISSUE THREAD

**Issue by pavanpalakurthi** [Shardeum/shardeum-bug-reporting#305]
<img width="862" alt="Screenshot 2023-04-05 200809" src="https://user-images.githubusercontent.com/66116488/230116370-6b644c00-8efa-4567-8584-48060830c9d5.png">

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/215
