### ISSUE TITLE
[Duplicate] Faucet Not Working Sphinx 1.1.6

### ISSUE THREAD

**Issue by LoniV** [Shardeum/shardeum-bug-reporting#307]
I sent a tweet to the website faucet for test tokens to run a validator node some hours ago and they are yet to arrive.
I have attached the pictures of the successful interaction but no tokens.

![Screenshot (569)](https://user-images.githubusercontent.com/130070173/230420539-1a287e64-8d30-4c93-80dd-609c78dd0a97.png)

![Screenshot (570)](https://user-images.githubusercontent.com/130070173/230420596-8a9c1e18-b59d-4993-b1b2-b12ba08c0b46.png)

![Screenshot (571)](https://user-images.githubusercontent.com/130070173/230420663-ed32eb1b-2024-4004-b259-01d86885516c.png)

Please can you send me the test tokens: 0x224407A7A03192690DD9cba4190A55b81cc6ddAe
 I would be most grateful. Thank you

Also is there a reason why it keeps telling me invalid wallet address in the Discord? Thank you

**Comment by MarcusWentz** [comment]
I sent you tokens now
https://explorer-sphinx.shardeum.org/account/0x224407a7a03192690dd9cba4190a55b81cc6ddae

Duplicate issue.

Share this info here:
https://github.com/Shardeum/shardeum-bug-reporting/issues/274
