### ISSUE TITLE
[Duplicate] Validator earning SHM rewards in standby mode

### ISSUE THREAD

**Issue by N4n0B1t** [Shardeum/shardeum-bug-reporting#308]
##### What is

https://user-images.githubusercontent.com/129899244/230479181-380050ff-5a58-4ff8-bfd2-7a86df6dc240.mp4

 the issue?
Node on Standby by still getting rewards
:red_circle:  Describe the error in simple terms. :red_circle: 
    Node on Standby by still getting rewards
#### What impact does the issue have?
I should nod getting earning rewards if node not active
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 
Amount Earnings keeps increasing
##### How to reproduce the issue? 
I don't know
:red_circle: 
Explain in as much detail as possible to help reproduce the bug
Before node went to Null status. I stopped it and start it again. Don't remember since then was it active or just stayed on standby status.
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
I can provide additional logs but not sure which one
```i
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by lostethd** [comment]
The node is in the waiting state on the dashboard and the reward is constantly increasing, but it is active in the explorer, the reward start time is certain, the reward end time is not certain, the reward amount does not increase

you can check: 0x753116e8823fa591397a4eb9fba4218299933387   
https://explorer-sphinx.shardeum.org/account/77e21160db4e8a3d159392cad09b8447ae44d0c43d271d1d21c86dd79a83c901

node dashboard: https://35.192.147.213:8080/maintenance

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/287
