### ISSUE TITLE
Validator `operator-cli set internal_ip` not the same IP address as local computer

### ISSUE THREAD

**Issue by hiromasa0629** [Shardeum/shardeum-bug-reporting#309]
##### What is the issue?

When I run `operator-cli set internal_ip <local ip>`, it does nothing.
To verify, `curl localhost:9000/nodeinfo` shows external_ip and internal_ip are the same.
    
#### What impact does the issue have?

The validator might not be able to be included into the network.

##### How to reproduce the issue? 

```
 1. operator-cli stop
 2. export APP_IP=<external ip>
 3. operator-cli start
 4. curl localhost:9000/nodeinfo  // externalIp and internalIp are same
 5. operator-cli set internal_ip <local ip> // tried to set internal_ip to the local machine ip
 6. curl localhost:9000/nodeinfo  // externalIp and internalIp are same
```

##### What other resources can you share regarding this issue?

CLI/GUI Running Version: 0.1.1 / 0.1.1
CLI/GUI Latest Version: 0.1.1 / 0.1.1
Validator Running Version: 1.1.6
Active Network Version: 1.1.6
Validator Minimum Version: 1.1.6

**Comment by hiromasa0629** [comment]
##### What i have tried

Restart validator after change

**Comment by MarcusWentz** [comment]
Is 
```shell
export APP_IP=<external_ip>
```
updating
https://docs.shardeum.org/node/run/validator#step-9-stake-shm-to-validator
?

**Comment by hiromasa0629** [comment]
> Is
> 
> ```shell
> export APP_IP=<external_ip>
> ```
> 
> updating https://docs.shardeum.org/node/run/validator#step-9-stake-shm-to-validator ?

Yes. APP_IP is updating. Would need to restart after exporting. Though, i would like to know that for self hosted server, i assume the internal ip has to be the local machine ip, is it not ?

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
