### ISSUE TITLE
Betanet 1.X Twitter Faucet Shows 100 SHM and 15 SHM per request

### ISSUE THREAD

**Issue by beerah** [Shardeum/shardeum-bug-reporting#31]
when i claimed Shardeum Sphinx Network Faucet, a popup msg appeared to be of 100 shm sent, but i actually received 15 shm.

**Comment by MarcusWentz** [comment]
Betanet 1.X gives 15 SHM for each faucet request.

For reference gas prices are lower on Betanet 1.X compared to Liberty 2.X.

https://github.com/Shardeum/shardeum-docs/pull/165
