### ISSUE TITLE
Validator Version 1.1.6 Stake Transaction Pending

### ISSUE THREAD

**Issue by AAZZ123** [Shardeum/shardeum-bug-reporting#310]
Hi, i've tried several time to stake my token. and my tx always still, i don't know why.
i've reset metamask.. change the browser but it's still same things.
![LOADINGSHARD](https://user-images.githubusercontent.com/35351379/230695802-720d234a-e1b0-4975-af9d-513546dca30e.png)
![staketxfail](https://user-images.githubusercontent.com/35351379/230695821-d3d6f521-6a14-48fd-aafb-9ced86e31e05.png)
![pending](https://user-images.githubusercontent.com/35351379/230695841-d694329e-c215-4d06-a02b-bb82628abfb4.png)

**Comment by MarcusWentz** [comment]
Did you try another wallet to stake as well?

**Comment by AAZZ123** [comment]
I can't send, haha. still pending too

**Comment by MarcusWentz** [comment]
We are working on Validator Version 1.1.7.

This should be out hopefully soon (possibly next week).

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
