### ISSUE TITLE
[Duplicate] Validator GUI Status Blank

### ISSUE THREAD

**Issue by jonathanrolfe** [Shardeum/shardeum-bug-reporting#311]
##### i have no status on my node - also i now have over 7 hours active but somehow less shm than before my last session. the shm from other active sessions is also missing - please inform me if this can be rectified or if i should report in bugs if it happens again as it seems regular
![SHM BUG REPORT 1](https://user-images.githubusercontent.com/96307912/230717314-1662d6a4-c45a-4524-9590-94ffb6a53834.jpg)
![shardeum update 2](https://user-images.githubusercontent.com/96307912/230717326-62fcc051-d143-4985-9c73-541a140a7793.jpg)

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by jonathanrolfe** [comment]
i made an error in including the first photo but it does show 'zero' active when there had been activity

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/301
