### ISSUE TITLE
Validator Staking Issue?

### ISSUE THREAD

**Issue by Luckkarp** [Shardeum/shardeum-bug-reporting#312]
<img width="356" alt="Знімок екрана 2023-04-09 о 10 28 55" src="https://user-images.githubusercontent.com/112563824/230762439-4fa4e258-2bd8-48a5-98ed-73e0c4a4ba06.png">
why i cant stake

**Comment by MarcusWentz** [comment]
Can you transfer SHM between wallets as a test transaction?

**Comment by artfulalchemists** [comment]
Any updates on this?

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
