### ISSUE TITLE
Validator CLI operator-cli - command not found

### ISSUE THREAD

**Issue by camzilla1050** [Shardeum/shardeum-bug-reporting#313]
##### Validator GUI Issue : $ operator-cli - command not found !

Hi,
I try to install open validator cli on ubuntu 22.4.1. Configuring default except port 9011 instead 9001.
In step 4 from docs : operator-cli command not found

```
node@36aa34a48ad3:~/app$ operator-cli gui start
bash: operator-cli: command not found
```

**Comment by camzilla1050** [comment]
I dont know why entrypoint.sh bugs..
Solved executing sep by step command git & npm to install operator-cli and certificates

**Comment by cresdent1** [comment]
> I dont know why entrypoint.sh bugs.. Solved executing sep by step command git & npm to install operator-cli and certificates

how? i try but I cant
