### ISSUE TITLE
Explorer Error `Unhandled  Runtime Error: TypeError: Cannot read properties of undefined (reading 'map')`

### ISSUE THREAD

**Issue by Sufyanpt** [Shardeum/shardeum-bug-reporting#314]
![IMG_20230409_212658_887.jpg](https://user-images.githubusercontent.com/121370124/230783220-6ef4708c-c7f6-46d0-994f-b23d4c7379b5.jpg)

Sometimes getting this error in spinix Explorer .

**Comment by MarcusWentz** [comment]
What steps did you take to see this issue?

**Comment by Sufyanpt** [comment]
Just clicked my newly created token in token list

**Comment by MarcusWentz** [comment]
Can you share the URL in text form so I can try it too?

**Comment by Sufyanpt** [comment]
https://explorer-sphinx.shardeum.org/account/0x00007fcf2649756581146e40836e25e6109f9338

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
