### ISSUE TITLE
[Duplicate] RPC `eth_gasPrice` value does not multiply with gasLimit from `eth_estimateGas` to be estimated Transaction Fee in Metamask 

### ISSUE THREAD

**Issue by daostarter** [Shardeum/shardeum-bug-reporting#316]
##### What is the issue?

As per the question, my metamask shows that GAS exceeds 1 SHM, but the actual consumption is less than 0.01
    
##### How to reproduce the issue? 

Create any contract and interact with it,I use Remix IDE to interact with contracts through metamask

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/276
