### ISSUE TITLE
[Duplicate] Validator earning SHM rewards in standby mode

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#317]
##### What is the issue?

even if my Validator is in standby, my rewards are still increasing 
    
#### What impact does the issue have?

increased balance

**Comment by AndreiW3b3** [comment]
https://www.loom.com/share/97f994e2d4fb4f51a0474e59ac19c5af

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/287
