### ISSUE TITLE
Solidity Liberty 2.X Add Liquidity Fails

### ISSUE THREAD

**Issue by Margtik** [Shardeum/shardeum-bug-reporting#319]
Can't add liquidity here https://testnet.swapped.finance/ru/add/ETH/0x325ecEB0c1f1c9F9B136361D3bfCD96466C6963C
Transaction details: https://explorer-liberty20.shardeum.org/transaction/0x2c0f8bc9b791ac6168d3da5aaa68f49f396433cd120da60a82d9e89e60123e7f

**Comment by swarna1101** [comment]
Pls check with the latest network release (currently try with Sphinx Dappnet).
For more detail - docs.shardeum.org
