### ISSUE TITLE
Validator Staked Wallet Has SHM Balance Decrease In 0.01 SHM Increments Over Time

### ISSUE THREAD

**Issue by hansfzlorenzana** [Shardeum/shardeum-bug-reporting#32]
##### What is the issue?

    I noticed that my SHM balance keeps on decreasing over time after running a validator node. I haven't rotated into 'active' status yet and is still on 'standby'. There are only two transactions on my address: Transfer method (received 15 SHM from faucet) and Staking method.
    
#### What impact does the issue have?

    I am not exactly sure if it affects every user on Sphinx network. 

##### How to reproduce the issue? 

    Again, I'm not sure how but here's what I've done.
    - Run a node
    - Request from faucet
    - Stake
    - 'Standby' status, never been on 'active'
    
    I noticed it's decreasing after staking.
    
Address: https://explorer-sphinx.shardeum.org/address/0x7c5fbb1af2adad3b7665f2001bd429330a5cd643
|        Event        |  Amount  |    Fee    |       Balance        |
|---------------------|----------|-----------|----------------------|
| Before running node |          |           | 0 SHM                |
| Faucet              | + 15 SHM |           | 15 SHM               |
| Staking             | - 14 SHM | -0.01 SHM | 0.98 SHM             |
| ,                   | ,        | ,         | 0.86 SHM - yesterday |
| ,                   | ,        | ,         | 0.46 SHM - today     |
| ,                   | ,        | ,         | 0.45 SHM - today     |
| ,                   | ,        | ,         | 0.43 SHM - current   |

Current balance is 0.43 SHM. Please validate if it decreases again.

##### What other resources can you share regarding this issue?

    
<img width="1329" alt="Screen Shot 2023-02-04 at 8 37 51 AM" src="https://user-images.githubusercontent.com/47592497/216738751-6200c57c-680e-4031-ad63-df0fccd6d60f.png">
<img width="1329" alt="Screen Shot 2023-02-04 at 8 47 33 AM" src="https://user-images.githubusercontent.com/47592497/216739098-cbd75266-e042-408c-96d5-6e2c6f714b71.png">

**Comment by bogachevanton** [comment]
same for me
like 1 SHM lost for 3 days

**Comment by MarcusWentz** [comment]
@bogachevanton 

Can you share your wallet address on the Betanet 1.X explorer? We can take a deeper look at your address.

**Comment by bogachevanton** [comment]
> @bogachevanton
> 
> Can you share your wallet address on the Betanet 1.X explorer? We can take a deeper look at your address.

sure, here is my adress
https://explorer-sphinx.shardeum.org/address/0xddb47057e44621f30495af8134babe687a8b6c58

**Comment by ksbaskar** [comment]
<img width="269" alt="M1" src="https://user-images.githubusercontent.com/6725456/217178192-e2dfd1af-ba4f-4636-b703-ffe9638c51f3.png">
<img width="273" alt="M2" src="https://user-images.githubusercontent.com/6725456/217178204-0bf6d6f9-c524-4237-a36b-b8e911693d8f.png">
Yes facing same issue here.

**Comment by AndreiW3b3** [comment]
i noticed the exact same thing

**Comment by MarcusWentz** [comment]
Did you notice this issue on Betanet 1.1 as well?

**Comment by MarcusWentz** [comment]
This issue still seems present in Betanet 1.1 as reported here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/56

**Comment by AndreiW3b3** [comment]
I still noticed the same bug. Ballance decreased from 4.98 to 4.90 within 1 h

**Comment by MarcusWentz** [comment]
@AndreiW3b3 

What is your wallet address and nominee public key so we can take a look?

**Comment by bogachevanton** [comment]
> Did you notice this issue on Betanet 1.1 as well? 

Yes, bug stays. Balance decreased by 0.01 in sometime when node is up.

Wallet: 0xddb47057E44621f30495Af8134bABe687A8B6C58

or explorer link

https://explorer-sphinx.shardeum.org/account/0xddb47057e44621f30495af8134babe687a8b6c58

**Comment by AndreiW3b3** [comment]
@MarcusWentz 0x7eb1DD4eC345dF607885597EC9f8aEFb4EeEEd4a

**Comment by MarcusWentz** [comment]
There is a potential bug fix coming soon for this it sounds like. 

Once the potential bug fix is added, we can check if the issue still exists.

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by AndreiW3b3** [comment]
at the moment it is not droping anymore. However sometimes it shows 0 as my balance and sometimes it goes back to intial ballance

**Comment by AndreiW3b3** [comment]
https://www.loom.com/share/b966b289ef034d04872ab37c543ef112

**Comment by MarcusWentz** [comment]
@AndreiW3b3 

What is your wallet address?

**Comment by AndreiW3b3** [comment]
@MarcusWentz 0x7eb1DD4eC345dF607885597EC9f8aEFb4EeEEd4a

**Comment by MarcusWentz** [comment]
@AndreiW3b3 

I see your wallet has sufficient funds on the Betanet 1.1 Explorer:

https://explorer-sphinx.shardeum.org/account/0x7eb1dd4ec345df607885597ec9f8aefb4eeeed4a

There are some RPC issues related to validators causing wallets to randomly detect 0 SHM. We are investigating this issue.

Can you transfer SHM between wallets as a test or does that transaction fail?

**Comment by AndreiW3b3** [comment]
@MarcusWentz first 2 attempts it did not work. did even show as a failed transactio

this is the one that it wokerd https://www.loom.com/share/508a3d25d0614bb9983811e9c3b75eab

**Comment by AndreiW3b3** [comment]
https://www.loom.com/share/684bf6477aa24e7e8ea9af053634b1ad

**Comment by MarcusWentz** [comment]
The RPC issue seems to be causing transfers to fail as well. 

Once transfers are stable, other transactions should be stable as well.

**Comment by MarcusWentz** [comment]
Closing this issue since it seems resolved.

@AndreiW3b3 

Let's discuss the transaction issues in this bug report:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92
