### ISSUE TITLE
Validator Errors in main.log while validating?

### ISSUE THREAD

**Issue by undecesjours** [Shardeum/shardeum-bug-reporting#320]
Hi, my VPS node is validating now, it seems to be ok in the GUI:

![image](https://user-images.githubusercontent.com/127980910/231121056-bde70879-2bbd-402b-a25b-7e2fa7e9cafb.png)

But when i havea look in the main log, i have the following issues :

![image](https://user-images.githubusercontent.com/127980910/231121472-9f4076f1-f5cb-4feb-9f7d-5338fc0b02db.png)

Is it normal ?

Thanks

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
