### ISSUE TITLE
RPC Transaction Fails `Internal Error`

### ISSUE THREAD

**Issue by Slashishere** [Shardeum/shardeum-bug-reporting#321]
##### What is the issue?

I got failed transaction in each swap or buy with test net . 
    
#### What impact does the issue have?

:red_circle: This is the message I received for each transaction 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen in all dex ( https://app.swapped.finance/swap.  and https://testnet.shardex.org/ )
    -how the error was potentially caused if possible (During any swap or transaction )
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
![Screen Shot 2023-04-11 at 12 46 25 PM](https://user-images.githubusercontent.com/130408792/231122671-5b74610a-64f2-4925-aa39-a9b86ca6fc53.png)
![Screen Shot 2023-04-11 at 12 48 32 PM](https://user-images.githubusercontent.com/130408792/231123482-4e8fdb22-36b0-492a-b31d-85c34e9cd9f7.png)

**Comment by Slashishere** [comment]
hi 
still have the problem . any suggestion ?

**Comment by swarna1101** [comment]
Can you try with the newly launched networks?
This is resolved their. 
For now, pls try Sphinx Dappnet
