### ISSUE TITLE
Validator Install Error Building base image error

### ISSUE THREAD

**Issue by pitu2k** [Shardeum/shardeum-bug-reporting#322]
When I try to install node it says network connection timed out and FROM https://t.co/D8FBqjbUTN
Get "https://t.co/RfRkdpKnr7": context deadline exceeded
Please help

**Comment by pitu2k** [comment]
![IMG_2023-04-11-19-02-31-837](https://user-images.githubusercontent.com/86554112/231179049-16ab1003-a74b-4be5-8e79-927f922087a2.jpg)

**Comment by pitu2k** [comment]
I used a vps server hosted on germany

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
