### ISSUE TITLE
RPC ethers.js version 5.7.2 getDefaultProvider error `unsupported getDefaultProvider network`

### ISSUE THREAD

**Issue by Anish0203** [Shardeum/shardeum-bug-reporting#323]
const provider = new ethers.getDefaultProvider(8082)

It is throwing the error 'unsupported getDefaultProvider network'.

**Comment by MarcusWentz** [comment]
Please share a full script with this working on other chains as well.

**Comment by MarcusWentz** [comment]
Q1. Does this work with ethers.js version 5.4.0?

Q2. Do you have a working full script example on Sepolia?

Q3. Do you have a full script example on Betanet 1.X?

**Comment by Anish0203** [comment]
Q2. 
  const provider = new ethers.getDefaultProvider(11155111);
  console.log(provider);
![image](https://user-images.githubusercontent.com/45678877/231174991-20322e53-77e8-4ba8-966f-e6e473e0e13a.png)

  const provider = new ethers.getDefaultProvider(8082);
  console.log(provider);
![image](https://user-images.githubusercontent.com/45678877/231175615-e1e87422-52d2-40b1-bd1b-e0717681c15b.png)

**Comment by Anish0203** [comment]
Q1. It is throwing the same error for ethers.js version 5.4.0 as well

**Comment by MarcusWentz** [comment]
Please use this for HTTP connections 

```js
const provider = new ethers.providers.JsonRpcProvider(rpcURL)
```

and this Websocket connections

```js
const provider = new ethers.providers.WebSocketProvider(rpcURL)
``` 

for now.

**Comment by swarna1101** [comment]
Pls reset the network and use this for HTTP connections:- 

```
const provider = new ethers.providers.JsonRpcProvider(rpcURL)
```
