### ISSUE TITLE
Validator GUI Status Standby While Explorer Status Active

### ISSUE THREAD

**Issue by baburao1810** [Shardeum/shardeum-bug-reporting#324]
##### What is the issue?
Dashboard node status is standby and on blockchain node status is active.
Earnings are updated on dashboard on standby mode as well. This happens in second active cycle for node. 

:red_circle:  Describe the error in simple terms. :red_circle: 

    
#### What impact does the issue have?
Rewards are not updated and calculated correctly on blockchain for node. 
Node is not getting picked up for validating in next cycle as well.
![New Node](https://user-images.githubusercontent.com/130603695/231571258-94310f2b-9182-4388-a014-0d172ae00baa.png)

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 
Create a new node. Wait for it to be active. After 2nd time it is active it does not update status on blockchain from Active to Standby.

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?
Original Node - 72d63d3fa5236bab16a5c98c17d37270fc5abb4ddf6b66b9d4ec8e1bc36ff189
New Node - bfe134b72d2580a946164ab9955f73f75819cf19015b5e15a7fdc9061bc486cf

:red_circle: Photos and links related to the error. :red_circle:

**Comment by atifnimran** [comment]
Please help status me

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
