### ISSUE TITLE
Validator status standby keeps asking to need stake when staked already 

### ISSUE THREAD

**Issue by ivan-strelka** [Shardeum/shardeum-bug-reporting#325]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
  
Status changes periodically.  Sometimes standby sometimes need steak . Status changes every 5-10 minutes. 
CLI/GUI Running Version: 0.1.2 / 0.1.2
CLI/GUI Latest Version: 0.1.2 / 0.1.2
Validator Running Version: 1.1.7
Active Network Version: 1.1.6
Validator Minimum Version: 1.1.6

```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 

![image](https://user-images.githubusercontent.com/48506765/231716443-06e10a73-5ed0-48ee-87e6-cb0c3a73ddc9.png)

**Comment by ivan-strelka** [comment]
![Monosnap StatusIndicator 2023-04-13 14-58-17(1)](https://user-images.githubusercontent.com/48506765/231717119-6af7e12f-12e1-46b3-a8a6-63b8f0537731.jpg)

**Comment by ivan-strelka** [comment]
lIke this 
![Monosnap StatusIndicator 2023-04-13 14-58-17(1)](https://user-images.githubusercontent.com/48506765/231717466-08b0fbae-adb8-42c9-8af4-89c732ab465f.jpg)

**Comment by ivan-strelka** [comment]
and

`{"state":"need-stake","totalTimeRunning":3344.282,"totalTimeValidating":"00:00:00","lastActive":"","lastRotationIndex":"","stakeRequirement":"10.0","nominatorAddress":"","nomineeAddress":"ca52105434360635dc139f2cb89ac2171bf7b36eb4adfd1c57d0f9cd62d8597c","performance":{"memPercentage":14.38265497220145,"diskPercentage":24.98712772398682,"cpuPercentage":3.868471953578334},"currentRewards":"0.0","lockedStake":"0.0","nodeInfo":{"publicKey":"ca52105434360635dc139f2cb89ac2171bf7b36eb4adfd1c57d0f9cd62d8597c","curvePublicKey":"da6614b0599f03fb2d5c0993183b85369f8f27c1185a1ec3f970cdd68730764e","externalIp":"31.220.81.234","externalPort":9001,"internalIp":"31.220.81.234","internalPort":10001,"status":null,"appData":{"shardeumVersion":"1.1.7","minVersion":"","activeVersion":"","latestVersion":"","operatorCLIVersion":"0.1.2","operatorGUIVersion":"0.1.2"}}}`

![Monosnap Shardeum Dashboard 2023-04-13 15-02-22(1)](https://user-images.githubusercontent.com/48506765/231717978-62307418-fbb8-4093-8e47-d02051042828.jpg)

**Comment by ivan-strelka** [comment]
And this 

![Monosnap Shardeum Dashboard 2023-04-13 15-02-22(1)](https://user-images.githubusercontent.com/48506765/231718373-2ef5f7f4-e323-4fbd-af28-086fae8b769a.jpg)

**Comment by ivan-strelka** [comment]
@MarcusWentz  is it bug?

**Comment by djack99587** [comment]
having same issue, just set up my node and status goes from standby to need stake every few minutes. Not sure if its because i just set the node up and i haven't come out of standby mode yet?

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
