### ISSUE TITLE
Validator GUI assets appear and disappear

### ISSUE THREAD

**Issue by Coolclasse75** [Shardeum/shardeum-bug-reporting#327]
Hi Shardeum team, 

I contact yo you because  on server " stop node " button appears and disaappear just after and reappears again, it's normal ? 
I have the same problem for Stake address information.
I could stake Shm tokens without problem, but i don't know if the node are active or not. 

So I would like to know if it's just a bug or if i can fix it ?

Thanks you and good luck team ( it's last step :D )

Regards,
Coolclasse#2749

![Capture d’écran 2023-04-13 à 20 25 01](https://user-images.githubusercontent.com/129293039/231850657-5f15e799-838c-4ac3-904b-ef593cbd510d.png)
![Capture d’écran 2023-04-13 à 20 25 17](https://user-images.githubusercontent.com/129293039/231850661-faf8f72d-3fc4-4467-87a6-d844f82fde26.png)

**Comment by camzilla1050** [comment]
Mm problem. Galeré à installer le validator gui... Ensuite Bug avec buton starter le node et mnt que j'ai attendu pendant 7 jours de recevoir mes SHM  impossible de staker les 10 SHZ avc metamsk, erreur fail to fetch :E

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/8630a3eb-d3c8-4372-a642-5cf209848023)
