### ISSUE TITLE
Validator CLI Unstake Error `No reward endTime set, can't unstake node yet`

### ISSUE THREAD

**Issue by soerenwa** [Shardeum/shardeum-bug-reporting#330]
##### What is the issue?

Cant unstake through cli.
    
#### What impact does the issue have?

getting following error in cli:

{"jsonrpc":"2.0","id":53,"error":{"code":101,"message":"No reward endTime set, can't unstake node yet","data":{"originalError":{"status":400}}}}

##### How to reproduce the issue? 

after cli update to 0.1.2, unstake with CLI command: "operator-cli unstake"

**Comment by MarcusWentz** [comment]
Can you use the Validator GUI to force unstake?

**Comment by Denistars** [comment]
I have the same problem, if I reinstall from scratch everything will solve?

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"No reward endTime set, can't unstake node yet","data":{"originalError":{"status":400}}}}}'

**Comment by Cyrelb** [comment]
I have the same issue

**Comment by vladimwd** [comment]
same

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
