### ISSUE TITLE
[Duplicate] Validator Install Error ```Client timeout exceed while waiting for headers```

### ISSUE THREAD

**Issue by crazykumarr** [Shardeum/shardeum-bug-reporting#331]
Dear Team,

Kindly check following error while executing dashboard command

Sending build context to Docker daemon  273.4kB
Step 1/9 : FROM registry.gitlab.com/shardeum/server:latest
Get "https://registry.gitlab.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Trying again with sudo...
Sending build context to Docker daemon  273.4kB
Step 1/9 : FROM registry.gitlab.com/shardeum/server:latest
Get "https://registry.gitlab.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/47
