### ISSUE TITLE
Validator VPS issue?

### ISSUE THREAD

**Issue by jonathanrolfe** [Shardeum/shardeum-bug-reporting#332]
my vps was down for day - before i could get to the dashboard but now google doesnt allow connection - Are there firewall issues and if so how is this dealt with
thanks in advance

**Comment by menchcpt** [comment]
Hey guys. Is there any update on this bug? I've had this recurring issue now for about a week and still haven't managed to gain access to my node. Has this bug been looked into? Thanks

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
