### ISSUE TITLE
Validator stake error updating validator from 1.1.6 to 1.1.7?

### ISSUE THREAD

**Issue by fabian93** [Shardeum/shardeum-bug-reporting#333]

**Comment by fabian93** [comment]
Problem with adding stake after updating validator from 1.1.6 to 1.1.7

**Comment by fabian93** [comment]
![Screenshot_20230416-153907_Kiwi Browser.jpg](https://user-images.githubusercontent.com/11017487/232322892-776516a5-8957-47fe-b6b0-007c43ccf989.jpg)

![Screenshot_20230416-152252_Kiwi Browser.jpg](https://user-images.githubusercontent.com/11017487/232322899-785a6a31-cc0f-476d-a3b2-c7b6a40494af.jpg)

![Screenshot_20230416-152209_Kiwi Browser.jpg](https://user-images.githubusercontent.com/11017487/232322905-12e09e5b-79e3-49f2-83f2-5738bc172c47.jpg)

![Screenshot_20230416-151810_Kiwi Browser.jpg](https://user-images.githubusercontent.com/11017487/232322910-c63d79ef-71be-49d9-879c-ec3dd272ed44.jpg)

![Screenshot_20230416-142612_Kiwi Browser.jpg](https://user-images.githubusercontent.com/11017487/232322916-15aae26a-d00d-4f29-90e5-f5a6e12c28e1.jpg)

**Comment by MarcusWentz** [comment]
Q1. Did you try a new wallet to stake with?

Q2. Does this work after you uninstall:
https://docs.shardeum.org/node/run/validator#uninstall-validator
then reinstall:
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator
?

**Comment by fabian93** [comment]
Now everything works fine

**Comment by Brave-Humens** [comment]
Hello, please tell me what did you do to successfully put shm?
I'm also having issues after upgrading from 1.1.6 to 1.1.7, sometimes getting the same errors as you and sometimes this error:
`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Failed to process transaction: {\"raw\":\"0xf90167028501dfd140008401c9c38094000000000000000000000000000000000000000188a688906bd8b00000b8f67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a362c226e6f6d696e61746f72223a22307866333131396664333934326664623961326562646139396462353964313833666131653166646565222c226e6f6d696e6565223a2231643237656131353637616166613239316230353138306238323734353532386438333335346336373138386231333733316536393836386637646461356637222c227374616b65223a223132303030303030303030303030303030303030222c2274696d657374616d70223a313638313734393634373337392c227374616b654f6b223a747275657d823f48a0778f8a0cd81a811f80414adb1540ce6b68cb30f3c425fa8f4aef5b67ebb2f691a02ff7ec188968a068cec17f61c4097355d22adb271c39a58e712db6de560befc3\",\"timestamp\":1681749694291} TypeError: Cannot read properties of undefined (reading 'length')","data":{"originalError":{"status":500}}}}}'

`

**Comment by camzilla1050** [comment]
Have same problem with GUI interface. It works fine forme passing by operator-cli described on
[https://docs.shardeum.org/node/run/validator setp 9](https://docs.shardeum.org/node/run/validator#cli](url)

**Comment by camzilla1050** [comment]
Have same problem with GUI interface. It works fine forme passing by operator-cli described on
<https://docs.shardeum.org/node/run/validator#cli>

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
