### ISSUE TITLE
Validator CLI Stake Error

### ISSUE THREAD

**Issue by chivodk** [Shardeum/shardeum-bug-reporting#334]
##### What is the issue?

After i connect my wallet Metamask on Shardeum i can't add stake i have a error.
    
#### What impact does the issue have?

i have a red banner with "unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)"

##### What other resources can you share regarding this issue?

I have reinstall my VM and the Shardeum is till connect to my wallet.

**Comment by camzilla1050** [comment]
Error after add stake returns in red banner
"failed to fetch"

and also  "JsonRpcEngine: Response has no error or result for request: { "method": "eth_gasPrice", "params": [], "jsonrpc": "2.0", "id": 1040279977, "origin": "...:8080", "tabId": 1574718963 }"

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
