### ISSUE TITLE
Validator GUI stop button does not refresh to start button on the maintainance page

### ISSUE THREAD

**Issue by atomstaker** [Shardeum/shardeum-bug-reporting#336]
##### What is the issue?

if the node is running, press "stop node" button, then press "start node", the button keep staying "start button" although the node already run
    
#### What impact does the issue have?

user can not judge the node is running or not.

##### How to reproduce the issue? 

if the node is running, press "stop node" button, then press "start node", the button keep staying "start button" although the node already run, sometime it will  keep the button unchanged until refresh the page, sometime it will turn good after long time.

##### What other resources can you share regarding this issue?
![image](https://user-images.githubusercontent.com/128807593/232361753-b62db916-c5e1-4fbb-96c5-588f3df16a8c.png)

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
