### ISSUE TITLE
Validator GUI Add Stake error?

### ISSUE THREAD

**Issue by camzilla1050** [Shardeum/shardeum-bug-reporting#337]
##### Can't add 10SHM stake in Validator GUI

![Capture d’écran du 2023-04-16 19-37-59](https://user-images.githubusercontent.com/10384623/232452995-18f02ace-bc22-4d72-9cec-acd0170aaf4b.png)

![Capture d’écran du 2023-04-16 19-45-59](https://user-images.githubusercontent.com/10384623/232453157-a45b1139-3882-45a4-9663-d7394dc2516c.png)

**Comment by camzilla1050** [comment]
Staking unsolved otherwise passing by cli
```
$operator-cli stake 10
```

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
