### ISSUE TITLE
RPC transaction fails `Maximum load exceeded`

### ISSUE THREAD

**Issue by rudra2310** [Shardeum/shardeum-bug-reporting#338]
AFTER REMOVING STAKING 
![image](https://user-images.githubusercontent.com/81848407/232514783-9029e4cd-a673-40f1-bf39-ae9ba5ab40f6.png)
**THIS ERROR COMING**

**Comment by nfts2me** [comment]
We're also getting this when trying to deploy a contract.

**Comment by nfts2me** [comment]
Now also getting this error:
```
ProviderError: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Failed to inject tx:  {}","data":{"originalError":{"status":500}}}}}'
```

And this:
```
ProviderError: Internal JSON-RPC error.
```

**Comment by emfaf** [comment]
Have the same when trying to stake

**Comment by sametserpil** [comment]
Same here.

**Comment by Mounasab** [comment]
meme erreur impossible de stacker

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
