### ISSUE TITLE
Validator Unstake Transaction Error `TypeError: Cannot read properties of undefined (reading 'length')`

### ISSUE THREAD

**Issue by kampred99** [Shardeum/shardeum-bug-reporting#339]
While trying to unstake, i'm getting this error.

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Failed to process transaction: {\"raw\":\"0xf9013f018501dfd140008401c9c38094000000000000000000000000000000000000000180b8d67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307836383934323264383231376433376135353037383166323536643435346263616134366664326231222c2274696d657374616d70223a313638313737363239313930332c226e6f6d696e6565223a2230353832306337333365366634396131353030623866353134343931316430336433336637343362383636623132666235313836633961356234633336373361222c22666f726365223a66616c73657d823f47a0ffd8eb07b39b6ef8fd41440d93b2b13bc56c5ba3f1da7c89e22e2cd271466297a066b675aad0f1f75a91642cc5fb7c3869ca026e3c98069a292bdd7914a51d74fb\",\"timestamp\":1681776296708} TypeError: Cannot read properties of undefined (reading 'length')","data":{"originalError":{"status":500}}}}}'

![photo_2023-04-18_07-17-35](https://user-images.githubusercontent.com/104084791/232637873-cb7e4dec-350f-4bce-992b-a88e3affe587.jpg)

**Comment by MarcusWentz** [comment]
Do you get this error when you try to force unstake from the Validator GUI?

**Comment by kampred99** [comment]
> 

yes.. from Validator GUI

**Comment by r-tom90** [comment]
This error is related to a failed transaction on the Shardeum blockchain. The message indicates that the transaction failed to process and returned an error with a specific code and message.

The error message also suggests that there was an issue with the input data or format of the transaction, specifically with the length of a property that was undefined.

To resolve this issue, you may need to review the input data and transaction parameters to ensure they are valid and formatted correctly. You may also need to check the code and message associated with the error to determine the cause of the issue and take appropriate action.

**Comment by SpaceRider401** [comment]
![Unable to Unstack 24 04 2023](https://user-images.githubusercontent.com/126847147/233901755-8c2e4dad-76a2-494f-b5c1-0e3d310067e3.jpg)
Unable to unstack receiving error message , Tried clearing history , resetted the metamask and also changed the gas fees but not working , Kindly fix the bug...

**Comment by techinfo00** [comment]
i have sim probleme 
### /
![helpp](https://user-images.githubusercontent.com/131919156/234704387-f33bdb54-df86-4a7e-bff0-35aeca4c621d.PNG)

/

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
