### ISSUE TITLE
Validator Stopped Lost Stake Reward 

### ISSUE THREAD

**Issue by johnt9x** [Shardeum/shardeum-bug-reporting#34]
What is the issue?
Lost reward when i restart
What impact does the issue have?
I get stopped when enough loops (This is also a bug and waiting to be fixed). 
So i restarted and i lost all my reward and start getting new rewards from 0.
I also don't see the reward in my wallet.

What other resources can you share regarding this issue?

![Capture2](https://user-images.githubusercontent.com/40466326/216799268-6b5dc6db-218c-47ce-bd96-17a70ebe6dd1.PNG)
![Capture3](https://user-images.githubusercontent.com/40466326/216799272-e64a85bb-594b-4bd9-a0f8-5ca68fe723a2.PNG)

**Comment by tawdarky2** [comment]
This happens to my node aswell.Only mine was in standby and i found it stopped in the morning.

**Comment by kvantIT** [comment]
Probably this happens when node was stopped, bcs after stop from active the gui shows in standby mode that still earning!!! So after restart earnings reset to real earnings recorded on blockchain...

**Comment by cnhotfire** [comment]
This happens to my node too, and it happened several times. 
According to my observation, the status of the node Earnings lost is like this: standby -> active -> standby -> active again, the Earnings will restart from 0 at this time

**Comment by Kraken133** [comment]
Hello! I started the node a few days ago, but every time the node stops spontaneously, my rewards are reset to zero. Yesterday, the node worked for more than a day, and the rewards were above 60 SHM. Today the node stopped itself twice already and at the moment I have the following values
<img width="1031" alt="Снимок экрана 2023-02-07 в 21 27 13" src="https://user-images.githubusercontent.com/102407107/217346209-5bd7020e-2822-4343-b009-37094e3a01d4.png">

**Comment by MarcusWentz** [comment]
Did anyone notice this issue on Betanet 1.1 as well?

**Comment by capybara1s** [comment]
i have the same problem. i forgot my shm too

**Comment by Hummagumma** [comment]
It is happening to me. 3 days active and about 60 of rewards yesterday. Today reseted to 0 and still active

**Comment by ScalperhuBhai** [comment]
But why thats happening all the SHM rewards got wasted or they are in Developers Blockchain Tx

**Comment by GONY7** [comment]
same problem
![image](https://user-images.githubusercontent.com/83521556/220427877-14c6cfc2-d043-4c1c-acde-77ecec644cab.png)

Earnings : 80 SHM -> 3 SHM down.

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by ScalperhuBhai** [comment]
how to know the verison updated or not ? also Remove stake was not working so i pasted the code without that
whats the code to know the version is updated or not?

**Comment by ScalperhuBhai** [comment]
![is this the new  version ](https://user-images.githubusercontent.com/107799534/220662084-2735fd8a-9afb-4443-9c7c-52fa4afc69ba.PNG)
HEY I HAVE USED THE CODES BUT GOT THIS VERSION IS THIS CORRECT

**Comment by MarcusWentz** [comment]
@ScalperhuBhai 

The GUI shows the CLI and GUI version, but not the validator version for some reason.

What do you see when you run:

```shell
curl localhost:9001/nodeinfo
```

?

https://docs.shardeum.org/node/run/validator#check-installed-version

**Comment by ksbaskar** [comment]
> Did anyone notice this issue on Betanet 1.1 as well?

Yes facing the same issue in  1.1.1 too previously it was more than 50 SHM but once get Active again Rewards become 0 and counted to start again.

<img width="805" alt="reward_disappered" src="https://user-images.githubusercontent.com/6725456/220858605-0aea75cc-5a6c-4a85-8b04-3cb921922965.png">

**Comment by cnhotfire** [comment]
Betanet 1.1 , same issue.   restart Lost Stake reward
Ubuntu 22.04
docker Server Version: 23.0.0
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/34259220/221067072-77220eb0-e754-4ae5-94db-f7f85f201055.png">

**Comment by tahirjamaluddin** [comment]
I had the same issue where often all my earning are reset to 0

**Comment by MJZ1995** [comment]
Is this problem not solved yet?

**Comment by SpaceRider401** [comment]
After update node is active, but earning rewards disappeared and rest to 0.4833shm and After update node running for 14hrs but still showing reward as 0.4833shm , Totally 95 Shm disappeared in a week after update...
Rewards Disappeared 13 03 2023
Address: 0xf6b37aA2cafC178AD3B10cc9C9464FDEa79037e7
https://94.131.10.13:8080/
![Rewards Disappeared 13 03 2023](https://user-images.githubusercontent.com/126847147/224896493-0aac152e-114e-4ff2-a3da-6bc3743d653a.jpg)

**Comment by swarna1101** [comment]
The upcoming version update is anticipated to address these issues. The development team has confirmed that the rewards will be retained upon restart, and the loop-related bug causing program interruptions will be resolved.
