### ISSUE TITLE
Validator GUI status Standby

### ISSUE THREAD

**Issue by camzilla1050** [Shardeum/shardeum-bug-reporting#340]
##### What is the issue?

Validator GUI status Standby after stake process during hours
    
![Capture d’écran du 2023-04-18 14-02-33](https://user-images.githubusercontent.com/10384623/232771374-0af559e1-1072-4813-9d35-10ec7dcc81bf.png)

**Comment by MarcusWentz** [comment]
Time to become active can vary.
```
If your node status is on Standby and you have 10 SHM or more staked, your validator node is setup correctly.

The network will automatically add your validator to be active in the network.

The time to be added as an active validator will vary based on network load and validators in the network.
```
https://docs.shardeum.org/node/run/validator#step-9-stake-shm-to-validator

**Comment by camzilla1050** [comment]
Ok Tnx
