### ISSUE TITLE
Validator CLI `operator-cli status` error `TypeError: Cannot read properties of undefined (reading 'data')`

### ISSUE THREAD

**Issue by drifter728** [Shardeum/shardeum-bug-reporting#342]
dashboard not laoding,not showing anything its blank

in terminal ,operator-cli status gives errored msg which imm attaching below    
![nodedat](https://user-images.githubusercontent.com/127377575/233007122-84a189f7-706b-4f3e-a044-7879a8f701f4.png)

**Comment by Glitch18** [comment]
Can you post the output of `cat cli/build/active-node.json`?

**Comment by Glitch18** [comment]
Please also provide the output of 
```
cd cli
git log --oneline | head -n 1
```

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
