### ISSUE TITLE
[Duplicate] RPC ```eth_getBalance``` returns 0 SHM in Metamask

### ISSUE THREAD

**Issue by anishk5555** [Shardeum/shardeum-bug-reporting#344]
##### What is the issue?

:red_circle:  shm sphinx not showing in the metamask. :red_circle: 
    
#### so not able to do staking as couldnt complete the transaction in metamask

:red_circle: not able to stake. :red_circle: 

##### How to reproduce the issue? need to solve the issue

:red_circle: 
shm sphinx not showing in metamask bt its showing in explorer
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by pinholove** [comment]
I've been having the same problem for several days.

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/44
