### ISSUE TITLE
[Duplicate] RPC ```eth_getBalance``` returns 0 SHM in Metamask

### ISSUE THREAD

**Issue by faizanr11** [Shardeum/shardeum-bug-reporting#346]
Please send faucet for running node
0x433026F0311D63A7f873DB75Eb1e744df624Ec30
All existing shm wiped off please @MarcusWentz

**Comment by MarcusWentz** [comment]
I see you have enough tokens in the Explorer:
https://explorer-sphinx.shardeum.org/account/0x433026f0311d63a7f873db75eb1e744df624ec30

We are tracking this issue here: 
https://github.com/Shardeum/shardeum-bug-reporting/issues/44
