### ISSUE TITLE
RPC Error `[ethjs-query] while formatting outputs from RPC "code":-32603, "id":6420567001889, "method":"eth_sendRawTransaction"`

### ISSUE THREAD

**Issue by davidkimoficial** [Shardeum/shardeum-bug-reporting#348]
##### What is the issue?

:red_circle:  Its beens almost a month since i cant stake SHM to start node :red_circle: 
    
#### What impact does the issue have?

:red_circle: this bug makes us not being able to participate as validators, i have SHM in wallet but it never approves the stake :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
to reproduce i simply try to stake 10 SHM and it returns this error:
```

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":6420567001889,"jsonrpc":"2.0","params":["0xf90167078501dfd140008401c9c380940000000000000000000000000000000000000001888ac7230489e80000b8f67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a362c226e6f6d696e61746f72223a22307832643866633337333534373936656632353030666538376230353933303630323531623862613836222c226e6f6d696e6565223a2235663963383165393737333962306635666536666535623130313333626638646335653064636564646534383031383037363862663538316234616339306135222c227374616b65223a223130303030303030303030303030303030303030222c2274696d657374616d70223a313638323137363134303235322c227374616b654f6b223a747275657d823f47a0ee699e4786eb28ee6edaf79a38b8e39db1c1572f1f299eaabfd67d7fb2ed3495a02fb8c8eea104523e9167f9832bef7a89368fd7166ceb2caea6ae5837ddd0b172"],"method":"eth_sendRawTransaction"}}}}'
```
:red_circle: 

##### What other resources can you share regarding this issue?

- :red_circle:  :red_circle:

**Comment by sametserpil** [comment]
I have the same error. [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":4239229531031,"jsonrpc":"2.0","params": ..........

**Comment by madmerr** [comment]
Good job! Node requires update, but update is impossible, cause got same error when trying to unstake.
![Screenshot_1](https://user-images.githubusercontent.com/115369466/233978905-6e5b5493-03f6-4cf3-b7eb-0a5b3f8649a6.png)

**Comment by rafalbujak** [comment]
I have this same error: 

output from version 1.1.7
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":778553840057,"jsonrpc":"2.0","params":["0xf9013f058501dfd140008401c9c38094000000000000000000000000000000000000000180b8d67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307833303432376131346265363539376235356232623362383138346336346665376134626563303765222c2274696d657374616d70223a313638323334363138323134392c226e6f6d696e6565223a2238653133323339396662353636373564653062613630333539656437623639316464656133323566346462373034353763656161663431313666383632353961222c22666f726365223a66616c73657d823f48a089ecf9b170b5ab8353c8314529af512e710237ce7691f5b4fccdce93996f48e0a04777a825fad44e9c7a2b26e33fd0e33fe5ececdf8cc23690e2b8e3fcafe72e58"],"method":"eth_sendRawTransaction"}}}}'

and after update to version 1.1.8:
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":778553840060,"jsonrpc":"2.0","params":["0xf9013f058501dfd140008401c9c38094000000000000000000000000000000000000000180b8d67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307833303432376131346265363539376235356232623362383138346336346665376134626563303765222c2274696d657374616d70223a313638323334363938343837342c226e6f6d696e6565223a2238653133323339396662353636373564653062613630333539656437623639316464656133323566346462373034353763656161663431313666383632353961222c22666f726365223a66616c73657d823f47a00f6bf3edeb5791f91366b3cf5e3cc9f793064c3cacaff159a5cf123280db9e2ca022390d2c051dcb31e0da4a575d730077f48e97a831d7d07bf348bda29eae4091"],"method":"eth_sendRawTransaction"}}}}'


I am not able to remove the staked SHM coins

**Comment by Brin-linge** [comment]
![image](https://user-images.githubusercontent.com/28498244/234170491-c8c53436-d6a4-4a5b-99ec-91ff63ad4607.png)

**Comment by tspring80** [comment]
I have the same issue, cannot unstake tokens to make the update to version 1.1.8.
![image](https://user-images.githubusercontent.com/31645674/234206170-3b679653-d7f0-4005-b6e5-8d3f8ec5d7f9.png)

**Comment by Robkynd** [comment]
Same issue

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":4719392494323,"jsonrpc":"2.0","params":["0xf901680b8501dfd140008401c9c3809400000000000000000000000000000000000000018901158e460913d00000b8f67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a362c226e6f6d696e61746f72223a22307861663030613862346538336130303539323164306638373864323030303664653063646130343463222c226e6f6d696e6565223a2237633764323138316234656137306638623863383165393636636262353337646336366235326336633430303336656361663461306132366630373364653962222c227374616b65223a223230303030303030303030303030303030303030222c2274696d657374616d70223a313638323531303536303931302c227374616b654f6b223a747275657d823f47a0e6cd6e9e45eaf04ae301730c86b7fd493ee32047f6aab4ab17aa575b899b3b25a07025cc3e9c5b49661c15f247030dad38af1bb93f9c619b7ae7f28fdd7af86c03"],"method":"eth_sendRawTransaction"}}}}'

**Comment by bcjcrypto** [comment]
Do we have any resolution for this issue? I am stuck , not able to remove stake from old node after upgrading node to latest version... and not able to participate as validators..

**Comment by MarcusWentz** [comment]
@bcjcrypto 

We are looking into this.

Please try to use other wallets for now to stake.

**Comment by bendable08** [comment]
Waiting to be resolved

**Comment by timsonDan** [comment]
same problem on updated version
Waiting to be resolved

![Ashampoo_Snap_пятница, 28 апреля 2023 г _14h10m35s](https://user-images.githubusercontent.com/121762080/235144569-8f33f964-98ff-487c-9210-e5b2b12304a8.png)

**Comment by skundu42** [comment]
This should be resolved in newer versions now.
