### ISSUE TITLE
[Duplicate] RPC Error `[ethjs-query] while formatting outputs from RPC "code":-32603, "id":6420567001889, "method":"eth_sendRawTransaction"`

### ISSUE THREAD

**Issue by shakib121** [Shardeum/shardeum-bug-reporting#349]
Can't stake, Can't remove stake, please solve these issue becouse we can't node run properly for this reason,  if you can blockchain more development so project automatically will be growth, hopefully solve this issue soon,What is the benefit if we can't manage nodes properly?  Hope to improve sphinix blockchain very soon, facing problem about 14/13days, more and more reported that sphinix blockchain used to develop
![IMG_20230422_214136_867](https://user-images.githubusercontent.com/57534601/233793791-22528c9a-f75b-4c9c-a588-29c5f4abe801.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/348
