### ISSUE TITLE
Validator Randomly Stops

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#35]
##### What is the issue?

Validator will stop running at random times.
    
#### What impact does the issue have?

Will turn an active or standby validator off, making it harder to secure Shardeum the network.

##### How to reproduce the issue? 

Operating System: 

Linux 

docker: 

```curl
docker --version
```

returns: 

```shell
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
```

docker-compose:

```shell
docker-compose --version
```

returns: 

```shell
docker-compose version 1.29.2, build 5becea4c
```

##### What other resources can you share regarding this issue?

Validator setup guide:

https://docs.shardeum.org/node/run/validator#step-1-install-prerequisites

**Comment by Inoutik** [comment]
Hi! Have the same problem( 
docker version 23.0.0, build e92dd87
docker-compose version 1.29.2, build 5becea4c
Ubuntu 22.10

**Comment by mesahin001** [comment]
Same here: I was running the node since 3 days and every night stoppes it self. I run it again and till the night (I don't know exact time) stop running.
Ubuntu 22.04.1 LTS 
Docker Version:           20.10.21
docker-compose version 1.29.2

**Comment by VCFAdvisor** [comment]
Same here. Node stops randomly and suddenly.

> docker version
> Client: Docker Engine - Community
>  Version:           20.10.23
>  API version:       1.41
>  Go version:        go1.18.10
>  Git commit:        7155243
>  Built:             Thu Jan 19 17:36:25 2023
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.23
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.18.10
>   Git commit:       6051f14
>   Built:            Thu Jan 19 17:34:14 2023
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.15
>   GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
>  runc:
>   Version:          1.1.4
>   GitCommit:        v1.1.4-0-g5fd4c4d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
>

**Comment by bogachevanton** [comment]
Validator stopped twice in 3 days for no reason

**Docker info:**

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
docker-compose version 1.29.2, build 5becea4c

**OS info:**

Linux Mint 21.1 Cinnamon
Cinnamon 5.6.7
core 5.15.0-58-generic

**Comment by AlphaQ741** [comment]
After clicking start node..
it will show standby for sometime..
then after a while upon checking, it shows stopped..

this happened 4 times in 2 days on trying to start a node..

but first time initially it did start..
all this happened after the initial node set up with a successful start

**Comment by JasonPingTwu** [comment]
Same here. Just stopped. 
![image](https://user-images.githubusercontent.com/19248241/216832506-4a71f01f-4012-463d-b2ad-322f17d987a0.png)

**Docker info**
Docker version 20.10.12, build 20.10.12-0ubuntu4
Docker-compose version 1.29.2, build 5becea4c
Ubuntu 22.10

**Comment by bogachevanton** [comment]
> Validator stopped twice in 3 days for no reason
> 
> **Docker info:**
> 
> Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
> docker-compose version 1.29.2, build 5becea4c
> 
> **OS info:**
> 
> Linux Mint 21.1 Cinnamon
> Cinnamon 5.6.7
> core 5.15.0-58-generic
> 
> ![2023-02-05 18-58-58](https://user-images.githubusercontent.com/90133006/216832710-de8af822-52a9-4de4-b1e8-367271f014c7.png)
> 
> About screenshot: like you see, operator started 32h ago, validator 21h ago after stop and restart

Stopped twice in last 10 minutes

**Comment by alvisahar** [comment]
my node stopped after few hours (picture attach)

**Docker info :**

Docker version 23.0.0, build e92dd87
docker-compose version 1.29.2, build 5becea4c

**OS info :**

OS Ubuntu 20.04 (Windows Subsystem for Linux)

![image](https://user-images.githubusercontent.com/53466222/216876125-df8e6f2f-89fd-4412-9062-a3f14ac4e057.png)

**Comment by cnhotfire** [comment]
I have a total of three nodes, which have been running for three days and found that there is the same issue. 
When the node becomes active, it will automatically stop at least once a day.

Ubuntu 22.04.1 LTS

docker version
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:04 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


Docker Compose version v2.14.1

**Comment by stepnalien** [comment]
Same here. it's Just auto stopped after few hour.


Docker info
Docker version 20.10.12, build 20.10.12-0ubuntu4
Docker-compose version 1.29.2, build 5becea4c

Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-105-generic x86_64)

**Comment by ralymov** [comment]
Node keeps constantly stopping

**Docker info:**
Docker version 20.10.17, build 100c701
Docker Compose version v2.6.0

**OS info:**
OS Ubuntu 20.04 

**Error log from PM2** (screenshot and logs file attached, last 100 lines here):
[validator-error.log](https://github.com/Shardeum/shardeum-bug-reporting/files/10677334/validator-error.log)

```
1|validato | (node:32032) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
1|validato | (Use `node --trace-deprecation ...` to show where the warning was created)
1|validato | Error: Unacceptable parameter value
1|validato |     at _base16BNParser (/usr/src/app/src/utils/serialization.ts:70:11)
1|validato |     at Object.signAppData (/usr/src/app/src/index.ts:4453:49)
1|validato |     at G.getAppDataSignatures (evalmachine.<anonymous>:1:208237)
1|validato |     at getCertSignatures (/usr/src/app/src/handlers/queryCertificate.ts:257:25)
1|validato |     at queryCertificateHandler (/usr/src/app/src/handlers/queryCertificate.ts:233:10)
1|validato |     at /usr/src/app/src/index.ts:1487:24
1|validato | (node:35383) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
1|validato | (Use `node --trace-deprecation ...` to show where the warning was created)
1|validato | 09:54:19 [ERROR] Connection to 167.94.138.61:57222 failed with Error: Failed to read from TCPStream. Connection reset by peer (os error 104)
1|validato | 09:54:24 [ERROR] Connection to 167.94.138.61:45440 failed with Error: Failed to read from TCPStream. Connection reset by peer (os error 104)
1|validato | 09:54:28 [ERROR] Connection to 167.94.138.61:40306 failed with Error: Failed to read from TCPStream. Connection reset by peer (os error 104)
1|validato | Error: Unacceptable parameter value
1|validato |     at _base16BNParser (/usr/src/app/src/utils/serialization.ts:70:11)
1|validato |     at Object.signAppData (/usr/src/app/src/index.ts:4453:49)
1|validato |     at G.getAppDataSignatures (evalmachine.<anonymous>:1:208237)
1|validato |     at getCertSignatures (/usr/src/app/src/handlers/queryCertificate.ts:257:25)
1|validato |     at queryCertificateHandler (/usr/src/app/src/handlers/queryCertificate.ts:233:10)
1|validato |     at /usr/src/app/src/index.ts:1487:24
1|validato | (node:61380) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
1|validato | (Use `node --trace-deprecation ...` to show where the warning was created)
1|validato | Error: Unacceptable parameter value
1|validato |     at _base16BNParser (/usr/src/app/src/utils/serialization.ts:70:11)
1|validato |     at Object.signAppData (/usr/src/app/src/index.ts:4453:49)
1|validato |     at G.getAppDataSignatures (evalmachine.<anonymous>:1:208237)
1|validato |     at getCertSignatures (/usr/src/app/src/handlers/queryCertificate.ts:257:25)
1|validato |     at queryCertificateHandler (/usr/src/app/src/handlers/queryCertificate.ts:233:10)
1|validato |     at /usr/src/app/src/index.ts:1487:24
1|validato | (node:63950) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
1|validato | (Use `node --trace-deprecation ...` to show where the warning was created)
1|validato | (node:66224) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
1|validato | (Use `node --trace-deprecation ...` to show where the warning was created)
```
![image](https://user-images.githubusercontent.com/17036618/217302874-9a914748-709a-4f0e-a759-9d392cd686a5.png)

**Comment by NeilCrypto7** [comment]
Hi, same here. Stopped after 1 day... 

docker --version : `Docker version 23.0.0, build e92dd87`
docker-compose --version : `docker-compose version 1.25.0, build unknown`

Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-137-generic x86_64)

**Comment by Kraken133** [comment]
Hey! I started node a few days ago and it has stopped spontaneously about 6-7 times already. For the first time yesterday, he worked for more than a day, but today he stopped twice

docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
docker-compose version 1.29.2, build 5becea4c

**Comment by ramzesisi** [comment]
https://docs.docker.com/config/containers/start-containers-automatically/
https://docs.docker.com/engine/reference/commandline/service_create/
probably it can fix your problem, you need to make flag and when docker will get it node connection will be restarted automatically(till it will not get any errors) 
I never worked with docker, but know that some guys did something with nodes (its effective)

**Comment by tawdarky2** [comment]
I am also having the same issue.It even stopped after it managed to get active status.

root@shardeum:~# docker --version
Docker version 20.10.16, build 20.10.16-0ubuntu1
root@shardeum:~# docker-compose --version
docker-compose version 1.29.2, build 5becea4c

Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic

**Comment by coldsjf** [comment]
same issue, running the node on Mac.

`Docker version 20.10.17, build 100c701`

`docker-compose version 1.29.2, build 5becea4c`

**Comment by 0xtbug** [comment]
Random stop in my node every 24 hours, in my case, the earning rewards was not reset to 0.

![chrome_6eFWJ48E2r](https://user-images.githubusercontent.com/54710482/217408687-794e893b-373c-4221-ae28-675e764db6a6.png)

**Node Info**

![screencapture-157-90-124-12-8080-performance-2023-02-08-09_01_07](https://user-images.githubusercontent.com/54710482/217409619-c29e0db5-003d-4f33-87ad-4572b01cf336.png)

**Cloud Console Graph Info**

![wM9o76fzQz](https://user-images.githubusercontent.com/54710482/217410420-9a74ad43-3773-4eae-9924-456403226aaf.png)

**Docker Info**
docker --version
```
Docker version 20.10.12, build 20.10.12-0ubuntu4
```

docker-compose --version
```
docker-compose version 1.29.2, build 5becea4c
```

**OS Info**
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**System Info**
```
Ram: 8GB
Vcpu: 4
Local Disk (SSD): 160GB
```

**Comment by losilo** [comment]
hi same issue, 
Docker Info
docker --version

Docker version 23.0.0, build e92dd87
docker-compose --version

docker-compose version 1.25.0, build unknown
OS

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

4 vCPU Cores
8 GB RAM
200 GB SSD

**Comment by imseya18** [comment]
hi same issue,
Docker Info
docker --version

Docker version 23.0.0, build e92dd87
docker-compose --version

docker-compose version 1.25.0, build unknown
OS

Distributor ID: Ubuntu
Description: Ubuntu 22.04.1 LTS
Release: 22.04
Codename: jammy

4 vCPU Cores
8 GB RAM
200 GB SSD

**Comment by cncxx0755** [comment]
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
Hello, I can get revenue, but the node will stop at any time, and the status is always displayed as standby.
![shm](https://user-images.githubusercontent.com/111628601/217430985-03a43fc2-8aba-469f-abfa-2b11071b4254.png)

**Comment by abeachmad** [comment]
same issue here. Node always stopped on its own after runs for several hours

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
docker-compose version 1.29.2, build 5becea4c
OS Ubuntu 20.04.5 LTS

Anyone finds a workaround to fix this issue?

**Comment by MarcusWentz** [comment]
Did anyone notice this issue on Betanet 1.1 as well?

**Comment by bogachevanton** [comment]
> Did anyone notice this issue on Betanet 1.1 as well? 

In my side - no, i didn't see this bug in 1.1

**Comment by mesahin001** [comment]
> Did anyone notice this issue on Betanet 1.1 as well?

After the 1.1 update have once stopped but since 2 days no problem (btw. my node is still in standby and not in active state changed)

**Comment by MarcusWentz** [comment]
Closing this issue since the GUI is reporting why validators are crashing now.

**Comment by MarcusWentz** [comment]
@gyanprakashlaishram

Please share your info here.

**Comment by MarcusWentz** [comment]
Closing this issue.

Please open a bug report if this is still an issue with the exit log info below.

Open a terminal on your system:
```
(Press at the same time)
Ctrl + Alt + T
```

Read exit log from the:

Method 1: Terminal directly:
```shell
sudo docker exec shardeum-dashboard cat cli/build/logs/exit-summary.json
```

Method 2: Validator CLI:

Navigate to the .shardeum directory by entering:
```shell
cd .shardeum
```
Execute the shell.sh script by entering: 
```shell
./shell.sh
```
With the Validator CLI running, navigate to the cli/build/logs directory by entering:
```shell
cd cli/build/logs
```
View the contents of the exit-summary.json file by entering:
```shell
cat exit-summary.json
```
