### ISSUE TITLE
Validator GUI Maintanence Page Switch Network Button Not Working 

### ISSUE THREAD

**Issue by Sufyanpt** [Shardeum/shardeum-bug-reporting#351]
##### What is the issue?

:red_circle:  Unable to move next step due to switch Network button. Even if change network , this button stays there. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Validator will not be able to complete the Node setup. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 

Once enter in validator page with wrong network, you can not undo the process.

:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: 
![swithe (1).JPG](https://user-images.githubusercontent.com/121370124/233814366-848e44fa-4e16-478d-a1dc-42e50f2e0ee2.JPG)

. :red_circle:

**Comment by skundu42** [comment]
This should be resolved now.
