### ISSUE TITLE
[Duplicate] RPC Error `[ethjs-query] while formatting outputs from RPC "code":-32603, "id":6420567001889, "method":"eth_sendRawTransaction"`

### ISSUE THREAD

**Issue by shakib121** [Shardeum/shardeum-bug-reporting#354]
1. Don't remove stake,  many time i have to try but don't work, 
2. Broken dashboard, both big issue, please soon fixe this
![IMG_20230425_065644_629](https://user-images.githubusercontent.com/57534601/234149241-bfa9337a-1a24-4e2b-957e-3fa4bd29189b.jpg)
![IMG_20230425_065638_473](https://user-images.githubusercontent.com/57534601/234149255-f9c4da86-47f6-45c9-84e3-e7ab3d57728d.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/348
