### ISSUE TITLE
Validator GUI Cannot Start Validator 

### ISSUE THREAD

**Issue by Robkynd** [Shardeum/shardeum-bug-reporting#355]
I has update my node to last version CLI 0.1.3,validator running1.1.8
On my case i cant hit start node button to start operate node.

**Comment by Denistars** [comment]
the same

**Comment by MarcusWentz** [comment]
What happens when you run this in the Validator CLI:
```shell
operator-cli start
```
?
https://docs.shardeum.org/node/run/validator#step-5-start-validator

**Comment by Denistars** [comment]
Good morning,
the error reported here refers to the node start button on the gui if I try
to connect with metamask shardeum on a new wallet.

But the current problem is this one in the photo that prevents me from
unstaking and restarting with my original wallet.
I redid the node from scratch but it doesn't change



[image: image.png]

Il giorno mer 26 apr 2023 alle ore 05:38 Marcus Wentz <
***@***.***> ha scritto:

**Comment by Robkynd** [comment]
Thx done sir
