### ISSUE TITLE
Validator GUI Status api failing for latest client?

### ISSUE THREAD

**Issue by abhishek-Kumar009** [Shardeum/shardeum-bug-reporting#356]
##### What is the issue?
Status api is failing after I upgraded to the latest client version by following setting up node guide of shardeum
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?
Dashboard is not loading
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 
Just update to the latest client version and open dashboard you would see
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
In the networks tab status API gives 400 bad request
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
<img width="658" alt="Screenshot 2023-04-25 at 8 53 03 AM" src="https://user-images.githubusercontent.com/39706657/234166677-6f8974ca-9bfb-4e42-8529-eef169c0cd7b.png">

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
