### ISSUE TITLE
RPC Warning `Transaction decoding is not available for chainid 8082` in Metamask

### ISSUE THREAD

**Issue by bendable08** [Shardeum/shardeum-bug-reporting#357]
When staking SHM to the node, this error appears "Transaction decoding is not available for chainid 8082" and staking does not proceed. Using the the latest node version.

**Comment by MarcusWentz** [comment]
1. Is this error seen in Metamask or somewhere else (might be related to this https://github.com/MetaMask/metamask-extension/issues/14878#issuecomment-1149939473 )?

2. Do you have a screenshot for the error?

**Comment by bendable08** [comment]
Hi, the error is on Metamask.

Attached is the screenshot.

**Comment by MarcusWentz** [comment]
I am not able to see the screenshot.

Can you try to manually drag and drop the screenshot into GitHub? 

Might also be related this: 
https://github.com/MetaMask/metamask-extension/issues/14878#issuecomment-1149939473

**Comment by bendable08** [comment]
![image](https://user-images.githubusercontent.com/113498323/234465109-d87c2218-cf3f-4a29-8310-2ea3650c9dfd.png)
![image](https://user-images.githubusercontent.com/113498323/234465140-80c938e1-a3bc-4be0-b954-1f15a01b0818.png)


see images uploaded.

**Comment by webfeld** [comment]
I have the same problem, it is not possible to withdraw from staking to metamask

**Comment by MarcusWentz** [comment]
@bendable08 

This error:

> ![image](https://user-images.githubusercontent.com/113498323/234465140-80c938e1-a3bc-4be0-b954-1f15a01b0818.png)

is being investigated in this bug report here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/348
