### ISSUE TITLE
[Duplicate] RPC Error `[ethjs-query] while formatting outputs from RPC "code":-32603, "id":6420567001889, "method":"eth_sendRawTransaction"`

### ISSUE THREAD

**Issue by bcjcrypto** [Shardeum/shardeum-bug-reporting#358]
##### What is the issue?
I am not able to remove stake before/after upgrading node
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?
Not able to remote SHM stake
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 
it is breaking functionality
##### How to reproduce the issue? 
Click on remote stake after connecting wallet ->approval
![Shardeum Node Error](https://user-images.githubusercontent.com/131753491/234213879-6301085d-a5f9-4bc6-a4a7-d0837168e22c.PNG)

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```

    -where the error is seen - On the UI after approving transaction from metamask browser wallet
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by bcjcrypto** [comment]
![Shardeum Node Error 2](https://user-images.githubusercontent.com/131753491/234216259-3aee8850-6f86-4355-ab79-1aeb77814481.PNG)

**Comment by filip709** [comment]
Hello,

same error here. With "Force remove stake" on or off.....

![error](https://user-images.githubusercontent.com/17141169/234217067-5012a291-b4a2-4435-99c2-657058b4b73e.jpg)

**Comment by Velkonost** [comment]
hello
same error
![image](https://user-images.githubusercontent.com/17786225/234267867-1ae856e9-18da-4111-9e97-5a06efccb61a.png)

**Comment by Brave-Humens** [comment]
hello, we have the same problem, but without "force remove stake"
`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":2442461411203,"jsonrpc":"2.0","params":["0xf9013f038501dfd140008401c9c38094000000000000000000000000000000000000000180b8d67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307866333131396664333934326664623961326562646139396462353964313833666131653166646565222c2274696d657374616d70223a313638323435313332333636392c226e6f6d696e6565223a2231643237656131353637616166613239316230353138306238323734353532386438333335346336373138386231333733316536393836386637646461356637222c22666f726365223a66616c73657d823f48a08c8d6f05c43dbd61bf8e003f86b36e2bb537b20c5f21de2d9d0927fdfcae42d0a00d2c5dac1fff2bc6b9cd4a7cce35ece1deac779fb262f34ad429bde465f8bcd2"],"method":"eth_sendRawTransaction"}}}}'`
![image](https://user-images.githubusercontent.com/129593734/234384818-dad2e3d1-2507-4fd5-a169-c6d22ccac0af.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/348
