### ISSUE TITLE
[Duplicate] RPC Error `[ethjs-query] while formatting outputs from RPC "code":-32603, "id":6420567001889, "method":"eth_sendRawTransaction"`

### ISSUE THREAD

**Issue by Ben15111** [Shardeum/shardeum-bug-reporting#359]
I have a problem with adding staking on my nodes. All the time I have errors - I tried to increase gas limit but without results. This situation is a global problem? Attached screen shot from one of my nodes. What I could to do to resolve this problem? 
![image](https://user-images.githubusercontent.com/114851627/234638060-b261626a-1cff-4122-9e02-2f6b9753978c.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/348
