### ISSUE TITLE
Validator Downloading and Installing Dial TCP I/O Timeout 

### ISSUE THREAD

**Issue by ScalperhuBhai** [Shardeum/shardeum-bug-reporting#36]
Getting Error while installing Validator node from the codes (The first code on Step 2)

```shell
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: registry.gitlab.com/shardeum/server:latest: 
failed to do request: Head "https://registry.gitlab.com/v2/shardeum/server/manifests/latest": dial tcp
35.227.35.254:443: i/o timeout
```

**Comment by MarcusWentz** [comment]
Were you able to get around the timeout after a few tries? 

What operating system are you on? 

Are you using curl to download and install with this command:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

from 

https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

?

**Comment by ScalperhuBhai** [comment]
i am trying from yesterday , i thought it  was some code problem from the Devs , but still today its showing the same error dont know wheres the problem i have tried many times , coping the code  and pasting it correctly 
 I am using UBUNTU 22.04 on a vps 8gb ram 4core 

yes i am using curl to download it showed me agian the same error

**Comment by ScalperhuBhai** [comment]
And also tell codes to start Docker Daemon  i will try code on my windows ,  but my main motive to run on my VPS which i am using and getting error

**Comment by ScalperhuBhai** [comment]
![shardeum nodes problem solved](https://user-images.githubusercontent.com/107799534/216831975-bd05f916-a7d7-4e57-8b03-759a8070bba5.PNG)

Ok i found out something , 
Installed Ubuntu on Windows then  tried to Setup the nodes and it gave me no error while installing 
Ubuntu version 20.04 
Added docker to the group , codes area 
sudo groupadd docker
sudo gpasswd -a ${USER} docker
sudo service docker restart
sudo service docker start

after this  the codes started working but when i tried this on UBUNTU 22.04 its not working , ON VPS i have already tested 2nodes of other companies they worked good i think theres something problem with the codes ,

**Comment by Timatu1232** [comment]
help me

**Comment by Timatu1232** [comment]
fatal: destination path '/root/.shardeum' already exists and is not an empty directory.

**Comment by MarcusWentz** [comment]
@Timatu1232 

Please open another bug report this seems like a different issue.

**Comment by Timatu1232** [comment]
failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: permission denied: unknown

**Comment by MarcusWentz** [comment]
@Timatu1232

Please open another bug report for these issues.

**Comment by ScalperhuBhai** [comment]
![now error in docker io](https://user-images.githubusercontent.com/107799534/216838260-c8058f5c-d7db-42f8-8628-f2a0124a219f.PNG)
 tried uninstalling Docker  now getting error how to solve this

**Comment by MarcusWentz** [comment]
How are you trying to uninstall docker?

Did you try this Ubuntu guide:

https://askubuntu.com/a/1021506

?

**Comment by ScalperhuBhai** [comment]
Re-installed Ubuntu many times still facing the same problem, can u join me for a screen video call tomorrow on Shardeum discord channel? I will show you what's the problem while installing in a fresh Ubuntu Os

**Comment by MarcusWentz** [comment]
This containerd.io conflicts seem related to this issue that is open:

https://github.com/moby/moby/issues/38185

**Comment by ScalperhuBhai** [comment]
Where can I send you the video i have recorded?? While setting up the node in a fresh Ubuntu Os

**Comment by MarcusWentz** [comment]
Is the containerd.io on Windows?

Please confirm first.

You can share a YouTube video link.

**Comment by ScalperhuBhai** [comment]
All problems are in Linux  Vps ( Pq hosting ) 80gb SSD 8gb ram 4core cpu  only ip4 supported 

Here's my video watch in 720p 2x and see the error is now :- Client timeout exceed while  waiting for headers 

https://youtu.be/ZFhsSJ88q9U

**Comment by MarcusWentz** [comment]
Check your firewall: 

https://github.com/kubernetes/dashboard/issues/3789  

Do you have ports 9001 and 100001 open: 

https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator 

?

**Comment by MarcusWentz** [comment]
Please open a new issue for:

```shell
Client timeout exceed while waiting for headers 
```

since the original issue is looks fixed now.

**Comment by scorpion141** [comment]
Hello i have the SAme Problem but on this Closed Issues there is no Solution to fix it.

**Comment by MarcusWentz** [comment]
@scorpion141 

Did you try this:

https://github.com/Shardeum/shardeum-bug-reporting/issues/36#issuecomment-1419645794

?

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.
