### ISSUE TITLE
[Duplicate] RPC Error `[ethjs-query] while formatting outputs from RPC "code":-32603, "id":6420567001889, "method":"eth_sendRawTransaction"`

### ISSUE THREAD

**Issue by drifter728** [Shardeum/shardeum-bug-reporting#361]
cant deploy a contract on sphinx network. ethjs qeury error
cant mint erc 721 nft

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/348
