### ISSUE TITLE
Validator Version 1.2.0 Cannot Start Validator and GUI Becomes Blank After Trying To Start Validator

### ISSUE THREAD

**Issue by Jamarox** [Shardeum/shardeum-bug-reporting#367]
After update, I can't start node and I can't stake - start button doesn't work, no stake buttons. There was no such problem before in previous CLI versions. When I click 'start node' button, it changes to 'loading' and after few seconds is going back to 'start node' state. It is impossible to stake, because it is no stake buttons.
![image](https://user-images.githubusercontent.com/126200428/236146731-9956d563-26b0-412b-86fd-f973767cfa7c.png)
![image](https://user-images.githubusercontent.com/126200428/236146778-3f8c5e62-a107-47c7-bef9-64efd4ab9174.png)

**Comment by Jamarox** [comment]
I have removed all: validator, containers and images. Next I installed everything from start, but I was not a solution. Still, I can't start node.
When I try to start with command operator-cli start, it also doesn't work, but after this I see in gui an additional message:
![image](https://user-images.githubusercontent.com/126200428/236331851-5abcb9cd-2f73-4e69-85ff-cb08a1eccf3f.png)

**Comment by MarcusWentz** [comment]
Did you configure your router to have TCP p2p ports 9001 and 10001 open?
Example:
https://www.att.com/support/article/u-verse-high-speed-internet/KM1010280/
Reference:
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

**Comment by Jamarox** [comment]
Nothing changed in my router and other system features, I have the same IP addresses and other rules, previous node versions worked properly from a longer time, I could start and stop the node without any problem from the command line and from the GUI. Of course, I have p2p ports 9001 and 10001 opened.
I see, that I am not the only one with this problem - watch Discord.

**Comment by MarcusWentz** [comment]
What router do you have?

Please double check your router port forwarding settings, 
since I had this issue with my ports in my router (even though I didn't have this issue with older validator versions).

**Comment by Jamarox** [comment]
> What router do you have?
> 
> Please double check your router port forwarding settings, since I had this issue with my ports in my router (even though I didn't have this issue with older validator versions).

I have Stormshield. Here is a screen from the morning showing traffic on ports:
![image](https://user-images.githubusercontent.com/126200428/236524956-24a9b3f7-e726-45f1-9209-ee5f692f79c4.png)

**Comment by Jamarox** [comment]
> What router do you have?
> 
> Please double check your router port forwarding settings, since I had this issue with my ports in my router (even though I didn't have this issue with older validator versions).

Here is more information from today. There is not outgoing traffic on port 10001.
![image](https://user-images.githubusercontent.com/126200428/236603351-5e044b1a-c747-4f50-8c93-ec89df604480.png)
![image](https://user-images.githubusercontent.com/126200428/236603370-0f980bc1-86cb-411d-8188-5bbf2b4b0a63.png)

**Comment by madmerr** [comment]
v 1.2.2 
Trying to stake SHM, but after pressing Start Node GUI becomes blank and I can do nothing with this...

**Comment by Jamarox** [comment]
The behavior of the GUI is completely different if I use 'operator-cli start' from command line. Then there is no 'start node' button and appears 'add stake' button. When I click 'add stake', GUI tabs are going blank, and I must use 'operator-cli stop' from command line, to bring GUI alive. When I want to start node without using command line, just from GUI, there is no 'add stake' button, clicking 'start node' doesn't work. 
When I leave GUI started for a few hours, all tabs except 'alert info' and 'settings' are going blank.
Below is the error after using the command 'operator-cli status':

AxiosError: timeout of 2000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2781:16)
    at RedirectableRequest.emit (node:events:390:28)
    at Timeout.<anonymous> (/home/node/app/cli/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 2000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://94.75.103.170:9001/nodeinfo',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/nodeinfo',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '94.75.103.170',
      port: '9001',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/nodeinfo'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /nodeinfo HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 94.75.103.170:9001\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/nodeinfo',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '94.75.103.170',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://94.75.103.170:9001/nodeinfo',
    _timeout: null,
    [Symbol(kCapture)]: false
  }
}
/home/node/app/cli/build/src/utils/fetch-network-data.js:141
        throw new Error('Node not active in the network. Unable to fetch node-info');
              ^

Error: Node not active in the network. Unable to fetch node-info
    at fetchNodeInfo (/home/node/app/cli/build/src/utils/fetch-network-data.js:141:15)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async /home/node/app/cli/build/src/node-commands.js:205:34

**Comment by shaheenwork** [comment]
I am having exactly the same issue. The only difference is, I am running in a VPS. Tried several times but still not able to fix it

**Comment by Jamarox** [comment]
@MarcusWentz Should I wait for new version of Validator?

**Comment by bjuanico** [comment]
Im having the same issue, i even spun up a new VM on a different IP Address with a fresh linux installation and i still have the same problem. 1TB SDD - 24 cores - 32gb ram

Firewall is configured OK. ( PFSense, even showing traffic on the rules from when it was working) 

I was able to unstake/stake using the CLI but i cannot start the validator.

operator-cli status gives the following output:
https://gist.github.com/bjuanico/2c9453faee3cdaa72eb6b81a150d7b94

**Comment by bjuanico** [comment]
Thanks for linking that issue, apparently the problem was caused because the validator is trying to retrieve info using its own PUBLIC IP, this wont work on some routers if you are behind a NAT.

I was able to make it work changing this on  /home/node/app/cli/build/src/utils/fetch-network-data.js

LINE 141:
    const url = `http://${config.server.ip.externalIp.replace('auto', '127.0.0.1')}:${config.server.ip.externalPort}/nodeinfo`;
to
   const url = `http://localhost:9001/nodeinfo`;

I made similar changes on lines 119 and 127

**Comment by Jamarox** [comment]
@MarcusWentz There is a new validator, but the problem remains. I still can't start validator with the same effect. I think @bjuanico is right that the problem is about retrieving information using my own PUBLIC IP. @bjuanico could you help me with changing lines in JS file? I can't find fetch-network-data.js in my system.

**Comment by bjuanico** [comment]
Yes! lots of people were asking so i made a tutorial! 
https://blog.blockmagnates.com/how-to-fix-black-screen-on-shardeum-validator-a183b17c017e

**Comment by Jamarox** [comment]
@bjuanico Thank you very much, now my node works again !!!

**Comment by shaheenwork** [comment]
@bjuanico 

Thanks for the tutorial. I followed it and unfortunately, my issue is not fixed. I am running node on Contabo VPS.

after making the changes, 'operator-cli status' gives:

AxiosError: timeout of 2000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2781:16)
    at RedirectableRequest.emit (node:events:390:28)
    at Timeout.<anonymous> (/home/node/app/cli/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 2000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://158.220.106.22:9001/nodeinfo',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/nodeinfo',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '158.220.106.22',
      port: '9001',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/nodeinfo'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /nodeinfo HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 158.220.106.22:9001\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/nodeinfo',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '158.220.106.22',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://158.220.106.22:9001/nodeinfo',
    _timeout: null,
    [Symbol(kCapture)]: false
  }
}
/home/node/app/cli/build/src/utils/fetch-network-data.js:141
        throw new Error('Node not active in the network. Unable to fetch node-info');
              ^

Error: Node not active in the network. Unable to fetch node-info
    at fetchNodeInfo (/home/node/app/cli/build/src/utils/fetch-network-data.js:141:15)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async /home/node/app/cli/build/src/node-commands.js:205:34


Can you please help

**Comment by bjuanico** [comment]
Can you please provide your line 141 of the /home/node/app/cli/build/src/utils/fetch-network-data.js script

**Comment by shaheenwork** [comment]
<img width="701" alt="image" src="https://github.com/Shardeum/shardeum-bug-reporting/assets/96775506/9c3a965c-600c-441f-ae28-55bac4961717">


Please see the screenshot

**Comment by bjuanico** [comment]
@shaheenwork  You need to change your public IP in the file (158.220.106.22) for 127.0.0.1
It should look like this:

![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/5189959/f3197f45-722d-4ef7-8e6e-486c37127391)


Let me know if it works

**Comment by shaheenwork** [comment]
It worked!

Thank you so much @bjuanico
