### ISSUE TITLE
Validator Update Issue?

### ISSUE THREAD

**Issue by defiCosmos** [Shardeum/shardeum-bug-reporting#371]
I have discovered that in order for me to install / update the Shardeum Node, I have to use this:

Install validator

First Run:```sudo chmod +x /usr/local/bin/docker-compose```

Install: ```curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh```

This is not in the documentation anywhere, I discovered this resolution on my own.

If I don not use this, the first question gets denied if I press Y/n. I press Y and permission is denied. 

I am running a VPS with: OS: Ubuntu 20.04 (64 Bit)

**Comment by Coollaitar** [comment]
So we have to update this in the `docs` write??
