### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shuaibwasifkhan** [Shardeum/shardeum-bug-reporting#372]
![image](https://user-images.githubusercontent.com/42069283/236648897-bd4a2e26-44fb-4b32-95a2-5027ba254a17.png)

**Comment by shuaibwasifkhan** [comment]
![image](https://user-images.githubusercontent.com/42069283/236649166-9f67db36-f5fe-4be4-a4f1-302668cde793.png)
not issue gone 
i

**Comment by MarcusWentz** [comment]
The original issue sounds like it resolved itself.
