### ISSUE TITLE
Validator GUI Start Validator Button Does Not Appear

### ISSUE THREAD

**Issue by Boulardos** [Shardeum/shardeum-bug-reporting#375]
<img width="1440" alt="Capture d’écran 2023-05-08 à 18 57 08" src="https://user-images.githubusercontent.com/52192939/236890075-72efb0ee-5b4c-48c7-a5f0-711c890bfd1e.png">

**Comment by MarcusWentz** [comment]
Do you see errors in your web browser console?

**Comment by Boulardos** [comment]
<img width="1440" alt="Capture d’écran 2023-05-09 à 21 41 25" src="https://github.com/Shardeum/shardeum-bug-reporting/assets/52192939/ac725195-9d9a-4a5d-b9fa-c543c509c660">

**Comment by Boulardos** [comment]
I restart drom step2 from doc after a cleanup, so 'start node' button shows up now, but unable to connect neither if i run ' operator-cli start ' from terminal

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
