### ISSUE TITLE
Explorer `Unhandled Runtime Error`

### ISSUE THREAD

**Issue by Sufyanpt** [Shardeum/shardeum-bug-reporting#376]
In spinix Explorer, showing this message at the time searching my address

![IMG_20230509_133130_386.jpg](https://user-images.githubusercontent.com/121370124/237055952-7f0b2ea8-b4ad-4f1f-96d4-653a32643019.jpg)

**Comment by Sufyanpt** [comment]
src/frontend/components/TableComp/Table.tsx (33:16) @ Table

**Comment by Sufyanpt** [comment]
</thead>
  32 | <tbody>
> 33 |   {data.map((row, index) => (
     |        ^
  34 |     <tr key={index}>
  35 |       {columns.map((col) => (
  36 |         <TableBodyItem col={col} row={row} key={col.key} />

**Comment by Sufyanpt** [comment]
Call Stack

renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js (16305:0)
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js (20074:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21587:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (4164:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4277:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27451:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26434:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)

**Comment by Sufyanpt** [comment]
Type error : data is undefined

**Comment by skundu42** [comment]
This issue is resolved now.
