### ISSUE TITLE
Faucet Did Not Send Tokens Betanet 1.2.0

### ISSUE THREAD

**Issue by tbossz** [Shardeum/shardeum-bug-reporting#377]
On requesting for token through every way listed, I got none. But the transaction was successful

**Comment by MarcusWentz** [comment]
What is your wallet address?

**Comment by tbossz** [comment]
0x154C9B3B31c274ED02055C56935C35240A666cD4

**Comment by VincFISCHER** [comment]
Hello, I have claimed on discord and other methods several times (4x) of SHM Faucet but without success... no Liberty 1.X and 2.X tokens appear. However the Sphinxes by the same process appear. I no longer know how. I uninstalled and reinstalled the 2 networks several times.

**Comment by MarcusWentz** [comment]
Betanet 1.3.0 has now been launched with new faucets.
