### ISSUE TITLE
[Duplicate] Validator Install Error `SSL connection timeout`

### ISSUE THREAD

**Issue by sumit6300** [Shardeum/shardeum-bug-reporting#378]
Hi i am sumit, running node since the start and my ip address is https://5.182.36.51:8080/

Last week there was DDos attact on my vps service provider Pq hosting Servers ( attacked on Switzerland VPS)  and my vps is from same location so my vps was impacted.

After the incident issue has been solved and everything is working fine.

so, Today morning i reinstalled OS on VPS and was installing Shardeum validator node.

I have already installed and updated node multiple times and i also handle my friends' nodes so i have good knowledge about commands and installing and using nodes.

While installing shardeum node i got error while installing docker compose ( it is not downloading files at all) tried multiple times but same issue.

Package managers working fine.
Update package managers working well.
Docker installation working well.

While installing Docker Compose i am getting error and its not downloading any files at all.

i have attached screenshot below.
![Screenshot (380)](https://github.com/Shardeum/shardeum-bug-reporting/assets/32560589/98ecbdc0-2636-4020-8a1d-b3ff599b8ea0)

**Comment by sumit6300** [comment]
![Screenshot (382)](https://github.com/Shardeum/shardeum-bug-reporting/assets/32560589/8dceddab-821c-432a-a65c-781a65ebf508)

**Comment by MarcusWentz** [comment]
What OS are you using on your VPS?

**Comment by sumit6300** [comment]
I am using Ubuntu 22.04

![Screenshot (385)](https://github.com/Shardeum/shardeum-bug-reporting/assets/32560589/d7bab358-ede4-47a8-8d0d-e81967015eb3)

**Comment by sumit6300** [comment]
Shardeum team ! can you please check is this issue with me only or all users having the same issue ??

please check and reply

**Comment by MarcusWentz** [comment]
Closing issue since it seems related to:

https://github.com/Shardeum/shardeum-bug-reporting/issues/383

**Comment by sumit6300** [comment]
issue has been solved.

Yesterday i installed node and didnot face any issue .
