### ISSUE TITLE
Validator 1.2.2 Force remove stake and remove stake not working 

### ISSUE THREAD

**Issue by Sufyanpt** [Shardeum/shardeum-bug-reporting#380]
File attached

![IMG_20230511_183924_538.jpg](https://github.com/Shardeum/shardeum-bug-reporting/assets/121370124/231a23b2-eed3-478f-891e-510ddc4d2cce)

**Comment by MarcusWentz** [comment]
Can you transfer SHM between wallets as a test?

**Comment by Sufyanpt** [comment]
Tested.( Both mobile and lap)

Showing 'Insufficient fund'

Later  confirm button enabled for transaction, but transaction failed 

![Screenshot_2023-05-12-09-52-44-80_3ce871bb60cb313382b75690e63e41d0.jpg](https://github.com/Shardeum/shardeum-bug-reporting/assets/121370124/b1667235-b5d1-46e8-bbbe-caa457ae0e85)

**Comment by skundu42** [comment]
This issue should be resolved now
