### ISSUE TITLE
[Duplicate] Validator earning SHM rewards in standby mode

### ISSUE THREAD

**Issue by Jimrish** [Shardeum/shardeum-bug-reporting#381]
My node was changed from standby mode to active earned reward some amount of SHM then node changed its status from active to standby still my earnings increasing. Solve the issue.
![Uploading Screenshot_2023-05-12-06-34-40-278_site.mises.browser.jpg…]()

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/287
