### ISSUE TITLE
Validator Install Error `SSL connection timeout`

### ISSUE THREAD

**Issue by lohith45** [Shardeum/shardeum-bug-reporting#383]
Getting connection timeout error while running below command 
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
![SmartSelect_20230513-202103_Termius](https://github.com/Shardeum/shardeum-bug-reporting/assets/50828565/eacd12f5-72d7-4c86-85d9-459fdd0adad4)

**Comment by MarcusWentz** [comment]
Is this on your local computer or a remote server?

**Comment by MarcusWentz** [comment]
Are you able to download this manually from https://github.com/docker/compose/releases/tag/1.29.2 ?

**Comment by lohith45** [comment]
> Is this on your local computer or a remote server?

I am using remote server

**Comment by lohith45** [comment]
I am using remote server

**Comment by lohith45** [comment]
> Are you able to download this manually from https://github.com/docker/compose/releases/tag/1.29.2 ?

I never tried to download manually

**Comment by lohith45** [comment]
Please fix this ASAP

**Comment by MarcusWentz** [comment]
> > Are you able to download this manually from https://github.com/docker/compose/releases/tag/1.29.2 ?
> 
> I never tried to download manually

Please try to download this manually. Does this work now?

**Comment by lohith45** [comment]
I am running node remotely If I download manually then how this will work

**Comment by MarcusWentz** [comment]
Try to install the docker-compose binaries with this:
```shell
curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
https://dockerlabs.collabnix.com/intermediate/workshop/DockerCompose/How_to_Install_Docker_Compose.html

**Comment by lohith45** [comment]
Thanks its started working
