### ISSUE TITLE
RPC Error Metamask Closes Instantly? 

### ISSUE THREAD

**Issue by Captainwhale009** [Shardeum/shardeum-bug-reporting#385]
##### What is the issue
Hi 
  Iam getting issue with only shadreum RPC .when iam selecting shareum 2.0 in metamask, metamask getting closed automatically.please resolve it if any technical error from tech sides .

**Comment by MarcusWentz** [comment]
I do not see this issue on my end.

Which network is having this issue:
https://docs.shardeum.org/network/endpoints
?

If you have a short video clip of what this issue looks like please share.
