### ISSUE TITLE
Validator Install Error `syntax error near unexpected token 'newline'`

### ISSUE THREAD

**Issue by Divno67** [Shardeum/shardeum-bug-reporting#386]
![Screenshot_20230515-190745~2](https://github.com/Shardeum/shardeum-bug-reporting/assets/133840983/06eff46e-ac8d-4ba5-a489-487503553e68)

When I put the 9th command it shows that problem 

curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh

That's the command

**Comment by MarcusWentz** [comment]
What OS are you running?

**Comment by MarcusWentz** [comment]
Also try running independently:
```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh 
```
then
```shell
chmod +x installer.sh 
```
then
```shell
./installer.sh
```

**Comment by Divno67** [comment]
> Also try running independently:
> 
> ```shell
> curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh 
> ```
> 
> then
> 
> ```shell
> chmod +x installer.sh 
> ```
> 
> then
> 
> ```shell
> ./installer.sh
> ```

**Comment by Divno67** [comment]
Sir same problem...

**Comment by Divno67** [comment]
> What OS are you running?

Ubanto 22.4
