### ISSUE TITLE
Validator Stake Error Betanet 1.3.0

### ISSUE THREAD

**Issue by drifter728** [Shardeum/shardeum-bug-reporting#387]
dashboard cant stake ,application error

**Comment by MarcusWentz** [comment]
Are you able to transfer SHM between wallets as a test?

**Comment by drifter728** [comment]
yes but now i cant unstake tried resetting mm many times very slow,keeps on loading ,i ve some shm in rewards too/

**Comment by drifter728** [comment]
ok unstaked . resetiing mm helps but had to do like 4 times
