### ISSUE TITLE
ERC-20 Tokens Vanish UniswapV2 ```TransferHelper.safeTransferFrom()```

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#39]
##### What is the issue?

Transaction status success while tokens are moved and not sent to any other address.
    
#### What impact does the issue have?

Prevents user from creating UniswapV2 pairs:

With MSG.VALUE and another ERC-20 token:

```solidity
function addLiquidityETH(
    address token,
    uint amountTokenDesired,
    uint amountTokenMin,
    uint amountETHMin,
    address to,
    uint deadline
) external virtual override payable ensure(deadline) returns (uint amountToken, uint amountETH, uint liquidity) {
    (amountToken, amountETH) = _addLiquidity(
        token,
        WETH,
        amountTokenDesired,
        msg.value,
        amountTokenMin,
        amountETHMin
    );
    address pair = UniswapV2Library.pairFor(factory, token, WETH);
    TransferHelper.safeTransferFrom(token, msg.sender, pair, amountToken);
    IWETH(WETH).deposit{value: amountETH}();
    assert(IWETH(WETH).transfer(pair, amountETH));
    liquidity = IUniswapV2Pair(pair).mint(to);
    // refund dust eth, if any
    if (msg.value > amountETH) TransferHelper.safeTransferETH(msg.sender, msg.value - amountETH);
}
```

With an ERC-20 token pair:

```solidity
function addLiquidity(
    address tokenA,
    address tokenB,
    uint amountADesired,
    uint amountBDesired,
    uint amountAMin,
    uint amountBMin,
    address to,
    uint deadline
) external virtual override ensure(deadline) returns (uint amountA, uint amountB, uint liquidity) {
    (amountA, amountB) = _addLiquidity(tokenA, tokenB, amountADesired, amountBDesired, amountAMin, amountBMin);
    address pair = UniswapV2Library.pairFor(factory, tokenA, tokenB);
    TransferHelper.safeTransferFrom(tokenA, msg.sender, pair, amountA);
    TransferHelper.safeTransferFrom(tokenB, msg.sender, pair, amountB);
    liquidity = IUniswapV2Pair(pair).mint(to);
}
```

##### How to reproduce the issue? 

Test contract:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.7;

import "@uniswap/lib/contracts/libraries/TransferHelper.sol";

contract safeTransferFromTester { 

    function testSafeTransferFrom(address token, address to, uint256 amountToken) public{
        TransferHelper.safeTransferFrom(token, msg.sender, to, amountToken);
    }
}
```

##### What other resources can you share regarding this issue?

UniswapV2 UniswapV2Router02 addLiquidityETH:

https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L77-L100

UniswapV2 UniswapV2Router02 addLiquidity:

https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L61-L76

UniswapV2 Library TransferHelper for safeTransferFrom():

https://github.com/Uniswap/solidity-lib/blob/master/contracts/libraries/TransferHelper.sol#L33-L45

**Comment by dexpad-dev** [comment]
Here is the flattened version of the test contract.

//SPDX-License-Identifier: MIT
pragma solidity ^0.6.12;
// helper methods for interacting with ERC20 tokens and sending ETH that do not consistently return true/false
library TransferHelper {
    function safeApprove(
        address token,
        address to,
        uint256 value
    ) internal {
        // bytes4(keccak256(bytes('approve(address,uint256)')));
        (bool success, bytes memory data) = token.call(
            abi.encodeWithSelector(0x095ea7b3, to, value)
        );
        require(
            success && (data.length == 0 || abi.decode(data, (bool))),
            "TransferHelper: APPROVE_FAILED"
        );
    }

    function safeTransfer(
        address token,
        address to,
        uint256 value
    ) internal {
        // bytes4(keccak256(bytes('transfer(address,uint256)')));
        (bool success, bytes memory data) = token.call(
            abi.encodeWithSelector(0xa9059cbb, to, value)
        );
        require(
            success && (data.length == 0 || abi.decode(data, (bool))),
            "TransferHelper: TRANSFER_FAILED"
        );
    }

    function safeTransferFrom(
        address token,
        address from,
        address to,
        uint256 value
    ) internal {
        // bytes4(keccak256(bytes('transferFrom(address,address,uint256)')));
        (bool success, bytes memory data) = token.call(
            abi.encodeWithSelector(0x23b872dd, from, to, value)
        );
        require(
            success && (data.length == 0 || abi.decode(data, (bool))),
            "TransferHelper: TRANSFER_FROM_FAILED"
        );
    }

    function safeTransferETH(address to, uint256 value) internal {
        (bool success, ) = to.call{value: value}(new bytes(0));
        require(success, "TransferHelper: ETH_TRANSFER_FAILED");
    }
}

contract TestForTransfer{
    function transferTokens(address tokenAddress, address receiver, uint256 amount) external {
        TransferHelper.safeTransferFrom(tokenAddress, msg.sender, receiver, amount);
    }
}

**Comment by MarcusWentz** [comment]
We could try to use 

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.18;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract transferTokensToMe {

    function transferTest(address tokenAddress, uint256 amount) public { 
        IERC20(tokenAddress).transferFrom(msg.sender, address(this), amount);
    }

}
```

in UniswapV2 instead for now to try to work around this as a quick fix for now:

https://github.com/Shardeum/shardeum-bug-reporting/issues/22#issuecomment-1416590857

**Comment by MarcusWentz** [comment]
Transactions work in Betanet 1.1 test environment. Error was potentially caused by RPC issues in Betanet 1.0.
