### ISSUE TITLE
Validator Version 1.3.0 GUI Not Showing Time Last Active Or Last Rotation Index

### ISSUE THREAD

**Issue by ksbaskar** [Shardeum/shardeum-bug-reporting#391]
##### What is the issue?
My node was active before some time and earned 9.137 SHM reward. Now my node is in Standby Mode but GUI not showing Time last active and Total time validating: 00:00:00 and Last rotation index shows : 0/0 (pls. refer image.)

```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?
operator-cli status 

node@c80935a33fd3:~/app$ operator-cli status
state: standby
totalTimeRunning: 12733.904
totalTimeValidating: '00:00:00'
lastActive: ''
lastRotationIndex: 0/0
stakeRequirement: '10.0'
nominatorAddress: '0x504d774357cbf3a22dfc1b4ceb5d4fdbdf86da92'
nomineeAddress: d5f693b13796450b73c6054a5ce52db7cb29fd2d0e8884c96b0f65e77193ee72
performance:
  memPercentage: 89.82133188955062
  diskPercentage: 59.50824095285287
  cpuPercentage: 10.89108910891089
currentRewards: '9.3006575'
lockedStake: '10.024'
nodeInfo:
  publicKey: d5f693b13796450b73c6054a5ce52db7cb29fd2d0e8884c96b0f65e77193ee72
  curvePublicKey: 61894ac928d0575417174097428136d3fd3c2493c21be89d86a50b3346f09066
  externalIp: 107.175.202.177
  externalPort: 9001
  internalIp: 107.175.202.177
  internalPort: 10001
  status: null
  appData:
    shardeumVersion: 1.3.0
    minVersion: ''
    activeVersion: ''
    latestVersion: ''
    operatorCLIVersion: 1.2.1
    operatorGUIVersion: 1.2.0

:red_circle: Photos and links related to the error. :red_circle: 
<img width="920" alt="bug" src="https://github.com/Shardeum/shardeum-bug-reporting/assets/6725456/178237ec-a08f-42dc-8cba-7d4e87e4b799">

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
