### ISSUE TITLE
Validator 1.3.1 unstake transaction failed

### ISSUE THREAD

**Issue by Makisblad** [Shardeum/shardeum-bug-reporting#392]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

can't unstake tokens, but i can start updated node without unstake) P.s. i do cleaned my activities in Metamask every timebefro trying to unstake

##### How to reproduce the issue? 

:red_circle: 
try to unstake tokens and get error with this description:  "[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"This nominee node is not found!","data":{"originalError":{"status":400}}}}}'"

##### What other resources can you share regarding this issue?

screenshots are attached
![2023-06-01_10-18-25](https://github.com/Shardeum/shardeum-bug-reporting/assets/108862387/97fda4f7-0142-41ef-a0fc-6eefb8c5c17d)

**Comment by Makisblad** [comment]
also i had other mistakes while i was trying to unstake (add screenshots)
![2023-06-01_10-30-29](https://github.com/Shardeum/shardeum-bug-reporting/assets/108862387/696a80a9-c485-4629-a382-b6509eda2961)
![2023-06-01_10-49-20](https://github.com/Shardeum/shardeum-bug-reporting/assets/108862387/c8d4926b-16d9-49e3-9ff7-518b15e9d63d)

**Comment by alexkirillovtech** [comment]
@MarcusWentz Adding one more case when this error is present
<img width="1118" alt="image" src="https://github.com/Shardeum/shardeum-bug-reporting/assets/51885928/3206529d-393b-468b-882c-22ba658bece6">

As you can see, it can see that I have some tokens staked, but status is Need-stake and Stake address is empty too


CLI/GUI Running Version: 1.2.1 / 1.2.0
CLI/GUI Latest Version: 1.2.1 / 1.2.0
Validator Running Version: 1.4.0
Active Network Version: 1.4.0
Validator Minimum Version: 1.4.0

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
