### ISSUE TITLE
Validator exit with error ,sphinx 1.3.1

### ISSUE THREAD

**Issue by drifter728** [Shardeum/shardeum-bug-reporting#394]
node exited with error ,in new version 1.3.1
![Screenshot 2023-06-02 091348](https://github.com/Shardeum/shardeum-bug-reporting/assets/127377575/9462b559-f1e8-4434-9953-edbc6476bc8c)

**Comment by Yorden** [comment]
My node also stopped by itself on 1.3.1. It's the first time it ever happens. There may be something wrong with the update. I restarted the node and now works again. I suspect the "Enable auto-restart node" function may not be working properly ? I will see what happens next time I am active. Plus, the rewards are now very small.

**Comment by Jzmmm-xikeui** [comment]
This problem appeared in 1.3.0, and it also exists in 1.3.1. The status of the startup node changes to standby, and the status becomes stopped after a short time.

**Comment by Eshanndev** [comment]
this happened to me without an error code in sphinx 1.3.0

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
