### ISSUE TITLE
Validator Cannot stake after 1.3.1 update

### ISSUE THREAD

**Issue by sithiiir** [Shardeum/shardeum-bug-reporting#395]
I cannot stake after updating the node to 1.3.1 version. Also my stake adress(wallet address) is not showing up after connecting the wallet
![Screenshot 2023-06-02 220822](https://github.com/Shardeum/shardeum-bug-reporting/assets/118453240/6ca6be7a-5398-42e7-8028-e1129a79d142)

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
