### ISSUE TITLE
Validator 1.3.1 Wont Start Validating 

### ISSUE THREAD

**Issue by Avinsingh666** [Shardeum/shardeum-bug-reporting#396]
My node will not start, i did several new installs and it will not start. Start button lights up then going to loading then, then goes back to start node. No stake button or connect wallet button. Unsure if this is a isolated issue but it is an issue, my node worked well in the past just this patch it will not start please look into this.  System specs intel xeon 32 core with 96 gb ram and 7 tb ssd, OS Ubuntu 22.10 . Please help!

![node](https://github.com/Shardeum/shardeum-bug-reporting/assets/118027653/71551a76-2d68-4e87-b9e7-6a06ad540b66)
![start](https://github.com/Shardeum/shardeum-bug-reporting/assets/118027653/391c17a6-cb93-46f6-a768-e93fa326506f)
![Loading](https://github.com/Shardeum/shardeum-bug-reporting/assets/118027653/a16492a2-5a67-4983-a36d-01f3a6526039)
![node version](https://github.com/Shardeum/shardeum-bug-reporting/assets/118027653/1c59b555-b30b-4689-9879-3e8a9dffb1b2)

**Comment by Avinsingh666** [comment]
This issue continues with 1.4 no stake button triggered and the node refuses to start.

**Comment by Avinsingh666** [comment]
Still didnt fix the issue 1.5.1 ..

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
