### ISSUE TITLE
Sphinx 1.4 "Internal JSON-RPC error.@

### ISSUE THREAD

**Issue by Makisblad** [Shardeum/shardeum-bug-reporting#397]
##### What is the issue?

Error message after staking operation/
    
#### What impact does the issue have?

Shm have staked, but o recieved error mesaage "Internal JSON-RPC error." Screenshots are attached

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/108862387/50c4a2a3-a77e-4e26-9329-e7206832e40f)

**Comment by skundu42** [comment]
This may happen when the RPC is busy due to other bad node hardware. I will recommend trying again when the Node count is greater than 300. Node count can be viewed on explorer.

The team is working on making the RPC experience better.

**Comment by Makisblad** [comment]
Staking was completed, but i just received this message and thought, that it could be helpful for you))
