### ISSUE TITLE
Requested test SHM tokens on https://faucet-sphinx.shardeum.org/ - Never received it

### ISSUE THREAD

**Issue by scarlet1000** [Shardeum/shardeum-bug-reporting#401]
##### What is the issue?
I requested test SHM . I never received it
:red_circle:  Describe the error in simple terms. :red_circle: 
    
![2023-06-11 (8)](https://github.com/Shardeum/shardeum-bug-reporting/assets/114299166/13fda347-8532-45b5-9394-391da9baaf69)

#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 
My metamask: 0xFB218fF09E4345834f554b8CcbD3742F014ae553
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```I retweeted the tweet like it says at https://faucet-sphinx.shardeum.org/
I waited more than 2 hours. still I have n't received the test SHM tokens. I reported about this problem two months ago. it still has not been fixed yet
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by coolm455** [comment]
How to reset metamask wallet, the balance isn't recognised

**Comment by coolm455** [comment]
Now after faucet command there is showing this message - **coolm455**, your message has been removed: the channel **#🚰・dapp-faucet** is dedicated to commands. You are not allowed to post anything else,  what can I do to fix it.

**Comment by swarna1101** [comment]
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/b7e70b2c-3b04-468c-bb57-aea93f70e0e7)
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/7008c438-8850-45a8-bdf5-e77c6c0e483f)

/faucet address: your address 
use this way
