### ISSUE TITLE
Unable to connect to Shardeum Liberty 2.X from Metamask

### ISSUE THREAD

**Issue by scarlet1000** [Shardeum/shardeum-bug-reporting#402]
##### What is the issue?
Tried connecting to Shardeum Liberty 2.X from Metamask and I am getting the error:
![2023-06-11 (9)](https://github.com/Shardeum/shardeum-bug-reporting/assets/114299166/63bd60f0-ec16-43c0-b3e8-d9a51e61ea4b)

We can't connect to Shardeum Liberty 2.X
:red_circle:  Describe the error in simple terms. :red_circle: 
    Can't connect to Liberty 1.x either
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by skundu42** [comment]
Liberty 2.X is sun setted. We will soon launch a stable Devnet instead.
