### ISSUE TITLE
Tried to deploy a smart contract on Sphinx 1.X and it failed

### ISSUE THREAD

**Issue by scarlet1000** [Shardeum/shardeum-bug-reporting#403]
##### What is the issue?
Tried to deploy a smart contract on Sphinx 1.X and it failed
:red_circle:  Describe the error in simple terms. :red_circle: 
    Your files are stored in indexedDB, 3.01 MB / 142.42 GB used

You can use this terminal to: 
Check transactions details and start debugging.
Execute JavaScript scripts:
 - Input a script directly in the command line interface 
 - Select a Javascript file in the file explorer and then run `remix.execute()` or `remix.exeCurrent()`  in the command line interface  
 - Right click on a JavaScript file in the file explorer and then click `Run` 
The following libraries are accessible:
[web3 version 1.5.2](https://web3js.readthedocs.io/en/1.0/)
[ethers.js](https://docs.ethers.io/) 
remix
Type the library name to see available commands.
creation of MyToken pending...
creation of MyToken errored: transaction execution failed
 
[block:81982 txIndex:1]from: 0xFB2...ae553to: value: 0 weidata: 0x686...c6f21logs: 0hash: 0x634...31c7c
creation of MyToken pending...
creation of MyToken errored: transaction execution failed
 
[block:81996 txIndex:1]from: 0xFB2...ae553to: value: 0 weidata: 0x686...c6f21logs: 0hash: 0xb47...0d0d4
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 
My metamask: 0xFB218fF09E4345834f554b8CcbD3742F014ae553
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by skundu42** [comment]
Thank you for reporting your issues. We are in the process of releasing a stable testnet soon.
