### ISSUE TITLE
Mistake after adding extra shm to stake

### ISSUE THREAD

**Issue by Makisblad** [Shardeum/shardeum-bug-reporting#404]
At first i added 10 shm to stake and today i've added 3 shm more. Now on page [Maintenance](https://31.220.95.183:8080/maintenance) i see, that i've staked 13 shm, but on page [Overview](https://31.220.95.183:8080/) i see 3 shm are staked (photos are attached)
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/108862387/f337b5e7-b948-425f-ab30-2173020ec345)
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/108862387/6c2ef0c4-1194-4420-9498-3cc85d357595)

**Comment by Makisblad** [comment]
and also my earnings are annuled after this action)

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
