### ISSUE TITLE
Validator 1.4 stops itself every day

### ISSUE THREAD

**Issue by Jamarox** [Shardeum/shardeum-bug-reporting#407]
Before 1.4 version, I have never reason to check, if validator works. Once started, worked without interruptions. But now I have to start the node every day. I updated to 1.4 very early (few hours after first information), claimed tokes from faucet, started node and left it as usual. Few days later I discovered, that the node not only didn't work, but also all tokens and staking disappeared from my wallet. Of course, I claimed tokens from faucet again. Why tokens disappeared from my wallet?

**Comment by H3rm44n** [comment]
I have the same problem. My node stops on its own after running for a while. I turn it on several times a day

**Comment by skundu42** [comment]
I have reported this to the team. Thank you for flagging the issue.

**Comment by skundu42** [comment]
This should be resolved with 1.5.1 update
