### ISSUE TITLE
Node always showing "stopped" status

### ISSUE THREAD

**Issue by Blarex** [Shardeum/shardeum-bug-reporting#409]
##### What is the issue?

The validator node always shows the status "stopped", after running for about 15 minutes.
    
#### What impact does the issue have?

Node is not working anymore in status "stopped"

##### How to reproduce the issue? 

Just click on "start node" and it will stop after a short time until you click on start again. 
Error appeared with update 1.4.0

**Comment by skundu42** [comment]
This is resolved now with 1.5.1 update.
