### ISSUE TITLE
No arm64 image support?

### ISSUE THREAD

**Issue by hatvik** [Shardeum/shardeum-bug-reporting#414]
##### What is the issue?

No arm64 image support?
    
#### What impact does the issue have?

Fails to install and start

##### How to reproduce the issue? 

Run installer on arm64 hardware

:red_circle: 
```
Status: Downloaded newer image for registry.gitlab.com/shardeum/server:latest
 ---> 84fdac1ece6d
Step 2/9 : ARG RUNDASHBOARD=y
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
:red_circle:

**Comment by skundu42** [comment]
We don't support ARM yet, but plan to do so in future.
