### ISSUE TITLE
TX Status (Success or Failed)

### ISSUE THREAD

**Issue by GushALKDev** [Shardeum/shardeum-bug-reporting#418]
##### What is the issue?

:red_circle:  The JS response is exactly the same for success TXs than for failed ones. :red_circle: 
    

![photo_2023-07-11 11 10 23](https://github.com/Shardeum/shardeum-bug-reporting/assets/112427468/0e8bc926-456b-4d77-a728-734d407d4d4c)

**Comment by skundu42** [comment]
getTransactionReceipt()  now returns correct status. 1 for successful transactions and 0 for unsuccessful.
