### ISSUE TITLE
Explorer Crashs With ```Unhandled Runtime Error```

### ISSUE THREAD

**Issue by bogachevanton** [Shardeum/shardeum-bug-reporting#42]
##### What is the issue?

    Error when operate with blockchain explorer
    
#### What impact does the issue have?

    Explorer fail
    F5 helps

##### How to reproduce the issue? 

    Click go back button in browser (Chrome - Version 109.0.5414.120 (Official Build) (64-bit))

##### What other resources can you share regarding this issue?

    Screenshots:
    
![image1](https://user-images.githubusercontent.com/90133006/217097602-bb1c8f58-8266-4f67-ac2e-42ab69bdcf39.png)
![image2](https://user-images.githubusercontent.com/90133006/217097611-71bd6f07-3042-4947-9c55-99f7334808c0.png)
![image3](https://user-images.githubusercontent.com/90133006/217097614-67e80e3a-181f-4c24-ae03-f47d6cf71e25.png)

    Logs:
[explorer-sphinx.shardeum.org-1675716697072.log](https://github.com/Shardeum/shardeum-bug-reporting/files/10669490/explorer-sphinx.shardeum.org-1675716697072.log)
[explorer-sphinx.shardeum.org-1675716718568.log](https://github.com/Shardeum/shardeum-bug-reporting/files/10669495/explorer-sphinx.shardeum.org-1675716718568.log)

**Comment by MarcusWentz** [comment]
Did you notice this issue on Betanet 1.1 as well?

**Comment by bogachevanton** [comment]
> Did you notice this issue on Betanet 1.1 as well? 

Yeah, i see it yesterday, same error when click " go back button <--" in Google chrome from wallet tab in explorer

**Comment by MarcusWentz** [comment]
We had a few explorer updates today.

Do you see this issue still after resetting the page and cookies with 

```
Ctrl+Fn+F5
```

?

**Comment by bogachevanton** [comment]
> We had a few explorer updates today.
> 
> Do you see this issue still after resetting the page and cookies with 
> 
> ```
> Ctrl+Fn+F5
> ```
> 
> ?
> 

Give me some time to check it. I'll back later

**Comment by bogachevanton** [comment]
> We had a few explorer updates today.
> 
> Do you see this issue still after resetting the page and cookies with
> 
> ```
> Ctrl+Fn+F5
> ```
> 
> ?

Tested, this bug did not appear anymore

**Comment by MarcusWentz** [comment]
Thank you for confirming @bogachevanton .
