### ISSUE TITLE
RPC eth_getBlockByNumber not supported return tx msg

### ISSUE THREAD

**Issue by Pzzzzzack** [Shardeum/shardeum-bug-reporting#423]
`url: https://dapps.shardeum.org
body: {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x87592",true],"id":1}

response: {
	"jsonrpc": "2.0",
	"id": 1,
	"result": {
		"difficulty": "0x4ea3f27bc",
		"extraData": "0x476574682f4c5649562f76312e302e302f6c696e75782f676f312e342e32",
		"gasLimit": "0x4a817c800",
		"gasUsed": "0x0",
		"hash": "0xa64e769860bf933a6557fe76163342ebec5cd3b033d16d7d2bc4baa41d9c0eef",
		"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
		"miner": "0xbb7b8287f3f0a933474a79eae42cbca977791171",
		"mixHash": "0x4fffe9ae21f1c9e15207b1f472d5bbdd68c9595d461666602f2be20daf5e7843",
		"nonce": "0x689056015818adbe",
		"number": "0x87592",
		"parentHash": "0xdee6a1592bf29098f053eb6f49a4fd2887d0c46ecba9a51855950158b7ef905b",
		"receiptsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
		"size": "0x220",
		"stateRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"timestamp": "0x64bde689",
		"totalDifficulty": "0x78ed983323d",
		"transactions": [],
		"transactionsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"uncles": []
	}
}
`
will this rpc support return tx msg in the mainnet?

**Comment by swarna1101** [comment]
This rpc anyways isn’t supposed to return transaction messages
Pls [check](https://www.quicknode.com/docs/ethereum/eth_getBlockByNumber) for more details.
