### ISSUE TITLE
Send SHM fail

### ISSUE THREAD

**Issue by Pzzzzzack** [Shardeum/shardeum-bug-reporting#424]
I send a transaction with MetaMask and the transaction failed although I have enough SHM.
This is my MetaMask network setting.
<img width="547" alt="image" src="https://github.com/Shardeum/shardeum-bug-reporting/assets/119295368/dab86734-03d5-4190-9f72-178ec2a03e4b">
Transaction Hash is `0x5e5abb648f8b47f8a0016def12604d188ee36eb2b30af4d567ce6793ec965c75`.

**Comment by skundu42** [comment]
This is because of insufficient gas
