### ISSUE TITLE
A Theme Problem

### ISSUE THREAD

**Issue by barisergan** [Shardeum/shardeum-bug-reporting#425]
Hello,
After performing a swap on app.swapped.finance, the message "Transaction submitted" appears. Below this notification there is a button to add the corresponding coin to the wallet (this is a great feature). But there is a minor theme (or variable) issue with the text above the button. Text above the button: "Add {0} to metamask"

**Comment by skundu42** [comment]
This is a Swapped Finance issue. I have reported this to their team.
