### ISSUE TITLE
my dashboard is black how to fix this 

### ISSUE THREAD

**Issue by ahmed159159** [Shardeum/shardeum-bug-reporting#427]
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/111837367/5f025304-e64a-420c-aac7-db060db6334a)
my dashboard is black how to fix this

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/5431346c-f54f-43eb-ac5b-de8185ce0c3e)
