### ISSUE TITLE
Wallet issue 

### ISSUE THREAD

**Issue by HatakeKaq** [Shardeum/shardeum-bug-reporting#428]
Hello I and I think a lot of users have problem with metamask and shardeum network. On the shardeum exploer mz wallet have 33 SHM after used faucet on discord but on wallet is 0 but some times for 10-20 sec I see the correct amount but after this time is 0 again for a long time I tried clear metamask data couple of times and nothing. I wait for amount apear for this 20 sec and try to add stake to the shardeum node and I recive this :

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"Node not ready for inject, waiting for network account data.","data":{"originalError":{"status":500}}}}}'

![shm](https://github.com/Shardeum/shardeum-bug-reporting/assets/85744436/7c6d81e6-a951-4b0d-b68d-f7d3db0f2dc4)

![amount](https://github.com/Shardeum/shardeum-bug-reporting/assets/85744436/6ca5059b-2a2f-410e-abe0-43ff2d39d521)

Do you have some adiveces?

**Comment by swarna1101** [comment]
The validator network is not up right now, so you won't be able to connect to it right now
