### ISSUE TITLE
Decreasing Balance in MM wallet

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#43]
##### What is the issue?

    Since i am running a node i have noticed that the balance in my MM it is decreasing in my wallet.

**Comment by MarcusWentz** [comment]
Please share your system info in this issue open for this issue:

https://github.com/Shardeum/shardeum-bug-reporting/issues/32

**Comment by AndreiW3b3** [comment]
i checked this on both my Mac and Windows Pc and it was the same on both devices

**Comment by AndreiW3b3** [comment]
also tried different browser google chrome and brave

**Comment by MarcusWentz** [comment]
Please continue the conversation in this issue:

#32
