### ISSUE TITLE
Shardeum Dapp Sphinx 1X

### ISSUE THREAD

**Issue by OliverGaneshaBerlin** [Shardeum/shardeum-bug-reporting#432]
<img width="938" alt="Bildschirmfoto 2023-08-20 um 19 24 59" src="https://github.com/Shardeum/shardeum-bug-reporting/assets/142744004/e44a8387-b3b5-4cfa-93f1-06708b31d786">
Tried to Swap SHM to SWPD at Swapped Finance. Did not work. First try with Shardeum. Good start :(

**Comment by swarna1101** [comment]
Can you try again as the network relaunched. Try on Sphinx Dappnet. 



Network Name | Shardeum Sphinx Dapp 1.X
-- | --
New RPC URL | https://dapps.shardeum.org
Chain ID | 8081
