### ISSUE TITLE
Unable to add Shardeum Liberty 2.x to Metamax

### ISSUE THREAD

**Issue by scarlet1000** [Shardeum/shardeum-bug-reporting#436]
##### What is the issue?
I tried to add Liberty 2.x to Metamax through Chainlist.org and I am getting an error message
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?
Unable to create an NFT using spriyo.xyz
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 
Go to chainlist.org and try to add Liberty 2.x to Metamask
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by swarna1101** [comment]
Can you try manually adding with these specs:-



Network Name | Shardeum Sphinx Dapp 1.X
-- | --
New RPC URL | https://dapps.shardeum.org
Chain ID | 8081
Websocket | wss://dapps.shardeum.org
Currency symbol (optional) | SHM
Block Explorer URL (optional) | https://explorer-dapps.shardeum.org
