### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kingzamzam** [Shardeum/shardeum-bug-reporting#445]
<img width="1280" alt="Снимок экрана 2023-09-22 в 2 43 16 PM" src="https://github.com/Shardeum/shardeum-bug-reporting/assets/111081937/64ba5720-90d6-4460-b72b-a52655d7bff0">

**Comment by ivvannnnnnn** [comment]
same situation

**Comment by swarna1101** [comment]
The validator network is not up right now, so you won't be able to connect to it right now
