### ISSUE TITLE
CSP Violation Blocking Wallet Integration on Validator Node GUI Website in Firefox

### ISSUE THREAD

**Issue by Alejandro-MartinG** [Shardeum/shardeum-bug-reporting#446]
##### What is the issue?

Content Security Policy (CSP) blocking resource loading when loading the GUI website for a validator node in Firefox.
    
#### What impact does the issue have?

The bug causes a CSP violation in Firefox when loading the GUI website for a validator node, potentially disrupting the expected functionality and integration of cryptocurrency wallet services. This issue is particularly noticeable when trying to connect with Metamask or WalletConnect through the "Connect Wallet" button.

##### How to reproduce the issue? 

   1. Visit the Validator GUI URL in Firefox.
   2. Here is the CSP violation error.
   3. Click on the "Connect Wallet" button.
   4. Select either "Metamask" or "WalletConnect" from the options.
   5. Happened nothing.

##### What other resources can you share regarding this issue?

<img width="1440" alt="image" src="https://github.com/Shardeum/shardeum-bug-reporting/assets/14140693/4a93c600-0fd4-41dc-b086-1063c277b5ce">

**Comment by JayShayOman** [comment]
Saw this issue too.

![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/114576011/bd1ca3e8-ff41-402d-ba86-d07382b5e6e6)

**Comment by swarna1101** [comment]
This is on update, will be update in the next version
