### ISSUE TITLE
Validator Staking GUI SHM Rewards Decreasing

### ISSUE THREAD

**Issue by ananth55** [Shardeum/shardeum-bug-reporting#45]
##### What is the issue?

Validator rewards decrease over time. 
    
#### What impact does the issue have?

Rewards while staked keep going down. 

##### How to reproduce the issue? 

Run a validator and this will randomly happen. 

##### What other resources can you share regarding this issue?

Shardeum Validator Guide:

https://docs.shardeum.org/node/run/validator

**Comment by MarcusWentz** [comment]
Closing this issue since it does not full the template. 

Please open the issue again which follows the template.

**Comment by MarcusWentz** [comment]
Is this from a local computer or remote server? 

Did you notice this issue on Betanet 1.1 as well? 

What OS is the validator running on?

**Comment by ananth55** [comment]
No I didn't notice it..But Some Issues Not Clear Like this..

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by terminator007x** [comment]
i have the same issue

**Comment by bjcd** [comment]
Same issue here, with the lastest updated validator.

**Comment by madmerr** [comment]
Same issue. Actually it was on 1.1.1 several times, but they were not decreasing, just reseting to 0. And after updating to 1.1.2 it happened again.
![Screenshot_1](https://user-images.githubusercontent.com/115369466/223426750-2966f31c-712e-42fd-878e-66ee5a67627a.png)

**Comment by yashjhade** [comment]
Been running a validator node on Sphinx 1.1.5 for 4 days now, this is what's happening: 

Got active for the first time: 

<img width="1086" alt="Screenshot 2023-03-26 at 9 01 28 PM" src="https://user-images.githubusercontent.com/109554593/228254127-1f02b496-94e9-4b6d-9c69-731704f4d0cc.png">

Was active for ~8 hours, earned 8 SHM and went on Standby 

Got active again 

<img width="1167" alt="Screenshot 2023-03-27 at 4 16 42 PM" src="https://user-images.githubusercontent.com/109554593/228254482-4fb15bb5-01e0-4160-9470-edd7933e89f9.png">

But this time, previous rewards disappeared. 

Became active third time, this time both the previous rewards are not visible. 

<img width="1110" alt="Screenshot 2023-03-28 at 4 53 14 PM" src="https://user-images.githubusercontent.com/109554593/228254853-fa1d5e04-c2de-4156-ad0e-d15473e5c6bd.png">

**Comment by jonathanrolfe** [comment]
this issue is   happening to me - i'm running on windows 10 ( 64) using putty for installation
my node has run on 2 seperate occasions - the first time accruing approx 3 shm - when the second session started it showed just over 2 shm ( from the second session - see screenshot) Now after unstaking to reduce stake this has disappeared too and im back to zero ( second screenshot)
[shardeum screenshots.pdf](https://github.com/Shardeum/shardeum-bug-reporting/files/11151808/shardeum.screenshots.pdf)

**Comment by jonathanrolfe** [comment]
is there anyway this can be recovered?

**Comment by MarcusWentz** [comment]
@jonathanrolfe 

We are investigating this.

**Comment by noel4za** [comment]
same issue.
this morning when my node standby earning is 4.333 SHM and when my node become active again reset 0.

after active again reset to 0 and now earning 1.8
my external ip 158.220.96.100
server ubuntu 20.04

**Comment by swarna1101** [comment]
Extensive monitoring and analysis of validator rewards highlighted a random decrease in rewards while staked. This issue has been identified and resolved in the upcoming network release. The adjustments made will ensure that validator rewards remain stable and do not diminish unexpectedly over time.
