### ISSUE TITLE
SHARDEUM DAPP EXPLORER ISSUE IN METAMASK ANDROID  & SWAPPED.FINANCE

### ISSUE THREAD

**Issue by SalmonXVR** [Shardeum/shardeum-bug-reporting#454]
Dear Shardeum,

I found this issues when I interact with Shardeum.

1. The dApp explorer in Metamask Android Version: when you click the top right three buttons to scroll available content as well as tokens, the window margins cuts off parts of the page content i.e looks like 'home' or/and 'about'?
2. While in app.swapped.finance, a very beautiful bridge indeed, clicking the 'faucet' button brings an error.
3. Allow interaction with many other tokens in Sepolia, Goerli and/or Holesky.
Thank you so much 
![Screenshot_20231122-201450_Firefox](https://github.com/Shardeum/shardeum-bug-reporting/assets/104695019/4ec2e8dd-5734-4c75-b381-405b00554c2c)
![Screenshot_20231122-201900_Firefox](https://github.com/Shardeum/shardeum-bug-reporting/assets/104695019/354f5f55-4e3a-42b6-a83b-243e38c427a2)

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
