### ISSUE TITLE
Betanet 1.X Explorer ERC-20 Tokens Not Visible 

### ISSUE THREAD

**Issue by saurabhburade** [Shardeum/shardeum-bug-reporting#46]
##### What is the issue?

Wallet have 2 ERC20 Tokens deployed but it shows only one ERC20 token on account
    
#### What impact does the issue have?

    - User can't identify their ERC20 balances even if they exist. 
    - Required to fetch balances through RPC to verify.

##### How to reproduce the issue? 

Test contract:

```solidity
pragma solidity ^0.8.0;
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract testToken is ERC20 {
    constructor(
        uint256 initialSupply,
        string memory name,
        string memory symbol
    ) ERC20(name, symbol) {
        _mint(msg.sender, initialSupply);
    }
}
```

##### What other resources can you share regarding this issue?

Wallet already have USDC but USDT balances not reflecting on Explorer.

https://explorer-sphinx.shardeum.org/account/0xc084713c04aa683b6b4a4ddbdfb63f6c5420b085

<img width="367" alt="Screenshot 2023-02-08 at 1 06 05 PM" src="https://user-images.githubusercontent.com/39492927/217464271-e0ea5bb3-944a-41ac-bef2-cb8d56a19886.png">

**Comment by saurabhburade** [comment]
I tried token transfers as well, but no luck with ERC20 balance. However, it shows the token transfers in ERC20 txns.

**Comment by MarcusWentz** [comment]
Is this issue present on Betanet 1.1 with your ERC-20 tokens? 

I have several ERC-20 tokens in my wallet that appear after doing transfers between wallets.

**Comment by MarcusWentz** [comment]
Closing for now since it seems to be working. 

If this issue come back we can open this issue again.

**Comment by MarcusWentz** [comment]
@praveenkump 

Q1. What is your wallet address (in text form)?

Q2. Which ERC-20 tokens did you mint?

Q3. What are the ERC-20 token addresses you are referring to?

Q4. Did you send these tokens between wallets as a test (this should cause the explorer to detect logsBloom filters for ERC-20 functions like 

```solidity
transfer(address recipient, uint256 amount) 
```

and 

```solidity
transferFrom(address sender, address recipient, uint256 amount)
```
