### ISSUE TITLE
0 SHM in MetaMask. And Account not found in Shardeum Explorer.

### ISSUE THREAD

**Issue by baktavirus** [Shardeum/shardeum-bug-reporting#461]
Hello! Firstly, no matter how many tokens I request, I always have 0 SHM in MetaMask. I was dumping my wallet, but it didn't help. 
Secondly, my wallet address is not in the Shardeum Explorer. Writes that the address does not exist
Please tell what i have to do

Shardeum Sphinx 1.X - ![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/128346252/0a41386b-52ba-4e20-9e43-6fc27ca437a1)
Shardeum Liberty 2.X - ![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/128346252/2edeb992-ebd5-45f9-bdef-e9dbe919b646)

![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/128346252/3f64d645-6fa4-4944-9b5e-a77359ebc9c1)
So, I cant stake tokens in my Node Validator

**Comment by baktavirus** [comment]
My address 0xF9e935E83E4D1C452E2dd2aF6726744E4E98d617

**Comment by malcolms73** [comment]
I have exactly the same problem. If anyone can help with this it would be much appreciated

**Comment by swarna1101** [comment]
It is fixed now, and working
