### ISSUE TITLE
Metamask  address not found on network 

### ISSUE THREAD

**Issue by malcolms73** [Shardeum/shardeum-bug-reporting#467]
Hi there. I have a validator node set up to start but don't seem to be able to get any tokens from the various faucet to get started. For some reason my generated metamask address is not resgistering on the shardeum betanet. 

My metamask address is 0x728a98766781048286087414736ef998D74D1873. I keep getting 'an address not found response' when I try to use a variety of faucets or search the address on the block explored

I am connected to Sphinx Validator 1.X chainId 8082

Many thanks for any help you can give.

Cheers Malcolm 

![Shardiun screen shot](https://github.com/Shardeum/shardeum-bug-reporting/assets/42191030/bba2ebef-9327-4665-86f2-93435e1a23a1)

**Comment by swarna1101** [comment]
This is fixed, you can check your address is visible on the explorer, pls try again, if the issue persist, pls reset the network again on metamask
