### ISSUE TITLE
version 1.90. has same error ? 

### ISSUE THREAD

**Issue by yeidy2** [Shardeum/shardeum-bug-reporting#469]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by yeidy2** [comment]
stopped 2 or more node 5

**Comment by swarna1101** [comment]
Not a relevant issue, the node working well and you can do all the functionality
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/4b1c8169-33b4-4a75-8e76-3c82350f44a8)
