### ISSUE TITLE
Validator Install Error ```Client timeout exceed while waiting for headers```

### ISSUE THREAD

**Issue by ScalperhuBhai** [Shardeum/shardeum-bug-reporting#47]
##### What is the issue?

    Describe the error in simple terms. 
    
#### What impact does the issue have?

    Describe if the bug is a visual warning or if it breaks functionality causing a system to fail.

##### How to reproduce the issue? 

    Explain in as much detail as possible to help reproduce the bug:
        -where the error is seen
        -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
        -share code and explain how the code was run

##### What other resources can you share regarding this issue?

    Photos and links related to the error.

**Comment by MarcusWentz** [comment]
@ScalperhuBhai 

Please fill out the template above and share terminal logs

**Comment by MarcusWentz** [comment]
Some ports might need to be edited since it sounds like the DNS settings are blocking blocking the download. 

Try this:

```
If you are behind a router, ensure ports 9001 and 10001 are forwarded (be careful doing this since it will modify your firewall):

https://www.noip.com/support/knowledgebase/general-port-forwarding-guide/

Reference:

https://gitlab.com/shardeum/validator/dashboard/
```

https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

**Comment by MarcusWentz** [comment]
Closing this issue for now since fixing the ports should resolve the issue.

If this didn't solve the issue, please open the bug report again.

If you see another error now, please open another bug report.

Thank you.

**Comment by swarna1101** [comment]
Regarding the validator node issue reported, after comprehensive investigation, it has been identified that the resolution for this particular issue will be included in the subsequent update following the upcoming release.
