### ISSUE TITLE
Node exited with the following message: Fatal: submitJoin: our node was reported to not be reachable by 2 or more nodes 5

### ISSUE THREAD

**Issue by yeidy2** [Shardeum/shardeum-bug-reporting#470]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by yeidy2** [comment]
Node exited with the following message:
Fatal: submitJoin: our node was reported to not be reachable by 2 or more nodes 5

**Comment by yeidy2** [comment]
higher docker compose version

**Comment by tm324462** [comment]
Which version
