### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Marnold49** [Shardeum/shardeum-bug-reporting#471]
When I access the Shardeum server overview is blank. If I click on maintenance I get the following error message: Sorry, something went wrong. Please report this issue to our support team so we can investigate and resolve the problem.

:red_circle:  Describe the error in simple terms. :server not functioning: 
    
#### What impact does the issue have? I cannot see if my node is running

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :visual warning: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -server overview blank, server maintenance page displays error message
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by swarna1101** [comment]
This is not a bug, the node is working fine, and you can add stack and do all the functionality properly
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/5a16983e-ae7d-4208-adbb-670ad403778f)
