### ISSUE TITLE
Unable to connect wallet via UI

### ISSUE THREAD

**Issue by mofouly** [Shardeum/shardeum-bug-reporting#472]
##### What is the issue?

:red_circle:  When going through the maintenance tab and clicking on the connect wallet button, and then selecting metamask or walletconnet nothing happens. :red_circle: 
    
#### What impact does the issue have?

:red_circle: The bug does not have any visual to show a failure, simply does nothing.. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
I can currently re-produce the issue on my node, when looking at the inspect of the page you find the following


Content-Security-Policy: The page’s settings blocked the loading of a resource at wss://relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtvZ010akxxamh4UjEyVDJmR3BqU2RKdVZhUGtXR2YyenB1V29Ibnpad3ROZSIsInN1YiI6IjYyODA0NDE4NTE5Y2E5ZDJmZGNjMTM4ZjJkNzE0YWJiNGY3MzAwYTZiOTgxYmUxNTIzMmU5YjQ0ZTY3ZTQ4OWEiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTcwNjA3MzM0OCwiZXhwIjoxNzA2MTU5NzQ4fQ.uYYxI3V7Dgl3pb9IOmX5z4iLW9hxTd5Xk_PLSh25K00WUFxFae1pN-p2M4Iy_NJ9x5TbU-taoBdSoF33fyUvBw&projectId=shm-dashboard&ua=wc-2%2Fjs-2.9.0%2Fwindows10-firefox-121.0.0%2Fbrowser%3A136.243.239.129%3A8080&useOnCloseEvent=true (“default-src”).


```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
![wallet_connect_error](https://github.com/shardeum/shardeum-bug-reporting/assets/25626947/4c88dc6b-63ef-4678-8710-73c458b88304)

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
