### ISSUE TITLE
Always exited my  node

### ISSUE THREAD

**Issue by ankurtyg1** [Shardeum/shardeum-bug-reporting#473]
My node is being exited always sometime it shows me and error = bogon external ip or sometime it shows 

Error "Unable to access external or internal ports. Please provide proper port access to the external and internal ports of shardeum  (9001 / 10001 are the defaults"
![Uploading Screenshot 2024-01-24 123910.png…]()

**Comment by ankurtyg1** [comment]
<img width="399" alt="Screenshot 2024-01-24 123910" src="https://github.com/shardeum/shardeum-bug-reporting/assets/107622672/840aa5d4-397a-4ba6-87a8-7e5c0d071783">
<img width="392" alt="Screenshot 2024-01-24 130215" src="https://github.com/shardeum/shardeum-bug-reporting/assets/107622672/c441fdb1-34dd-475d-8143-97a535c542f5">

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
