### ISSUE TITLE
Waiting for network all the time and node being exited continously

### ISSUE THREAD

**Issue by Ankittyg1** [Shardeum/shardeum-bug-reporting#474]
My node is not working properly. I even updated my node and despite that, the error is still showing. Also doing continuous manual start and still getting the error, so I reinstalled the node fresh. Even then the same error is showing. So please help me to remove this error. 

I am continuously trying to solve it but I am not able to solve it and this error keeps coming. With this, instead of standing by, and waiting for the network to keep coming continuously, for more than 5 minutes, so how to solve it? I have been running the node for the last one years. But since the last two to three months these errors are troubling me a lot.

Error - Node exited with the following message:
Unable to access external or internal ports. Please provide proper port access to the external and internal ports of Shardeum 
<img width="460" alt="Screenshot 2024-01-24 125638" src="https://github.com/shardeum/shardeum-bug-reporting/assets/113989087/ce87aa9b-93c8-43fc-a7cb-b989edf396d4">
<img width="380" alt="Screenshot 2024-01-24 124044" src="https://github.com/shardeum/shardeum-bug-reporting/assets/113989087/40685acb-f767-4cb5-8977-356638fdfaa2">
<img width="407" alt="Screenshot 2024-01-24 125818" src="https://github.com/shardeum/shardeum-bug-reporting/assets/113989087/1a59238e-52e5-4df5-9918-c412ce8ad02e">
(9001 / 10001 are the defaults)

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
