### ISSUE TITLE
SHM node stopping after 1.9.1 update

### ISSUE THREAD

**Issue by JaR1110** [Shardeum/shardeum-bug-reporting#475]
Dear Shardeum team,

I have been advised by @shuwamrana on Discord to submit bug report here.

I am running a couple of nodes. All was going smoothly. After the last validator update to 1.9.1 my node keeps suddenly stopping with the following message:

_An exception occurred while executing a neon::event::Channel::send callback_

I need to manually restart the node in Dashboard. There is no problem in terminal.

Please let me know if you need any further information. This bug shows near the button for STOP/START node under Maintenance.

Thanks!
JRose1110

**Comment by vinothselvaraj** [comment]
<img width="556" alt="image" src="https://github.com/shardeum/shardeum-bug-reporting/assets/18004747/9e86ce93-1ea1-470c-b510-27c1a40e43f5">

I have also got the same error, image for referance

**Comment by jayaabadi88** [comment]
help hw do we fix this

**Comment by JaR1110** [comment]
I have now installed the new validator version, I will report back if the bug keeps appearing.

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.

**Comment by JaR1110** [comment]
Great, all is fine rn!

Dňa ne 4. 2. 2024, 1:00 swarna1101 ***@***.***> napísal(a):
