### ISSUE TITLE
Exit with error - post updating to 1.9.1

### ISSUE THREAD

**Issue by shady4165** [Shardeum/shardeum-bug-reporting#476]
![Screenshot 2024-01-24 211554](https://github.com/shardeum/shardeum-bug-reporting/assets/122225013/7b9f8d47-da1f-4eed-a0f9-a97b8d3fc519)

hey guys, 

so after updating to 1.9.1 , i kept receiving the attached error ( Sorry, something went wrong. Please report this issue to our support team so we can investigate and resolve the problem. ) 

I waited another day post the new update launch but still nothing , the team on the discord asked to share the error here, 

I have deleted the node and create a new one all together,
thank you for letting me know

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version 1.9.5.
