### ISSUE TITLE
Node can't connect to the network (Error)

### ISSUE THREAD

**Issue by ankurtyg1** [Shardeum/shardeum-bug-reporting#478]
My node still exited by showing this message =  "Unable to access external or internal ports. Please provide proper port access to the external and internal ports of shardeum  (9001 / 10001 are the defaults)"

To resolve this i have open ports from firewall and Router as well but nothing is working.
<img width="390" alt="Screenshot 2024-01-25 152356" src="https://github.com/shardeum/shardeum-bug-reporting/assets/107622672/db3623a7-3315-4fd6-8d56-b251d08cb289">

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version.
