### ISSUE TITLE
Internal JSON-RPC error

### ISSUE THREAD

**Issue by ZozoCrypto** [Shardeum/shardeum-bug-reporting#479]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    Internal JSON-RPC error.
#### What impact does the issue have?
unable to stake
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 
Internal JSON-RPC error.
##### How to reproduce the issue? 
I dont know
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```I installed a node, it worked fine, but unable to stake
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```Internal JSON-RPC error.
:red_circle: 
Internal JSON-RPC error.
##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
Internal JSON-RPC error.

**Comment by ZozoCrypto** [comment]
I hit stake , and then it says Internal JSON-RPC error. in red circle

**Comment by brkgzll39** [comment]
Multiple trip errors are gone

**Comment by brkgzll39** [comment]
Try more than once, the error is fixed

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version.

**Comment by ZozoCrypto** [comment]
Thank you for your response
