### ISSUE TITLE
Validator Staking Transaction Fails With ```32603: Internal error```

### ISSUE THREAD

**Issue by Hanaver** [Shardeum/shardeum-bug-reporting#48]
##### What is the issue?

After installing the validator, I failed to stake SHM:

```javascript
[ethjs-query] while formatting outputs from RPC 
'{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal error"}}}'
```

#### What impact does the issue have?

    Describe if the bug is a visual warning or if it breaks functionality causing a system to fail.

##### How to reproduce the issue? 

    Explain in as much detail as possible to help reproduce the bug:
        -where the error is seen
        -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
        -share code and explain how the code was run

##### What other resources can you share regarding this issue?

Stake SHM To Validator:

https://docs.shardeum.org/node/run/validator#step-9-stake-shm-to-validator

**Comment by MarcusWentz** [comment]
This is most likely due to an RPC issue we are working on. 

@Hanaver 

Please fill out the template so we have more info on the bug.

**Comment by MarcusWentz** [comment]
Working now on Betanet 1.1.
