### ISSUE TITLE
Node exited with the error Node exited with the following message: An exception occurred while executing a `neon::event::Channel::send` callback

### ISSUE THREAD

**Issue by TECHYNODE** [Shardeum/shardeum-bug-reporting#482]
I am running v1.9.2 which I upgraded yesterday and the node exited with the below error 
Node exited with the following message:
An exception occurred while executing a `neon::event::Channel::send` callback

Please note I had the same issue with v1.9.1 as well . Thanks

**Comment by swarna1101** [comment]
This is fixed in `1.9.5` which is launched tofay. Pls check again
