### ISSUE TITLE
The legacy builder is deprecated 

### ISSUE THREAD

**Issue by jurbolg** [Shardeum/shardeum-bug-reporting#483]
Hi I have a problem, there is a solution?
1.9.2 tried to update reinstall
<img width="548" alt="q" src="https://github.com/shardeum/shardeum-bug-reporting/assets/102218062/2ee6f011-8968-44b5-96d2-0e27520b2c08">

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version.
