### ISSUE TITLE
Wrong SHM balance in the wallet

### ISSUE THREAD

**Issue by zioju** [Shardeum/shardeum-bug-reporting#485]
##### What is the issue?

:red_circle:  The balance in my wallet doesn't match with the transactions in the Shardeum Explorer. :red_circle: 
    
#### What impact does the issue have?

:red_circle: If I look at my wallet transaction I'm supposed to have ~15 SHM more in my balance but the total shows a wrong amount :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
I have no idea how to reproduce. What I did is just to ask for additional SHM from the Faucet ... I never seen them in the Wallet but I've just realized now that the transaction is somehow there but the SHM are not available in the balance.

wallet address: 0x604Cf8647d87842c153120C496c3E7568a7BD31f
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: 
![image](https://github.com/shardeum/shardeum-bug-reporting/assets/155679985/5ca5d1eb-9703-4a27-bd3c-49620666f61a)
:red_circle:

**Comment by swarna1101** [comment]
This is fixed in new network launch. Pls reset and check again, I have sent you 1000 tokens as well
