### ISSUE TITLE
It keeps connecting 

### ISSUE THREAD

**Issue by zandrino** [Shardeum/shardeum-bug-reporting#486]
##### What is the issue?
it's not connecting 
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: since i can't connect, i can't do the testnet and can't see if it really works perfectly
##### How to reproduce the issue? 
![shm](https://github.com/shardeum/shardeum-bug-reporting/assets/141105786/7721811f-2077-4fd9-a170-84baab5cf397)

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by swarna1101** [comment]
check now its working fine.
