### ISSUE TITLE
After the update to 1.9.3 version status is still "Waiting-For-Network"

### ISSUE THREAD

**Issue by Jamarox** [Shardeum/shardeum-bug-reporting#487]
##### What is the issue?

:red_circle:  After the update to 1.9.3 version status is still "Waiting-For-Network". :red_circle:

**Comment by Jamarox** [comment]
The node is not working anymore:
![image](https://github.com/shardeum/shardeum-bug-reporting/assets/126200428/257aae0b-49bb-4cd7-a093-f86606016d7b)

**Comment by swarna1101** [comment]
This is fixed in `1.9.5` launch today, pls check again
