### ISSUE TITLE
Something went wrong error message in the dashboard

### ISSUE THREAD

**Issue by martinpagac01** [Shardeum/shardeum-bug-reporting#488]
##### What is the issue?

Error when accessing dashboard after installation. No error code, nothing. No content loaded on overview page. Then error message when clicking on "maintenance".
    
#### What impact does the issue have?

Not possible to change settings.

##### How to reproduce the issue? 

Not sure. Installation went well. No error messages or anything. 

##### What other resources can you share regarding this issue?
<img width="1118" alt="Screenshot 2024-01-28 at 20 53 15" src="https://github.com/shardeum/shardeum-bug-reporting/assets/11560241/251ee775-2026-451a-bb96-8e569378cabe">

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version.
