### ISSUE TITLE
Problem with Dashboard

### ISSUE THREAD

**Issue by TomCasteur** [Shardeum/shardeum-bug-reporting#490]
Hello

I have a problem with the dashboard

![image](https://github.com/shardeum/shardeum-bug-reporting/assets/34270962/4e498c53-470c-4b1e-90ea-dc3614fbffa9)
![2024-01-29 23_19_01-Shardeum Dashboard](https://github.com/shardeum/shardeum-bug-reporting/assets/34270962/4f28b340-5537-4adb-ac12-66c63e3e50df)

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version.
