### ISSUE TITLE
"An exception occurred while executing a `neon::event::Channel::send` callback" 

### ISSUE THREAD

**Issue by Venuraghav** [Shardeum/shardeum-bug-reporting#491]
1.What is the issue

After i updated to new 1.9.4 version...My node was active and validated 4 hrs+    and stopped with the error

 "An exception occurred while executing a `neon::event::Channel::send` callback"

And 5 SHM has been slashed as penalty.

    
2.What impact does the issue have?

Due to this error my node is getting stopped frequently even after I restart the node manytimes

**Comment by swarna1101** [comment]
can you share the logs, from `AllLogs` as a .zip?

**Comment by Venuraghav** [comment]
> can you share the logs, from `AllLogs` as a .zip?

Shared here👇

[allLogs.zip](https://github.com/shardeum/shardeum-bug-reporting/files/14113704/allLogs.zip)

**Comment by swarna1101** [comment]
update to the latest node version its fixed in latest version.
