### ISSUE TITLE
Node Stopped invoke-exit 1.9.4

### ISSUE THREAD

**Issue by weles88** [Shardeum/shardeum-bug-reporting#492]
##### What is the issue?

:red_circle:  Some nodes stopped with message "Node exited with following message: invoke-exit: removed from standby list." :red_circle: 
    
#### What impact does the issue have?

:red_circle: After starting again it works fine (at least for some time) :red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: 
![sh](https://github.com/shardeum/shardeum-bug-reporting/assets/134953353/ad82aeb0-f533-4f8d-a37d-1af68c8c3d1d)
:red_circle:

**Comment by trankil123** [comment]
same pb here invoke-exit: removed from standby list. but exiting cleanly for a restart

**Comment by swarna1101** [comment]
update to the latest node its solved in latest version.
