### ISSUE TITLE
Something went wrong error message in the dashboard

### ISSUE THREAD

**Issue by mizumart** [Shardeum/shardeum-bug-reporting#493]
<img width="1152" alt="スクリーンショット 2024-01-31 5 47 49" src="https://github.com/shardeum/shardeum-bug-reporting/assets/103994229/bb903c46-261b-4fa0-aba7-4121dc673295">

unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)

🔴When staking on the dashboard, Metamask does not start and an error is displayed.🔴
    

🔴 When I logged into my dashboard, I saw that my wallet was staked to another node. If I try to stake again, I will see an error message on my dashboard after pressing the stake button. Metamask did not start. 🔴

🔴 I restarted the server and connected a different wallet, but there was no change. 🔴

CLI/GUI Running Version: 1.2.1 / 1.2.0
CLI/GUI Latest Version: 1.2.1 / 1.2.0
Validator Running Version: 1.9.4
Active Network Version: 1.9.4
Validator Minimum Version: 1.9.4

**Comment by mizumart** [comment]
<img width="1064" alt="スクリーンショット 2024-01-31 6 07 09" src="https://github.com/shardeum/shardeum-bug-reporting/assets/103994229/a09f91b9-fb10-4717-af3c-f97ecbd2120a">

<img width="1075" alt="スクリーンショット 2024-01-31 6 02 03" src="https://github.com/shardeum/shardeum-bug-reporting/assets/103994229/ae4c6370-4f7a-4ef1-9747-136763a7af76">

**Comment by swarna1101** [comment]
update to the latest node version its solved in latest version.

**Comment by mizumart** [comment]
<img width="742" alt="スクリーンショット 2024-02-04 9 08 39" src="https://github.com/shardeum/shardeum-bug-reporting/assets/103994229/12116025-0403-4ef6-8f92-6f571ffc92a9">






<img width="1152" alt="スクリーンショット 2024-02-04 9 06 03" src="https://github.com/shardeum/shardeum-bug-reporting/assets/103994229/bb5267f3-6080-45c0-b92b-f6580f97bbbc">


Thank you for always helping me!! 

CLI/GUI Running Version: 1.2.1 / 1.2.0
CLI/GUI Latest Version: 1.2.1 / 1.2.0
Validator Running Version: 1.9.5
Active Network Version: 1.9.4
Validator Minimum Version: 1.9.5
