### ISSUE TITLE
Node exited with the following message: Unable to access external or internal ports. Please provide proper port access to the external and internal ports of shardeum  (9001 / 10001 are the defaults)

### ISSUE THREAD

**Issue by sultanmaa0** [Shardeum/shardeum-bug-reporting#506]
![image_2024-02-10_151650212](https://github.com/shardeum/shardeum-bug-reporting/assets/136260941/0544abff-5d20-41d4-936a-38a1b21f68e0)

tried everything to open port 9001 and 10001, but i still receive the same issue.

this is when trying to activate the node, waiting to network :
{"nodeInfo":{"publicKey":"cd87adb050b14596ce39336bc2b1e3a900f0c47bb578c8ccb5c81c8235bfb188","curvePublicKey":"1293aee84c84795648ca481c356aab22a6d508587be302abfc7587252851cc78","externalIp":"182.253.126.2","externalPort":9001,"internalIp":"182.253.126.2","internalPort":10001,"status":null,"appData":{"shardeumVersion":"1.9.6","minVersion":"1.9.6","activeVersion":"1.9.4","latestVersion":"1.9.7","operatorCLIVersion":"1.2.1","operatorGUIVersion":"1.2.0"}}}
![image_2024-02-10_151821796](https://github.com/shardeum/shardeum-bug-reporting/assets/136260941/78b262a9-b719-4b02-bf68-847218af5b31)
![image](https://github.com/shardeum/shardeum-bug-reporting/assets/136260941/a86038ba-59a5-459d-aa87-acec64d9d7e2)

**Comment by borisevich-a-v** [comment]
I got the same error (you can see that docker forwards ports and ufw disable)
![image](https://github.com/shardeum/shardeum-bug-reporting/assets/61206636/67700f9b-e5cb-4ff5-ae5a-80af3e060773)

My node's wallet is: 0xd073d8C451fA5556E44aBCadd0537D507641Af61

**Comment by sultanmaa0** [comment]
seems like using windows home wsl cannot forward port
