### ISSUE TITLE
RPC ```debug_traceTransaction``` not supported for Remix IDE transaction debugging 

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#51]
##### What is the issue?

Remix IDE gives the following error when trying to debug a transaction even when it is successful:

```shell
The method "debug_traceTransaction" does not exist / is not available.
```
    
#### What impact does the issue have?

Makes it difficult to debug transactions that: 

```
-failed:
     -figure out why a transaction is failing
-succeeded:
     -review which branch path executed in case states changed in an unexpected way
```

##### How to reproduce the issue? 

Send a transaction through Remix IDE on Liberty 2.X and Betanet 1.1 test environment, then click the 

```shell
Debug
```

button in the Remix IDE terminal once the transaction has been successful or failed.

##### What other resources can you share regarding this issue?

RPC method debug_traceTransaction documentation: 

https://www.quicknode.com/docs/ethereum/debug_traceTransaction

Geth TraceTransaction

https://github.com/multi-geth/multi-geth/blob/master/eth/api_tracer.go#L718-L741

**Comment by swarna1101** [comment]
`debug_traceTransaction` is not currently supported in the current version of the network, it will be added in the coming versions.
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/d7c5471a-4865-41c4-af6f-91cde0e6883a)
