### ISSUE TITLE
Waiting for network or Stand by for many days

### ISSUE THREAD

**Issue by airdrop4cb** [Shardeum/shardeum-bug-reporting#519]
##### What is the issue?
I have been running the node for more than 35+ days, every day I see the same status as waiting for network. 

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?
Though I run the node, I am unable to contribute and share the network space. 

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 
It displays on the screen in maintenance section.

##### How to reproduce the issue? 
start the node, and stake the funds and verify on maintenance screen. 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
![image](https://github.com/shardeum/shardeum-bug-reporting/assets/157122500/6e850892-4100-4150-a2bc-f17e2bf6a26a)

```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by airdrop4cb** [comment]
my staker address: 
0x1aFFC83874BC5E1ba75F6c746e231a8092541f13

**Comment by airdrop4cb** [comment]
it  says standby status now.. let me know how to make it active status..

**Comment by airdrop4cb** [comment]
it is validating now.. thanks!

**Comment by dilox75** [comment]
Hi, how did you do to get the right status?
