### ISSUE TITLE
No have public key

### ISSUE THREAD

**Issue by twinleq** [Shardeum/shardeum-bug-reporting#53]
#52 
![image](https://user-images.githubusercontent.com/49478275/219138188-51c9f7cb-7db6-4d8a-8efc-c01f0ca8c88f.png)
Try reinstall node, try reboot dashbord. But I still get this error
#48 
![image](https://user-images.githubusercontent.com/49478275/219138461-7ef3ec3d-abb0-4f5a-8383-193d745f8ad1.png)
Changed the network, reset the metamax. It doesn't help

**Comment by MarcusWentz** [comment]
Please share your node setup info here to help reproduce this issue: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/54
