### ISSUE TITLE
Validator Nominee Public Key For Staking SHM Not Appearing 

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#54]
##### What is the issue?

Nominee public key does not appear when trying to stake on Betanet 1.1.
    
#### What impact does the issue have?

Makes it difficult to stake. 

##### How to reproduce the issue? 

Run a node on Betanet 1.1 and connect your wallet to the dashboard. 

##### What other resources can you share regarding this issue?

Stake SHM To Validator:

https://docs.shardeum.org/node/run/validator#step-9-stake-shm-to-validator

# :green_circle: Update: 

Bug patch has been added. 

Get the patch by:

1. Run this command in the the Validator CLI:

```shell
exit
```

(you can also close the terminal manually, or press the following keys with the window selected at the same time):

```
Ctrl+D
```

2. Go to the root directory:

```shell
cd
```

3. Install the latest Validator dashboard version:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

**Comment by earningdose** [comment]
yes same problem i'm facing ... tnx fail is also an issue during staking

**Comment by Dwentzart** [comment]
Yep ,me use ubuntu 20 and cant generate pubkey after connect wallet

**Comment by adnanrana39** [comment]
i am facing this problem also, i hope it ll fix soon

**Comment by xaaaaaanny** [comment]
made all like in shardeum dock, grab the tokens before connected metamask to gui. OS: Ubuntu 20.04. Installed node from scratch, but used the same wallet as in sphinx 1.0

**Comment by ruiscoin** [comment]
Have this problem too. I get once the Nominee Public Key, but after it lost after reinstall.

**Comment by Loliamba** [comment]
i have ubuntu 20.04 and have the same problem

**Comment by Vidi-byte** [comment]
Така ж проблема

**Comment by dthanhthai** [comment]
I am facing this problem. My os is Ubuntu 20.04

**Comment by pittpv** [comment]
Ubuntu 20.04. Have this issue. Installed a node according to the instructions. Reset the account in Metamask. Added a new network. Started the node. Tried to stake.

**Comment by Singhtwt1** [comment]
> ##### What is the issue?
> Nominee public key does not appear when trying to stake on Betanet 1.1.
> 
> #### What impact does the issue have?
> Makes it difficult to stake.
> 
> ##### How to reproduce the issue?
> Run a node on Betanet 1.1 and connect your wallet to the dashboard.
> 
> ##### What other resources can you share regarding this issue?
> Stake SHM To Validator:
> 
> https://docs.shardeum.org/node/run/validator#step-9-stake-shm-to-validator

Same problem with my node at OS un

**Comment by Singhtwt1** [comment]
Have this problem too. I get once the Nominee Public Key, but it lost after reinstall. at OS unbantu 22.04

**Comment by rrvelar** [comment]
ubuntu 20.04, its empty after clear installation done.
First of all deleted sphinx from metamask, then added again, then install node according official manual.

**Comment by sadykovdmi** [comment]
The same problem. Ubuntu 20.04. Installing according guide https://docs.shardeum.org/node/run/validator

**Comment by JesCR** [comment]
Ubuntu 20.04LTS, same problem, docker was already instaled, just launch the scripts. Default ports and folders

**Comment by mizovsky2304** [comment]
1 - installation of the node is done successfully
2 - starting the node perfectly
3 - connecting wallet witout any problem 
4 - when trying to do stacking, the public address is not populated automatically in the specified textbox

**Comment by ugurkutuk** [comment]
Description:    Ubuntu 20.04.5 LTS

I installed according to the document. ports are open.
https://docs.shardeum.org/node/run/validator

**Comment by MarcusWentz** [comment]
Patch has been updated. 

Get the patch running:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

**Comment by Nubia-crypto** [comment]
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
Didn't fix the problem!!!!!

**Comment by ANiX5202** [comment]
> # 🟢 Update:
> Bug patch has been added.
> 
> Get the patch by running:
> 
> ```shell
> curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
> ```

Didn't fix

**Comment by MarcusWentz** [comment]
@Nubia-crypto @ANiX5202 

Try this:

Get the patch by:

1. Exiting the Validator CLI:

(close the terminal manually, or press the following keys with the window selected at the same time):

```
Ctrl+D
```

2. Go to the root directory:

```shell
cd
```

3. Install the latest Validator dashboard version:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

**Comment by ANiX5202** [comment]
![Снимок экрана 2023-02-16 001914](https://user-images.githubusercontent.com/125510374/219168731-d8c57403-c713-4b9c-b7a8-7260bd56cc70.jpg)

**Comment by webfeld** [comment]
> @Nubia-crypto @ANiX5202
> 
> Try this:
> # 🟢 Update:
> 
> Get the patch by:
> 
>     1. Exiting the Validator CLI:
> 
> 
> (close the terminal manually, or press the following keys with the window selected at the same time):
> 
> ```
> Ctrl+D
> ```
> 
>     2. Go to the root directory:
> 
> 
> ```shell
> cd
> ```
> 
>     3. Install the latest Validator dashboard version:
> 
> 
> ```shell
> curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
> ```

its work, thanks

**Comment by MarcusWentz** [comment]
@ANiX5202 

Are you able to transfer SHM between wallets or do any other transaction?

**Comment by ANiX5202** [comment]
> @ANiX5202
> 
> Are you able to transfer SHM between wallets or do any other transaction?

i have only one wallet with sphinx 1.x

**Comment by velyar** [comment]
> ![Снимок экрана 2023-02-16 001914](https://user-images.githubusercontent.com/125510374/219168731-d8c57403-c713-4b9c-b7a8-7260bd56cc70.jpg)

I support, the same error when staking, the transaction does not even reach the explorer.

**Comment by ANiX5202** [comment]
one more problem
![Снимок экрана 2023-02-16 003817](https://user-images.githubusercontent.com/125510374/219174255-6b4647c6-b818-445e-8e8b-b349adf666eb.jpg)

**Comment by MarcusWentz** [comment]
@ANiX5202 @velyar 

try sending 1 SHM to:

```solidity
0xc1202e7d42655F23097476f6D48006fE56d38d4f
```

as a test.

**Comment by velyar** [comment]
> @ANiX5202
> 
> Are you able to transfer SHM between wallets or do any other transaction?

Sending tokens from a metamask doesn't work either.

**Comment by ANiX5202** [comment]
> @ANiX5202 @velyar
> 
> try sending 1 SHM to:
> 
> ```solidity
> 0xc1202e7d42655F23097476f6D48006fE56d38d4f
> ```
> 
> as a test.
the same error

**Comment by MarcusWentz** [comment]
> one more problem 

![Снимок экрана 2023-02-16 003817](https://user-images.githubusercontent.com/125510374/219174255-6b4647c6-b818-445e-8e8b-b349adf666eb.jpg)

See:

https://github.com/Shardeum/shardeum-bug-reporting/issues/55

**Comment by MarcusWentz** [comment]
> > @ANiX5202
> > Are you able to transfer SHM between wallets or do any other transaction?
> 
> Sending tokens from a metamask doesn't work either.

Reset your Metamask activity to update the nonce then try again: 

https://metamask.zendesk.com/hc/en-us/articles/360015488891-How-to-reset-an-account

**Comment by ANiX5202** [comment]
> > > @ANiX5202
> > > Are you able to transfer SHM between wallets or do any other transaction?
> > 
> > 
> > Sending tokens from a metamask doesn't work either.
> 
> Reset your Metamask activity to update the nonce:
> 
> https://metamask.zendesk.com/hc/en-us/articles/360015488891-How-to-reset-an-account
> 
> then try again.
![Снимок экрана 2023-02-16 004745](https://user-images.githubusercontent.com/125510374/219176159-7bce2b10-4683-42af-8e1b-fdd2cc0ed0fe.jpg)


Now it's OK. Thanks so much for help!

**Comment by ugurkutuk** [comment]
> # 🟢 Update:
> Bug patch has been added.
> 
> Get the patch by running:
> 
> ```shell
> curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
> ```

problem solved.

**Comment by Nubia-crypto** [comment]
@MarcusWentz  Thanks bro for your help!
