### ISSUE TITLE
Validator Stops With Error ```Could not get seed list from seed node server, connect ENETUNREACH```

### ISSUE THREAD

**Issue by Shekelme** [Shardeum/shardeum-bug-reporting#55]
##### What is the issue?

    My validator is stopping after a while with this error in dashboard:

> Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: connect ENETUNREACH 3.127.57.166:4000

I have faced this problem twice already.    
#### What impact does the issue have?

    I can't run the validator 

##### How to reproduce the issue? 

    Simply start the validator in accordance with docs.shardeum.org, forwsrd the ports (9001 amd 10001) and wait for a while.

##### What other resources can you share regarding this issue?

![image](https://user-images.githubusercontent.com/26449500/219146020-35803b16-bbdb-44ff-82f9-4297515c326b.png)

**Comment by MarcusWentz** [comment]
It's possible the validator is not able to reach the archiver based on its current location. 

Are you able to do a ping or trace route the archiver from that validator?

**Comment by Shekelme** [comment]
Yes.
![image](https://user-images.githubusercontent.com/26449500/219150894-8f001f5e-a275-4dec-b0a2-8f66ff4fdefd.png)

**Comment by Shekelme** [comment]
![image](https://user-images.githubusercontent.com/26449500/219151593-d1395c80-5826-4a47-bff8-98a6d28bdf5a.png)

**Comment by MarcusWentz** [comment]
It looks like most packets are transmitted. 

A few questions:

Q1. Is your validator on a local computer or remote server? 

Q2. What is your estimated internet bandwidth?

Q3. Are you having other network issues?

Q4. What is your current tested bandwidth https://www.google.com/search?client=firefox-b-1-lm&q=google+test+speed ?

**Comment by Shekelme** [comment]
A1. Local PC
A2.

> Testing download speed................................................................................
> Download: 305.36 Mbit/s
> Testing upload speed......................................................................................................
> Upload: 40.97 Mbit/s
A3. I didn't notice anything significant, other applications are working fine.

**Comment by MarcusWentz** [comment]
@ANiX5202

https://github.com/Shardeum/shardeum-bug-reporting/issues/54#issuecomment-1432072371

Please answer the following questions as well:

Q1. Is your validator on a local computer or remote server?

Q2. What is your current tested bandwidth

https://www.google.com/search?client=firefox-b-1-lm&q=google+test+speed

?

Q3. Are you having other network issues?

**Comment by ANiX5202** [comment]
> What is your current tested bandwidth

A1. Remote server Ubuntu 20.04
A2.  Node Name        Upload Speed      Download Speed      Latency
 Speedtest.net    1989.05 Mbps      12111.80 Mbps       0.26 ms

**Comment by ANiX5202** [comment]
> @ANiX5202
> 
> [#54 (comment)](https://github.com/Shardeum/shardeum-bug-reporting/issues/54#issuecomment-1432072371)
> 
> Please answer the following questions as well:
> 
> Q1. Is your validator on a local computer or remote server?
> 
> Q2. What is your current tested bandwidth
> 
> https://www.google.com/search?client=firefox-b-1-lm&q=google+test+speed
> 
> ?
> 
> Q3. Are you having other network issues?

A1. Remote server Ubuntu 20.04
A2.  Node Name        Upload Speed      Download Speed      Latency
 Speedtest.net    1989.05 Mbps      12111.80 Mbps       0.26 ms
A3. I haven't

**Comment by MarcusWentz** [comment]
@Shekelme 

Do you have logs when the validator goes from active to inactive in the CLI and GUI?

https://docs.shardeum.org/node/run/validator#step-6-monitor-validator

@ANiX5202 

Were you able to run a validator in the past?

If so, was the remote server location the same when it was working before?

**Comment by Shekelme** [comment]
BTW my validator was working during Sphinx 1.0.
Not sure how to watch the logs, but here is what it says in CLI:
````
node@8b031bec162e:~/app$ operator-cli status
state: stopped
exitMessage: 'Fatal: Node cannot join with invalid external IP: 0.0.0.0'
exitStatus: Exit with error
performance:
  memPercentage: 56.53958321089468
  diskPercentage: 33.34332108101633
  cpuPercentage: 2.3213194868662135
stakeRequirement: '10.0'
lockedStake: '14.0'
nominatorAddress: '0xf9055a98e7947d4000fe9a2ae30ae3e11b0bf58a'
```

**Comment by chanderpalrathore** [comment]
![image](https://user-images.githubusercontent.com/113320393/219297337-9fe89454-8f31-436e-9885-190fde3b6ba0.png)
Getting same error for me

**Comment by mihauman** [comment]
> ![image](https://user-images.githubusercontent.com/113320393/219297337-9fe89454-8f31-436e-9885-190fde3b6ba0.png) Getting same error for me

I have the same error

**Comment by SOURAV0505** [comment]
I was facing the same issue I tried to reinstall the OS of the VPS  and did all processes again and had to remove the last stakes and stake again ...this worked for me and now it's working fine .

**Comment by Jensnicolaigustavsen** [comment]
alright my node is up and running!

**Comment by mihauman** [comment]
> let me know if you have any problems

ok thx

**Comment by Shekelme** [comment]
@Jensnicolaigustavsen What did you do to make your node work?

**Comment by MarcusWentz** [comment]
@Shekelme 

Is port 4000 open on your system?

I heard someone opened this port and the network timeouts were fixed.

**Comment by Shekelme** [comment]
I have opened it today. Should I restart Shardeum validator somehow?

**Comment by MarcusWentz** [comment]
Try: 

//go into the operator dashboard docker (may be different if you customized install location
cd ~/.shardeum
./shell.sh
//get your node's external IP:
curl https://ipinfo.io/ip
//the returned IP in the format of nnn.nnn.nnn.nnn is your <external IP>
//Set it like this.   use the number above in place of <external IP>
export APP_IP="<external IP>"

**Comment by Shekelme** [comment]
Done already. No positive effect...

**Comment by mihauman** [comment]
> Done already. No positive effect...
You restarted the node after opening the port?

**Comment by mizovsky2304** [comment]
![Capture d’écran 2023-02-16 à 17 00 19](https://user-images.githubusercontent.com/74463073/219429867-c665e4b9-64ee-4bd9-ac2c-e7d174205cc8.png)

I have the same issue...

**Comment by Shekelme** [comment]
@mihauman Restarted the node via web GUI dashboard, and aftere a while I restarted the docker container. But again:
![image](https://user-images.githubusercontent.com/26449500/219430602-bb3732d4-8ec4-4b34-bf7b-a9b390117646.png)
I even opened the port 3001....

**Comment by mihauman** [comment]
[Shekelme](https://github.com/Shekelme)
open port 4000 and 4001 and restart node

**Comment by Shekelme** [comment]
@mihauman No effect, still the same error. But this time, it seems, the node worked for several hours...

**Comment by MarcusWentz** [comment]
You can open port 4000 in Linux with:

```shell
sudo ufw allow 4000
```

https://www.digitalocean.com/community/tutorials/opening-a-port-on-linux

**Comment by Shekelme** [comment]
I can't, since my `ufw` is always inactive.

**Comment by tbros6868** [comment]
How to open ports 4000 and 4001 and then restart the validator:

```shell
sudo apt install ufw
sudo ufw allow 4000
sudo ufw allow 4001
ufw allow ssh
ufw allow 8080
ufw allow https
ufw allow http
ufw allow 443
ufw enable
sudo ufw reload
sudo ufw status
```

**Comment by Shekelme** [comment]
I like this project so much.

**Comment by ShriyanshShukla** [comment]
> 

Not working, getting the same error
![image](https://user-images.githubusercontent.com/121439434/219642220-213bf666-0f79-467a-8bda-c555251fbaf7.png)

**Comment by ShriyanshShukla** [comment]
> open port 4000 and 4001 and restart node sudo apt install ufw sudo ufw allow 4000 sudo ufw allow 4001 ufw allow ssh ufw allow 8080 ufw allow https ufw allow http ufw allow 443 ufw enable sudo ufw reload sudo ufw status

**Comment by MarcusWentz** [comment]
@Shekelme 

We are looking into the archive node to see what might be causing this.

**Comment by mizovsky2304** [comment]
Same issue here...
I think the devs had a lot of work the last three days...
1- public key address
2- seed list: port 4000 problem
3- today: _getSeedNodes
![Capture d’écran 2023-02-17 à 16 48 28](https://user-images.githubusercontent.com/74463073/219701186-612790a4-9eee-4e6e-9a5b-2d26e53d0eae.png)

**Comment by xkemox** [comment]
![IMG_20230218_011551](https://user-images.githubusercontent.com/102267815/219796796-0b3b684f-1ca3-4391-a397-814d992f4332.jpg)
All ports  are open still got the same error.. Anyone manage to fix it?

**Comment by Jensnicolaigustavsen** [comment]
im also getting this error:
![image](https://user-images.githubusercontent.com/62223508/219815070-9f9c0614-f675-41dd-a2e7-5decb4ea8181.png)

**Comment by Jongjh** [comment]
Im facing the same issue - Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms

![image](https://user-images.githubusercontent.com/72982650/219824894-08ea5cc5-7b43-472a-9be9-4d254ad845e9.png)

**Comment by anaderiasoft** [comment]
> Im facing the same issue - Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms
> 
> ![image](https://user-images.githubusercontent.com/72982650/219824894-08ea5cc5-7b43-472a-9be9-4d254ad845e9.png)

yes same "ufw allow 4000" doesnt give any result

**Comment by ostd6212** [comment]
Similar issue
![Screenshot 2023-02-18 at 14 20 42 copy](https://user-images.githubusercontent.com/103498665/219865798-48d6ec66-d478-4594-b70d-cec21bcc0634.png)

**Comment by zodiac55** [comment]
Node exited with following message: Cannot read properties of undefined (reading 'id')

What can be a problem?

**Comment by mihauman** [comment]
Who had a port 4000 error in shardeum
1. sudo nano /etc/ufw/before.rules
 add next row before COMMIT row
2. -A ufw-before-input -p tcp --dport 4000 -j ACCEPT
3. Save the files and close the file.
4. sudo ufw reload

**Comment by Shekelme** [comment]
@mihauman But what if `ufw` is simply disabled?

**Comment by ostd6212** [comment]
![Uploading Screenshot 2023-02-20 at 11.28.59.png…]()

**Comment by mihauman** [comment]
[Shekelme](https://github.com/Shekelme) 
1)sudo ufw status
2)sudo ufw enable
3)sudo nano /etc/ufw/before.rules
4)add next row before COMMIT row:
-A ufw-before-input -p tcp --dport 4000 -j ACCEPT
5)-A ufw-before-input -p tcp --dport 4000 -j ACCEPT
6)sudo ufw reload

**Comment by MarcusWentz** [comment]
It sounds like we have a potential bug fix for this with the latest validator update.

Update your validator with:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

Does this error still occur after the latest validator update?

**Comment by Shekelme** [comment]
@MarcusWentz Unfortunately yes, still the same error:
![image](https://user-images.githubusercontent.com/26449500/220165638-b9f0fc14-f721-42a2-86d4-b5a9a98b603f.png)

**Comment by Heymma** [comment]
Same Error also ![Uploading IMG_20230220_194123_404.jpg …]()

**Comment by ehenry-50** [comment]
I am having the same error-Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms

![](https://cdn.discordapp.com/attachments/1067519725745225758/1077486960253337650/IMG_2805.png)

**Comment by scorpion141** [comment]
I have the Same Error. 



![grafik](https://user-images.githubusercontent.com/89877808/220404811-c93b9ab3-d392-48ad-ab40-fd1d7527b3ad.png)

Ports are open: 

![grafik](https://user-images.githubusercontent.com/89877808/220404979-5e24bb04-3889-4312-b882-fe030dfb0c44.png)

**Comment by Shekelme** [comment]
@scorpion141 It seems that you forgot 9001 and 10001.

**Comment by scorpion141** [comment]
@Shekelme thank you very mutch. 

i opend the Porta now but i get a Link in the Discord to test the IP and the Port and it says closed to me. Maybe its a Problem with the VPS. 

https://www.yougetsignal.com/tools/open-ports/

**Comment by scorpion141** [comment]
Ok i think that is not correct the Page said Port 8080 is closed but i can connect on the Webpage.

**Comment by scorpion141** [comment]
@Shekelme  got the Same Error with the New Ports opend. 

Iam also Try this without a Firewall and i ask the Service Provider if they Blocked Ports but no.

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by Shekelme** [comment]
First of all, there was no ability to unstake prior to update, so the stake went to waste. Second:
![image](https://user-images.githubusercontent.com/26449500/220581505-a127c68f-8f60-4592-8713-b4ab61d2799e.png)
And still

> Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms

**Comment by Kafiirr** [comment]
@MarcusWentz After I update the Validator but ```operator-cli: command not found``` Is it a bug?

**Comment by marcelkb** [comment]
after update to 1.1.1 still same problem of connection timeout on port 4000
(ufw port is allowed)

**Comment by MarcusWentz** [comment]
@Kafiirr 

Manually uninstall the validator:

https://docs.shardeum.org/node/run/validator#uninstall-validator

Then install the validator again: 

https://docs.shardeum.org/node/run/validator#step-1-install-prerequisites

Is this issue still there?

If it is, please open a new bug report for this issue ```operator-cli: command not found```.

**Comment by gigidinizza** [comment]
same as other, updated the validator with fresh install, ports opened, extenal IP done, and still same issue

**Comment by scorpion141** [comment]
@MarcusWentz  Updated Yesterday and the Last 22 Hours i dont get this Error. 

Note Stopped from Time to Time but with no Error. 

But this is only on my Notes.

**Comment by Admiral121** [comment]
Unfortunately, the same as for the others. I have done all the steps above and still get the error

**Comment by gigidinizza** [comment]
well, did it again, erased it all, clean install, opened ports, external ip and somehow, it worked! I guess that's a win, so thanks!

**Comment by Admiral121** [comment]
@gigidinizza congratz. So you just set up a new server? or just uninstalled validator and docker?

**Comment by gigidinizza** [comment]
> @gigidinizza congratz. So you just set up a new server? or just uninstalled validator and docker?

uninstalled validator and docker, same server hosted by pq.

**Comment by Admiral121** [comment]
> > @gigidinizza congratz. So you just set up a new server? or just uninstalled validator and docker?
> 
> uninstalled validator and docker, same server hosted by pq.

Lucky you. In my case even reinstallation of ubuntu and doing everyting step by step again didn't help. Ports openned, Export APP_IP done. Running the latest version of node. Still same error "Could not get seed list from seed node server"

**Comment by Tripmag** [comment]
> 

Same problem... (Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms)

installed UFW
allowed all ports
complete new installation
export current IP
did i forget something...?
VPS Ubuntu 22.04 is from vpsdime.com

**Comment by gitn17** [comment]
in fact docker-compose ports: setting override ufw, so there is no need to open it additionaly.

**Comment by MarcusWentz** [comment]
The original error seems resolved, but there is a new error. 

We can create a new bug report for the new error:

```
Timeout awaiting 'request' for 5000ms
```

**Comment by MarcusWentz** [comment]
The original error seems resolved, but there is a new error.

Bug report tracking for the new timeout issue:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104

**Comment by dquocthang811989** [comment]
help me. Why does my button reset the reward over and over?
![image](https://user-images.githubusercontent.com/116693686/221400496-20708a12-9d9b-40b8-bc46-0229cc025dd4.png)

**Comment by mrdex150** [comment]
Shardeum Developers and team members are donky Fkn Shareum Node. Please stop this failed project a node cant run how you will run a blockchain are your network Secure?
