### ISSUE TITLE
[Duplicated] Validator Staked Wallet Has SHM Balance Decrease In 0.01 SHM Increments Over Time

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#56]
##### What is the issue?

    It seems we still have the bug we had before the update.
    
#### What impact does the issue have?

Reduces balance in metamask

**Comment by MarcusWentz** [comment]
Closing duplicate issue and moving discuss to: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/32

**Comment by AndreiW3b3** [comment]
Hello, i just noticed the balance in my metamask decreasing again.
