### ISSUE TITLE
Validator ```Add Stake``` And ```Stake``` GUI Buttons Not Responding

### ISSUE THREAD

**Issue by MOTOR92** [Shardeum/shardeum-bug-reporting#58]
##### What is the problem?

There is no stake button on the validator dashboard.  

Instead, there is a button to change the network.

Changing the network manually in the Metamask and then reloading the page does not help.
    
#### What is the impact of the problem?

This error does not allow a bid to be made, which is a critical error for the operation of the validator.

##### How to reproduce the problem? 

The error is detected in the dashboard. Validator was installed earlier, so a file cleanup was done 

```shell
cd ~/.shardeum
./cleanup.sh
cd ~/
rm -rf .shardeum
rm installer.sh
```

The following is the installation: 

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

##### What other resources can you share regarding this issue?
![2023-02-16_10-11-32](https://user-images.githubusercontent.com/88778695/219280998-26b2bfb0-5861-412b-aeae-d72f5055572a.png)
![2023-02-16_10-44-38](https://user-images.githubusercontent.com/88778695/219281015-b30433a6-308c-4309-9b50-c41ecdec5dde.png)

**Comment by MarcusWentz** [comment]
What do you see when you delete all Shardeum networks, then add Betanet 1.X here:

https://docs.shardeum.org/network/endpoints#connect-wallet

?

Does anything change when you refresh the page now with 

```
Ctrl+R
```

? 

Does resetting your cookies and site data for this page help:

```
Ctrl+Fn+F5
```

?

**Comment by MarcusWentz** [comment]
What do you see in the web browser console when you click the ```Switch Network``` and ```Add Stake``` buttons?  

https://balsamiq.com/support/faqs/browserconsole/ . What do you see in the console?

**Comment by Igorymba** [comment]
![image](https://user-images.githubusercontent.com/124623039/219470989-759a86b5-9b17-4813-99ed-cdf97796bdae.png)
![image](https://user-images.githubusercontent.com/124623039/219471054-e865c4ca-542c-4939-aa70-6483066e9d9c.png)

**Comment by Igorymba** [comment]
![image](https://user-images.githubusercontent.com/124623039/219471284-41e096d9-30ae-4469-b55e-366f99f13999.png)

**Comment by MarcusWentz** [comment]
@Igorymba 

Sent an update:

Able to stake with Metamask (originally used the Trust Wallet, which has issues in general on Shardeum).

Bitkeep and Brave Wallets should work as well.

**Comment by MarcusWentz** [comment]
@MOTOR92 

What wallet are you using when trying to stake SHM in the validator GUI?

**Comment by AndrewFucher** [comment]
Error
![image](https://user-images.githubusercontent.com/17062829/219479949-13bd2a97-0517-4d57-a8dc-82719ea842f3.png)

is produced when connecting metamask wallet via phone app and **not** extension.

**Comment by MarcusWentz** [comment]
@AndrewFucher

Are you on Android or iOS with the Metamask Wallet App?

Which Metamask Wallet App are you using (please update to the latest version)? 

Are you able to stake with the Metamask web browser extension while we look into the Metamask Wallet App?

**Comment by AndrewFucher** [comment]
@MarcusWentz

I am on Android. Metamask Wallet App is up to date.

I can add SHM to stake with extension. Though I cannot add new SHM to stake neither via Metamask wallet extension not via Android App.

With extension I continuously get error 
![image](https://user-images.githubusercontent.com/17062829/219485111-fc0a2fcb-6808-4a25-8915-605f491fed42.png)

**Comment by MOTOR92** [comment]
@MarcusWentz 
Thanks Marcus, I cleared the cookies and it worked.

**Comment by MarcusWentz** [comment]
@AndrewFucher 

Are you able to transfer SHM between wallets on the Metamask web browser extension?

If not, your Metamask wallet has an outdated nonce value from Betanet 1.0. 
You can reset your Metamask activity to update your wallet address nonce here: 

https://metamask.zendesk.com/hc/en-us/articles/360015488891-How-to-reset-an-account

**Comment by AndrewFucher** [comment]
@MarcusWentz

I no longer see any problem. I did reset account right after an announcement and there was an error. Now I tried again sending between accounts and adding new SHM to staking and it worked fine. So I have no problems right now

**Comment by Igorymba** [comment]
WHY IS IT CLOSED?

[image: image.png]


вс, 19 февр. 2023 г. в 21:36, Marcus Wentz ***@***.***>:

**Comment by MarcusWentz** [comment]
@Igorymba 

Are you still facing the issue?

I thought you mentioned on Discord the issue was fixed: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/58#issuecomment-1433671831

**Comment by MarcusWentz** [comment]
@Igorymba 

Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.
