### ISSUE TITLE
Explorer Not Showing Transaction Method Names

### ISSUE THREAD

**Issue by iragsraghu** [Shardeum/shardeum-bug-reporting#59]
##### Shardeum Sphinx Chain

```
As we are integrating the Shardeum Sphinx Chain, we are not able to find the logic to get the methods like 
[Stake, Transfer],attached file will give you the picture of those methods
```
1. [Explorer](https://explorer-sphinx.shardeum.org/account/0x69e2f102e9d042a0c6b03beaa798f13b764b47b8)
2. [Explorer API](https://explorer-sphinx.shardeum.org/api/transaction?address=0x69e2f102e9d042a0c6b03beaa798f13b764b47b8&page=1&txType=0)

<img width="1387" alt="Screenshot 2023-02-16 at 2 04 17 PM" src="https://user-images.githubusercontent.com/100752246/219311125-8f52b026-cede-444e-8780-13799bf46862.png">

**Comment by MarcusWentz** [comment]
We had a few explorer updates from today.

Do you see this issue still after resetting the page and cookies with 

```
Ctrl+Fn+F5
```

?

**Comment by MarcusWentz** [comment]
If the issue still exists, 
reopen the issue with a specific transaction hash that is supposed to show a function name in the explorer.

**Comment by iragsraghu** [comment]
1. [Explorer](https://explorer-sphinx.shardeum.org/account/0x69e2f102e9d042a0c6b03beaa798f13b764b47b8) - @MarcusWentz  - we can get the methods from this explorer
2. [Explorer API](https://explorer-sphinx.shardeum.org/api/transaction?address=0x69e2f102e9d042a0c6b03beaa798f13b764b47b8&page=1&txType=0) - but we are not getting method from this API
