### ISSUE TITLE
pending assets

### ISSUE THREAD

**Issue by Legolasariamila19** [Shardeum/shardeum-bug-reporting#6]
![pending](https://user-images.githubusercontent.com/113190337/201046830-ad5081be-707c-4445-bca6-09fce6c840f8.jpg)

I can't fix the issue of pending transaction. Tried cancelling, speeding it up, but nothing works. I know een new contract with the same node etc.. would make it go away, but it won't.

Too bad but I did my best.

**Comment by MarcusWentz** [comment]
Please use another wallet until the transaction is accepted or reverted.

Generally, you can increase the gas price at that same account address nonce to incentive miners/validators to mine your transaction based on increased transactions fees (MEV), However, Shardeum has no mempool, so transactions are validated based on the earliest timestamp (and then ID if two transactions are submitted at the same time). 

Please use the following format when opening an issue: 
https://github.com/Shardeum/shardeum-bug-reporting#format-bug-report

**Comment by MarcusWentz** [comment]
Did you try resetting your wallet in Metamask?
This will reset the nonce value in the Metamask wallet activity locally.

**Comment by MarcusWentz** [comment]
Did you try resetting your wallet in Metamask?
This will reset the nonce value in the Metamask wallet activity locally. 

This worked for me with my stuck transactions on Liberty 1.6.
Please reopen the issue if the error stays after resetting your Metamask.

**Comment by Legolasariamila19** [comment]
I did reïnstall but I think that everything is offline. Can't mint the NFT again and neither swapping. Thanks and I'll try tomorrow again. :)
