### ISSUE TITLE
Faucet Discord SHM Request Fails ```Requested 5 times```

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#61]
##### What is the issue?

    every day when i try to claim faucet on discord i get this reply that i already claimed 5 times

**Comment by MarcusWentz** [comment]
Please follow the format for bug reporting with all fields filled so we can reproduce and test the issue.

**Comment by MarcusWentz** [comment]
We have increased the faucet wallet limit to 10 times for now. 

If the issue comes back after the next few hours please open this issue again.

**Comment by AndreiW3b3** [comment]
thx for the update.

**Comment by AndreiW3b3** [comment]
can you guys increase it agin? i have reached 10 faucets and i can not claim anymore. ty

**Comment by MarcusWentz** [comment]
@AndreiW3b3 

Does this faucet work as well:

https://chaindrop.org/?chainid=8082&token=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

?

**Comment by AndreiW3b3** [comment]
chaindrop does not work atm. after i press request it is just loading

**Comment by AndreiW3b3** [comment]
i managed to get with this https://faucet-sphinx.shardeum.org/?_ga=2.32624890.595527845.1676483422-432795400.1675530484
 but it is not working all the time

**Comment by AndreiW3b3** [comment]
i can not get any faucets now . on the one you shared it says this  Error SENDTXN_ERR
the twitter faucet does not work
on discord it says i reached 10 requests

**Comment by MarcusWentz** [comment]
@AndreiW3b3 

This is most likely related to an RPC issue with the Validator we are investigating.

I will request a higher faucet limit for the Discord faucet.

**Comment by AndreiW3b3** [comment]
@MarcusWentz Thx Buddy
