### ISSUE TITLE
Faucet Transactions Fail Need To Improve Performance And Monitor Status

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#66]
##### What is the issue?

Faucets are not sending SHM while the network has RPC latency issues.
    
#### What impact does the issue have?

Most users cannot get SHM tokens to pay for gas fees on Shardeum with automated faucets. 
Developers and the community need to manually send tokens instead which is very slow and time consuming.

##### How to reproduce the issue? 

Try faucets on Shardeum.

##### What other resources can you share regarding this issue?

Shardeum SHM Faucets: 

https://docs.shardeum.org/faucet/claim

**Comment by MarcusWentz** [comment]
Shardeum Discord and Twitter faucets:

```
-have their own RPC endpoint for low latency until RPC nodes become open source later in Betanet
-rotating multiple wallets with nonce checks
```

It is possible a nonce check failed. We will look into this issue.

**Comment by MarcusWentz** [comment]
Faucet Improvement Proposals: 

1. Send SHM transfers with a bulk transfer smart contract (bounded to 10 to 100 users to prevent transactions from failing):

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.7;

contract bulkSender {

    function bulkSend(address[] memory myArray) public payable {
        for (uint256 i = 0; i < myArray.length;) {
            payable(myArray[i]).transfer(1 ether);
            unchecked { i += 1; }
        }
    }
}
```


2. Rewrite the faucets in Golang or Rust for more performance since this service is high demand and critical.

3. Have another archive node to reduce load on the current archive node the RPC node is connected to.

**Comment by swarna1101** [comment]
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/69ffd2db-e5f2-4516-a8a7-5449fe5d2c99)
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/3b59df3c-b545-48c6-aca8-e689a50db2cc)


/faucet address: your address
use this way
