### ISSUE TITLE
Validator CLI and GUI shows different Reward value in Explorer 

### ISSUE THREAD

**Issue by bogachevanton** [Shardeum/shardeum-bug-reporting#67]
##### What is the issue?

Displaying different values ​​in three sources of information
    
#### What impact does the issue have?

This does not break the network, but gives the end user incorrect information.

##### How to reproduce the issue? 

View values ​​on your node, dashboard or explorer if the node was already active

##### What other resources can you share regarding this issue?

Wallet: https://explorer-sphinx.shardeum.org/account/0xddb47057e44621f30495af8134babe687a8b6c58
Node: https://explorer-sphinx.shardeum.org/account/a372310355c3d36e207136f997cb5df7dca3bab73c8c32d2e058e1d098e0a7e5

##### Screenshots:

**Node**
![node](https://user-images.githubusercontent.com/90133006/219582538-41dcd95d-de1d-46af-8a48-f32a04d68264.png)

**Dashboard**
![dashboard](https://user-images.githubusercontent.com/90133006/219582557-d33f15c4-2138-417e-8225-ba11e7554eae.png)

**Explorer**
![explorer](https://user-images.githubusercontent.com/90133006/219582571-9308911c-e92f-4c1b-9463-8990803de5cb.png)

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by bogachevanton** [comment]
@MarcusWentz 

After update to 1.1.1 and being active

##### Screenshots:

**Node**
![111](https://user-images.githubusercontent.com/90133006/221140879-ea70e67c-e83a-4d2a-94d0-e542e032acb8.png)


**Dashboard**
![222](https://user-images.githubusercontent.com/90133006/221141085-500d72e2-d41d-437a-bda3-76a79942181c.png)


**Explorer**
![333](https://user-images.githubusercontent.com/90133006/221142560-a4769322-a511-4430-b09a-dcc65094aa99.png)


Nothing changes, your dashboard and explorer have bugs.
Like:

1.
Explorer didn't see all txs and truly balances.
I was staked 150 SHM in 7 txs, but Explorer shows 100 SHM and only 1 tx.

https://explorer-sphinx.shardeum.org/account/510db4df22f154023757ade490b3066496bcd522d3aee2cfe71188d337538179

2.
My node being active, but explorer shows not (Rewards, Reward Start Time, Reward End Time).

**Comment by swarna1101** [comment]
The issue affecting validator nodes is acknowledged and being actively addressed by our development team. However, due to the intricacies involved in the fix, it necessitates additional refinement and validation before deployment. The team is diligently working on this to ensure a comprehensive and robust solution in the subsequent update after the next one.
