### ISSUE TITLE
Validator Stops With Error ```Fatal: _getSeedNodes seed list was not signed by archiver!```

### ISSUE THREAD

**Issue by aveandrian** [Shardeum/shardeum-bug-reporting#68]
Sphinx betanet: 
Run a node according to docs
Node is in standby mode

Suddenly stopped with error `Node exited with following message: Fatal: _getSeedNodes seed list was not signed by archiver!`
When trying to rerun - stopped again after a ~minute
![image](https://user-images.githubusercontent.com/13519212/219698670-f30302a5-4b8a-4636-bc6f-ea0439687610.png)

**Comment by MarcusWentz** [comment]
Closing issue since it exists here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/55

Please share your system info there.

**Comment by MarcusWentz** [comment]
@aveandrian 

We are looking into the archive node to see what might be causing this.

**Comment by mizovsky2304** [comment]
Same issue here...
I think the devs had a lot of work the last three days...
1- public key address
2- seed list: port 4000 problem
3- today: _getSeedNodes
![Capture d’écran 2023-02-17 à 16 48 28](https://user-images.githubusercontent.com/74463073/219701359-5d4aa432-fccb-4e3e-bf38-34903a51345d.png)

**Comment by Kalomes** [comment]
same for me after reinstalling node

**Comment by tawdarky** [comment]
also having this problem.for now i rebooted the vps and started the node again.right now it's still in standby but at least it doesn't crash.

**Comment by MaPiJu** [comment]
Same problem here: "Node exited with following message: Fatal: _getSeedNodes seed list was not signed by archiver!"

**Comment by UnderGCrypto** [comment]
Same: Node exited with following message: Fatal: _getSeedNodes seed list was not signed by archiver!

**Comment by CuanAway** [comment]
After all error like IP:0.0.0.0 , can't node list with 5000ms, and now Fatal:_getSeedNodes , please fixed that all issue.

**Comment by FASHAKING** [comment]
![Screenshot_20230217_172548_Mises](https://user-images.githubusercontent.com/79075610/219709915-9793e25d-e6cf-4300-bada-9695d0564f3f.jpg)
Please I am having the same error over here too

**Comment by LunarTorch** [comment]
Hello team , after being in 24 hrs on standby status - I also got the same issue :  

Node exited with following message: Fatal: _getSeedNodes seed list was not signed by archiver!

**Comment by krmbzglu** [comment]
Node exited with following message: Fatal: _getSeedNodes seed list was not signed by archiver! I am getting this error message can you help me

**Comment by arrtrader** [comment]
Hello team i got this err after 48H , what should I do ?
![Untitled](https://user-images.githubusercontent.com/103467661/219715166-2dbc8d98-fb66-4cda-9ba4-6f97fd5bcd2d.png)

**Comment by rin061998** [comment]
![image](https://user-images.githubusercontent.com/116488417/219717503-14ddc483-41bf-4a3a-b94e-0845f4f63aa9.png)
same for me

**Comment by EdwardWilliam87** [comment]
I get this error: "Node exited with following message: Fatal: _getSeedNodes seed list was not signed by archiver". After that, i restart and waiting response from network. I hope not failed.

**Comment by LIHebzy** [comment]
[
![Sup](https://user-images.githubusercontent.com/119897053/219752896-f9b49f4f-084a-42a1-b218-b342a018aa68.jpg)
We are plenty here tho](url)

**Comment by AndreiW3b3** [comment]
i have the same issue. My validator node was on standby and after i got this message on my dashboard: ¨Fatal: _getSeedNodes seed list was not signed by achiever

**Comment by GarrySE89** [comment]
Hello team. I have same problem. After being in 24 hrs on standby status - I also got the same issue :
Node exited with following message: Fatal: _getSeedNodes seed list was not signed by archiver!
My node - 135.181.82.205:8080 - never got picked on Active status.
I started the node again. Right now it's still in standby but at least it doesn't crash.

**Comment by yue1823** [comment]
Hello team. I have same problem

**Comment by mogoll92** [comment]
Hi team, also here is logs from my validator that also faced with this issue
```/home/node/.pm2/logs/validator-error.log last 15 lines:
/home/node/.pm2/logs/validator-error.log last 15 lines:
1|validato |     at /usr/src/app/src/index.ts:4885:5
1|validato | (node:3658) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
1|validato | (Use `node --trace-deprecation ...` to show where the warning was created)
1|validato | 07:57:11 [ERROR] Connection to 89.248.163.209:37214 failed with Error: Failed to read from TCPStream. early eof
1|validato | 12:51:25 [ERROR] Connection to 180.149.125.164:4969 failed with Error: Failed to read from TCPStream. early eof
1|validato | 14:06:30 [ERROR] Connection to 184.105.139.68:24360 failed with Error: Failed to read from TCPStream. early eof
1|validato | Error: Fatal: _getSeedNodes seed list was not signed by archiver!
1|validato |     at T (evalmachine.<anonymous>:1:154467)
1|validato |     at runMicrotasks (<anonymous>)
1|validato |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|validato |     at Object.startup (evalmachine.<anonymous>:1:155750)
1|validato |     at B.start (evalmachine.<anonymous>:1:194169)
1|validato |     at /usr/src/app/src/index.ts:4885:5
1|validato | (node:6236) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
1|validato | (Use `node --trace-deprecation ...` to show where the warning was created)```

**Comment by sendusd** [comment]
Im having same issue till now

**Comment by EmmyGeorge** [comment]
am having thesame issue, node ahs been on stanby for like 48hrs, just check it to see this error 
![sss](https://user-images.githubusercontent.com/76501055/219875725-be63dcec-4a45-4300-9f47-b3174d519bb1.PNG)

**Comment by VikaPika1994** [comment]
Same thing for me. The node stays in standby mode for 12-24 hours, then I get this Fatal message. Hope the team will release an update or something.

**Comment by hashpuppy** [comment]
Same this happened to my node.  Any updates for this?

**Comment by MarcusWentz** [comment]
@hashpuppy 

Not yet. This issue along with this one:

https://github.com/Shardeum/shardeum-bug-reporting/issues/55

might be potentially related. The core team has both issues as high priority bugs to fix.

**Comment by akaVLadek** [comment]
Waiting for resolving. I have the same issue.

**Comment by shikkiy2** [comment]
5.78.70.127
I have this issue too. 
![image](https://user-images.githubusercontent.com/38682138/220035897-bfe77bc8-a21c-41f1-8f91-c15331d82701.png)

**Comment by xttttv** [comment]
After my node is running, this error will appear later. The same is true for re-running
![1676879680970](https://user-images.githubusercontent.com/116323904/220045745-7b331192-999b-4913-9ab7-519b96b81f2c.jpg)

**Comment by MarcusWentz** [comment]
It sounds like we have a potential bug fix for this with the latest validator update.

Update your validator with:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

Does this error still occur after the latest validator update?

**Comment by fdw2342** [comment]
我也是这个问题  1个小时3次报

![image](https://user-images.githubusercontent.com/121989687/220328061-9a26555f-081c-4c49-8014-d0ed59470c48.png)

**Comment by pratikgarg1122** [comment]
@MarcusWentz - I have updated the validator in the morning. And again it got failed with the old error :
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/123742309/220328281-0ec3d3d2-61ce-4cb8-b79b-fb0f2665045a.png">

Fyi, 
My port 4000 is already open. 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/123742309/220328577-e41c3570-8f33-4697-bee7-f8bf44a7f05d.png">

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by TheDark777** [comment]
Same issue after update, node hasn't worked since installing and updating, constant drops when im assuming its about to validate.

**Comment by QQHHUH** [comment]
![6713acb41390886631b03e8d9b32f70](https://user-images.githubusercontent.com/92560156/220841960-f0b6157a-7f67-4622-99ae-6f16e32c325d.png)

I have made sure to update the latest system
![df15b60bb8a477d6b35b643938edc45](https://user-images.githubusercontent.com/92560156/220841834-27334a7c-9747-4eaa-a4c7-989d14c1453a.png)
And the ports are opened!
![cc67d60e7bb54d340e80b2d9c3652b5](https://user-images.githubusercontent.com/92560156/220842015-2c440095-8032-4822-86a9-d87e84a8afe3.png)
At the same time my server has been active!

One small confusion: my server in Bangalore had frequent errors, but the server in Germany did not. Weird, the VPS I use is Vultr

**Comment by MarcusWentz** [comment]
@QQHHUH 

Thank you for sharing the difference in servers in Germany and Bangalore. I will report this to the team.

**Comment by QQHHUH** [comment]
@MarcusWentz Just now they had a collective failure again, all of which belonged to Bangalore's server (there was a 5000ms problem, as well as an IP problem)! The servers in Germany and Singapore are all normal, but they are still in standby
I'm not quite sure if it's Vultr's problem or validator's problem

**Comment by MarcusWentz** [comment]
@QQHHUH 

If your validator meets these requirements:
```
-10 SHM or more staked 
-standby status
```
this means your validator is working properly. 

The network will automatically make your validator become active with these conditions met over time based on:
```
-validator supply  
-network demand
```

**Comment by nControl88** [comment]
@MarcusWentz, updated the validator to version 1.1.1 a few hours ago. Yet still getting the "Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms" message. Server is running in Germany.

**Comment by Jrrr74** [comment]
![image](https://user-images.githubusercontent.com/112872929/220973379-1fff3d71-6686-4cf3-88d2-dd9a1ab50282.png)

Get the same issue after updating !
My vps have the right requirement...

**Comment by Denismrpl** [comment]
![изображение](https://user-images.githubusercontent.com/88948105/220982165-4e6e8e89-1603-4d14-a547-591e08f94693.png)


how to solve this problem, I can't do anything for 5 days

**Comment by MarcusWentz** [comment]
The original error seems resolved, but there is a new error. 

We can create a new bug report for the new error:

```
Timeout awaiting 'request' for 5000ms
```

**Comment by MarcusWentz** [comment]
The original error seems resolved, but there is a new error.

Bug report tracking for the new timeout issue:

https://github.com/Shardeum/shardeum-bug-reporting/issues/104

**Comment by vsamavila** [comment]
> ![Screenshot_20230217_172548_Mises](https://user-images.githubusercontent.com/79075610/219709915-9793e25d-e6cf-4300-bada-9695d0564f3f.jpg) Please I am having the same error over here too

I keep getting this error. Is there any fix to the bug?
