### ISSUE TITLE
Explorer Footer Links Are Broken

### ISSUE THREAD

**Issue by sagarvd01** [Shardeum/shardeum-bug-reporting#69]
##### What is the issue?

The footer links in sphinx explorer are broken and throwing error if clicked inside an account/ tx page. It looks like the param `[id]` is being parsed as string and causing the error. Inside tx/ account page, the link will be shown as _https://explorer-sphinx.shardeum.org/transaction/[id]_ or _https://explorer-sphinx.shardeum.org/account/[id]_
    
#### What impact does the issue have?

UI glitch.

##### How to reproduce the issue? 

1. Go to [Sphinx explorer](https://explorer-sphinx.shardeum.org/).
2. Click on any transaction/ address.
3. Inside the page, click on any of the footer links.
##### What other resources can you share regarding this issue?

Photos and links related to the error.

![image](https://user-images.githubusercontent.com/15938422/219744090-5a1e55c3-4934-4358-bd04-7575f021d703.png)

**Comment by MarcusWentz** [comment]
Broken footer links for the explorer have been removed now.
