### ISSUE TITLE
MetaMask: Received invalid network parameters

### ISSUE THREAD

**Issue by saurabhburade** [Shardeum/shardeum-bug-reporting#7]
##### Overview

   Metamask returns error -> Received invalid network parameters, with and w/o connecting wallet. 
   This doesn't stop the txns submission but instead causes undefined chainId for web3 connection libraries eg. web3-react.
  

##### Context 

        - Error saw on Metamask Web Extension
        - const { chainId } = useWeb3React();  // returns previous chainId after changing chain through Metamask
       

##### Resources
 - Error Reference [Metamask Extension BaseProvider#chainChanged](https://github.com/MetaMask/providers/blob/e93698288a5b42ed8a71d5f6d5446b047aabda68/src/BaseProvider.ts#L337)
<img width="1440" alt="Screenshot 2022-11-17 at 7 04 07 PM" src="https://user-images.githubusercontent.com/39492927/202465013-f4f47713-d27b-4d13-9c59-57b444405e9d.png">

**Comment by atisheksingh** [comment]
we are integrating Metamask wallet into one of the Dapp, but it's prompting  an error as "Received invalid network parameter."

**Comment by MarcusWentz** [comment]
Please also try the Brave and Bitkeep Wallets in the meantime, 
since I can use them similar to Metamask for interacting with smart contracts through user interfaces.

**Comment by MarcusWentz** [comment]
Might be related to this:

ethers.js ```provider.getNetwork()``` format wrong might be causing Golang ```chainId``` type error ```client.NetworkID(context.Background())```

https://github.com/Shardeum/shardeum-bug-reporting/issues/29
