### ISSUE TITLE
Validator GUI Refused to connect to ```https://<IP_ADDRESS>:8080/``` with ```ERR_CONNECTION_REFUSED```

### ISSUE THREAD

**Issue by efidal** [Shardeum/shardeum-bug-reporting#70]
I started a Node using ContaboVPS, to connection to the shardeum monitoring https://localhost:8080/ failed and refused from the browser. I tried many solution, but nothing helps. Fyi, i use also a VPN.
Help needed please!
Regards

**Comment by MarcusWentz** [comment]
Q1. Is this a remote server?

Q2, The OS is Linux?

Q3 . Do you have a screenshot for the error?

Q4. What happens when you run

```shell
operator-cli start
```

then after a few seconds, run:

```shell
operator-cli status
```

https://docs.shardeum.org/node/run/validator#step-5-start-validator

?

**Comment by efidal** [comment]
Q1: yes, this is a VPS
Q2: Linux
Q3: attached
Q4: where to place it and how please? do I need a command ahead of it?
![Screenshot schardeum connection](https://user-images.githubusercontent.com/116714385/219786403-2e6297df-53e7-4d36-a02e-4f3ff7823292.png)

**Comment by MarcusWentz** [comment]
Q4. Try this in the CLI:

https://docs.shardeum.org/node/run/validator#step-3-open-validator-cli

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by efidal** [comment]
Ok, thanks
Regards
