### ISSUE TITLE
[Duplicate] Validator Stops With ```Error Fatal: _getSeedNodes seed list was not signed by archiver!```

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#71]
##### What is the issue?

My validator node was on standby and after i got this message on my dashboard: ¨Fatal: _getSeedNodes seed list was not signed by achiever
    
#### What impact does the issue have?

it stopped my node

##### How to reproduce the issue? 

Explain in as much detail as possible to help reproduce the bug:
    -where the error is seen
the error was on my dashboard
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
do not know
    -share code and explain how the code was run

##### What other resources can you share regarding this issue?

Made a creenshot if needed

**Comment by MarcusWentz** [comment]
We are tracking this issue here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/68
