### ISSUE TITLE
[Duplicate] Validator Stops With Error ```Could not get seed list from seed node server, connect ENETUNREACH``` On TCP Port 4000

### ISSUE THREAD

**Issue by Jongjh** [Shardeum/shardeum-bug-reporting#74]
![1C756583-AE2A-4C15-BB52-A05851ADE3C0](https://user-images.githubusercontent.com/72982650/219822735-d67186f1-041d-4956-834b-71ce5fb6f3a9.png)

i have been facing this issue

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share your info here where the issue is being tracked:

https://github.com/Shardeum/shardeum-bug-reporting/issues/55
