### ISSUE TITLE
Validator Hardware Raspberry Pi 4 (ARM64) Support

### ISSUE THREAD

**Issue by rahpal** [Shardeum/shardeum-bug-reporting#75]
##### What is the issue?

Shardeum node doesn't work with Raspberry PI 4 (ARM64).
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
-where the error is seen
-how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
-share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Q1. Which Raspberry Pi 4 model are you using?

Q2. Can you share the system hardware info here?

Q3. Does your system hardware match these hardware specifications:

https://docs.shardeum.org/node/run/validator#minimum-hardware-requirements

?

Please fill out the the template fully as well for more context.

**Comment by MarcusWentz** [comment]
I am assuming the hardware requirements mentioned are not met for your Raspberry Pi 4 model.  

Closing this issue for now. 

Please open the issue again if you have updates on the hardware specifications.
