### ISSUE TITLE
RPC Metamask Error Before Sending Transaction With ```Insufficent funds``` When There Are Sufficent SHM Funds On Explorer

### ISSUE THREAD

**Issue by shellboyi** [Shardeum/shardeum-bug-reporting#76]
hi. i tried several times to do stake! tried several amounts of token. used different wallets and browsers. but still had the problem! 
here some screenshots what i got! 
![image](https://user-images.githubusercontent.com/116570470/219869716-dcbd555a-7209-452d-8f87-ff7e828f1134.png)
tried to send tokens to other wallet in opera browser! and here what i got
![image](https://user-images.githubusercontent.com/116570470/219869759-c70c4c2e-32eb-4de4-98de-2c1475d575aa.png)
i did reset account but still had the problem!
![image](https://user-images.githubusercontent.com/116570470/219869793-e6280423-7acc-4beb-92a9-8a2a79d28522.png)
 here my first and main wallet which was on opera and i had to change it
 0xc137d66d57d3BB2f5138164E2Ea18473252b6994
 
![image](https://user-images.githubusercontent.com/116570470/219869862-bbff40bc-60a7-4f1d-bf9e-6cbd6ccbb3f4.png)

![image](https://user-images.githubusercontent.com/116570470/219869872-22710c25-d7f2-41d7-b24b-0feec1d2fe4d.png)

wen i try 10 usually MetaMask does not react. and after several times it shows error about funds! and also i tried 20 once and after confirmation of transaction, it failed finally! but let me try 50!
here with 50
![image](https://user-images.githubusercontent.com/116570470/219869893-8c111078-6412-489a-b83c-cf72ab511570.png)

after that:
used another browser. 
sending token was so fast!
did not get error about fund.
confirmed the transaction but failed finally!
did the reset stuff and still transaction fails!

after a day my problem solved by itself!
![image](https://user-images.githubusercontent.com/116570470/219869946-e778447b-6d91-4457-b744-4e93fc29557c.png)

**Comment by MarcusWentz** [comment]
This is related to an RPC issue. We will look into this.

**Comment by MarcusWentz** [comment]
Closing for now since the RPC seems stable for now.

Please reopen the issue if the error comes back.
