### ISSUE TITLE
Validator ```Remove Stake``` Transaction Fails With ```32603: Internal error```

### ISSUE THREAD

**Issue by shellboyi** [Shardeum/shardeum-bug-reporting#77]
hi. i tried to remove my staked tokens but got failed transaction several times.
also i did used commands to run node to my server already did. and the red message in the dashboard came so i decided to remove stake! 
![image](https://user-images.githubusercontent.com/116570470/219870186-85b4770e-bac8-4f3d-9eb7-9b050a667d85.png)

thanks.

**Comment by MarcusWentz** [comment]
This is related to an RPC issue. We will look into this.

**Comment by MarcusWentz** [comment]
This is related to an RPC issue. We will look into this.

**Comment by MarcusWentz** [comment]
Closing for now since the RPC seems stable for now. 

Please reopen the issue if the error comes back.
