### ISSUE TITLE
Validator Standby Earning Rewards SHM

### ISSUE THREAD

**Issue by sumit6300** [Shardeum/shardeum-bug-reporting#78]
##### What is the issue?

SHM earning keep increasing and reached mine to 60 SHM even only on standby mode.
    
#### What impact does the issue have?

SHM earning rising even on standby mode without being validator active.

Here are the screenshot of my dashboard showing my validator IP address 

https://files.fm/u/be9ahfj4s

**Comment by MarcusWentz** [comment]
Please add the photos directly to the issue.

Please also share your wallet address and nominee public key so we can track what might be happening.

**Comment by sumit6300** [comment]
![Screenshot_20230220_091357_Chrome](https://user-images.githubusercontent.com/32560589/220003087-0e4c56e7-4edd-455f-8812-4938b394cf68.jpg)


above also i attached screenshot images link.  And here this is the screenshot of my dashboard ( https://5.182.36.51:8080)

This is common issue for all users , all users's SHM earning is keep increasing when node is running on standby mode .

My wallet address associated with Shardeum node is :  0x5018387261258EeA799C9539f03C8ECB2806d086

Here is another screenshot which shows my SHM earning increased 👇

![Screenshot_20230220_091932_Chrome](https://user-images.githubusercontent.com/32560589/220003761-8b5e31e7-c132-4806-a703-f21f8f2ed4a2.jpg)


Here is another screenshot after few minutes and u can see shm is keep increaing . And its happening with all users when node is running .   But shm earning stops when node is stopped.  

![Screenshot_20230220_092243_Chrome](https://user-images.githubusercontent.com/32560589/220004014-7a828b33-f03d-4e5c-a154-7d4a109eeebc.jpg)

**Comment by sumit6300** [comment]
my nominee public key is :   2049e2495bc031fe6b096909dac6651ad09f83a10c29dcb7bd702b149032eaee

**Comment by eaddaaa** [comment]
Why are you sharing the public key?

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by sumit6300** [comment]
I have followed and completed your instructions.

now node is on standby mode and earnings showing 0 . Issue has been fixed.  but my wallet had 4.26 shm before unstaking.  After unstaking it should show 10 shm (staked)  but we can see total 20 shm was there in wallet after unstaking. so around 15 shm received into wallet. It was from node reward or staking reward i dont know .  But yes now earning SHM on standby mode issue has been fixed following your instructions



![Screenshot (236)](https://user-images.githubusercontent.com/32560589/220503931-e01580c6-427f-4e82-82f1-5d72623e49fd.png)
![Screenshot (235)](https://user-images.githubusercontent.com/32560589/220503939-4883c888-4466-492a-b140-482c0e93a426.png)
![Screenshot (234)](https://user-images.githubusercontent.com/32560589/220503943-c01906e2-d0d1-467c-aaad-ff7362de917c.png)
![Screenshot (233)](https://user-images.githubusercontent.com/32560589/220503944-90641db4-d0b4-4452-9fc1-f5c3543afb98.png)
![Screenshot (232)](https://user-images.githubusercontent.com/32560589/220503947-2c6ee3c6-2486-4c82-82da-f48fb3040940.png)

**Comment by sumit6300** [comment]
SHM Earning on standby mode Issue has been fixed. Thanks a lot 

![Screenshot (237)](https://user-images.githubusercontent.com/32560589/220505364-426bd38e-26ea-4092-9821-fb7cb9ea6b2f.png)

**Comment by sumit6300** [comment]
You have to roll out this new update for all node validators because this issues is for all validators.  I am also  running 2 other  shardeum nodes of my friends' . So there is also same issue like SHM earning keep increases on standby mode. You can see attached screenshot below . You have to rollout update for all validator users. Thanks 👍

![Screenshot_20230222_083516_Chrome](https://user-images.githubusercontent.com/32560589/220509315-47835d49-343d-4ab2-b098-f4ef2765fc6d.jpg)
![Screenshot_20230222_083618_Chrome](https://user-images.githubusercontent.com/32560589/220509324-86d47105-526d-4b75-8d1e-1ad458715cc9.jpg)

**Comment by MarcusWentz** [comment]
Closing this issue for now since it sounds like it is fixed.

**Comment by sumit6300** [comment]
I updated my node version to 1.1.2 yesterday. Again having same earning increasing on standby mode. Below u can see earning keep increasing on standby mode. Yesterday it was keep showing 0 . but when i opened dashboard i found it was stopped and saying node exited with normal condition. And i thing my node was active for a while and since that time it started showing earning and now even on standby mode its earning SHM

![Screenshot (259)](https://user-images.githubusercontent.com/32560589/223631753-784c3ecc-3357-4983-b06e-ab1941ed14d8.png)
![Screenshot (258)](https://user-images.githubusercontent.com/32560589/223631761-bb5474bb-0f5a-4317-8724-2e765f196b7a.png)
