### ISSUE TITLE
Sorry, something went wrong. Please report this issue to our support team so we can investigate and resolve the problem

### ISSUE THREAD

**Issue by kirill-sr** [Shardeum/shardeum-bug-reporting#785]
![Screenshot from 2024-06-27 17-06-04](https://github.com/shardeum/bug-reporting/assets/160257390/f331432c-0a15-4a84-84d6-6abe3fe3c32a)

:red_circle: Photos and links related to the error. :red_circle:

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK
