### ISSUE TITLE
Validator ```Add Stake``` Transaction Metamask Warning ```Transaction decoding is not available for chainid 8082```

### ISSUE THREAD

**Issue by maximilianWP** [Shardeum/shardeum-bug-reporting#79]
##### What is the issue?
Hey, guys. I still cannot find the solution of the problem with the SHM staking. I have enough balance in my wallet, I sign the transaction, but nothing happens. What am I doing wrong? Thanks in advance. 
P.S. My Metamask Wallet is being reset, so It is not the possible solution
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

I sign the transaction in Metamask wallet, go to the dashboard and nothing happens.

**Comment by MarcusWentz** [comment]
What is your wallet address? 

Can you transfer SHM between wallets as a test transaction? 

Do you see the same error as this:

https://github.com/Shardeum/shardeum-bug-reporting/issues/48 

?

**Comment by maximilianWP** [comment]
My wallet address info:

https://explorer-sphinx.shardeum.org/account/0x0d448eee33f7181478c18d03f262ef1906bcd2cf

I can transfer SHM between wallets, and I did this with some guys in discord channel.

I don't see any errors. Transaction is signed, nothing happens in the dashboard. 

In Metamask I see that transaction is failed. But I don`t know why:

![image](https://user-images.githubusercontent.com/95386839/220179447-1f439079-7f8d-4f9f-8d3e-0038dc843270.png)

**Comment by maximilianWP** [comment]
Okay, I found this. Maybe something wrong with the chain ID. Please find attached the screenshot

![image](https://user-images.githubusercontent.com/95386839/220179710-6039e2ca-9c9d-47b3-98fc-977f17d5d4e8.png)

**Comment by maximilianWP** [comment]
Okay, I found the solution. Now it`s working
![image](https://user-images.githubusercontent.com/95386839/220184030-d5f7b5d2-606f-4d50-9396-9439c1708018.png)

**Comment by MarcusWentz** [comment]
It looks like:

```
Transaction decoding is not available for chainid 8082
```

is just a warning and will not impact the transaction. 

Since this is working now I will close the issue.

**Comment by scorpion141** [comment]
I get the Same Error by trying to Remove Stake from the Note but i only get the Error and the SHM still staked.
