### ISSUE TITLE
SHARDEUM LIBERTY 1.6 INTERFACE SHOWING SHM as ETH

### ISSUE THREAD

**Issue by ruban0007** [Shardeum/shardeum-bug-reporting#8]
##### Overview 

SHM TOKENS are being shown as ETH 

##### Context 

   I opted for Shardeum airdrop and in my Shardeum Liberty 1.6 wallet ( 0xB57b4F94E48981D22034f52Ee074E97d263ABBA3) ,I received 100 ETH instead of 100 SHM. I did not use the ETH I have received , with a doubt that it was accidently transferred to my account .Then it was reversed to 100 SHM .I have done transactions sending out SHM for testing after I received 100 SHM from your end ( PDF enclosed ).

But within 2 days the Shardeum Liberty 1.6 interface has changed the shardeum tokens as ETH tokens . on the day 2 it was showing as Shardeum tokens and the trasactions were done via SHM  but  on the third day I could see all the tokens are shown as ETH and the transactions being done with ETH . 

This would result in serious consequences to the Shardeum system if such bugs continues when the Mainnet is activated. Hence necessary action may be initiated to rectify the deviation.

##### Resources

[Shardeum.pdf](https://github.com/Shardeum/shardeum-bug-reporting/files/10040945/Shardeum.pdf)

[ETH SHARDEUM1.pdf](https://github.com/Shardeum/shardeum-bug-reporting/files/10040935/ETH.SHARDEUM1.pdf)
[Transferring fund.pdf](https://github.com/Shardeum/shardeum-bug-reporting/files/10040939/Transferring.fund.pdf)
https://streamable.com/vc9gz6

**Comment by MarcusWentz** [comment]
Metamask says 

    Swap Exact E T H For Tokens 

when swapping SHM for other tokens in SwappedFinance. This does not impact the logic on chain (the swap updates correctly). 
I am closing this issue and will contact SwappedFinance about changing the name from ETH to SHM.

**Comment by ruban0007** [comment]
Sir,

I had reset my Metamask wallet and I am unable to add "  Shardeum Liberty
1.6" network . I had done testnet transactions and waiting for the Airdrop
tokens. Now I could add only  "Shardeum Sphinx 1.X" &  "Shardeum Liberty
2.x ". And also I could not view the transactions i have done with Swaaped
finance .
My Wallet address is  0xB57b4F94E48981D22034f52Ee074E97d263ABBA3 . Kindly
do the needful.

Ruban
