### ISSUE TITLE
[Duplicate] Validator Restart Lost Stake Reward

### ISSUE THREAD

**Issue by Hummagumma** [Shardeum/shardeum-bug-reporting#82]
I'm 3 days active, my rewards get up to 60 tokens, now I'm still active but my rewards are aboyut 0,6 and the rest didnt go to my wallet

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Please share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/34
