### ISSUE TITLE
Validator Install Error ```Failed to connect to gitlab.com port 443: Connection timed out code ETIMEDOUT``` npm and node

### ISSUE THREAD

**Issue by Hudson31** [Shardeum/shardeum-bug-reporting#84]
##### What is the issue?

When trying to run the curl command to run the installer it returns various npm ERRs and then completes the install but does not launch.
    
#### What impact does the issue have?

It breaks functionality and does not allow you to start the node or node interface.

##### How to reproduce the issue? 

Run the installer process with:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

After the "Starting image. This could take a while..." message comes up:

```javascript 
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/pm2 failed, reason: connect ETIMEDOUT 104.16.22.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-02-20T22_15_45_113Z-debug.log
Cloning into 'cli'...
fatal: unable to access 'https://gitlab.com/shardeum/validator/cli.git/': Failed to connect to gitlab.com port 443: Connection timed out
./entrypoint.sh: line 16: cd: cli: No such file or directory
Cloning into 'gui'...
fatal: unable to access 'https://gitlab.com/shardeum/validator/gui.git/': Failed to connect to gitlab.com port 443: Connection timed out
./entrypoint.sh: line 23: cd: gui: No such file or directory
npm ERR! code ENOENT
npm ERR! syscall open
```

If this is relevant to the problem, 
I port forwarded both port 443 on my router and locally through ufw and am still facing the same issue. 

##### What other resources can you share regarding this issue?

Near the end it also has these errors: 

```shell
./entrypoint.sh: line 98: operator-cli: command not found
./entrypoint.sh: line 100: operator-cli: command not found
./entrypoint.sh: line 102: operator-cli: command not found
./entrypoint.sh: line 105: operator-cli: command not found
./entrypoint.sh: line 106: operator-cli: command not found
```

Before proceeding to do the normal text talking about how to access your node.

I appreciate your help!

**Comment by MarcusWentz** [comment]
What happens when you run this from your root directory:

```shell
cd .shardeum 
```

?

https://docs.shardeum.org/node/run/validator#step-3-open-validator-cli

**Comment by CryptoHudson** [comment]
Hi Marcus, 

I appreciate you responding so quickly. 

It does go into the .shardeum directory so I know it is making one. When trying to launch the validator CLI it says the command does not exist because I'm assuming it does not install correctly.

**Comment by Hudson31** [comment]
Hi Marcus,

That directory does exist but it looks like due to that error it doesn't install correctly so it says the command is not found. Btw I am running the command as root as well so its not a permission error. 

I am still unsure whats causing it but I am doing my own digging and if I find anything I will report back,

**Comment by MarcusWentz** [comment]
While in directory:

```shell
.shardeum
```

run:

```shell
ls
```

Do you see shell.sh in the Shell output anywhere?

**Comment by Hudson31** [comment]
Yep, I will paste the output:
![image](https://user-images.githubusercontent.com/33123786/220459909-31c56cfb-ab22-4739-ad31-bc487ff2730c.png)

**Comment by MarcusWentz** [comment]
What happens when you run: 

```shell
./shell.sh
```

?

**Comment by Hudson31** [comment]
It actually works as intended. Just when I go to run operator-cli it says the command does not exist.

**Comment by MarcusWentz** [comment]
While in the Validator CLI, what happens when you run:

```shell
operator-cli --help
```

?

https://docs.shardeum.org/node/run/validator#commands

**Comment by Hudson31** [comment]
It returns 
bash: operator-cli: command not found

**Comment by MarcusWentz** [comment]
Q1. Is this a local computer or remote server?

Q2. What OS is the validator running on?

**Comment by Hudson31** [comment]
A remote server accessed through SSH.

The OS is Linux Ubuntu 22.04.2 LTS.

**Comment by MarcusWentz** [comment]
I am reading the error message again and it sounds like it might have something to do with proxy settings. 

Do you see anything with 

```shell
npm help config
```

?

**Comment by MarcusWentz** [comment]
What happens with:

```shell
curl https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh
```

?

https://support.glitch.com/t/cannot-connect-to-gitlab/19524

You should see raw text in your terminal that is linked below:

https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh

For context:

```curl
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh
```

writes output to a file named as the remote file.

Source:

```shell
curl --help
```

https://phoenixnap.com/kb/curl-command

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by Hudson31** [comment]
> What happens with:
> 
> ```shell
> curl https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh
> ```
> 
> ?
> 
> https://support.glitch.com/t/cannot-connect-to-gitlab/19524
> 
> You should see raw text in your terminal that is linked below:
> 
> https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh
> 
> For context:
> 
> ```
> curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh
> ```
> 
> writes output to a file named as the remote file.
> 
> Source:
> 
> ```shell
> curl --help
> ```
> 
> https://phoenixnap.com/kb/curl-command

Yeah all the raw text displays from GitLab, therefore GitLab doesn't seem to be the issue.

Regarding the npm proxy settings, I followed a guide to remove all of them and set them all back to null and it is still throwing the same errors. I even made sure to change my registry back to the default. 

Its very strange why none of this solved the issue, and the logs are not very helpful. 

I appreciate your support thus far and hope I can solve the issue.

**Comment by MarcusWentz** [comment]
I will share this feedback with the core team.

**Comment by MarcusWentz** [comment]
Q1: Does running:
```shell
npm --version
```
return:
```shell
8.0.0  
```
?

Q2: Does running:
```shell
node --version should 
```
return:
```shell 
16.11.1 
```
?

**Comment by Hudson31** [comment]
npm version returns 9.5.1, node returns 14.21.3. This could be potentially the problem. Let me get those versions and report back with the results.

**Comment by Hudson31** [comment]
After trying with those specific versions unfortunately it still flashes the same error.

**Comment by MarcusWentz** [comment]
Did you uninstall the validator before trying to reinstall the validator again?

**Comment by Hudson31** [comment]
Yes, I completely deleted the .shardeum folder.

**Comment by MarcusWentz** [comment]
Did you remove the .shardeum folder, and then remove all docker images and containers:

https://docs.shardeum.org/node/run/validator#uninstall-validator

?

**Comment by sralser** [comment]
I had the same issue. In my case there were two installations of docker on the system (snap and apt sources), i think this happens with a fresh Ubuntu 22 server installation if you select docker during the installation process (I did so) and then install docker with apt on top of it. 

After a:
```shell
sudo snap remove docker
```
then:
```shell
sudo apt install --reinstall docker.io
```
The error did not appear anymore.
