### ISSUE TITLE
Validator GUI ```https://<server_ip>:8080``` Web Browser Error ```This site can’t be reached```

### ISSUE THREAD

**Issue by satoshiman** [Shardeum/shardeum-bug-reporting#85]
I tried to launch the validator GUI but it responded nothing, I opened `pm2 monit` inside the docker, and see this warning. Is it a bug?

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/37683529/220231954-48f51e56-d07a-43d0-afff-4ce22cd78825.png">

**Comment by MarcusWentz** [comment]
Which commands did you run in the CLI?

https://docs.shardeum.org/node/run/validator#step-4-open-validator-gui

**Comment by satoshiman** [comment]
I followed instructions (from root): 

```shell
cd .shardeum
./shell.sh
operator-cli gui start
pm2 monit
```

to start GUI (started when the installation was completed).

**Comment by MarcusWentz** [comment]
Your web browser opened automatically to start the GUI at the correct URL?

Which web browser are you using?

Please try to access the GUI manually with the GUI URL.

Is this on a local computer or remote server? 

Local:

```shell
https://localhost:8080/
```

Server:

```shell
https://<server_ip>:8080/
```

https://docs.shardeum.org/node/run/validator#step-4-open-validator-gui

**Comment by satoshiman** [comment]
I'm using VPS server
- I tried accessing `https://<server_ip>:8080/`, server responsed empty
- I SSH to the server and run `curl localhost:8080` it also returns an empty response.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/37683529/220249885-3b1f549f-4295-4438-8600-b3fa69adad25.png">

**Comment by MarcusWentz** [comment]
Q1. Which web browser are you using?

Q2. Have you tried other web browsers?

Q3. Do you have a screenshot for your main web browser with:

```shell
https://<server_ip>:8080/
```

?

Q4. What happens when you run the following the validator CLI:

```shell 
operator-cli start
```

then after a few seconds run

```shell
operator-cli start
```

?

https://docs.shardeum.org/node/run/validator#step-5-start-validator
https://docs.shardeum.org/node/run/validator#step-6-monitor-validator

**Comment by satoshiman** [comment]
- I am using Google Chrome, I tried Safary.
- This is my browser screenshot
![image](https://user-images.githubusercontent.com/37683529/220266427-425441c2-f3a8-4f4e-9a81-ce9fc8a5cfdc.png)
****
- and my operator status
<img width="787" alt="image" src="https://user-images.githubusercontent.com/37683529/220266737-b07dcf58-77d2-494a-904f-931d0fc01ad1.png">

**Comment by satoshiman** [comment]
- I am using Google Chrome, I tried Safary.
- This is my browser screenshot
![image](https://user-images.githubusercontent.com/37683529/220267284-4920f83c-71ed-4e16-88a2-72fca8eaf1b4.png)


- and my operator status
![image](https://user-images.githubusercontent.com/37683529/220267048-3257836b-c8fa-4538-afbb-6d626ad26ef2.png)

**Comment by MarcusWentz** [comment]
The validator seems to be running from the CLI. 

I do not see:

```curl
https://
```

in the URL screenshot you shared. What do you see when you add this to the URL in your web browsers? 

This fixed a similar issue: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/33#issuecomment-1417418355

**Comment by MarcusWentz** [comment]
Are you able to see your stake balance with:

```shell
operator-cli stake_info <staked_address>
```

to use your wallet, add your private key inside the Validator CLI as an environmental variable:

```shell
export PRIV_KEY=<WALLET_PRIVATE_KEY>
```

then add stake:

```shell
operator-cli stake 10 
```

then remove stake:

```shell
operator-cli unstake
```

?

Validator CLI commands list:

https://docs.shardeum.org/node/run/validator#commands

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by satoshiman** [comment]
I tried uninstalling and reinstalling, but nothing changed, It still has the same issue.

**Comment by MarcusWentz** [comment]
Q1. Did you try the updated URL as mentioned here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85#issuecomment-1438883261

?

Q2. Were you able to stake from the CLI as a test: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/85#issuecomment-1438936416

?

**Comment by satoshiman** [comment]
Q1: GUI is working, but it responds nothing (EMPTY RESPONSE). I checked it from inside docker, localhost from VPS, and public IP. It's not a problem from the protocol setting (http/https), I also tested both these protocol too. 

Q2. I will try to use CLI, instead of GUI.

**Comment by MarcusWentz** [comment]
You might see an error with connecting to the network if you try to stake or unstake from the Validator CLI right now:

https://github.com/Shardeum/shardeum-bug-reporting/issues/85#issuecomment-1438936416

We have a fix for this coming soon as well:

https://gitlab.com/shardeum/validator/cli/-/commit/166165ef9aa0de681941c13fc923c8e164207ddd

**Comment by Noah407** [comment]
Hello i tried to connect to my Shardeum dashboard but got this response 'refused to connect'. Although when i updated my shardeum node i was able to access my dashboard to unstake and stake SHM again but after a while i couldn't access any more.
Image is attached......
![Screenshot (82)](https://user-images.githubusercontent.com/118976162/221371372-cc1d757c-8284-4b02-b158-32cb7b9b7359.jpg)

**Comment by bestsvetny** [comment]
Hello, same issue, running on vps. Was trying to connect local via curl:

`curl http://localhost:8080`
curl: (52) Empty reply from server

`curl https://localhost:8080`
curl: (60) SSL certificate problem: self signed certificate in certificate chain

`curl -k https://localhost:8080`
-Here i got html doc! Same results with internal ip

But while i try to connect from my laptop via chrome/firefox
`https://<EXTERNAL_SERVER_IP>:8080/`
get "This site can’t be reached"
_Tested Appache on this instance, works nice_

**Comment by bestsvetny** [comment]
Found solution
In google cloud default-allow-http rule applied to port 80, changed to 8080 now its works perfect

**Comment by Noah407** [comment]
> Hello i tried to connect to my Shardeum dashboard but got this response 'refused to connect'. Although when i updated my shardeum node i was able to access my dashboard to unstake and stake SHM again but after a while i couldn't access any more. Image is attached...... ![Screenshot (82)](https://user-images.githubusercontent.com/118976162/221371372-cc1d757c-8284-4b02-b158-32cb7b9b7359.jpg)

Please can anyone help resolve this?

**Comment by MarcusWentz** [comment]
Do you have this issue on Linux or Mac?

**Comment by MarcusWentz** [comment]
@Noah407 

Do you have this issue on Linux or Mac?

**Comment by xhzi** [comment]
Had this same issue. Problem is the UI wont work in http. You need to do it in https

**Comment by MarcusWentz** [comment]
Closing issue for now.

We can reopen the issue if needed.

You can stake and unstake from the Validator CLI as well:

https://docs.shardeum.org/node/run/validator#cli

**Comment by barnabas626** [comment]
This the issue am having too please why is it saying site can’t be reached

**Comment by MarcusWentz** [comment]
@barnabas626 

Did you add https:// at the start of your URL?

If so, please wait for Validator Version 1.1.3 coming out soon.

**Comment by MarcusWentz** [comment]
Validator Version 1.1.5 is out now. 

Upgrade to this latest version.

If you still see this issue then we can reopen the issue.
