### ISSUE TITLE
[Duplicate] Validator ```Add Stake``` and ```Remove Stake``` Transactions Fail With ```32603: Internal error```

### ISSUE THREAD

**Issue by datestorm88** [Shardeum/shardeum-bug-reporting#86]
Cant unstake coz transaction error and cant stake again coz i need to unstake before
    

![shd1](https://user-images.githubusercontent.com/111326817/220246621-ba42be86-3d2e-4688-8c67-a1f065ab7641.jpg)
![shd2](https://user-images.githubusercontent.com/111326817/220246690-37155c1a-6bf0-4fce-8de0-91e308c58bc8.jpg)
![shd3](https://user-images.githubusercontent.com/111326817/220246932-64ab8047-649f-4895-b303-dc07c8ded226.jpg)
![shd4](https://user-images.githubusercontent.com/111326817/220247060-3267a8b8-3baa-48ac-90a6-4ccfa4bad20b.jpg)
ts tottaly break my node and wallet,resetting wallet and delete add network again doesnt help . :red_circle:

**Comment by MarcusWentz** [comment]
This sounds similar to issues https://github.com/Shardeum/shardeum-bug-reporting/issues/48 and https://github.com/Shardeum/shardeum-bug-reporting/issues/77 .

Q1. What is your wallet address for these transactions?

Q2. Did you reset your Metamask activity to update your wallet address nonce: 

https://metamask.zendesk.com/hc/en-us/articles/360015488891-How-to-reset-an-account

?

Q3. Can you transfer SHM between wallets as a test?

**Comment by datestorm88** [comment]
my wallet address
0xd1910bB0Bcc6B87176aDCEF814e749e95C2B8936

yes resetted it 3 times and tryed delete and add network

and yes i can send transactions between my adresses
![shd 5](https://user-images.githubusercontent.com/111326817/220249555-8827bdf5-207f-42ac-862f-4f02cfdd9a5d.jpg)
![shd6](https://user-images.githubusercontent.com/111326817/220249686-5668e23e-6e7f-4e10-b25c-ec4676a96437.jpg)

transaction id for wallet to wallet
0x75d263dbeaee0a82cebc4cfefca0a77f89b5d883f985ee5505a53158e949c23f

**Comment by MarcusWentz** [comment]
Are you able to stake with other wallets?

**Comment by datestorm88** [comment]
yes,but i want to use my mine wallet,coz i used it for all shardeum activity
![shd7](https://user-images.githubusercontent.com/111326817/220257413-5c50947b-8828-43f7-a97e-c733ba9068e5.jpg)
and cant understand what the problem with my mine wallet

**Comment by MarcusWentz** [comment]
This is most likely an RPC or Validator issue.

We will look into this.

**Comment by adityamasineedi** [comment]
even i'm also facing same issue

**Comment by scorpion141** [comment]
I have the Same Problem.

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by datestorm88** [comment]
updated,and nothin changed i unstaked from second wallet,but cant unstake from main wallet,and after update some as early cant stake from main wallet,and cant unstake...
![sdd1](https://user-images.githubusercontent.com/111326817/220486268-796504fb-6b5a-4a74-bde7-018914e3d316.jpg)
![sdd2](https://user-images.githubusercontent.com/111326817/220486289-1b41de28-c249-4af8-88e6-74fa44da7b1e.jpg)

**Comment by MarcusWentz** [comment]
@datestorm88 

There are some other RPC issues causing transactions to fail. We are looking into this.

**Comment by AndreiW3b3** [comment]
solution. use another wallet address, it works straight away. hope that helps

**Comment by MarcusWentz** [comment]
@AndreiW3b3 

Thank you for the feedback. We will continue to look into the RPC issue for other wallets.

**Comment by AndreiW3b3** [comment]
@MarcusWentz yw. but would be nice to fix this. haha. still can not unstake from old wallet

**Comment by ANiX5202** [comment]
I have the same problem

![Снимок экрана 2023-02-22 172833](https://user-images.githubusercontent.com/125510374/220853955-ed644686-8b1b-4e5f-8759-9d451520fcf0.jpg)

https://github.com/Shardeum/shardeum-bug-reporting/issues/86#issuecomment-1439194823 it didn't help

**Comment by ANiX5202** [comment]
Hi guys! How can i change metamask address? in faucet i have this error
 Your account has already claimed tokens for address 0xb16030...02399e. Please use the same address to claim again

**Comment by qniscompbeti** [comment]
I have the same problem, I can't unstake
0x00C95F8305Bd1c991243d95EFF0Dd0A52737c5f4
![image](https://user-images.githubusercontent.com/126170922/220917410-334d08a2-5b21-4748-a88c-b59076c14fe9.png)

**Comment by MarcusWentz** [comment]
Tracking this issue here now:

https://github.com/Shardeum/shardeum-bug-reporting/issues/92

**Comment by maximilianWP** [comment]
I have the same problem, as I already told. So maybe I will try to clean the old files of the node and run again? Or it is not a good idea? Because I have already tried everything
