### ISSUE TITLE
[Duplicate] Validator Restart Lost Stake Reward

### ISSUE THREAD

**Issue by GONY7** [Shardeum/shardeum-bug-reporting#87]
##### What is the issue?

Reward SHM has disappeared.

staking address:0x6e89216b6d5c8fbed5cdb21b7838b801b9a9ca52
![20230221](https://user-images.githubusercontent.com/83521556/220308652-2c25035c-cc9f-4713-9a28-354a8cb7a3dc.png)

    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by GONY7** [comment]
Earnings: 94 SHM -> now 3 SHM

**Comment by GONY7** [comment]
![image](https://user-images.githubusercontent.com/83521556/220315707-39ac7c2e-afd4-47b4-bb7d-f2d5d6c265bb.png)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Please share this info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/34
