### ISSUE TITLE
[Duplicate] Explorer ERC-20 Tokens Not Visible

### ISSUE THREAD

**Issue by praveenkump** [Shardeum/shardeum-bug-reporting#88]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
Once the token deployed and tokens minted to other wallets, I dont see the token balances in the explorere, When i import in metamask i can see them
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 
Its just that explorer doesn't show the token balance and users will only know when they import the token contract on to metamask, People doesn't really know if they really have their tokens on their wallet if its doesn't show up on explorer.

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen - No token balances shown on explorer
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant) Not sure usually we 
    need to see the token balances once its standard erc20 token, But not sure of what is causing this issue
    -share code and explain how the code was run
    pretty much extended contract from standard erc20 token and calling mint and burn functionality to issue tokens to the new users.
```
:red_circle: 

##### What other resources can you share regarding this issue?
It can be replicated with the test erc20 contract IMO.
:red_circle: Photos and links related to the error. :red_circle: 
![image](https://user-images.githubusercontent.com/28045205/220325356-f2f4126f-8d31-4bc5-9a25-7930404ffd36.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please respond to the questions here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/46#issuecomment-1438678219
