### ISSUE TITLE
RPC ```eth_getBlockTransactionCountByNumber``` Support

### ISSUE THREAD

**Issue by saurabhburade** [Shardeum/shardeum-bug-reporting#89]
##### What is the issue?

Getting the same value for ```getBlockTransactionCount``` for any block/cycle number.    

##### How to reproduce the issue? 

```javascript
const web3 = new Web3("https://sphinx.shardeum.org/");
const res = await web3.eth.getBlockTransactionCount(10520);
console.log({ res });
```

Output:
```JSON
{ 
 "res": "10" 
}
```

##### What other resources can you share regarding this issue?

RPC method ```eth_getBlockTransactionCountByNumber``` documentation:

https://www.quicknode.com/docs/ethereum/eth_getBlockTransactionCountByNumber

**Comment by MarcusWentz** [comment]
This issue is caused by:

https://github.com/Shardeum/shardeum-bug-reporting/issues/40

You can use the Shardeum Explorer to find transaction count for cycles.

Example checking transaction count on Betanet 1.1 for cycle 2000: 

https://explorer-sphinx.shardeum.org/api/transaction?startCycle=2000&endCycle=2000

Returns:

```JSON
{
 "success":true,
 "totalTransactions":9
}
```

Typescript example:

```typescript
//Javascript require
// const axios = require('axios');
//Typescript import
import axios from "axios";

testConvertCycleToBlockForTransactionCount(2000)

async function testConvertCycleToBlockForTransactionCount(cycleToEmulateBlock: number){

	let testValue = await eth_getBlockTransactionCountByNumber(cycleToEmulateBlock);
    console.log("Total transactions for cycle 2000: " + testValue)

}

async function eth_getBlockTransactionCountByNumber(cycleToEmulateBlock: number) {

	let baseUrl = 
		"https://explorer-sphinx.shardeum.org/api/transaction?startCycle=" + 
		cycleToEmulateBlock.toString() + 
		"&endCycle=" + 
		cycleToEmulateBlock.toString();
    
    let responseRawJSON = await axios.get(baseUrl);
    let responseDataJSON = responseRawJSON.data;
    let totalTransactionsValue = responseDataJSON.totalTransactions; 
    return totalTransactionsValue

}
```

**Comment by saurabhburade** [comment]
It works for now.
