### ISSUE TITLE
[Duplicate] Validator Downloading and Installing Dial TCP I/O Timeout 

### ISSUE THREAD

**Issue by scorpion141** [Shardeum/shardeum-bug-reporting#90]
##### What is the issue?

Device cant finish the Install  "curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh"
    
#### What impact does the issue have?

Note doenst work correct.

Ubuntu 22.04

##### How to reproduce the issue? 

Just start curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh

![grafik](https://user-images.githubusercontent.com/89877808/220349953-61c8a80b-a109-4e1a-af5b-79ba96bfa527.png)

**Comment by MarcusWentz** [comment]
Duplicate issue. 

Please review this bug report:

https://github.com/Shardeum/shardeum-bug-reporting/issues/36

**Comment by scorpion141** [comment]
In the Other Issuie there is no Solution for this Problem. The Creater just have another Problem and the old one is not fixed.

**Comment by MarcusWentz** [comment]
@scorpion141 

I reopened the original issue now. Let's continue the bug reporting there.

**Comment by scorpion141** [comment]
Thank you very mutch how can i help you for the error analysis ? :)

**Comment by MarcusWentz** [comment]
@scorpion141 

please give feedback to this comment in the original issue: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/36#issuecomment-1438769958
