### ISSUE TITLE
[Duplicate] Validator Stops With Error ```Could not get seed list from seed node server, connect ENETUNREACH``` On TCP Port 4000

### ISSUE THREAD

**Issue by Kafiirr** [Shardeum/shardeum-bug-reporting#91]
**Node exited with following message: Fatal: Could not get seed list from seed node server http://archiver-sphinx.shardeum.org:4000/nodelist: Timeout awaiting 'request' for 5000ms**

The bug keeps happening. I've done various ways to try to solve it but after 3-5 days later my Node stops because the bug reappears. I have tried resetting the VPS and Removing the validator and then reinstalling it several times it's work for 1-2 days but a few days later it didn't work, it's keep stoping my Node.

![Screenshot_20230222_005716_1](https://user-images.githubusercontent.com/124496288/220427108-0d26fb67-1bd5-4bfa-b331-98be731dcfb0.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please add your info here: 

https://github.com/Shardeum/shardeum-bug-reporting/issues/55
