### ISSUE TITLE
Validator GUI Did Not Ask For Password

### ISSUE THREAD

**Issue by AndreiW3b3** [Shardeum/shardeum-bug-reporting#93]
##### What is the issue?

After installing the node in puty successfully and seting up my password i go on my browser and and open up dashboard. But it did not ask for any password like first time. Is this normal?
#### What impact does the issue have?
do not know

**Comment by MarcusWentz** [comment]
Did you have the validator installed on this system before?

If so, this is expected and we can close the issue.

**Comment by AndreiW3b3** [comment]
yws, it was installed prior. First time i used the dashboard i used the password

**Comment by MarcusWentz** [comment]
This is expected then. I will close this issue.
