### ISSUE TITLE
Explorer Address Error ```Account Not Found!```

### ISSUE THREAD

**Issue by blaisinho10** [Shardeum/shardeum-bug-reporting#95]
##### What is the issue?
When visit the explorer page and search an address, it shows the account cannot be found.
:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?
It is not possible to see the account balance on the explorer.
:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 
visit: https://explorer-sphinx.shardeum.org/ and search for an address
:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources ca
![Capture](https://user-images.githubusercontent.com/44775232/220659098-da7dadef-b955-4e92-8552-9a11efe5ab39.PNG)
n you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by MarcusWentz** [comment]
Q1. Do you have any SHM in Metamask when on Betanet 1.X:

https://docs.shardeum.org/network/endpoints#connect-wallet

?

Q2. What is your wallet address in text form so I can check this too?

**Comment by blaisinho10** [comment]
I don't have any SHM in my metamask.
Here is my address: 0x10Bf282eA3D2bfD914268A7b73039A18dFA164f9

**Comment by MarcusWentz** [comment]
This message is displayed in the explorer when you have 0 SHM with no account activity.

Are you able to request SHM from any of these faucets:

https://docs.shardeum.org/faucet/claim

?

**Comment by blaisinho10** [comment]
I've tried with different addresses but I have once got failed transaction or no transaction at all.

**Comment by MarcusWentz** [comment]
I have some failed transactions right now too. This seems related to be an RPC issue. We will investigate this.

**Comment by blaisinho10** [comment]
Ok thanks.

**Comment by MarcusWentz** [comment]
I sent you some SHM now.

I see your account at this address now with SHM:

https://explorer-sphinx.shardeum.org/account/0x10bf282ea3d2bfd914268a7b73039a18dfa164f9

Closing issue since the error is gone now.

**Comment by MarcusWentz** [comment]
@yassir781

I see your addess now after I sent you some tokens:
 https://explorer-sphinx.shardeum.org/account/0x7077ff7e627767dc20c802e76202106ed5f4e52d
