### ISSUE TITLE
[Duplicate] Validator ```Add Stake``` and ```Remove Stake``` Transactions Fail With ```32603: Internal error```

### ISSUE THREAD

**Issue by ANiX5202** [Shardeum/shardeum-bug-reporting#99]
Hi. After update i can't remove stake. Error is shown in the photo. Reset the account in metamask did not help. Whats am i doing wrong? Thanks
![Снимок экрана 2023-02-22 172833](https://user-images.githubusercontent.com/125510374/220791075-a6ea4c3e-c11a-44d0-a173-0459febcbbb6.jpg)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Please share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/86
